### ISSUE TITLE
Oracle schema double click on procedure does not load

### ISSUE THREAD

**Issue by kiravi** [serge-rider/dbeaver#1035]
Status message is saying:

Reload object 'org.jkiss.dbeaver.ext.oracle.mode.OracleProcedureStandalone@<some number>' from <some_schema>

where <some_number> is a 8 digit number
and    <some_schema> is the schema name for which I am attempting to load the procedure under folder "Procedures".

I have enabled the garbage collector icon on the status bar and it keeps increasing/decreasing paging memory.

**Comment by kiravi** [comment]
There is no error, the above process continues indefinitely and double clicking on procedure does not show up. I created a debug log:

2016-12-07 11:45:37.005 - Error copying object state
j2016-12-07 11:45:37.039 - Error copying object state
java.lang.StackOverflowError
	at java.io.FileOutputStream.writeBytes(Native Method)
	at java.io.FileOutputStream.write(Unknown Source)
	at java.io.BufferedOutputStream.flushBuffer(Unknown Source)
	at java.io.BufferedOutputStream.write(Unknown Source)
	at java.io.PrintStream.write(Unknown Source)
	at org.jkiss.dbeaver.core.application.DBeaverApplication$ProxyPrintStream.write(DBeaverApplication.java:397)
	at java.io.OutputStream.write(Unknown Source)
	at java.io.PrintStream.write(Unknown Source)
	at sun.nio.cs.StreamEncoder.writeBytes(Unknown Source)
	at sun.nio.cs.StreamEncoder.implFlushBuffer(Unknown Source)
	at sun.nio.cs.StreamEncoder.flushBuffer(Unknown Source)
	at java.io.OutputStreamWriter.flushBuffer(Unknown Source)
	at java.io.PrintStream.write(Unknown Source)
	at java.io.PrintStream.print(Unknown Source)
	at java.io.PrintStream.println(Unknown Source)
	at java.lang.Throwable$WrappedPrintStream.println(Unknown Source)
	at java.lang.Throwable.printStackTrace(Unknown Source)
	at java.lang.Throwable.printStackTrace(Unknown Source)
	at org.jkiss.dbeaver.Log.debugMessage(Log.java:122)
	at org.jkiss.dbeaver.Log.writeExceptionStatus(Log.java:197)
	at org.jkiss.dbeaver.Log.error(Log.java:182)
	at org.jkiss.dbeaver.model.impl.AbstractObjectCache.deepCopyCachedObject(AbstractObjectCache.java:289)
	at org.jkiss.dbeaver.model.impl.AbstractObjectCache.deepCopyCachedObject(AbstractObjectCache.java:280)
	at org.jkiss.dbeaver.model.impl.AbstractObjectCache.deepCopyCachedObject(AbstractObjectCache.java:280)

**Comment by kiravi** [comment]
The last line on log  repeats indefinitely

**Comment by serge-rider** [comment]
Yeah, I've reproduced that.
Thanks for report. Will be fixed in the next version.
