### ISSUE TITLE
Syntax error at ')' in position 30 (PostgreSQL stacktrace)

### ISSUE THREAD

**Issue by GiantCrocodile** [serge-rider/dbeaver#1061]
I've got this stacktrace after inserting data in my PostgreSQL database with DBeaver:

```
org.jkiss.dbeaver.model.exec.DBCException: SQL Error [42601]: FEHLER: Syntaxfehler bei »)«
  Position: 30
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCPreparedStatementImpl.executeStatement(JDBCPreparedStatementImpl.java:202)
	at org.jkiss.dbeaver.model.impl.data.ExecuteBatchImpl.executeStatement(ExecuteBatchImpl.java:259)
	at org.jkiss.dbeaver.model.impl.data.ExecuteBatchImpl.processBatch(ExecuteBatchImpl.java:157)
	at org.jkiss.dbeaver.model.impl.data.ExecuteBatchImpl.execute(ExecuteBatchImpl.java:78)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetPersister$DataUpdaterJob.executeStatements(ResultSetPersister.java:522)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetPersister$DataUpdaterJob.run(ResultSetPersister.java:411)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:103)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)
Caused by: org.postgresql.util.PSQLException: FEHLER: Syntaxfehler bei »)«
  Position: 30
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2455)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2155)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:288)
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:430)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:356)
	at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:168)
	at org.postgresql.jdbc.PgPreparedStatement.execute(PgPreparedStatement.java:157)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCPreparedStatementImpl.execute(JDBCPreparedStatementImpl.java:255)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCPreparedStatementImpl.executeStatement(JDBCPreparedStatementImpl.java:199)
	... 7 more
```

Maybe also related to this:
```
org.jkiss.dbeaver.model.exec.DBCException: SQL Error [23505]: FEHLER: doppelter Schlüsselwert verletzt Unique-Constraint »category_pkey«
  Detail: Schlüssel »(tag_id)=(24)« existiert bereits.
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCPreparedStatementImpl.executeStatement(JDBCPreparedStatementImpl.java:202)
	at org.jkiss.dbeaver.model.impl.data.ExecuteBatchImpl.executeStatement(ExecuteBatchImpl.java:259)
	at org.jkiss.dbeaver.model.impl.data.ExecuteBatchImpl.processBatch(ExecuteBatchImpl.java:157)
	at org.jkiss.dbeaver.model.impl.data.ExecuteBatchImpl.execute(ExecuteBatchImpl.java:78)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetPersister$DataUpdaterJob.executeStatements(ResultSetPersister.java:522)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetPersister$DataUpdaterJob.run(ResultSetPersister.java:411)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetPersister.execute(ResultSetPersister.java:279)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetPersister.applyChanges(ResultSetPersister.java:130)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetViewer.applyChanges(ResultSetViewer.java:2329)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetViewer.applyChanges(ResultSetViewer.java:2301)
	at org.jkiss.dbeaver.ui.editors.data.DatabaseDataEditor.doSave(DatabaseDataEditor.java:150)
	at org.jkiss.dbeaver.ui.editors.entity.EntityEditor$SaveJob.run(EntityEditor.java:876)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:103)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)
Caused by: org.postgresql.util.PSQLException: FEHLER: doppelter Schlüsselwert verletzt Unique-Constraint »category_pkey«
  Detail: Schlüssel »(tag_id)=(24)« existiert bereits.
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2455)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2155)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:288)
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:430)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:356)
	at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:168)
	at org.postgresql.jdbc.PgPreparedStatement.execute(PgPreparedStatement.java:157)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCPreparedStatementImpl.execute(JDBCPreparedStatementImpl.java:255)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCPreparedStatementImpl.executeStatement(JDBCPreparedStatementImpl.java:199)
	... 13 more
```

I tried to reproduce the issue at #1053 where you said it is possibly a PostgreSQl behaviour. Sadly I can't provide you with the generated queries from Query Manager view because they are just these:
- SELECT * FROM public.category

I've expected to see the insert query there. Maybe I've done something wrong?

**Comment by serge-rider** [comment]
Please post table DDL. There should be some non-standard column data type.

**Comment by GiantCrocodile** [comment]
```
CREATE TABLE public.category (
	tag_id int4 NOT NULL DEFAULT nextval('category_tag_id_seq'::regclass),
	name varchar(30) NOT NULL,
	CONSTRAINT category_pkey PRIMARY KEY (tag_id)
)
WITH (
	OIDS=FALSE
);
```

**Comment by serge-rider** [comment]
Thanks. Although I still can't reproduce that.
To see INSERTs open Query Manager settings (Query Manager view toolbar, action "Filters...") and check all object types and query types.
Then retry.

**Comment by GiantCrocodile** [comment]
The queries are:
```INSERT INTO public.category ("name") VALUES ('idcawowjcoid')
SELECT x.* FROM public.category x WHERE x.tag_id = 31
SELECT x.* FROM public.category x WHERE x.tag_id = 30
INSERT INTO public.category (tag_id,"name") VALUES (31,'cawdawc')
INSERT INTO public.category (tag_id,"name") VALUES (30,'wcjiadocaw')
SELECT x.* FROM public.category x WHERE x.tag_id = 29
SELECT x.* FROM public.category x WHERE x.tag_id = 28
SELECT x.* FROM public.category x WHERE x.tag_id = 27
INSERT INTO public.category ("name") VALUES ('cdwadcw')
INSERT INTO public.category ("name") VALUES ('cwadcaw')
INSERT INTO public.category ("name") VALUES ('cwacawddcaw')
```

Error: `FEHLER: doppelter Schlüsselwert verletzt Unique-Constraint »category_pkey«
  Detail: Schlüssel »(tag_id)=(30)« existiert bereits.`

**Comment by serge-rider** [comment]
This is an error from #1053. And it is a PostgreSQL specific behavior.

Try to reproduce `Syntax error at ')'` error

**Comment by GiantCrocodile** [comment]
It is hard to reproduce but I noticed that if you leave both columns empty it generates this query:
- INSERT INTO public.category () VALUES ()

I think a (small, maybe related) issue to this is that the columns field is empty even though it shouldn't.

**Comment by serge-rider** [comment]
Well, you need to specify at least one column value. This is not a DBeaver issue but limitation of a database engine.
