### ISSUE TITLE
[MS SQLServer] Cannot connect with instance specified

### ISSUE THREAD

**Issue by Jiehong** [serge-rider/dbeaver#1109]
Hello,

When trying to connect to a Microsoft SQL Server, I cannot connect to all servers with instances.

I have 3, yet dbeaver can only connect to 1.

The other two try to connect, but fail after like 10 seconds with an error message.

JDBC URL looks like `jdbc:sqlserver://value\instance:1433`
Read-only Connection.
Driver: Microsoft Driver
Platform: Microsoft Windows 7 and Ubuntu 16.04 (I tested on both).
Everything else is default (no proxy, no tunnel, no database/schema.

Error:
```
2017-01-02 15:12:25.860 - DBeaver 3.8.2 is starting
2017-01-02 15:12:25.863 - Install path: '/usr/share/dbeaver'
2017-01-02 15:12:25.863 - Instance path: 'file:/home/user/.dbeaver/'
2017-01-02 15:12:25.863 - Memory available 239Mb/3547Mb
2017-01-02 15:12:25.866 - Starting RMI server at 55295
2017-01-02 15:12:25.951 - Initialize display
2017-01-02 15:12:27.154 - Initializing DBeaver 3.8.2
2017-01-02 15:12:27.156 - Host plugin: org.jkiss.dbeaver.core.application 3.8.2
2017-01-02 15:12:27.158 - Initialize Core...
2017-01-02 15:12:27.291 - Core initialized (133ms)
2017-01-02 15:12:27.293 - Configure workbench window
2017-01-02 15:12:27.334 - Create actions
2017-01-02 15:12:27.647 - Initialize workbench window
2017-01-02 15:12:27.668 - Finish initialization
2017-01-02 15:12:31.447 - Connect with 'XXX (MS SQL Server - instance)' (mssql_ms-1595f5c034b-1e0770addfeddaac)
2017-01-02 15:12:46.025 - Connection failed (mssql_ms-1595f5c034b-1e0770addfeddaac)
2017-01-02 15:12:46.026 - org.jkiss.dbeaver.model.exec.DBCConnectException: The TCP/IP connection to the host value, port 1433 has failed. Error: "null. Verify the connection properties. Make sure that an instance of SQL Server is running on the host and accepting TCP/IP connections at the port. Make sure that TCP connections to the port are not blocked by a firewall.".
org.jkiss.dbeaver.model.exec.DBCConnectException: The TCP/IP connection to the host value, port 1433 has failed. Error: "null. Verify the connection properties. Make sure that an instance of SQL Server is running on the host and accepting TCP/IP connections at the port. Make sure that TCP connections to the port are not blocked by a firewall.".
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.openConnection(JDBCDataSource.java:173)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCExecutionContext.connect(JDBCExecutionContext.java:73)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.<init>(JDBCDataSource.java:99)
	at org.jkiss.dbeaver.ext.generic.model.GenericDataSource.<init>(GenericDataSource.java:84)
	at org.jkiss.dbeaver.ext.generic.model.meta.GenericMetaModel.createDataSource(GenericMetaModel.java:86)
	at org.jkiss.dbeaver.ext.generic.GenericDataSourceProvider.openDataSource(GenericDataSourceProvider.java:153)
	at org.jkiss.dbeaver.registry.DataSourceDescriptor.connect(DataSourceDescriptor.java:679)
	at org.jkiss.dbeaver.runtime.jobs.ConnectJob.run(ConnectJob.java:74)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:103)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)
Caused by: com.microsoft.sqlserver.jdbc.SQLServerException: The TCP/IP connection to the host value, port 1433 has failed. Error: "null. Verify the connection properties. Make sure that an instance of SQL Server is running on the host and accepting TCP/IP connections at the port. Make sure that TCP connections to the port are not blocked by a firewall.".
	at com.microsoft.sqlserver.jdbc.SQLServerException.makeFromDriverError(SQLServerException.java:190)
	at com.microsoft.sqlserver.jdbc.SQLServerException.ConvertConnectExceptionToSQLServerException(SQLServerException.java:241)
	at com.microsoft.sqlserver.jdbc.SocketFinder.findSocket(IOBuffer.java:2243)
	at com.microsoft.sqlserver.jdbc.TDSChannel.open(IOBuffer.java:491)
	at com.microsoft.sqlserver.jdbc.SQLServerConnection.connectHelper(SQLServerConnection.java:1309)
	at com.microsoft.sqlserver.jdbc.SQLServerConnection.login(SQLServerConnection.java:991)
	at com.microsoft.sqlserver.jdbc.SQLServerConnection.connect(SQLServerConnection.java:827)
	at com.microsoft.sqlserver.jdbc.SQLServerDriver.connect(SQLServerDriver.java:1012)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.openConnection(JDBCDataSource.java:159)
	... 9 more
```

Nothing added in the ErrorLog though.

Yet, using Microsoft Sql Server Studio, I can connect just fine.

How could I try to find more logs about the request itself? As it's working fine with Microsoft Studio (and I re-created the connection 5 times to make sure no typos), I'd like to understand what happens for 10 seconds while trying to connect, as it should be working just fine.

Let me know what I can do to help resolve this issue.

**Comment by yao-bin** [comment]
Mine works fine

My JDBC URL is 'jdbc:sqlserver://<host>:1433;databaseName=<database name>'

Could you try?

**Comment by Jiehong** [comment]
@yao-bin It doesn't change anything (same error).

But the fact is that it works fine for 2 of my databases, but not for 2 others (the read-only ones).

Is there a way to add more logs (like a verbose setting)?

**Comment by serge-rider** [comment]
Check this topic: http://dbeaver.jkiss.org/forum/viewtopic.php?f=3&t=624

**Comment by Jiehong** [comment]
Checking the topic given by @serge-rider didn't change anything. I mean I tried, yet it doesn't work.

**Comment by serge-rider** [comment]
Your SQL Server instance doesn't listen TCP/IP port 1433. 
This means it is not possible to connect to it thru JDBC/ODBC (SQL Server studio uses different protocol).
Topic I have posted was about server configuration and client connection properties. If this doesn't help then I think you need to talk with your database administrator.

**Comment by janschulz** [comment]
In my dbeaver are two different jdbc drivers: I could get it to work with the `MS SQL Server / jTDS` driver (Under driver properties I could insert a name after "INSTANCE") but not the other driver, even though there is a instance name setting under driver properties as well.

**Comment by serge-rider** [comment]
Answered
