### ISSUE TITLE
[PostGres] Problem with jdbc driver

### ISSUE THREAD

**Issue by MadKulhas** [serge-rider/dbeaver#1112]
Hello,

I'm currently using DBeaver 3.8.2 to connect to PostGres using the 9.4.1212 JDBC 41 driver available on the database website. When I try to compile a function that returns a table, I get the following error:

`
!ENTRY org.jkiss.dbeaver.model 4 0 2017-01-03 10:33:00.677
!MESSAGE org.jkiss.dbeaver.model.exec.DBCException: SQL Error: Internal jdbc driver error
!SUBENTRY 1 org.jkiss.dbeaver.model 4 0 2017-01-03 10:33:00.677
!MESSAGE SQL Error: Internal jdbc driver error
!STACK 0
org.jkiss.dbeaver.model.exec.DBCException: SQL Error: Internal jdbc driver error
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCStatementImpl.executeStatement(JDBCStatementImpl.java:141)
	at org.jkiss.dbeaver.runtime.sql.SQLQueryJob.executeSingleQuery(SQLQueryJob.java:344)
	at org.jkiss.dbeaver.runtime.sql.SQLQueryJob.run(SQLQueryJob.java:182)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:103)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)
Caused by: java.sql.SQLException: Internal jdbc driver error
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCStatementImpl.handleExecuteError(JDBCStatementImpl.java:313)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCStatementImpl.execute(JDBCStatementImpl.java:347)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCStatementImpl.executeStatement(JDBCStatementImpl.java:138)
	... 4 more
Caused by: java.lang.ArrayIndexOutOfBoundsException
	at java.lang.System.arraycopy(Native Method)
	at java.lang.AbstractStringBuilder.append(Unknown Source)
	at java.lang.StringBuilder.append(Unknown Source)
	at org.postgresql.core.Parser.parseSql(Parser.java:1020)
	at org.postgresql.core.Parser.replaceProcessing(Parser.java:972)
	at org.postgresql.core.CachedQueryCreateAction.create(CachedQueryCreateAction.java:40)
	at org.postgresql.core.QueryExecutorBase.createQueryByKey(QueryExecutorBase.java:309)
	at org.postgresql.jdbc.PgStatement.executeCachedSql(PgStatement.java:281)
	at org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:266)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:262)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCStatementImpl.execute(JDBCStatementImpl.java:345)
	... 5 more
!SUBENTRY 2 org.jkiss.dbeaver.model 4 0 2017-01-03 10:33:00.677
!MESSAGE Internal jdbc driver error
!STACK 0
java.sql.SQLException: Internal jdbc driver error
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCStatementImpl.handleExecuteError(JDBCStatementImpl.java:313)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCStatementImpl.execute(JDBCStatementImpl.java:347)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCStatementImpl.executeStatement(JDBCStatementImpl.java:138)
	at org.jkiss.dbeaver.runtime.sql.SQLQueryJob.executeSingleQuery(SQLQueryJob.java:344)
	at org.jkiss.dbeaver.runtime.sql.SQLQueryJob.run(SQLQueryJob.java:182)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:103)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)
Caused by: java.lang.ArrayIndexOutOfBoundsException
	at java.lang.System.arraycopy(Native Method)
	at java.lang.AbstractStringBuilder.append(Unknown Source)
	at java.lang.StringBuilder.append(Unknown Source)
	at org.postgresql.core.Parser.parseSql(Parser.java:1020)
	at org.postgresql.core.Parser.replaceProcessing(Parser.java:972)
	at org.postgresql.core.CachedQueryCreateAction.create(CachedQueryCreateAction.java:40)
	at org.postgresql.core.QueryExecutorBase.createQueryByKey(QueryExecutorBase.java:309)
	at org.postgresql.jdbc.PgStatement.executeCachedSql(PgStatement.java:281)
	at org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:266)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:262)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCStatementImpl.execute(JDBCStatementImpl.java:345)
	... 5 more
!SUBENTRY 3 org.jkiss.dbeaver.model 4 0 2017-01-03 10:33:00.677
!MESSAGE 
!STACK 0
java.lang.ArrayIndexOutOfBoundsException
	at java.lang.System.arraycopy(Native Method)
	at java.lang.AbstractStringBuilder.append(Unknown Source)
	at java.lang.StringBuilder.append(Unknown Source)
	at org.postgresql.core.Parser.parseSql(Parser.java:1020)
	at org.postgresql.core.Parser.replaceProcessing(Parser.java:972)
	at org.postgresql.core.CachedQueryCreateAction.create(CachedQueryCreateAction.java:40)
	at org.postgresql.core.QueryExecutorBase.createQueryByKey(QueryExecutorBase.java:309)
	at org.postgresql.jdbc.PgStatement.executeCachedSql(PgStatement.java:281)
	at org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:266)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:262)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCStatementImpl.execute(JDBCStatementImpl.java:345)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCStatementImpl.executeStatement(JDBCStatementImpl.java:138)
	at org.jkiss.dbeaver.runtime.sql.SQLQueryJob.executeSingleQuery(SQLQueryJob.java:344)
	at org.jkiss.dbeaver.runtime.sql.SQLQueryJob.run(SQLQueryJob.java:182)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:103)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)`

But when I use the pgAdmin tool with the same code, I don't have any errors.

I'm using the following code:

`create or replace function ptl.pg_space_table() returns table(table_schema name, table_name name, total text, data text, index text, toast text)
as $func$

begin
    

    return query
	select a.table_schema, a.table_name
		, pg_size_pretty(total_bytes) AS total
		, pg_size_pretty(table_bytes) AS data
		, pg_size_pretty(index_bytes) AS index
		, pg_size_pretty(coalesce(toast_bytes,0)) AS toast
	  FROM (
	  SELECT *, total_bytes-index_bytes-COALESCE(toast_bytes,0) AS table_bytes FROM (
		  SELECT c.oid,nspname AS table_schema, relname AS TABLE_NAME
				  , c.reltuples AS row_estimate
				  , pg_total_relation_size(c.oid) AS total_bytes
				  , pg_indexes_size(c.oid) AS index_bytes
				  , pg_total_relation_size(reltoastrelid) AS toast_bytes
			  FROM pg_class c
			  LEFT JOIN pg_namespace n ON n.oid = c.relnamespace
			  WHERE relkind = 'r'
	  ) a
	) a
	order by 1;

end

$func$ language plpgsql;`

Thank you for your help.

**Comment by serge-rider** [comment]
It is a known PostgreSQL driver issue.
Check #900
