### ISSUE TITLE
 Dbeaver jobs still running after shutdown

### ISSUE THREAD

**Issue by mdontsov** [serge-rider/dbeaver#1146]
Hi,

I've been encountering with an issue using various versions of Dbeaver: 3.7.5 (currently in use), 3.8.1, 3.8.2
The issue itself means that at some random moment Dbeaver is no longer able to  execute queries or reload existing DB connection or connect to DB upon start or just cannot expand DB connection properties in 'Database navigator' menu or display some DB table live data. The issue also happens along with high CPU usage ~ 25-28%
The problem also persists after killing the running relevant service and so far the only workaround i've found is to uninstall dbeaver with all dependencies, reinstall again, set-up again all the DB connections and start using it with fingers crossed.

After last freeze the following information is taken from the log file
!SESSION 2017-01-13 09:55:18.384 -----------------------------------------------
eclipse.buildId=unknown
java.version=1.7.0_80
java.vendor=Oracle Corporation
BootLoader constants: OS=linux, ARCH=x86_64, WS=gtk, NL=en_US
Command-line arguments:  -os linux -ws gtk -arch x86_64

!ENTRY org.eclipse.osgi 4 0 2017-01-13 09:57:45.295
!MESSAGE Application error
!STACK 1
org.eclipse.swt.SWTException: Failed to execute runnable (org.eclipse.swt.SWTException: Widget is disposed)
	at org.eclipse.swt.SWT.error(SWT.java:4491)
	at org.eclipse.swt.SWT.error(SWT.java:4406)
	at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Synchronizer.java:138)
	at org.eclipse.swt.widgets.Display.runAsyncMessages(Display.java:3794)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3433)
	at org.eclipse.swt.widgets.Display.release(Display.java:3485)
	at org.eclipse.swt.graphics.Device.dispose(Device.java:248)
	at org.jkiss.dbeaver.core.application.DBeaverApplication.start(DBeaverApplication.java:217)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:380)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:235)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:669)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:608)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1515)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1488)
Caused by: org.eclipse.swt.SWTException: Widget is disposed
	at org.eclipse.swt.SWT.error(SWT.java:4491)
	at org.eclipse.swt.SWT.error(SWT.java:4406)
	at org.eclipse.swt.SWT.error(SWT.java:4377)
	at org.eclipse.swt.widgets.Widget.error(Widget.java:482)
	at org.eclipse.swt.widgets.Widget.checkWidget(Widget.java:419)
	at org.jkiss.dbeaver.ui.controls.CImageCombo.getSelectionIndex(CImageCombo.java:559)
	at org.jkiss.dbeaver.ui.perspective.DataSourceManagementToolbar$10.run(DataSourceManagementToolbar.java:836)
	at org.eclipse.ui.internal.UILockListener.doPendingWork(UILockListener.java:162)
	at org.eclipse.ui.internal.UISynchronizer$3.run(UISynchronizer.java:154)
	at org.eclipse.swt.widgets.RunnableLock.run(RunnableLock.java:35)
	at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Synchronizer.java:135)
	... 18 more

!ENTRY org.eclipse.e4.ui.workbench 4 0 2017-01-13 09:57:45.314
!MESSAGE FrameworkEvent ERROR
!STACK 0
org.eclipse.e4.core.di.InjectionException: org.eclipse.swt.SWTException: Invalid thread access
	at org.eclipse.e4.core.internal.di.MethodRequestor.execute(MethodRequestor.java:68)
	at org.eclipse.e4.core.internal.di.InjectorImpl.processAnnotated(InjectorImpl.java:898)
	at org.eclipse.e4.core.internal.di.InjectorImpl.disposed(InjectorImpl.java:398)
	at org.eclipse.e4.core.internal.di.Requestor.disposed(Requestor.java:148)
	at org.eclipse.e4.core.internal.contexts.ContextObjectSupplier$ContextInjectionListener.update(ContextObjectSupplier.java:78)
	at org.eclipse.e4.core.internal.contexts.TrackableComputationExt.update(TrackableComputationExt.java:111)
	at org.eclipse.e4.core.internal.contexts.TrackableComputationExt.handleInvalid(TrackableComputationExt.java:74)
	at org.eclipse.e4.core.internal.contexts.EclipseContext.dispose(EclipseContext.java:174)
	at org.eclipse.e4.core.internal.contexts.EclipseContext.dispose(EclipseContext.java:159)
	at org.eclipse.e4.core.internal.contexts.osgi.EclipseContextOSGi.dispose(EclipseContextOSGi.java:106)
	at org.eclipse.e4.core.internal.contexts.osgi.EclipseContextOSGi.bundleChanged(EclipseContextOSGi.java:139)
	at org.eclipse.osgi.internal.framework.BundleContextImpl.dispatchEvent(BundleContextImpl.java:902)
	at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:230)
	at org.eclipse.osgi.framework.eventmgr.ListenerQueue.dispatchEventSynchronous(ListenerQueue.java:148)
	at org.eclipse.osgi.internal.framework.EquinoxEventPublisher.publishBundleEventPrivileged(EquinoxEventPublisher.java:165)
	at org.eclipse.osgi.internal.framework.EquinoxEventPublisher.publishBundleEvent(EquinoxEventPublisher.java:75)
	at org.eclipse.osgi.internal.framework.EquinoxEventPublisher.publishBundleEvent(EquinoxEventPublisher.java:67)
	at org.eclipse.osgi.internal.framework.EquinoxContainerAdaptor.publishModuleEvent(EquinoxContainerAdaptor.java:102)
	at org.eclipse.osgi.container.Module.publishEvent(Module.java:466)
	at org.eclipse.osgi.container.Module.doStop(Module.java:624)
	at org.eclipse.osgi.container.Module.stop(Module.java:488)
	at org.eclipse.osgi.container.SystemModule.stop(SystemModule.java:186)
	at org.eclipse.osgi.internal.framework.EquinoxBundle$SystemBundle$EquinoxSystemModule$1.run(EquinoxBundle.java:159)
	at java.lang.Thread.run(Thread.java:745)
Caused by: org.eclipse.swt.SWTException: Invalid thread access
	at org.eclipse.swt.SWT.error(SWT.java:4491)
	at org.eclipse.swt.SWT.error(SWT.java:4406)
	at org.eclipse.swt.SWT.error(SWT.java:4377)
	at org.eclipse.swt.widgets.Display.error(Display.java:1186)
	at org.eclipse.swt.widgets.Display.checkDevice(Display.java:765)
	at org.eclipse.swt.widgets.Display.removeFilter(Display.java:3703)
	at org.eclipse.e4.ui.workbench.renderers.swt.MenuManagerRenderer.contextDisposed(MenuManagerRenderer.java:338)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.eclipse.e4.core.internal.di.MethodRequestor.execute(MethodRequestor.java:56)
	... 23 more

!ENTRY org.eclipse.core.jobs 2 2 2017-01-13 09:57:45.736
!MESSAGE Job found still running after platform shutdown.  Jobs should be canceled by the plugin that scheduled them during shutdown: org.eclipse.ui.internal.progress.ProgressViewUpdater$1

!ENTRY org.eclipse.core.jobs 2 2 2017-01-13 09:57:45.738
!MESSAGE Job found still running after platform shutdown.  Jobs should be canceled by the plugin that scheduled them during shutdown: org.eclipse.ui.internal.progress.AnimationManager$1

!ENTRY org.eclipse.core.jobs 2 2 2017-01-13 09:57:45.740
!MESSAGE Job found still running after platform shutdown.  Jobs should be canceled by the plugin that scheduled them during shutdown: org.jkiss.dbeaver.ui.LoadingJob$LoadingUIJob

!ENTRY org.eclipse.core.jobs 2 2 2017-01-13 09:57:45.742
!MESSAGE Job found still running after platform shutdown.  Jobs should be canceled by the plugin that scheduled them during shutdown: org.eclipse.ui.internal.progress.ProgressManager$2$1

**Comment by serge-rider** [comment]
These errors happen (sometimes) during DBeaver shutdown. Some of them are DBeaver-specific, some come from Eclipse internals. Generally these errors are just warnings.

Please clarify what exactly problem do you have - why do you need to reinstall dbeaver/connections?

**Comment by mdontsov** [comment]
I have to do this because otherwise Dbeaver won't do anything 
- Database connection tree not expandable - message 'Loading' is hanging and that's all
- Even when the database connection status is established, after executing MySql statement i receive an error 'Not  connected'
- MySql driver library not listed anymore under 'Edit driver settings' despite it was there when i've set up the connection for the first time
- Like i wrote before CPU usage raises drastically when this connectivity/driver issues start to occur

My last try was using an executable Dbeaver version not installable from .deb package. Currently it works

**Comment by mdontsov** [comment]
![dbeaver](https://cloud.githubusercontent.com/assets/16574445/21928512/ea5bf4ec-d993-11e6-941d-5a53f4ea9574.png)

I made the screenshot while Dbeaver was consuming ~25% of CPU resources

**Comment by serge-rider** [comment]
This looks like good old GTK problem. Check this: #1041
Please inform about results.

**Comment by mdontsov** [comment]
So far so good. I suspect that something went broken after installation from .deb package.

**Comment by serge-rider** [comment]
Ok.
Anyhow this problem with GTK should be solved after Eclipse 4.6 migration.
