### ISSUE TITLE
[build] mvn install fails

### ISSUE THREAD

**Issue by codebling** [serge-rider/dbeaver#115]
When attempting to build according to instructions in `README.md`, running `mvn install` on Windows 7 (presumably on any system other than OS X) will fail with error `Cannot set permissions or symbolic links for macosx.cocoa.x86_64 if there are no root files for that configuration` while building module `org.jkiss.dbeaver.standalone.feature`, UNLESS directory `generated-macos` and a dummy file within it are manually created under that module's `target` directory prior to running `mvn install`.

The directory comes from `root.macosx.cocoa.x86_64` in `org.jkiss.dbeaver.standalone.feature`'s `build.properties`. 

Build completes fine as long as directory `dbeaver/features/org.jkiss.dbeaver.standalone.feature/target/generated-macos` exists and has more than one file in it. 

Unhelpful stack trace below:
```
[ERROR] Failed to execute goal org.eclipse.tycho:tycho-p2-plugin:0.23.1:p2-metadata-default (default-p2-metadata-default) on project org.jkiss.dbeaver.standalone.feature: Execution default-p2-metadata-default of goal org.eclipse.tycho:tycho-p2-plugin:0.23.1:p2-metadata-default failed: Cannot set permissions or symbolic links for macosx.cocoa.x86_64 if there are no root files for that configuration -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.eclipse.tycho:tycho-p2-plugin:0.23.1:p2-metadata-default (default-p2-metadata-default) on project org.jkiss.dbeaver.standalone.feature: Execution default-p2-metadata-default of goal org.eclipse.tycho:tycho-p2-plugin:0.23.1:p2-metadata-default failed: Cannot set permissions or symbolic links for macosx.cocoa.x86_64 if there are no root files for that configuration
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:212)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
        at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
        at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
        at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
        at org.apache.maven.cli.MavenCli.execute(MavenCli.java:863)
        at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
        at org.apache.maven.cli.MavenCli.main(MavenCli.java:199)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:483)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
        at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
        at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.apache.maven.plugin.PluginExecutionException: Execution default-p2-metadata-default of goal org.eclipse.tycho:tycho-p2-plugin:0.23.1:p2-metadata-default failed: Cannot set permissions or symbolic links for macosx.cocoa.x86_64 if there are no root files for that configuration
        at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:145)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:207)
        ... 20 more
Caused by: java.lang.RuntimeException: Cannot set permissions or symbolic links for macosx.cocoa.x86_64 if there are no root files for that configuration
        at org.eclipse.tycho.p2.impl.publisher.AbstractMetadataGenerator.publish(AbstractMetadataGenerator.java:125)
        at org.eclipse.tycho.p2.impl.publisher.AbstractMetadataGenerator.generateMetadata(AbstractMetadataGenerator.java:58)
        at org.eclipse.tycho.p2.impl.publisher.P2GeneratorImpl.generateMetadata(P2GeneratorImpl.java:96)
        at org.eclipse.tycho.plugins.p2.P2MetadataMojo.attachP2Metadata(P2MetadataMojo.java:149)
        at org.eclipse.tycho.plugins.p2.P2MetadataMojo.execute(P2MetadataMojo.java:107)
        at org.eclipse.tycho.plugins.p2.P2MetadataDefaultMojo.execute(P2MetadataDefaultMojo.java:33)
        at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
        ... 21 more
Caused by: java.lang.IllegalArgumentException: Cannot set permissions or symbolic links for macosx.cocoa.x86_64 if there are no root files for that configuration
        at org.eclipse.tycho.p2.impl.publisher.rootfiles.FeatureRootAdvice.ensureRootFilesConfigured(FeatureRootAdvice.java:204)
        at org.eclipse.tycho.p2.impl.publisher.rootfiles.FeatureRootAdvice.getDescriptor(FeatureRootAdvice.java:153)
        at org.eclipse.equinox.p2.publisher.eclipse.FeaturesAction.generateRootFileIUs(FeaturesAction.java:453)
        at org.eclipse.equinox.p2.publisher.eclipse.FeaturesAction.generateFeatureIUs(FeaturesAction.java:423)
        at org.eclipse.equinox.p2.publisher.eclipse.FeaturesAction.perform(FeaturesAction.java:605)
        at org.eclipse.equinox.p2.publisher.Publisher$ArtifactProcess.run(Publisher.java:207)
        at org.eclipse.equinox.p2.repository.artifact.spi.AbstractArtifactRepository.executeBatch(AbstractArtifactRepository.java:187)
        at org.eclipse.equinox.p2.publisher.Publisher.publish(Publisher.java:231)
        at org.eclipse.tycho.p2.impl.publisher.AbstractMetadataGenerator.publish(AbstractMetadataGenerator.java:122)
        ... 27 more
[ERROR]
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginExecutionException
```

**Comment by serge-rider** [comment]
This is not related to OS, one of property files was broken. My dev machine is Windows 7-10, build machine is Linux.
By accident I committed fix in #113 issue)

**Comment by codebling** [comment]
I figured it was probably broken on across all OS but couldn't confirm. Just wanted to let you know. Otherwise the project is very easy to build. 

What's the suggested method for running DBeaver in debug mode? Right now I've added `<vmArgs>-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=5005</vmArgs>` to `product/standalone/DBeaver.product`, but this seems contrived.

**Comment by serge-rider** [comment]
Yeah, thanks for report btw. I build binary archives on dev machine quite rarely and on Linux this issue wasn't reproducible so I didn't notice this issue.
It doesn't make sense to modify .product files. If you run/debug it from Eclipse (jdt) then you can modify any VM parameters right in debug configuration.
Also it is possible to run it in debugger from Intellij IDEA (my favorite Java IDE). But it will require a few additional tricks.

**Comment by codebling** [comment]
If you saw the patch I submitted (PR still coming), you may have spotted that I was using IntelliJ too :)
Product file is just the first hack I found which would allow me to debug. If you're curious to know, here's how I run it: 

![intellij screenshot](https://cloud.githubusercontent.com/assets/1073841/11842855/5d960e26-a3d4-11e5-9865-2bcf388a4322.png)


It's a remote debug configuration which first runs maven `install` goal, then an external tool which launches the DBeaver binary and quits (DBeaver binary listens for debugger because of the altered `.product` file).

**Comment by serge-rider** [comment]
If you use remote debugger (process attach) then, instead of patching .product, you can pass command line parameters to dbeaver executable:
```
dbeaver.exe -vmargs -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=5005
```
In fact it is not a convenient way. You have to spend a lot of time to build executable after every minor change rather than debugging directly from sources. Disgusting.
I run DBeaver directly from Idea. The trick is to find out how Eclipse JDT starts RCP applications from debugger (actual command line) and then use it in Idea debug config. How it looks on one of my dev machines:
![idea-debug-config](https://cloud.githubusercontent.com/assets/6398845/11843280/d3b1e4aa-a419-11e5-8c04-8217d66688af.png)
Another trick: create Idea project from Eclipse .project configs (not from Maven poms).

**Comment by codebling** [comment]
Great! I'll try it !  

You're right, I'm spending a long time building. I'd looked for a way to run the Equinox launcher but I couldn't find it easily. I might try hot reloading the changed classes with the debugger but that doesn't always work well with OSGI. 

I'll try your way or I'll recreate my project from the `.project` files! Thanks!
