### ISSUE TITLE
java.lang.NullPointerException when trying to open Columns data

### ISSUE THREAD

**Issue by gkorland** [serge-rider/dbeaver#1164]
The following error is thrown when clicking on 'columns' (Version 3.8.3 Linux64bit)

![screenshot from 2017-01-19 19-51-18](https://cloud.githubusercontent.com/assets/753206/22118551/f7c1e4f6-de80-11e6-9fc5-d47ef1e18c35.png)

`java.lang.NullPointerException
	at org.jkiss.dbeaver.model.navigator.DBNModel.getNodePath(DBNModel.java:205)
	at org.jkiss.dbeaver.model.navigator.DBNModel.getNodeByPath(DBNModel.java:234)
	at org.jkiss.dbeaver.ui.editors.NodeEditorInputFactory.createElement(NodeEditorInputFactory.java:53)
	at org.eclipse.ui.internal.EditorReference.createInput(EditorReference.java:273)
	at org.eclipse.ui.internal.EditorReference.restoreInput(EditorReference.java:245)
	at org.eclipse.ui.internal.EditorReference.getEditorInput(EditorReference.java:307)
	at org.jkiss.dbeaver.ui.actions.navigator.NavigatorHandlerObjectOpen.openEntityEditor(NavigatorHandlerObjectOpen.java:158)
	at org.jkiss.dbeaver.ui.actions.navigator.NavigatorHandlerObjectOpen.openEntityEditor(NavigatorHandlerObjectOpen.java:128)
	at org.jkiss.dbeaver.ui.navigator.NavigatorUtils.openNavigatorNode(NavigatorUtils.java:594)
	at org.jkiss.dbeaver.ui.navigator.database.NavigatorViewBase$2.doubleClick(NavigatorViewBase.java:151)
	at org.eclipse.jface.viewers.StructuredViewer$1.run(StructuredViewer.java:832)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.eclipse.ui.internal.JFaceUtil$1.run(JFaceUtil.java:50)
	at org.eclipse.jface.util.SafeRunnable.run(SafeRunnable.java:173)
	at org.eclipse.jface.viewers.StructuredViewer.fireDoubleClick(StructuredViewer.java:829)
	at org.eclipse.jface.viewers.AbstractTreeViewer.handleDoubleSelect(AbstractTreeViewer.java:1470)
	at org.eclipse.jface.viewers.StructuredViewer$4.widgetDefaultSelected(StructuredViewer.java:1263)
	at org.eclipse.jface.util.OpenStrategy.fireDefaultSelectionEvent(OpenStrategy.java:252)
	at org.eclipse.jface.util.OpenStrategy.access$0(OpenStrategy.java:249)
	at org.eclipse.jface.util.OpenStrategy$1.handleEvent(OpenStrategy.java:311)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:84)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4481)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1329)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:3819)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3430)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$4.run(PartRenderingEngine.java:1127)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:337)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1018)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:156)
	at org.eclipse.ui.internal.Workbench$5.run(Workbench.java:694)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:337)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:606)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:150)
	at org.jkiss.dbeaver.core.application.DBeaverApplication.start(DBeaverApplication.java:212)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:380)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:235)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:669)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:608)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1515)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1488)
`

**Comment by serge-rider** [comment]
It is a bug in DBeaver. As a workaround - try to close all open editors (one of them seems to have incorrect persistent state).
