### ISSUE TITLE
Cannot open Dbeaver

### ISSUE THREAD

**Issue by nmadham** [serge-rider/dbeaver#1182]
![image](https://cloud.githubusercontent.com/assets/16705400/22256677/85f5b198-e229-11e6-8e80-ccd26d8881e0.png)

Below is the content in .log file...

!SESSION 2017-01-23 09:18:54.108 -----------------------------------------------
eclipse.buildId=unknown
java.version=1.8.0_77
java.vendor=Oracle Corporation
BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=en
Command-line arguments:  -os win32 -ws win32 -arch x86_64

This is a continuation of log file C:\Users\nitesh_madham\.dbeaver\.metadata\.bak_0.log
Created Time: 2017-01-23 10:13:24.521

!ENTRY org.jkiss.dbeaver.model 4 0 2017-01-23 10:13:24.527
!MESSAGE SQL Error [1064] [42000]: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'order by PLTRN_POL_NUM,PLTRN_SEQ' at line 4
!STACK 0
org.jkiss.dbeaver.model.exec.DBCException: SQL Error [1064] [42000]: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'order by PLTRN_POL_NUM,PLTRN_SEQ' at line 4
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCStatementImpl.executeStatement(JDBCStatementImpl.java:141)
	at org.jkiss.dbeaver.runtime.sql.SQLQueryJob.executeSingleQuery(SQLQueryJob.java:344)
	at org.jkiss.dbeaver.runtime.sql.SQLQueryJob.extractData(SQLQueryJob.java:708)
	at org.jkiss.dbeaver.ui.editors.sql.SQLEditor$QueryResultsContainer.readData(SQLEditor.java:1683)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetJobDataRead.run(ResultSetJobDataRead.java:92)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:103)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)
Caused by: com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'order by PLTRN_POL_NUM,PLTRN_SEQ' at line 4
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:425)
	at com.mysql.jdbc.Util.getInstance(Util.java:408)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:943)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3970)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3906)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2524)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2677)
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2545)
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2503)
	at com.mysql.jdbc.StatementImpl.executeInternal(StatementImpl.java:839)
	at com.mysql.jdbc.StatementImpl.execute(StatementImpl.java:739)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCStatementImpl.execute(JDBCStatementImpl.java:345)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCStatementImpl.executeStatement(JDBCStatementImpl.java:138)
	... 6 more
!SUBENTRY 1 org.jkiss.dbeaver.model 4 0 2017-01-23 10:13:24.527
!MESSAGE You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'order by PLTRN_POL_NUM,PLTRN_SEQ' at line 4
!STACK 0
com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'order by PLTRN_POL_NUM,PLTRN_SEQ' at line 4
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:425)
	at com.mysql.jdbc.Util.getInstance(Util.java:408)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:943)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3970)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3906)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2524)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2677)
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2545)
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2503)
	at com.mysql.jdbc.StatementImpl.executeInternal(StatementImpl.java:839)
	at com.mysql.jdbc.StatementImpl.execute(StatementImpl.java:739)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCStatementImpl.execute(JDBCStatementImpl.java:345)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCStatementImpl.executeStatement(JDBCStatementImpl.java:138)
	at org.jkiss.dbeaver.runtime.sql.SQLQueryJob.executeSingleQuery(SQLQueryJob.java:344)
	at org.jkiss.dbeaver.runtime.sql.SQLQueryJob.extractData(SQLQueryJob.java:708)
	at org.jkiss.dbeaver.ui.editors.sql.SQLEditor$QueryResultsContainer.readData(SQLEditor.java:1683)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetJobDataRead.run(ResultSetJobDataRead.java:92)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:103)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)

!ENTRY org.jkiss.dbeaver.model 4 0 2017-01-23 10:13:29.195
!MESSAGE SQL Error [1064] [42000]: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'order by PLTRN_POL_NUM,PLTRN_SEQ' at line 4
!STACK 0

**Comment by serge-rider** [comment]
Please attach whole `.log` file (or send it to me on serge@jkiss.org).
Log above contains just two SQL errors  - that's definitely not the reason why DBeaver doesn't start.
Did this problem appear after version update?

**Comment by nmadham** [comment]
attached is the .log file in the path mentioned.
Yes,this problem appeared after the update.
And its awesome,you guys are really active,I thought I will never going to
get a reply.Thanks for proving me wrong.

Nitesh M
SQL Developer (Contractor)
Windhaven™ Insurance
*8550 33rd Street,Suite 400*
*Doral,FL 3122*
T: (786) 709-4800  Extn-5003

**Comment by serge-rider** [comment]
You didn't attache the log file. You can just drag'n'drop it in GitHub comment.

If you setup from zip archive - make sure you have deleted previous DBeaver version completely before extracting new one.

**Comment by nmadham** [comment]
[log.zip](https://github.com/serge-rider/dbeaver/files/727829/log.zip)

I always used .exe for installation.

![image](https://cloud.githubusercontent.com/assets/16705400/22264752/158d1cb6-e247-11e6-9865-23c202be54a5.png)

**Comment by serge-rider** [comment]
DBeaver workspace was corrupted (can't say why). Sometimes this happens with Eclipse based products (http://stackoverflow.com/questions/37829251/error-loading-workspace-in-eclipse).

Delete directory C:\Users\nitesh_madham\.dbeaver\.metadata\.plugins\org.eclipse.core.resources and start DBeaver.
If this won't help - delete C:\Users\nitesh_madham\.dbeaver\.metadata\.
Note: you may loose some workspace settings (but all scripts/connection configuration will remain).

**Comment by nmadham** [comment]
Perfect..!!
It resolved the issue,you guys are awesome...!!
I believe,DBeaver gonna make markets go crazy soon...!!

**Comment by dkeerthy** [comment]
Iam also having similar issue

**Comment by nmadham** [comment]
@dkeerthy Which version are you trying to install?

**Comment by dkeerthy** [comment]
@nmadham I followed multiple similar issue in this portal and found having multiple instance of java version may cause issue.I have removed one version which is Not needed after which iam able to access.

**Comment by fralyx** [comment]
This just happened to me..
All my work for months listing all customer datas & IDs are all gone
Good god ...

**Comment by serge-rider** [comment]
@fralyx most likely it  is not that bad (unless you have deleted your workspace manually).
1. Try to reset workspace: https://github.com/dbeaver/dbeaver/wiki/Reset-UI-settings
2. Updgrade to the most recent version of DBeaver (it is bundled with proper Java which should solve start problems).

If it won't help - please create new ticket and attach logs (if any) - https://github.com/dbeaver/dbeaver/wiki/Log-files
