### ISSUE TITLE
Cannot execute a query

### ISSUE THREAD

**Issue by nmadham** [serge-rider/dbeaver#1216]
org.jkiss.dbeaver.model.impl.jdbc.JDBCException: SQL Error [HY010]: Invalid state, the Connection object is closed.
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCConnectionImpl.prepareStatement(JDBCConnectionImpl.java:163)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCConnectionImpl.prepareStatement(JDBCConnectionImpl.java:1)
	at org.jkiss.dbeaver.model.DBUtils.createStatement(DBUtils.java:935)
	at org.jkiss.dbeaver.model.DBUtils.makeStatement(DBUtils.java:906)
	at org.jkiss.dbeaver.runtime.sql.SQLQueryJob.executeSingleQuery(SQLQueryJob.java:325)
	at org.jkiss.dbeaver.runtime.sql.SQLQueryJob.extractData(SQLQueryJob.java:708)
	at org.jkiss.dbeaver.ui.editors.sql.SQLEditor$QueryResultsContainer.readData(SQLEditor.java:1686)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetJobDataRead.run(ResultSetJobDataRead.java:92)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:103)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)
Caused by: java.sql.SQLException: Invalid state, the Connection object is closed.
	at net.sourceforge.jtds.jdbc.JtdsConnection.checkOpen(JtdsConnection.java:1744)
	at net.sourceforge.jtds.jdbc.JtdsConnection.prepareStatement(JtdsConnection.java:2448)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCConnectionImpl.prepareStatement(JDBCConnectionImpl.java:199)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCConnectionImpl.prepareStatement(JDBCConnectionImpl.java:131)
	... 9 more

java.sql.SQLException: Invalid state, the Connection object is closed.
	at net.sourceforge.jtds.jdbc.JtdsConnection.checkOpen(JtdsConnection.java:1744)
	at net.sourceforge.jtds.jdbc.JtdsConnection.prepareStatement(JtdsConnection.java:2448)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCConnectionImpl.prepareStatement(JDBCConnectionImpl.java:199)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCConnectionImpl.prepareStatement(JDBCConnectionImpl.java:131)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCConnectionImpl.prepareStatement(JDBCConnectionImpl.java:1)
	at org.jkiss.dbeaver.model.DBUtils.createStatement(DBUtils.java:935)
	at org.jkiss.dbeaver.model.DBUtils.makeStatement(DBUtils.java:906)
	at org.jkiss.dbeaver.runtime.sql.SQLQueryJob.executeSingleQuery(SQLQueryJob.java:325)
	at org.jkiss.dbeaver.runtime.sql.SQLQueryJob.extractData(SQLQueryJob.java:708)
	at org.jkiss.dbeaver.ui.editors.sql.SQLEditor$QueryResultsContainer.readData(SQLEditor.java:1686)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetJobDataRead.run(ResultSetJobDataRead.java:92)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:103)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)

**Comment by nmadham** [comment]
![image](https://cloud.githubusercontent.com/assets/16705400/22517864/94320216-e878-11e6-98cb-45d59f444d7a.png)

**Comment by serge-rider** [comment]
Looks like broken connection.
Any details?

**Comment by nmadham** [comment]
But,when I tried it through another Dbeaver instance it was working good.

Nitesh M
SQL Developer (Contractor)
Windhaven™ Insurance
*8550 33rd Street,Suite 400*
*Doral,FL 3122*
T: (786) 709-4800  Extn-5003

**Comment by nmadham** [comment]
This is completely different but I would like to get this to your
attention,whenever we install a new update ,why installation steps are not
deleting the previous version from my machine.

Nitesh M
SQL Developer (Contractor)
Windhaven™ Insurance
*8550 33rd Street,Suite 400*
*Doral,FL 3122*
T: (786) 709-4800  Extn-5003

**Comment by serge-rider** [comment]
This may be result of anything. If this is reproducible please provide steps to reproduce.

In regards to installer: Windows installer always removes previous version before installation (if it was installed in the same location).

**Comment by ganeshmt** [comment]
ok
