### ISSUE TITLE
SSH key password not prompted for connection with SSH tunneling

### ISSUE THREAD

**Issue by Arakmar** [serge-rider/dbeaver#1222]
I have a connection to a MySQL DB accessed though a SSH tunnel.
It's configured to not remember the password so it asks it every time.

Since 3.8.3, the password isn't asked and the connection fails with the following error :

```
2017-02-02 09:57:39.005 - org.jkiss.dbeaver.model.exec.DBCException: Can't initialize tunnel
org.jkiss.dbeaver.model.exec.DBCException: Can't initialize tunnel
        at org.jkiss.dbeaver.registry.DataSourceDescriptor.connect(DataSourceDescriptor.java:698)
        at org.jkiss.dbeaver.runtime.jobs.ConnectJob.run(ConnectJob.java:74)
        at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:103)
        at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)
Caused by: org.jkiss.dbeaver.DBException: Cannot establish tunnel
        at org.jkiss.dbeaver.model.impl.net.SSHTunnelImpl.initializeTunnel(SSHTunnelImpl.java:159)
        at org.jkiss.dbeaver.registry.DataSourceDescriptor.connect(DataSourceDescriptor.java:696)
        ... 3 more
Caused by: com.jcraft.jsch.JSchException: Auth fail
        at com.jcraft.jsch.Session.connect(Session.java:512)
        at org.jkiss.dbeaver.model.impl.net.SSHTunnelImpl.initializeTunnel(SSHTunnelImpl.java:151)
        ... 4 more
```

**Comment by serge-rider** [comment]
This happens only in case of password protected private key auth.
Thanks for report.
