### ISSUE TITLE
SSH connection refused - Postgresql 95

### ISSUE THREAD

**Issue by jerryhall** [serge-rider/dbeaver#1244]
I'm trying to connect with DBeaver with no success. I am able to access the DB via Putty and Powershell, WinSCP and PGAdmin4.

The only error message I get is "Can't initialize tunnel'

I'm on a Windows7-64 and server is AWS EC2 Centos 6

Thanks much for any help.

**Comment by serge-rider** [comment]
Check debug log (https://github.com/serge-rider/dbeaver/wiki/Log-files) there should be much more SSH-related info.

**Comment by jerryhall** [comment]
Thanks Serge. Here's what I found, which unfortunately I haven't been able to determine the issue. Do you see anything that might help? 

2017-02-08 14:08:57.518 - Connect with 'PostgreSQL - myDBname' (postgres-jdbc-15a1fb10a06-5922e81be6ce3463)
2017-02-08 14:08:57.535 - Instantiate SSH tunnel
2017-02-08 14:08:57.536 - Connect to tunnel host
2017-02-08 14:08:57.538 - SSH INFO: Connecting to myec2IP#.us-west-2.compute.amazon port 22
2017-02-08 14:09:07.544 - Connection failed (postgres-jdbc-15a1fb10a06-5922e81be6ce3463)
2017-02-08 14:09:07.546 - org.jkiss.dbeaver.model.exec.DBCException: Can't initialize tunnel
org.jkiss.dbeaver.model.exec.DBCException: Can't initialize tunnel
	at org.jkiss.dbeaver.registry.DataSourceDescriptor.connect(DataSourceDescriptor.java:698)
	at org.jkiss.dbeaver.runtime.jobs.ConnectJob.run(ConnectJob.java:74)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:103)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)
Caused by: org.jkiss.dbeaver.DBException: Cannot establish tunnel
	at org.jkiss.dbeaver.model.impl.net.SSHTunnelImpl.initializeTunnel(SSHTunnelImpl.java:159)
	at org.jkiss.dbeaver.registry.DataSourceDescriptor.connect(DataSourceDescriptor.java:696)
	... 3 more
Caused by: com.jcraft.jsch.JSchException: timeout: socket is not established
	at com.jcraft.jsch.Util.createSocket(Util.java:394)
	at com.jcraft.jsch.Session.connect(Session.java:215)
	at org.jkiss.dbeaver.model.impl.net.SSHTunnelImpl.initializeTunnel(SSHTunnelImpl.java:151)
	... 4 more
2017-02-08 14:10:36.369 - Shutdown Core...
2017-02-08 14:10:36.650 - Shutdown completed in 281ms

**Comment by serge-rider** [comment]
Looks like connection timeout. 
Try to increase "Tunnel connection timeout" value (to 20000-30000 ms or more).
