### ISSUE TITLE
Cannot connect to Oracle DB

### ISSUE THREAD

**Issue by HJOW** [serge-rider/dbeaver#1305]
With DBeaver Community Edition 4.0.0
I tried to connect oracle DB by both TNS, and Basic type.

I can run DBeaver with java.exe and I get following logs like...

2017-02-22 13:39:18.873 - Connect with 'Oracle - BVS "ONE"' (oracle_thin-158cd
c8351d-3d8f99c743aa6901)
2017-02-22 13:39:19.138 - Connection failed (oracle_thin-158cdc8351d-3d8f99c743a
a6901)
2017-02-22 13:39:19.154 - org.jkiss.dbeaver.DBException: Internal error connecti
ng to Oracle - BVS "ONE"
org.jkiss.dbeaver.DBException: Internal error connecting to Oracle - BVS "ONE"

        at org.jkiss.dbeaver.registry.DataSourceDescriptor.connect(DataSourceDes
criptor.java:766)
        at org.jkiss.dbeaver.runtime.jobs.ConnectJob.run(ConnectJob.java:73)
        at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:102)

        at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)
Caused by: java.lang.NullPointerException
        at org.jkiss.dbeaver.ext.oracle.model.OracleDataSource.initializeContext
State(OracleDataSource.java:144)
        at org.jkiss.dbeaver.model.impl.jdbc.JDBCExecutionContext.connect(JDBCEx
ecutionContext.java:119)
        at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.initializeMainContex
t(JDBCDataSource.java:117)
        at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.<init>(JDBCDataSourc
e.java:111)
        at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.<init>(JDBCDataSourc
e.java:100)
        at org.jkiss.dbeaver.ext.oracle.model.OracleDataSource.<init>(OracleData
Source.java:80)
        at org.jkiss.dbeaver.ext.oracle.OracleDataSourceProvider.openDataSource(
OracleDataSourceProvider.java:131)
        at org.jkiss.dbeaver.registry.DataSourceDescriptor.connect(DataSourceDes
criptor.java:715)
        ... 3 more

**Comment by HJOW** [comment]
Oh no. I found that it is already reported problems on 
https://github.com/serge-rider/dbeaver/issues/1301
