### ISSUE TITLE
v4.0. 1 oracle 8 error Colum "SUPERVIEW_NAME'  doesn´t exist

### ISSUE THREAD

**Issue by luisalb85** [serge-rider/dbeaver#1353]
SELECT TEXT,TYPE_TEXT,OID_TEXT,VIEW_TYPE_OWNER,VIEW_TYPE,SUPERVIEW_NAME
FROM SYS.ALL_VIEWS WHERE OWNER='SYS' AND VIEW_NAME='ALL_CONSTRAINTS'

Solution: Colum "SUPERVIEW_NAME'  doesn´t exist in Oracle 8

java.sql.SQLException: ORA-00904: nombre de columna no valido

	at oracle.jdbc.driver.DatabaseError.throwSqlException(DatabaseError.java:125)

	at oracle.jdbc.driver.T4CTTIoer.processError(T4CTTIoer.java:316)

	at oracle.jdbc.driver.T4CTTIoer.processError(T4CTTIoer.java:282)

	at oracle.jdbc.driver.T4C8Oall.receive(T4C8Oall.java:639)

	at oracle.jdbc.driver.T4CPreparedStatement.doOall8(T4CPreparedStatement.java:185)

	at oracle.jdbc.driver.T4CPreparedStatement.execute_for_describe(T4CPreparedStatement.java:500)

	at oracle.jdbc.driver.T4CPreparedStatement.execute_maybe_describe(T4CPreparedStatement.java:566)

	at oracle.jdbc.driver.OracleStatement.doExecuteWithTimeout(OracleStatement.java:1051)

	at oracle.jdbc.driver.OraclePreparedStatement.executeInternal(OraclePreparedStatement.java:2984)

	at oracle.jdbc.driver.OraclePreparedStatement.executeQuery(OraclePreparedStatement.java:3026)

	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCPreparedStatementImpl.executeQuery(JDBCPreparedStatementImpl.java:230)

	at org.jkiss.dbeaver.ext.oracle.model.OracleView.loadAdditionalInfo(OracleView.java:180)

	at org.jkiss.dbeaver.ext.oracle.model.OracleView.getAdditionalInfo(OracleView.java:155)

	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)

	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)

	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)

	at java.lang.reflect.Method.invoke(Unknown Source)

	at org.jkiss.dbeaver.runtime.properties.ObjectPropertyGroupDescriptor.getGroupObject(ObjectPropertyGroupDescriptor.java:78)

	at org.jkiss.dbeaver.runtime.properties.ObjectPropertyDescriptor.readValue(ObjectPropertyDescriptor.java:217)

	at org.jkiss.dbeaver.runtime.properties.PropertySourceAbstract$PropertySheetLoadService.evaluate(PropertySourceAbstract.java:350)

	at org.jkiss.dbeaver.runtime.properties.PropertySourceAbstract$PropertySheetLoadService.evaluate(PropertySourceAbstract.java:1)

	at org.jkiss.dbeaver.ui.LoadingJob.run(LoadingJob.java:85)

	at org.jkiss.dbeaver.ui.LoadingJob.run(LoadingJob.java:70)

	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:102)

	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)

**Comment by serge-rider** [comment]
Thanks for report
