### ISSUE TITLE
Package navigation (CTRL+Mouse1) not working for Oracle

### ISSUE THREAD

**Issue by cpum** [serge-rider/dbeaver#1354]
Since upgrade to DBeaver 4.0.1 this isn't working anymore (worked fine for me in 3.x).
Steps to reproduce: Connect to Oracle DB, write package name into SQL editor window, then hover over the package name and press CTRL+MOUSE1. Works fine for e.g. tablenames, but not for packages.

I'm using DBeaver (x64) 4.0.1, Oracle Thin client. The following stacktrace is shown in debug logfile:
`
2017-02-27 16:27:20.035 - Can't execute command 'org.jkiss.dbeaver.ext.oracle.code.package.navigate'
org.eclipse.core.commands.NotEnabledException: Trying to execute the disabled command org.jkiss.dbeaver.ext.oracle.code.package.navigate
	at org.eclipse.core.commands.Command.executeWithChecks(Command.java:485)
	at org.eclipse.core.commands.ParameterizedCommand.executeWithChecks(ParameterizedCommand.java:488)
	at org.eclipse.e4.core.commands.internal.HandlerServiceImpl.executeHandler(HandlerServiceImpl.java:210)
	at org.eclipse.ui.internal.handlers.LegacyHandlerService.executeCommandInContext(LegacyHandlerService.java:405)
	at org.jkiss.dbeaver.ui.ActionUtils.runCommand(ActionUtils.java:239)
	at org.jkiss.dbeaver.ui.navigator.NavigatorUtils.executeNodeAction(NavigatorUtils.java:266)
	at org.jkiss.dbeaver.ui.editors.entity.EntityHyperlink$ObjectFinder$1.run(EntityHyperlink.java:98)
	at org.eclipse.swt.widgets.RunnableLock.run(RunnableLock.java:35)
	at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Synchronizer.java:182)
	at org.eclipse.swt.widgets.Display.runAsyncMessages(Display.java:4211)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3827)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$4.run(PartRenderingEngine.java:1121)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:336)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1022)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:150)
	at org.eclipse.ui.internal.Workbench$5.run(Workbench.java:693)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:336)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:610)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:148)
	at org.jkiss.dbeaver.core.application.DBeaverApplication.start(DBeaverApplication.java:166)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:388)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:243)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:673)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:610)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1519)
`

**Comment by serge-rider** [comment]
Can't reproduce.
And it looks like navigation to a particular package procedure - not to a package itself.

Could you provide an example of package name (maybe using some system package/procedure) which doesn't work.

**Comment by cpum** [comment]
Sorry, indeed it's about a procedure, not a package. Another thing to note: Double-clicking the procedure in the database navigator view usually opened the procedure to edit (== pressing F4), right now nothing happens for me if I double-click.

I have tried to reproduce the issue before (pressing CTRL+MOUSE1) with procedure sys.client_ip_address, which yields the following stacktrace:

`
2017-02-27 18:13:54.886 - Can't execute command 'org.jkiss.dbeaver.ext.oracle.code.package.navigate'
org.eclipse.core.commands.NotEnabledException: Trying to execute the disabled command org.jkiss.dbeaver.ext.oracle.code.package.navigate
	at org.eclipse.core.commands.Command.executeWithChecks(Command.java:485)
	at org.eclipse.core.commands.ParameterizedCommand.executeWithChecks(ParameterizedCommand.java:488)
	at org.eclipse.e4.core.commands.internal.HandlerServiceImpl.executeHandler(HandlerServiceImpl.java:210)
	at org.eclipse.ui.internal.handlers.LegacyHandlerService.executeCommandInContext(LegacyHandlerService.java:405)
	at org.jkiss.dbeaver.ui.ActionUtils.runCommand(ActionUtils.java:239)
	at org.jkiss.dbeaver.ui.navigator.NavigatorUtils.executeNodeAction(NavigatorUtils.java:266)
	at org.jkiss.dbeaver.ui.editors.entity.EntityHyperlink$ObjectFinder$1.run(EntityHyperlink.java:98)
	at org.eclipse.swt.widgets.RunnableLock.run(RunnableLock.java:35)
	at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Synchronizer.java:182)
	at org.eclipse.swt.widgets.Display.runAsyncMessages(Display.java:4211)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3827)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$4.run(PartRenderingEngine.java:1121)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:336)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1022)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:150)
	at org.eclipse.ui.internal.Workbench$5.run(Workbench.java:693)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:336)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:610)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:148)
	at org.jkiss.dbeaver.core.application.DBeaverApplication.start(DBeaverApplication.java:166)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:388)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:243)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:673)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:610)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1519)
`

**Comment by serge-rider** [comment]
It is a bug in 4.0, thanks for details.
