### ISSUE TITLE
V 4.0.1 Oracle 8 command not properly ended

### ISSUE THREAD

**Issue by luisalb85** [serge-rider/dbeaver#1355]
SELECT
	c.TABLE_NAME,
	c.CONSTRAINT_NAME,
	c.CONSTRAINT_TYPE,
	c.STATUS,
	c.R_OWNER,
	c.R_CONSTRAINT_NAME,
	ref.TABLE_NAME AS R_TABLE_NAME,
	c.DELETE_RULE,
	col.COLUMN_NAME,
	col.POSITION
FROM
	SYS.ALL_CONSTRAINTS c
----->JOIN SYS.ALL_CONS_COLUMNS col ON
	c.OWNER = col.OWNER
	AND c.CONSTRAINT_NAME = col.CONSTRAINT_NAME
JOIN SYS.ALL_CONSTRAINTS REF ON
	ref.OWNER = c.R_OWNER
	AND ref.CONSTRAINT_NAME = c.R_CONSTRAINT_NAME
WHERE
	c.CONSTRAINT_TYPE = 'R'
	AND c.OWNER = 'AGENTE'
	AND c.TABLE_NAME = 'ACTIVADOR_CONF'
ORDER BY
	c.CONSTRAINT_NAME,
	col.POSITION

org.jkiss.dbeaver.model.exec.DBCException: SQL Error [933] [42000]: ORA-00933: comando SQL no terminado correctamente

	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCPreparedStatementImpl.executeStatement(JDBCPreparedStatementImpl.java:205)

	at org.jkiss.dbeaver.model.impl.jdbc.cache.JDBCCompositeCache.loadObjects(JDBCCompositeCache.java:264)

	at org.jkiss.dbeaver.model.impl.jdbc.cache.JDBCCompositeCache.getObjects(JDBCCompositeCache.java:112)

	at org.jkiss.dbeaver.ext.oracle.model.OracleTableBase.getConstraints(OracleTableBase.java:243)

	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)

	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)

	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)

	at java.lang.reflect.Method.invoke(Unknown Source)

	at org.jkiss.dbeaver.model.navigator.DBNDatabaseNode.extractPropertyValue(DBNDatabaseNode.java:793)

	at org.jkiss.dbeaver.model.navigator.DBNDatabaseNode.loadTreeItems(DBNDatabaseNode.java:479)

	at org.jkiss.dbeaver.model.navigator.DBNDatabaseNode.loadChildren(DBNDatabaseNode.java:403)

	at org.jkiss.dbeaver.model.navigator.DBNDatabaseNode.getChildren(DBNDatabaseNode.java:190)

	at org.jkiss.dbeaver.model.navigator.DBNDatabaseNode.getChildren(DBNDatabaseNode.java:1)

	at org.jkiss.dbeaver.ui.navigator.NavigatorUtils.getNodeChildrenFiltered(NavigatorUtils.java:560)

	at org.jkiss.dbeaver.ui.controls.itemlist.ItemListControl$ItemLoadService.evaluate(ItemListControl.java:216)

	at org.jkiss.dbeaver.ui.controls.itemlist.ItemListControl$ItemLoadService.evaluate(ItemListControl.java:1)

	at org.jkiss.dbeaver.ui.LoadingJob.run(LoadingJob.java:85)

	at org.jkiss.dbeaver.ui.LoadingJob.run(LoadingJob.java:70)

	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:102)

	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)

Caused by: java.sql.SQLException: ORA-00933: comando SQL no terminado correctamente

	at oracle.jdbc.driver.DatabaseError.throwSqlException(DatabaseError.java:125)

	at oracle.jdbc.driver.T4CTTIoer.processError(T4CTTIoer.java:316)

	at oracle.jdbc.driver.T4CTTIoer.processError(T4CTTIoer.java:282)

	at oracle.jdbc.driver.T4C8Oall.receive(T4C8Oall.java:639)

	at oracle.jdbc.driver.T4CPreparedStatement.doOall8(T4CPreparedStatement.java:185)

	at oracle.jdbc.driver.T4CPreparedStatement.execute_for_describe(T4CPreparedStatement.java:500)

	at oracle.jdbc.driver.T4CPreparedStatement.execute_maybe_describe(T4CPreparedStatement.java:566)

	at oracle.jdbc.driver.OracleStatement.doExecuteWithTimeout(OracleStatement.java:1051)

	at oracle.jdbc.driver.OraclePreparedStatement.executeInternal(OraclePreparedStatement.java:2984)

	at oracle.jdbc.driver.OraclePreparedStatement.execute(OraclePreparedStatement.java:3076)

	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCPreparedStatementImpl.execute(JDBCPreparedStatementImpl.java:258)

	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCPreparedStatementImpl.executeStatement(JDBCPreparedStatementImpl.java:202)

	... 19 more

[ALL_CONS_COLUMS_ORACLE8.html.txt](https://github.com/serge-rider/dbeaver/files/804183/ALL_CONS_COLUMS_ORACLE8.html.txt)

[ALL_CONSTRAINTS_ORACLE8.html.txt](https://github.com/serge-rider/dbeaver/files/804171/ALL_CONSTRAINTS_ORACLE8.html.txt)

**Comment by serge-rider** [comment]
I can't figure out what is wrong with that query. All queried columns exist in Oracle 8i.
Could you try to make this query to work:
```sql
SELECT
c.TABLE_NAME, c.CONSTRAINT_NAME, c.CONSTRAINT_TYPE, c.STATUS, c.R_OWNER, c.R_CONSTRAINT_NAME, ref.TABLE_NAME AS R_TABLE_NAME, c.DELETE_RULE, col.COLUMN_NAME, col.POSITION
FROM SYS.ALL_CONSTRAINTS c
JOIN SYS.ALL_CONS_COLUMNS col ON c.OWNER = col.OWNER AND c.CONSTRAINT_NAME = col.CONSTRAINT_NAME
JOIN SYS.ALL_CONSTRAINTS REF ON ref.OWNER = c.R_OWNER AND ref.CONSTRAINT_NAME = c.R_CONSTRAINT_NAME
WHERE c.CONSTRAINT_TYPE = 'R' AND c.OWNER = 'AGENTE' AND c.TABLE_NAME = 'ACTIVADOR_CONF'
ORDER BY c.CONSTRAINT_NAME, col.POSITION
```

Maybe problem is in column name conflict with reserved word (e.g. POSITION or REF) or something like that.

**Comment by luisalb85** [comment]
I don´t understand too. I´ll try tomorrow changing as you say. Curiously in oracle 11 the same sql answers correcly.

**Comment by luisalb85** [comment]
This works on all versions:

SELECT  
c.TABLE_NAME, c.CONSTRAINT_NAME,c.CONSTRAINT_TYPE,c.STATUS,c.R_OWNER,c.R_CONSTRAINT_NAME,ref.TABLE_NAME as R_TABLE_NAME,c.DELETE_RULE, 
col.COLUMN_NAME,col.POSITION
FROM SYS.ALL_CONSTRAINTS c, SYS.ALL_CONS_COLUMNS col,SYS.ALL_CONSTRAINTS ref WHERE c.OWNER=col.OWNER AND c.CONSTRAINT_NAME=col.CONSTRAINT_NAME
  and ref.OWNER=c.r_OWNER AND ref.CONSTRAINT_NAME=c.R_CONSTRAINT_NAME and 
 c.CONSTRAINT_TYPE='R' AND c.OWNER='AGENTE' AND c.TABLE_NAME='ACTIVADOR_CONF'
ORDER BY c.CONSTRAINT_NAME,col.POSITION

**Comment by serge-rider** [comment]
Looks like Oracle doesn't like `REF` identifier as joined table alias.

**Comment by serge-rider** [comment]
Just renewed EA version
