### ISSUE TITLE
Issues cancelling query to Apache Drill

### ISSUE THREAD

**Issue by jaltekruse** [serge-rider/dbeaver#1356]
Hello DBeaver Team,

I am working with Apache Drill and experiencing some issues with cancellation. The drill driver does support the cancel method on the JDBC Statement object, which I have verified in a small JDBC  application. When I cancel a query from DBeaver I am getting an InterruptedException and a cancellation is never sent to the Drill server. The Drill code for handling interruptions does not call cancel on outstanding queries, as a round-trip RPC is rather heavy an operation to perform while handling an interruption. It just throws back a SqlException in response. I have not been able to find specific guidelines in the JDBC spec about how drivers should handle interruptions, but it appears that other drivers have issues with interrupts. From the Oracle docs on multithreaded applications: "Do not use the Thread.interrupt method."
https://docs.oracle.com/database/121/JJDBC/apxtips.htm#JJDBC28950

It appears that the code that is causing this interrupt is in AbstractJob in the cancelling() method. There is a comment there saying specifically "Try to interrupt thread first" and then "Schedule block cancel after timeout (let activeThread.interrupt to finish it's job)". Is it typical for drivers to require interruption before being able to handle a call to cancel? 
https://github.com/serge-rider/dbeaver/blob/171df7641e667f389085b74dea9c873f0ff15a5a/plugins/org.jkiss.dbeaver.model/src/org/jkiss/dbeaver/model/runtime/AbstractJob.java
```
org.jkiss.dbeaver.model.exec.DBCException: SQL Error: Interrupted
    at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCStatementImpl.executeStatement(JDBCStatementImpl.java:140)
    at org.jkiss.dbeaver.model.impl.jdbc.struct.JDBCTable.readData(JDBCTable.java:180)
    at org.jkiss.dbeaver.ui.controls.resultset.ResultSetJobDataRead.run(ResultSetJobDataRead.java:91)
    at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:102)
    at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)
Caused by: java.sql.SQLException: Interrupted
    at org.apache.drill.jdbc.impl.DrillResultSetImpl.execute(DrillResultSetImpl.java:1938)
    at org.apache.drill.jdbc.impl.DrillResultSetImpl.execute(DrillResultSetImpl.java:76)
    at oadd.org.apache.calcite.avatica.AvaticaConnection$1.execute(AvaticaConnection.java:473)
    at org.apache.drill.jdbc.impl.DrillMetaImpl.prepareAndExecute(DrillMetaImpl.java:465)
    at oadd.org.apache.calcite.avatica.AvaticaConnection.prepareAndExecuteInternal(AvaticaConnection.java:477)
    at org.apache.drill.jdbc.impl.DrillConnectionImpl.prepareAndExecuteInternal(DrillConnectionImpl.java:172)
    at oadd.org.apache.calcite.avatica.AvaticaStatement.executeInternal(AvaticaStatement.java:109)
    at oadd.org.apache.calcite.avatica.AvaticaStatement.execute(AvaticaStatement.java:121)
    at org.apache.drill.jdbc.impl.DrillStatementImpl.execute(DrillStatementImpl.java:101)
    at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCStatementImpl.execute(JDBCStatementImpl.java:344)
    at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCStatementImpl.executeStatement(JDBCStatementImpl.java:137)
    ... 4 more
Caused by: java.lang.InterruptedException
    at java.util.concurrent.locks.AbstractQueuedSynchronizer.doAcquireSharedInterruptibly(AbstractQueuedSynchronizer.java:998)
    at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireSharedInterruptibly(AbstractQueuedSynchronizer.java:1304)
    at java.util.concurrent.CountDownLatch.await(CountDownLatch.java:231)
    at org.apache.drill.jdbc.impl.DrillResultSetImpl.execute(DrillResultSetImpl.java:1929)
    ... 14 more
```

**Comment by jaltekruse** [comment]
Hi @serge-rider, thanks for taking a look!

Can you give a brief description of your planned fix? I want to confirm if you think the current Drill behavior seems reasonable, as it is possible we would be able to update the driver if the current behavior is going to cause issues with other JDBC tools as well.

**Comment by serge-rider** [comment]
JDBC API provides a way to cancel running query. But there is no way to ensure that this function is supported by driver. 
Big number of drivers doesn't support it all (they do nothing or throw FeatureNotImplemented). 
Other drivers do not implement query cancel but they use NIO so blocked execution can be interrupted by simple Tread.interrupt.
And some drivers just hang when you call statement cancel function.

That's why DBeaver calls Thread.interrupt before cancel.

One option is to add new driver config option which will say that driver supports query cancelation. So DBeaver won't call interrupt for such drivers.
And I'm still thinking about other options.

Do you have any thoughts about that?

**Comment by jaltekruse** [comment]
I would rather not force you to maintain a list of metadata about each of the drivers, as this would seem to be something that should fall into the domain of the spec itself. Unfortunately trying to search the JDBC spec for both the words "interrupt" and "thread" came up with nothing, which is probably at least partly to blame for the current inconsistency in implementations.

One possibility for fixing our case would be to catch any exceptions thrown after calling interrupt and allow them to be handled (likely just logged) before calling cancel. I can try to do a build of DBeaver with this change to see if it will make this work with the current Drill behavior.

I will also be looking into how the Drill driver behavior is handled by some other tools to see if this is a problem we are likely going to hit with a variety of clients.

**Comment by jaltekruse** [comment]
@serge-rider Your suggestion to add a new property to driver configuration sounds good. I think with the variety of different cases you described, it is not possible to come up with a single code path that will work for all tools. Let us know if you need help making the changes, my team would like to get this incorporated into DBeaver soon if possible and we can try to provide a patch given some pointers on the code that needs modifying.

**Comment by serge-rider** [comment]
Another option:
1. call cancel
2. wait for some time (e.g. 2-5 secs)
3. if blocked thread is still blocked - call Thread.interrupt

Will try that and probably fix will will be included in 4.0.3

**Comment by serge-rider** [comment]
You can try new approach in EA version (http://dbeaver.jkiss.org/files/ea/)

**Comment by jaltekruse** [comment]
@serge-rider Thank you for the quick turnaround! I have tested Drill with the EA build and I was able to successfully cancel a long running query. I'll close the issue as resolved.
