### ISSUE TITLE
4.0.1 Error duplicate key when clone record. Postgresql.

### ISSUE THREAD

**Issue by greenpeas** [serge-rider/dbeaver#1370]
4.0.1
Postgresql 9.5. Windows 10 x64. Table has unique column "ID" UUID type.
1. Select table, Data tab.
2. Select item.
3. Press Ctrl+Alt+Ins for clone item.
4. Edit "ID" value for cloned item.
5. Press Ctrl+Alt+S for save.
Error duplicate key for column "ID".
`CREATE EXTENSION IF NOT EXISTS "uuid-ossp";`
`create table "TEST"(
    "ID" UUID primary key default uuid_generate_v4(),
    "CODE" int null default null
);`
`insert into "TEST" ("CODE") values (1),(2);`
![image](https://cloud.githubusercontent.com/assets/3856344/23452891/1ff633b2-fe77-11e6-90af-c71c552d10fb.png)
![image](https://cloud.githubusercontent.com/assets/3856344/23452925/3b5f1786-fe77-11e6-9592-c0a01429d47d.png)

**Comment by serge-rider** [comment]
Can't reproduce. UUID values are copied in the same fashion as any other data types.
Post table DDL, maybe there are some tricks with default/auto-generated values?

**Comment by greenpeas** [comment]
I send email for you.
Generate SQL on first screenshot

**Comment by serge-rider** [comment]
Ah, sorry, missed that.

I saw some similar issue with numeric auto-increment columns. Will check it..

**Comment by greenpeas** [comment]
I can provide access to the my computer via TeamViewer.
Telegram @artyomov (https://t.me/artyomov)

**Comment by greenpeas** [comment]
I use uuid-ossp EXT:
`CREATE EXTENSION IF NOT EXISTS "uuid-ossp";`

**Comment by serge-rider** [comment]
Thanks, hopefully teamviewer won't be needed.

I think this is similar issue: #398
You copying the row with ID
Then change original row ID

On save PG inserts new row with same ID as your old row and THEN change old row id. And, obviously, fails on the first step.

Or am I missing something?

**Comment by greenpeas** [comment]
Yes. It turns out that I edited line donor record.
This is because of that a cloned line appears above the donor. I intuitively edit bottom line.
But now, when I edit green line, I get a syntax error on Refresh rows:
![image](https://cloud.githubusercontent.com/assets/3856344/23506256/69c306fa-ff58-11e6-8a64-11c6fef61efc.png)
...and insert is successfully.

**Comment by serge-rider** [comment]
Ok.

Interesting error though. "Refresh rows" action executed after table update (to get new values updated on server). It shouldn't fail ever.
Could you post error details (and failed query - you can get it in Query Manager view).

**Comment by greenpeas** [comment]
Query Manager view is empty after error message:
![image](https://cloud.githubusercontent.com/assets/3856344/23506830/3d8f7de0-ff5b-11e6-879c-54c0fe9e6495.png)
failed query dont logged.
And after F5:
![image](https://cloud.githubusercontent.com/assets/3856344/23506886/79000d0e-ff5b-11e6-8231-ce6ac4572457.png)

**Comment by greenpeas** [comment]
`!ENTRY org.jkiss.dbeaver.model 4 0 2017-03-02 15:15:11.966
!MESSAGE SQL Error [42601]: ERROR: syntax error at or near "aa"
  Позиция: 59
!STACK 0
org.jkiss.dbeaver.model.exec.DBCException: SQL Error [42601]: ERROR: syntax error at or near "aa"
  Позиция: 59
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCStatementImpl.executeStatement(JDBCStatementImpl.java:140)
	at org.jkiss.dbeaver.model.impl.jdbc.struct.JDBCTable.readData(JDBCTable.java:180)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetPersister$RowRefreshJob.run(ResultSetPersister.java:820)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:102)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)
Caused by: org.postgresql.util.PSQLException: ERROR: syntax error at or near "aa"
  Позиция: 59
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2458)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2158)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:291)
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:432)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:358)
	at org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:305)
	at org.postgresql.jdbc.PgStatement.executeCachedSql(PgStatement.java:291)
	at org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:269)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:265)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCStatementImpl.execute(JDBCStatementImpl.java:344)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCStatementImpl.executeStatement(JDBCStatementImpl.java:137)
	... 4 more
!SUBENTRY 1 org.jkiss.dbeaver.model 4 0 2017-03-02 15:15:11.966
!MESSAGE ERROR: syntax error at or near "aa"
  Позиция: 59
!STACK 0
org.postgresql.util.PSQLException: ERROR: syntax error at or near "aa"
  Позиция: 59
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2458)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2158)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:291)
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:432)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:358)
	at org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:305)
	at org.postgresql.jdbc.PgStatement.executeCachedSql(PgStatement.java:291)
	at org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:269)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:265)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCStatementImpl.execute(JDBCStatementImpl.java:344)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCStatementImpl.executeStatement(JDBCStatementImpl.java:137)
	at org.jkiss.dbeaver.model.impl.jdbc.struct.JDBCTable.readData(JDBCTable.java:180)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetPersister$RowRefreshJob.run(ResultSetPersister.java:820)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:102)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)`

**Comment by serge-rider** [comment]
Thanks, I found the bug.

**Comment by greenpeas** [comment]
Super. Good luck!
