### ISSUE TITLE
v 4.0.1   errors on Oracle 8 DB with explicit JOIN

### ISSUE THREAD

**Issue by luisalb85** [serge-rider/dbeaver#1376]
I think these are the latest to fix , (  I hope ):

1.- [933] ORA-00933

SELECT  i.OWNER,i.INDEX_NAME,i.INDEX_TYPE,i.TABLE_OWNER,i.TABLE_NAME,i.UNIQUENESS,i.TABLESPACE_NAME,i.STATUS,i.NUM_ROWS,i.SAMPLE_SIZE,
ic.COLUMN_NAME,ic.COLUMN_POSITION,ic.COLUMN_LENGTH,ic.DESCEND
FROM SYS.ALL_INDEXES i 
JOIN SYS.ALL_IND_COLUMNS ic ON ic.INDEX_OWNER=i.OWNER AND ic.INDEX_NAME=i.INDEX_NAME
WHERE  i.TABLE_OWNER='CORRECTIVO_IRM' AND i.TABLE_NAME='ALARMAS_ACTIVAS'
ORDER BY i.INDEX_NAME,ic.COLUMN_POSITION
[933] ORA-00933: comando SQL no terminado correctamente

java.sql.SQLException: ORA-00933: comando SQL no terminado correctamente

	at oracle.jdbc.driver.DatabaseError.throwSqlException(DatabaseError.java:125)

	at oracle.jdbc.driver.T4CTTIoer.processError(T4CTTIoer.java:316)

	at oracle.jdbc.driver.T4CTTIoer.processError(T4CTTIoer.java:282)

	at oracle.jdbc.driver.T4C8Oall.receive(T4C8Oall.java:639)

	at oracle.jdbc.driver.T4CPreparedStatement.doOall8(T4CPreparedStatement.java:185)

	at oracle.jdbc.driver.T4CPreparedStatement.execute_for_describe(T4CPreparedStatement.java:500)

	at oracle.jdbc.driver.T4CPreparedStatement.execute_maybe_describe(T4CPreparedStatement.java:566)

	at oracle.jdbc.driver.OracleStatement.doExecuteWithTimeout(OracleStatement.java:1051)

	at oracle.jdbc.driver.OraclePreparedStatement.executeInternal(OraclePreparedStatement.java:2984)

	at oracle.jdbc.driver.OraclePreparedStatement.execute(OraclePreparedStatement.java:3076)

	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCPreparedStatementImpl.execute(JDBCPreparedStatementImpl.java:258)

	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCPreparedStatementImpl.executeStatement(JDBCPreparedStatementImpl.java:202)

	at org.jkiss.dbeaver.model.impl.jdbc.cache.JDBCCompositeCache.loadObjects(JDBCCompositeCache.java:264)

	at org.jkiss.dbeaver.model.impl.jdbc.cache.JDBCCompositeCache.getObject(JDBCCompositeCache.java:146)

	at org.jkiss.dbeaver.ext.oracle.model.OracleSchema$ForeignKeyCache.loadObjects(OracleSchema.java:527)

	at org.jkiss.dbeaver.ext.oracle.model.OracleSchema$ForeignKeyCache.loadObjects(OracleSchema.java:1)

	at org.jkiss.dbeaver.model.impl.jdbc.cache.JDBCCompositeCache.getObjects(JDBCCompositeCache.java:112)

	at org.jkiss.dbeaver.ext.oracle.model.OracleTable.getReferences(OracleTable.java:175)

	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)

	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)

	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)

	at java.lang.reflect.Method.invoke(Unknown Source)

	at org.jkiss.dbeaver.model.navigator.DBNDatabaseNode.extractPropertyValue(DBNDatabaseNode.java:793)

	at org.jkiss.dbeaver.model.navigator.DBNDatabaseNode.loadTreeItems(DBNDatabaseNode.java:479)

	at org.jkiss.dbeaver.model.navigator.DBNDatabaseNode.loadChildren(DBNDatabaseNode.java:403)

	at org.jkiss.dbeaver.model.navigator.DBNDatabaseNode.getChildren(DBNDatabaseNode.java:190)

	at org.jkiss.dbeaver.model.navigator.DBNDatabaseNode.getChildren(DBNDatabaseNode.java:1)

	at org.jkiss.dbeaver.ui.navigator.NavigatorUtils.getNodeChildrenFiltered(NavigatorUtils.java:560)

	at org.jkiss.dbeaver.ui.controls.itemlist.ItemListControl$ItemLoadService.evaluate(ItemListControl.java:216)

	at org.jkiss.dbeaver.ui.controls.itemlist.ItemListControl$ItemLoadService.evaluate(ItemListControl.java:1)

	at org.jkiss.dbeaver.ui.LoadingJob.run(LoadingJob.java:85)

	at org.jkiss.dbeaver.ui.LoadingJob.run(LoadingJob.java:70)

	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:102)

	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)

2.- [933] ORA-00933

SELECT 
c.TABLE_NAME, c.CONSTRAINT_NAME,c.CONSTRAINT_TYPE,c.STATUS,c.SEARCH_CONDITION,col.COLUMN_NAME,col.POSITION
FROM SYS.ALL_CONSTRAINTS c
JOIN SYS.ALL_CONS_COLUMNS col ON c.OWNER=col.OWNER AND c.CONSTRAINT_NAME=col.CONSTRAINT_NAME
WHERE c.CONSTRAINT_TYPE<>'R' AND c.OWNER='CORRECTIVO_IRM' AND c.TABLE_NAME='ALARMAS_ACTIVAS'
ORDER BY c.CONSTRAINT_NAME,col.POSITION
[933] ORA-00933: comando SQL no terminado correctamente

java.sql.SQLException: ORA-00933: comando SQL no terminado correctamente

	at oracle.jdbc.driver.DatabaseError.throwSqlException(DatabaseError.java:125)

	at oracle.jdbc.driver.T4CTTIoer.processError(T4CTTIoer.java:316)

	at oracle.jdbc.driver.T4CTTIoer.processError(T4CTTIoer.java:282)

	at oracle.jdbc.driver.T4C8Oall.receive(T4C8Oall.java:639)

	at oracle.jdbc.driver.T4CPreparedStatement.doOall8(T4CPreparedStatement.java:185)

	at oracle.jdbc.driver.T4CPreparedStatement.execute_for_describe(T4CPreparedStatement.java:500)

	at oracle.jdbc.driver.T4CPreparedStatement.execute_maybe_describe(T4CPreparedStatement.java:566)

	at oracle.jdbc.driver.OracleStatement.doExecuteWithTimeout(OracleStatement.java:1051)

	at oracle.jdbc.driver.OraclePreparedStatement.executeInternal(OraclePreparedStatement.java:2984)

	at oracle.jdbc.driver.OraclePreparedStatement.execute(OraclePreparedStatement.java:3076)

	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCPreparedStatementImpl.execute(JDBCPreparedStatementImpl.java:258)

	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCPreparedStatementImpl.executeStatement(JDBCPreparedStatementImpl.java:202)

	at org.jkiss.dbeaver.model.impl.jdbc.cache.JDBCCompositeCache.loadObjects(JDBCCompositeCache.java:264)

	at org.jkiss.dbeaver.model.impl.jdbc.cache.JDBCCompositeCache.getObject(JDBCCompositeCache.java:146)

	at org.jkiss.dbeaver.ext.oracle.model.OracleSchema$ForeignKeyCache.loadObjects(OracleSchema.java:527)

	at org.jkiss.dbeaver.ext.oracle.model.OracleSchema$ForeignKeyCache.loadObjects(OracleSchema.java:1)

	at org.jkiss.dbeaver.model.impl.jdbc.cache.JDBCCompositeCache.getObjects(JDBCCompositeCache.java:112)

	at org.jkiss.dbeaver.ext.oracle.model.OracleTable.getReferences(OracleTable.java:175)

	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)

	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)

	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)

	at java.lang.reflect.Method.invoke(Unknown Source)

	at org.jkiss.dbeaver.model.navigator.DBNDatabaseNode.extractPropertyValue(DBNDatabaseNode.java:793)

	at org.jkiss.dbeaver.model.navigator.DBNDatabaseNode.loadTreeItems(DBNDatabaseNode.java:479)

	at org.jkiss.dbeaver.model.navigator.DBNDatabaseNode.loadChildren(DBNDatabaseNode.java:403)

	at org.jkiss.dbeaver.model.navigator.DBNDatabaseNode.getChildren(DBNDatabaseNode.java:190)

	at org.jkiss.dbeaver.model.navigator.DBNDatabaseNode.getChildren(DBNDatabaseNode.java:1)

	at org.jkiss.dbeaver.ui.navigator.NavigatorUtils.getNodeChildrenFiltered(NavigatorUtils.java:560)

	at org.jkiss.dbeaver.ui.controls.itemlist.ItemListControl$ItemLoadService.evaluate(ItemListControl.java:216)

	at org.jkiss.dbeaver.ui.controls.itemlist.ItemListControl$ItemLoadService.evaluate(ItemListControl.java:1)

	at org.jkiss.dbeaver.ui.LoadingJob.run(LoadingJob.java:85)

	at org.jkiss.dbeaver.ui.LoadingJob.run(LoadingJob.java:70)

	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:102)

	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)

**Comment by serge-rider** [comment]
Obviously Oracle 8i doesn't like explicit joins. I'll check all of them.

**Comment by luisalb85** [comment]
OK, thank very much for your patience and your excellent work. 

If helps you, I´ll put here the cases I found and I ´ll open a new issue with the problem of DBMS_METADATA

SELECT P.*,CASE WHEN A.DATA_TYPE IS NULL THEN 'PROCEDURE' ELSE 'FUNCTION' END as PROCEDURE_TYPE FROM ALL_PROCEDURES P
LEFT OUTER JOIN ALL_ARGUMENTS A ON A.OWNER=P.OWNER AND A.PACKAGE_NAME=P.OBJECT_NAME AND A.OBJECT_NAME=P.PROCEDURE_NAME AND A.ARGUMENT_NAME IS NULL AND A.DATA_LEVEL=0
WHERE P.OWNER='AGENTE' AND P.OBJECT_NAME='PKG_PARTIC_AGENTE'
ORDER BY P.PROCEDURE_NAME

**Comment by luisalb85** [comment]
SELECT  s.*,O.OBJECT_TYPE 
FROM ALL_SYNONYMS S
JOIN ALL_OBJECTS O ON  O.OWNER=S.TABLE_OWNER AND O.OBJECT_NAME=S.TABLE_NAME
WHERE S.OWNER='AGENTE' AND O.OBJECT_TYPE NOT IN ('JAVA CLASS','PACKAGE BODY')
ORDER BY S.SYNONYM_NAME

**Comment by serge-rider** [comment]
BTW could you test how it will work after replacing "JOIN" with "INNER JOIN"?

**Comment by luisalb85** [comment]
Same result

SELECT 
c.TABLE_NAME, c.CONSTRAINT_NAME,c.CONSTRAINT_TYPE,c.STATUS,c.SEARCH_CONDITION,col.COLUMN_NAME,col.POSITION
FROM SYS.ALL_CONSTRAINTS c
INNER JOIN SYS.ALL_CONS_COLUMNS col ON c.OWNER=col.OWNER AND c.CONSTRAINT_NAME=col.CONSTRAINT_NAME
WHERE c.CONSTRAINT_TYPE<>'R' AND c.OWNER='CORRECTIVO_IRM' AND c.TABLE_NAME='ALARMAS_ACTIVAS'
ORDER BY c.CONSTRAINT_NAME,col.POSITION

[933] ORA-00933: comando SQL no terminado correctamente
