### ISSUE TITLE
dbeaver 4.0.2 - Internal error (java.lang.NullPointerException) occurred - Flat files (CSV) / CSV/DBF

### ISSUE THREAD

**Issue by 4llan** [serge-rider/dbeaver#1377]
After upgrading DBeaver, every .CSV table that I try to read gives me the following message:
`An internal error occurred during: "Read data [CSV table]".`

Version 4.0.2
```eclipse.buildId=unknown
java.version=1.8.0_121
java.vendor=Oracle Corporation
BootLoader constants: OS=linux, ARCH=x86_64, WS=gtk, NL=en_US
Command-line arguments:  -os linux -ws gtk -arch x86_64
```

Exception Stack Trace:
```java.lang.NullPointerException
	at java.lang.String.indexOf(String.java:1718)
	at java.lang.String.indexOf(String.java:1698)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCColumnMetaData.<init>(JDBCColumnMetaData.java:125)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCColumnMetaData.<init>(JDBCColumnMetaData.java:69)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCResultSetMetaDataImpl.createColumnMetaDataImpl(JDBCResultSetMetaDataImpl.java:57)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCResultSetMetaDataImpl.<init>(JDBCResultSetMetaDataImpl.java:51)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCFactoryDefault.createResultSetMetaData(JDBCFactoryDefault.java:58)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCResultSetImpl.createMetaDataImpl(JDBCResultSetImpl.java:1682)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCResultSetImpl.getMeta(JDBCResultSetImpl.java:228)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCResultSetImpl.getMeta(JDBCResultSetImpl.java:1)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetDataReceiver.fetchStart(ResultSetDataReceiver.java:84)
	at org.jkiss.dbeaver.model.impl.jdbc.struct.JDBCTable.readData(JDBCTable.java:186)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetJobDataRead.run(ResultSetJobDataRead.java:91)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:102)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)
```

**Comment by serge-rider** [comment]
Can't reproduce.
Maybe it is the same problem as in #1371 - try to re-download DBeaver 4.0.2 again.

**Comment by 4llan** [comment]
@serge-rider, purged my installation of dbeaver, reinstalled, created an connection to CSV, tried to read the data and the error persists.

I'm on Arch Linux, download via [AUR](https://aur.archlinux.org/packages/dbeaver/), my CSV files is separated with semicolon ";" and this is configured within the driver properties.

Will check later a fresh installation of dbeaver in another computer.

**Comment by serge-rider** [comment]
Umm, not the first time when AUR package differs from release version on the site. Now they build from sources and take sources from latest release source archive on GitHub. It is outdated a bit. I'll try to fix this.

Meanwhile you can try to download from http://dbeaver.jkiss.org/download/

**Comment by serge-rider** [comment]
Just changed 4.0.2 tag on Github, Now AUR package should be fine too.

**Comment by oulenz** [comment]
I had the same issue and I can confirm that re-installing 4.0.2 helped for me (downloaded directly from dbeaver.jkiss.org both times).
