### ISSUE TITLE
V 4.0.2 problems with DBMS_METADATA at Oracle 8i DB

### ISSUE THREAD

**Issue by luisalb85** [serge-rider/dbeaver#1379]
3.- [6550] ORA-06550  PLS-00201

begin DBMS_METADATA.SET_TRANSFORM_PARAM(DBMS_METADATA.SESSION_TRANSFORM,'STORAGE',true); end;
[6550] ORA-06550: linea 1, columna 41:
PLS-00201: el identificador 'DBMS_METADATA.SESSION_TRANSFORM' debe declararse
ORA-06550: linea 1, columna 7:
PL/SQL: Statement ignored

java.sql.SQLException: ORA-06550: linea 1, columna 41:
PLS-00201: el identificador 'DBMS_METADATA.SESSION_TRANSFORM' debe declararse
ORA-06550: linea 1, columna 7:
PL/SQL: Statement ignored

	at oracle.jdbc.driver.DatabaseError.throwSqlException(DatabaseError.java:125)

	at oracle.jdbc.driver.T4CTTIoer.processError(T4CTTIoer.java:316)

	at oracle.jdbc.driver.T4CTTIoer.processError(T4CTTIoer.java:282)

	at oracle.jdbc.driver.T4C8Oall.receive(T4C8Oall.java:639)

	at oracle.jdbc.driver.T4CCallableStatement.doOall8(T4CCallableStatement.java:184)

	at oracle.jdbc.driver.T4CCallableStatement.execute_for_rows(T4CCallableStatement.java:873)

	at oracle.jdbc.driver.OracleStatement.doExecuteWithTimeout(OracleStatement.java:1086)

	at oracle.jdbc.driver.OraclePreparedStatement.executeInternal(OraclePreparedStatement.java:2984)

	at oracle.jdbc.driver.OraclePreparedStatement.execute(OraclePreparedStatement.java:3076)

	at oracle.jdbc.driver.OracleCallableStatement.execute(OracleCallableStatement.java:4273)

	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCPreparedStatementImpl.execute(JDBCPreparedStatementImpl.java:258)

	at org.jkiss.dbeaver.model.impl.jdbc.JDBCUtils.executeProcedure(JDBCUtils.java:583)

	at org.jkiss.dbeaver.ext.oracle.model.OracleUtils.getDDL(OracleUtils.java:71)

	at org.jkiss.dbeaver.ext.oracle.model.OracleTableBase.getDDL(OracleTableBase.java:272)

	at org.jkiss.dbeaver.ext.oracle.model.OracleTable.getObjectDefinitionText(OracleTable.java:233)

	at org.jkiss.dbeaver.ui.editors.sql.SQLSourceViewer.getSourceText(SQLSourceViewer.java:53)

	at org.jkiss.dbeaver.ui.editors.sql.SQLEditorNested$ObjectDocumentProvider$1.run(SQLEditorNested.java:230)

	at org.jkiss.dbeaver.runtime.TasksJob.run(TasksJob.java:60)

	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:102)

	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)

**Comment by infectormp** [comment]
Please update to 4.0.2

**Comment by luisalb85** [comment]
Updated to 4.0.2, error persists

begin DBMS_METADATA.SET_TRANSFORM_PARAM(DBMS_METADATA.SESSION_TRANSFORM,'STORAGE',true); end;

[6550] ORA-06550: linea 1, columna 41:
PLS-00201: el identificador 'DBMS_METADATA.SESSION_TRANSFORM' debe declararse
ORA-06550: linea 1, columna 7:
PL/SQL: Statement ignored


	at oracle.jdbc.driver.DatabaseError.throwSqlException(DatabaseError.java:125)

	at oracle.jdbc.driver.T4CTTIoer.processError(T4CTTIoer.java:316)

	at oracle.jdbc.driver.T4CTTIoer.processError(T4CTTIoer.java:282)

	at oracle.jdbc.driver.T4C8Oall.receive(T4C8Oall.java:639)

	at oracle.jdbc.driver.T4CCallableStatement.doOall8(T4CCallableStatement.java:184)

	at oracle.jdbc.driver.T4CCallableStatement.execute_for_rows(T4CCallableStatement.java:873)

	at oracle.jdbc.driver.OracleStatement.doExecuteWithTimeout(OracleStatement.java:1086)

	at oracle.jdbc.driver.OraclePreparedStatement.executeInternal(OraclePreparedStatement.java:2984)

	at oracle.jdbc.driver.OraclePreparedStatement.execute(OraclePreparedStatement.java:3076)

	at oracle.jdbc.driver.OracleCallableStatement.execute(OracleCallableStatement.java:4273)

	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCPreparedStatementImpl.execute(JDBCPreparedStatementImpl.java:258)

	at org.jkiss.dbeaver.model.impl.jdbc.JDBCUtils.executeProcedure(JDBCUtils.java:583)

	at org.jkiss.dbeaver.ext.oracle.model.OracleUtils.getDDL(OracleUtils.java:71)

	at org.jkiss.dbeaver.ext.oracle.model.OracleTableBase.getDDL(OracleTableBase.java:272)

	at org.jkiss.dbeaver.ext.oracle.model.OracleTable.getObjectDefinitionText(OracleTable.java:233)

	at org.jkiss.dbeaver.ui.editors.sql.SQLSourceViewer.getSourceText(SQLSourceViewer.java:53)

	at org.jkiss.dbeaver.ui.editors.sql.SQLEditorNested$ObjectDocumentProvider$1.run(SQLEditorNested.java:230)

	at org.jkiss.dbeaver.runtime.TasksJob.run(TasksJob.java:60)

	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:102)

	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)
