### ISSUE TITLE
Concurrent modification exception

### ISSUE THREAD

**Issue by codebling** [serge-rider/dbeaver#139]
```
java.util.ConcurrentModificationException
	at java.util.ArrayList$Itr.checkForComodification(Unknown Source)
	at java.util.ArrayList$Itr.next(Unknown Source)
	at org.jkiss.dbeaver.ui.actions.datasource.DataSourceHandler.connectToDataSource(DataSourceHandler.java:92)
	at org.jkiss.dbeaver.registry.DataSourceDescriptor.initConnection(DataSourceDescriptor.java:551)
	at org.jkiss.dbeaver.model.navigator.DBNDataSource.initializeNode(DBNDataSource.java:123)
	at org.jkiss.dbeaver.model.navigator.DBNDatabaseNode.getChildren(DBNDatabaseNode.java:182)
	at org.jkiss.dbeaver.ui.navigator.database.load.TreeLoadService.evaluate(TreeLoadService.java:57)
	at org.jkiss.dbeaver.ui.navigator.database.load.TreeLoadService.evaluate(TreeLoadService.java:1)
	at org.jkiss.dbeaver.runtime.load.jobs.LoadingJob.run(LoadingJob.java:76)
	at org.jkiss.dbeaver.runtime.load.jobs.LoadingJob.run(LoadingJob.java:63)
	at org.jkiss.dbeaver.runtime.AbstractJob.run(AbstractJob.java:100)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)
```

More details to follow

**Comment by codebling** [comment]
Seems to only occur in conjunction with #142. Will close this now and can retest after #142 is fixed.

**Comment by codebling** [comment]
I managed to reproduce this. Something to do with SSH Tunnel saved passwords. I have a procedure, but it's long. 

It seems like there is an issue with this connection now. I close DBeaver, then open it and immediately attempt to open that connection. It prompts for my SSH tunnel password. I enter anything and get the exception.

Here is the connection from `dbeaver-data-sources.xml`:
```
	<data-source id="teradata-15204473ae9-9bc48e1a0e0e0d6" provider="generic" driver="teradata" name="Teradata - jkl" create-date="1451770755754" update-date="1451770915571" save-password="true" show-system-objects="true" read-only="false">
		<connection host="localhost" server="" database="jkl" url="jdbc:teradata://localhost/jkl" user="jkl" password="GAhmwQ==" type="dev">
			<network-handler type="TUNNEL" id="ssh_tunnel" enabled="true" user="root" save-password="false">
				<property name="port" value="22"/>
				<property name="keyPath" value=""/>
				<property name="host" value="teradata.testing.dbeaver.com"/>
				<property name="authType" value="PASSWORD"/>
			</network-handler>
			<network-handler type="PROXY" id="socks_proxy" enabled="false" user="" save-password="false">
				<property name="socks-host" value=""/>
				<property name="socks-port" value="1080"/>
			</network-handler>
			<bootstrap/>
		</connection>
	</data-source>
```

**Comment by serge-rider** [comment]
Thanks for report!
