### ISSUE TITLE
Handle Hive arrays

### ISSUE THREAD

**Issue by Dubrzr** [serge-rider/dbeaver#1409]
Version of DBeaver: 4.0.1 on Ubuntu 16.04

DBeaver seems not to be able to handle hive's arrays.

I have multiple columns such as:

- gain ARRAY\<FLOAT\>
- units ARRAY\<STRING\>
- baseline ARRAY\<INT\>

and the displayed value in DBeaver when browsing tables is "NULL". Plus I have the following warning:

```
Unsupported array type: java.lang.String
org.jkiss.dbeaver.model.exec.DBCException: Unsupported array type: java.lang.String
	at org.jkiss.dbeaver.model.impl.jdbc.data.handlers.JDBCArrayValueHandler.getValueFromObject(JDBCArrayValueHandler.java:61)
	at org.jkiss.dbeaver.model.impl.jdbc.data.handlers.JDBCArrayValueHandler.getValueFromObject(JDBCArrayValueHandler.java:1)
	at org.jkiss.dbeaver.model.impl.jdbc.data.handlers.JDBCComplexValueHandler.fetchColumnValue(JDBCComplexValueHandler.java:50)
	at org.jkiss.dbeaver.model.impl.jdbc.data.handlers.JDBCAbstractValueHandler.fetchValueObject(JDBCAbstractValueHandler.java:49)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetDataReceiver.fetchRow(ResultSetDataReceiver.java:106)
	at org.jkiss.dbeaver.model.impl.jdbc.struct.JDBCTable.readData(JDBCTable.java:195)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetJobDataRead.run(ResultSetJobDataRead.java:91)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:102)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)

```

Do you think it could be possible to handle arrays?

Thanks!

**Comment by Au80** [comment]
I have the same question, but how to fix it?

**Comment by serge-rider** [comment]
Each driver has its own specific arrays implementation. I can't make full arrays support for Hive right now but at least I will try to show values.

**Comment by serge-rider** [comment]
Please check fix in EA version (http://dbeaver.jkiss.org/files/ea/)

**Comment by Dubrzr** [comment]
Warnings are gone, but it still display array entries as NULL:

![reg](https://cloud.githubusercontent.com/assets/3718838/23835474/30179c46-0768-11e7-9527-2d505f2d81ce.png)
![hnntyujuy](https://cloud.githubusercontent.com/assets/3718838/23835475/31cd17be-0768-11e7-9c06-b838e79faec3.png)

Thanks a lot for your work! 🥇

**Comment by serge-rider** [comment]
I can't reproduce that :(
Please post some DDL/inserts

**Comment by Dubrzr** [comment]
Ok I'll check tomorrow ;)

**Comment by Dubrzr** [comment]
I can't make it work.
```
CREATE TABLE mimic3.record(
	id BIGINT,
	signame ARRAY<STRING>
);
CREATE TABLE mimic3.dummy(
	id BIGINT
);
INSERT INTO TABLE mimic3.dummy values (1);
INSERT INTO TABLE mimic3.record SELECT 1, array('a','b') from mimic3.dummy;
```

Then it displays:
![htr](https://cloud.githubusercontent.com/assets/3718838/23856467/469dd9ea-07e9-11e7-9d70-f0d6a631ff61.png)

I see one difference that may explain the problem, it is with the picture in this issue: https://github.com/serge-rider/dbeaver/issues/403#issuecomment-222460894 where we can see that the element editor on the right displays one row by values, whereas in my screenshots we can see that it display all the array in one row only.

**Comment by serge-rider** [comment]
Hive driver doesn't support JDBC array but returns arrays as strings. I did some basic string->array translation. This should work ok in read-only mode.

**Comment by Dubrzr** [comment]
It works perfectly!! Thank you very much!!

**Comment by sidSingla** [comment]
I am also facing the same issue on latest DBeaver release. What is the solution to it ?

**Comment by serge-rider** [comment]
@sidSingla Please post error/debug log (https://github.com/dbeaver/dbeaver/wiki/Log-files)

**Comment by Espanta** [comment]
Same here. in version 5.1.4, it fails even to return any record if there is one NULL array in it. See below error

eclipse.buildId=unknown
java.version=1.8.0_77
java.vendor=Oracle Corporation
BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=en
Command-line arguments:  -os win32 -ws win32 -arch x86_64

org.jkiss.dbeaver.model
Warning
Wed Sep 12 11:12:12 EDT 2018
Can't resolve NULL array data type

org.jkiss.dbeaver.model.exec.DBCException: Can't resolve NULL array data type
	at org.jkiss.dbeaver.model.impl.jdbc.data.JDBCCollection.makeCollectionFromArray(JDBCCollection.java:219)
	at org.jkiss.dbeaver.model.impl.jdbc.data.handlers.JDBCArrayValueHandler.getValueFromObject(JDBCArrayValueHandler.java:55)
	at org.jkiss.dbeaver.model.impl.jdbc.data.handlers.JDBCArrayValueHandler.getValueFromObject(JDBCArrayValueHandler.java:1)
	at org.jkiss.dbeaver.model.impl.jdbc.data.handlers.JDBCComplexValueHandler.fetchColumnValue(JDBCComplexValueHandler.java:50)
	at org.jkiss.dbeaver.model.impl.jdbc.data.handlers.JDBCAbstractValueHandler.fetchValueObject(JDBCAbstractValueHandler.java:49)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetDataReceiver.fetchRow(ResultSetDataReceiver.java:118)
	at org.jkiss.dbeaver.runtime.sql.SQLQueryJob.fetchQueryData(SQLQueryJob.java:725)
	at org.jkiss.dbeaver.runtime.sql.SQLQueryJob.executeStatement(SQLQueryJob.java:462)
	at org.jkiss.dbeaver.runtime.sql.SQLQueryJob.lambda$0(SQLQueryJob.java:389)
	at org.jkiss.dbeaver.model.DBUtils.tryExecuteRecover(DBUtils.java:1552)
	at org.jkiss.dbeaver.runtime.sql.SQLQueryJob.executeSingleQuery(SQLQueryJob.java:387)
	at org.jkiss.dbeaver.runtime.sql.SQLQueryJob.extractData(SQLQueryJob.java:818)
	at org.jkiss.dbeaver.ui.editors.sql.SQLEditor$QueryResultsContainer.readData(SQLEditor.java:2345)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetJobDataRead.lambda$0(ResultSetJobDataRead.java:93)
	at org.jkiss.dbeaver.model.DBUtils.tryExecuteRecover(DBUtils.java:1552)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetJobDataRead.run(ResultSetJobDataRead.java:91)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:95)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:60)

Appreciate your help!

**Comment by serge-rider** [comment]
@Espanta could you post table DDL and some sample INSERT statement to reproduce this?
