### ISSUE TITLE
XMLTYPE Data Type not supported for Oracle

### ISSUE THREAD

**Issue by sgabisaad** [serge-rider/dbeaver#1410]
Hi there,

I am reading from a database and some fields are set to XMLTYPE which does not seem to be supported?

Below is the error message:

java.lang.NoClassDefFoundError: oracle/xdb/XMLType
	at oracle.jdbc.driver.NamedTypeAccessor.getOracleObject(NamedTypeAccessor.java:249)
	at oracle.jdbc.driver.NamedTypeAccessor.getObject(NamedTypeAccessor.java:136)
	at oracle.jdbc.driver.NamedTypeAccessor.getObject(NamedTypeAccessor.java:110)
	at oracle.jdbc.driver.GeneratedStatement.getObject(GeneratedStatement.java:261)
	at oracle.jdbc.driver.GeneratedScrollableResultSet.getObject(GeneratedScrollableResultSet.java:761)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCResultSetImpl.getObject(JDBCResultSetImpl.java:628)
	at org.jkiss.dbeaver.ext.oracle.data.OracleXMLValueHandler.fetchColumnValue(OracleXMLValueHandler.java:52)
	at org.jkiss.dbeaver.ext.oracle.data.OracleXMLValueHandler.fetchColumnValue(OracleXMLValueHandler.java:1)
	at org.jkiss.dbeaver.model.impl.jdbc.data.handlers.JDBCAbstractValueHandler.fetchValueObject(JDBCAbstractValueHandler.java:49)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetDataReceiver.fetchRow(ResultSetDataReceiver.java:106)
	at org.jkiss.dbeaver.runtime.sql.SQLQueryJob.fetchQueryData(SQLQueryJob.java:602)
	at org.jkiss.dbeaver.runtime.sql.SQLQueryJob.executeSingleQuery(SQLQueryJob.java:355)
	at org.jkiss.dbeaver.runtime.sql.SQLQueryJob.extractData(SQLQueryJob.java:707)
	at org.jkiss.dbeaver.ui.editors.sql.SQLEditor$QueryResultsContainer.readData(SQLEditor.java:1752)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetJobDataRead.run(ResultSetJobDataRead.java:91)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:102)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)
Caused by: java.lang.ClassNotFoundException: oracle.xdb.XMLType
	at java.net.URLClassLoader.findClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	... 17 more

**Comment by serge-rider** [comment]
You need to add Oracle XML jars (xdb6.jar) in driver libraries. 
Also discussed in #171

**Comment by serge-rider** [comment]
Resolved in #171
