### ISSUE TITLE
Open Database Object results in NPE

### ISSUE THREAD

**Issue by michal-petrik** [serge-rider/dbeaver#1431]
I use version 4.0.2 and Sybase ASE (SAP) connection (jTDS Driver). Prior to my current version object search worked well. However in 4.0.2 tha application opens the search dialog and the first inserted char results in NPE.

![image](https://cloud.githubusercontent.com/assets/26402001/23889804/25a4de04-088f-11e7-8df3-a17105a9e32c.png)

**Comment by serge-rider** [comment]
Please post error stacktrace (you can get it in Error Log view of in debug log (https://github.com/serge-rider/dbeaver/wiki/Log-files)

**Comment by michal-petrik** [comment]
Stacktrace from .log file (there is not much in dbeaver-debug.log):

!SESSION 2017-03-14 11:08:12.348 -----------------------------------------------
eclipse.buildId=unknown
java.version=1.8.0_77
java.vendor=Oracle Corporation
BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=en_US
Command-line arguments:  -os win32 -ws win32 -arch x86_64

!ENTRY org.eclipse.core.jobs 4 2 2017-03-14 11:08:50.859
!MESSAGE An internal error occurred during: "Items filtering".
!STACK 0
java.lang.NullPointerException
	at org.jkiss.dbeaver.ext.generic.model.GenericStructureAssistant.findObjectsByMask(GenericStructureAssistant.java:85)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCStructureAssistant.findObjectsByMask(JDBCStructureAssistant.java:78)
	at org.jkiss.dbeaver.ui.dialogs.GotoObjectDialog.fillContentProvider(GotoObjectDialog.java:136)
	at org.eclipse.ui.dialogs.FilteredItemsSelectionDialog$FilterJob.filterContent(FilteredItemsSelectionDialog.java:2099)
	at org.eclipse.ui.dialogs.FilteredItemsSelectionDialog$FilterJob.internalRun(FilteredItemsSelectionDialog.java:2047)
	at org.eclipse.ui.dialogs.FilteredItemsSelectionDialog$FilterJob.doRun(FilteredItemsSelectionDialog.java:2019)
	at org.eclipse.ui.dialogs.FilteredItemsSelectionDialog$FilterJob.run(FilteredItemsSelectionDialog.java:2006)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)

!ENTRY org.eclipse.core.jobs 4 2 2017-03-14 11:08:57.269
!MESSAGE An internal error occurred during: "Items filtering".
!STACK 0
java.lang.NullPointerException
	at org.jkiss.dbeaver.ext.generic.model.GenericStructureAssistant.findObjectsByMask(GenericStructureAssistant.java:85)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCStructureAssistant.findObjectsByMask(JDBCStructureAssistant.java:78)
	at org.jkiss.dbeaver.ui.dialogs.GotoObjectDialog.fillContentProvider(GotoObjectDialog.java:136)
	at org.eclipse.ui.dialogs.FilteredItemsSelectionDialog$FilterJob.filterContent(FilteredItemsSelectionDialog.java:2099)
	at org.eclipse.ui.dialogs.FilteredItemsSelectionDialog$FilterJob.internalRun(FilteredItemsSelectionDialog.java:2047)
	at org.eclipse.ui.dialogs.FilteredItemsSelectionDialog$FilterJob.doRun(FilteredItemsSelectionDialog.java:2019)
	at org.eclipse.ui.dialogs.FilteredItemsSelectionDialog$FilterJob.run(FilteredItemsSelectionDialog.java:2006)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)

!ENTRY org.eclipse.core.jobs 4 2 2017-03-14 11:08:58.434
!MESSAGE An internal error occurred during: "Items filtering".
!STACK 0
java.lang.NullPointerException
	at org.jkiss.dbeaver.ext.generic.model.GenericStructureAssistant.findObjectsByMask(GenericStructureAssistant.java:85)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCStructureAssistant.findObjectsByMask(JDBCStructureAssistant.java:78)
	at org.jkiss.dbeaver.ui.dialogs.GotoObjectDialog.fillContentProvider(GotoObjectDialog.java:136)
	at org.eclipse.ui.dialogs.FilteredItemsSelectionDialog$FilterJob.filterContent(FilteredItemsSelectionDialog.java:2099)
	at org.eclipse.ui.dialogs.FilteredItemsSelectionDialog$FilterJob.internalRun(FilteredItemsSelectionDialog.java:2047)
	at org.eclipse.ui.dialogs.FilteredItemsSelectionDialog$FilterJob.doRun(FilteredItemsSelectionDialog.java:2019)
	at org.eclipse.ui.dialogs.FilteredItemsSelectionDialog$FilterJob.run(FilteredItemsSelectionDialog.java:2006)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)

!ENTRY org.eclipse.core.jobs 4 2 2017-03-14 11:09:00.005
!MESSAGE An internal error occurred during: "Items filtering".
!STACK 0
java.lang.NullPointerException
	at org.jkiss.dbeaver.ext.generic.model.GenericStructureAssistant.findObjectsByMask(GenericStructureAssistant.java:85)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCStructureAssistant.findObjectsByMask(JDBCStructureAssistant.java:78)
	at org.jkiss.dbeaver.ui.dialogs.GotoObjectDialog.fillContentProvider(GotoObjectDialog.java:136)
	at org.eclipse.ui.dialogs.FilteredItemsSelectionDialog$FilterJob.filterContent(FilteredItemsSelectionDialog.java:2099)
	at org.eclipse.ui.dialogs.FilteredItemsSelectionDialog$FilterJob.internalRun(FilteredItemsSelectionDialog.java:2047)
	at org.eclipse.ui.dialogs.FilteredItemsSelectionDialog$FilterJob.doRun(FilteredItemsSelectionDialog.java:2019)
	at org.eclipse.ui.dialogs.FilteredItemsSelectionDialog$FilterJob.run(FilteredItemsSelectionDialog.java:2006)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)

**Comment by serge-rider** [comment]
Probably the same bug as in #1371
Try to re-download 4.0.2 version.

**Comment by michal-petrik** [comment]
Hi, I confirm that. Same problem as in #1371. After reinstall everything works.

Thanks a lot!
