### ISSUE TITLE
Fail to open DBeaver on macOS Yosemite

### ISSUE THREAD

**Issue by glaucocustodio** [serge-rider/dbeaver#1448]
Hi folks, steps to reproduce on macOS Yosemite 10.10.5:

1- Download DBeaver 4.0.2 Mac OS X x86 64 bit (dmg) (http://dbeaver.jkiss.org/download/)
2- Install it
3- Install Java (It was't installed)
4- Open DBeaver

An error has occurred: see the log file.. Here is the tail of the log:
```
!ENTRY org.eclipse.osgi 4 0 2017-03-16 14:33:51.939
!MESSAGE Application error
!STACK 1
java.lang.IllegalStateException: Unable to acquire application service. Ensure that the org.eclipse.core.runtime bundle is resolved and started (see config.ini).
        at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:78)
        at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:388)
        at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:243)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
        at java.lang.reflect.Method.invoke(Method.java:597)
        at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:673)
        at org.eclipse.equinox.launcher.Main.basicRun(Main.java:610)
        at org.eclipse.equinox.launcher.Main.run(Main.java:1519)
~
       org.eclipse.equinox.common [59]
         Unresolved requirement: Require-Capability: osgi.ee; filter:="(&(osgi.ee=JavaSE)(version=1.7))"


!ENTRY org.eclipse.core.contenttype 2 0 2017-03-16 14:33:51.937
!MESSAGE Could not resolve module: org.eclipse.core.contenttype [20]
  Unresolved requirement: Require-Bundle: org.eclipse.equinox.preferences; bundle-version="[3.2.0,4.0.0)"
    -> Bundle-SymbolicName: org.eclipse.equinox.preferences; bundle-version="3.6.1.v20160815-1406"; singleton:="true"
       org.eclipse.equinox.preferences [69]
         Unresolved requirement: Require-Bundle: org.eclipse.equinox.common; bundle-version="[3.2.0,4.0.0)"
           -> Bundle-SymbolicName: org.eclipse.equinox.common; bundle-version="3.8.0.v20160509-1230"; singleton:="true"
              org.eclipse.equinox.common [59]
                Unresolved requirement: Require-Capability: osgi.ee; filter:="(&(osgi.ee=JavaSE)(version=1.7))"


!ENTRY org.eclipse.osgi 4 0 2017-03-16 14:33:51.939
!MESSAGE Application error
!STACK 1
java.lang.IllegalStateException: Unable to acquire application service. Ensure that the org.eclipse.core.runtime bundle is resolved and started (see config.ini).
        at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:78)
        at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:388)
        at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:243)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
        at java.lang.reflect.Method.invoke(Method.java:597)
        at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:673)
        at org.eclipse.equinox.launcher.Main.basicRun(Main.java:610)
        at org.eclipse.equinox.launcher.Main.run(Main.java:1519)
```
I am not a Java developer, do I have to install anything else?

**Comment by serge-rider** [comment]
You need to download and install JDK 1.8 (http://www.oracle.com/technetwork/java/javase/downloads/jdk8-downloads-2133151.html)

On MacOS this is a bit over-complicated (for some reason you have install JDK, not JRE).

**Comment by glaucocustodio** [comment]
Thank you, it is written in the download page, I am sorry.

**Comment by arychand282** [comment]
it works for java 8, but doesnt for java 7. Can you tell me how to run it using java 7?

**Comment by serge-rider** [comment]
@arychand282 DBeaver requires Java 8.
You can download MacOS pkg installer - it is bundled with Java 8 JRE so you won't need to install Java.
