### ISSUE TITLE
Running 'explain execution plan' throws error

### ISSUE THREAD

**Issue by aymer** [serge-rider/dbeaver#1467]
Running 'explain execution plan' raises the following error

"SQL Error [42601]: ERROR: syntax error at or near "FORMAT"
  Position: 10
  org.postgresql.util.PSQLException: ERROR: syntax error at or near "FORMAT"
  Position: 10
"

happens for any kind of sql.

DB: PostgreSQL 8.4.20 on x86_64-redhat-linux-gnu, compiled by GCC gcc (GCC) 4.4.7 20120313 (Red Hat 4.4.7-17), 64-bit
dbeaver Version 4.0.3/Windows 7
Pg JDBC driver - both 9.4.1212 and 8.4-703.jdbc4 shows this problem

**Comment by serge-rider** [comment]
Can't reproduce.
1. Please post error log (with stacktrace). You can get it in Error Log view (main menu Window->Show View).
2. What happens if you execute explain manually? E.g. `explain select 1`.

**Comment by aymer** [comment]
eclipse.buildId=unknown
java.version=1.8.0_92
java.vendor=Oracle Corporation
BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=en_US
Command-line arguments:  -os win32 -ws win32 -arch x86_64

org.jkiss.dbeaver.model
Error
Thu Mar 23 11:14:00 SGT 2017
SQL Error [42601]: ERROR: syntax error at or near "FORMAT"
  Position: 10

org.jkiss.dbeaver.model.exec.DBCException: SQL Error [42601]: ERROR: syntax error at or near "FORMAT"
  Position: 10
	at org.jkiss.dbeaver.ext.postgresql.model.plan.PostgrePlanAnalyser.explain(PostgrePlanAnalyser.java:86)
	at org.jkiss.dbeaver.ext.postgresql.model.PostgreDataSource.planQueryExecution(PostgreDataSource.java:367)
	at org.jkiss.dbeaver.ui.views.plan.PlanNodesTree$ExplainPlanService.evaluate(PlanNodesTree.java:151)
	at org.jkiss.dbeaver.ui.views.plan.PlanNodesTree$ExplainPlanService.evaluate(PlanNodesTree.java:1)
	at org.jkiss.dbeaver.ui.LoadingJob.run(LoadingJob.java:85)
	at org.jkiss.dbeaver.ui.LoadingJob.run(LoadingJob.java:70)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:95)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)
Caused by: org.postgresql.util.PSQLException: ERROR: syntax error at or near "FORMAT"
  Position: 10
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2455)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2155)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:288)
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:430)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:356)
	at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:168)
	at org.postgresql.jdbc.PgPreparedStatement.executeQuery(PgPreparedStatement.java:116)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCPreparedStatementImpl.executeQuery(JDBCPreparedStatementImpl.java:230)
	at org.jkiss.dbeaver.ext.postgresql.model.plan.PostgrePlanAnalyser.explain(PostgrePlanAnalyser.java:76)
	... 7 more


eclipse.buildId=unknown
java.version=1.8.0_92
java.vendor=Oracle Corporation
BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=en_US
Command-line arguments:  -os win32 -ws win32 -arch x86_64

org.jkiss.dbeaver.model
Error
Thu Mar 23 11:14:00 SGT 2017
ERROR: syntax error at or near "FORMAT"
  Position: 10

org.postgresql.util.PSQLException: ERROR: syntax error at or near "FORMAT"
  Position: 10
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2455)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2155)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:288)
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:430)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:356)
	at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:168)
	at org.postgresql.jdbc.PgPreparedStatement.executeQuery(PgPreparedStatement.java:116)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCPreparedStatementImpl.executeQuery(JDBCPreparedStatementImpl.java:230)
	at org.jkiss.dbeaver.ext.postgresql.model.plan.PostgrePlanAnalyser.explain(PostgrePlanAnalyser.java:76)
	at org.jkiss.dbeaver.ext.postgresql.model.PostgreDataSource.planQueryExecution(PostgreDataSource.java:367)
	at org.jkiss.dbeaver.ui.views.plan.PlanNodesTree$ExplainPlanService.evaluate(PlanNodesTree.java:151)
	at org.jkiss.dbeaver.ui.views.plan.PlanNodesTree$ExplainPlanService.evaluate(PlanNodesTree.java:1)
	at org.jkiss.dbeaver.ui.LoadingJob.run(LoadingJob.java:85)
	at org.jkiss.dbeaver.ui.LoadingJob.run(LoadingJob.java:70)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:95)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)




`explain select 1` works without any issues

**Comment by serge-rider** [comment]
DBeaver uses PostgreSQL 9+ execution plan explain method.
I'll add support for older PG versions.
Thanks for report.
