### ISSUE TITLE
Viewing table data doesn't include the schema in the query

### ISSUE THREAD

**Issue by jk3us** [serge-rider/dbeaver#1493]
This just started in 4.0.3.  When you go to the Data tab while for a table, the query that is run doesn't include the schema, so if that schema isn't "active", it gives an error about the table not existing.  This is with Postgres 9.4.  I have to go set that schema as the active schema to get it to work.

**Comment by serge-rider** [comment]
Can't reproduce.
Please provide more details. That's what I see:
![default](https://cloud.githubusercontent.com/assets/6398845/24422532/89095fa0-1402-11e7-934f-9b14f729fdec.png)

**Comment by jk3us** [comment]
![image](https://cloud.githubusercontent.com/assets/41621/24423937/641a891e-13c4-11e7-81d5-6c710180fc46.png)

![image](https://cloud.githubusercontent.com/assets/41621/24423952/6fb9dc66-13c4-11e7-95dc-256883cf90d3.png)

And then interestingly: 

![image](https://cloud.githubusercontent.com/assets/41621/24423969/821ca9d8-13c4-11e7-830f-6abd54a7d738.png)

The last one changes when I change the active schema:

![image](https://cloud.githubusercontent.com/assets/41621/24424014/a8aee6f6-13c4-11e7-8053-45950e306b3f.png)

**Comment by serge-rider** [comment]
I have no clues so far. Please post error/debug log.

**Comment by jk3us** [comment]
Does this help any?  If not, how can I get logs that do help?

`!ENTRY org.jkiss.dbeaver.model 4 0 2017-04-06 17:04:16.936
!MESSAGE SQL Error [42P01]: ERROR: relation "orders" does not exist
  Position: 15
!STACK 0
org.jkiss.dbeaver.model.exec.DBCException: SQL Error [42P01]: ERROR: relation "orders" does not exist
  Position: 15
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCStatementImpl.executeStatement(JDBCStatementImpl.java:141)
	at org.jkiss.dbeaver.model.impl.jdbc.struct.JDBCTable.readData(JDBCTable.java:180)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetJobDataRead.run(ResultSetJobDataRead.java:91)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:95)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)
Caused by: org.postgresql.util.PSQLException: ERROR: relation "orders" does not exist
  Position: 15
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2455)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2155)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:288)
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:430)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:356)
	at org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:303)
	at org.postgresql.jdbc.PgStatement.executeCachedSql(PgStatement.java:289)
	at org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:266)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:262)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCStatementImpl.execute(JDBCStatementImpl.java:345)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCStatementImpl.executeStatement(JDBCStatementImpl.java:138)
	... 4 more
!SUBENTRY 1 org.jkiss.dbeaver.model 4 0 2017-04-06 17:04:16.936
!MESSAGE ERROR: relation "orders" does not exist
  Position: 15
!STACK 0
org.postgresql.util.PSQLException: ERROR: relation "orders" does not exist
  Position: 15
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2455)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2155)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:288)
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:430)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:356)
	at org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:303)
	at org.postgresql.jdbc.PgStatement.executeCachedSql(PgStatement.java:289)
	at org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:266)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:262)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCStatementImpl.execute(JDBCStatementImpl.java:345)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCStatementImpl.executeStatement(JDBCStatementImpl.java:138)
	at org.jkiss.dbeaver.model.impl.jdbc.struct.JDBCTable.readData(JDBCTable.java:180)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetJobDataRead.run(ResultSetJobDataRead.java:91)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:95)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)`

**Comment by serge-rider** [comment]
Debug log may contain some warnings/info messages. Instructions are here:
https://github.com/serge-rider/dbeaver/wiki/Log-files

**Comment by jk3us** [comment]
`2017-04-07 09:22:44.110 - null
org.jkiss.dbeaver.model.exec.DBCException: SQL Error [42P01]: ERROR: relation "orders" does not exist
  Position: 15
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCStatementImpl.executeStatement(JDBCStatementImpl.java:141)
	at org.jkiss.dbeaver.model.impl.jdbc.struct.JDBCTable.readData(JDBCTable.java:180)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetJobDataRead.run(ResultSetJobDataRead.java:91)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:95)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)
Caused by: org.postgresql.util.PSQLException: ERROR: relation "orders" does not exist
  Position: 15
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2455)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2155)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:288)
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:430)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:356)
	at org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:303)
	at org.postgresql.jdbc.PgStatement.executeCachedSql(PgStatement.java:289)
	at org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:266)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:262)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCStatementImpl.execute(JDBCStatementImpl.java:345)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCStatementImpl.executeStatement(JDBCStatementImpl.java:138)
	... 4 more`

**Comment by serge-rider** [comment]
I need full log. This just an error about wrong table name. If there is nothing else then it doesn't make sense of course.
Could you provide any more details? Scheenshot would be helpful.

**Comment by jk3us** [comment]
I've sent an email to the address in your profile, in case there are things in the fuller log and wider screenshot that shouldn't be in the public.

**Comment by jk3us** [comment]
This seems to work correctly for me in 4.0.5. I can view table data from schemas that aren't in the search_path, and I see the schema name in the little sql popout you see when you click on the table name left of the filter bar.

**Comment by serge-rider** [comment]
Ok then. Seems to be fixed.
