### ISSUE TITLE
dbeaver 4.0.3 Oracle "SQL Error [17023]: Unsupported feature" when trying to save an inserted record

### ISSUE THREAD

**Issue by luisalb85** [serge-rider/dbeaver#1504]
Same problem with oracle 8 and oracle 11

!SESSION 2017-03-21 12:27:59.128 -----------------------------------------------
eclipse.buildId=unknown
java.version=1.8.0_77
java.vendor=Oracle Corporation
BootLoader constants: OS=win32, ARCH=x86, WS=win32, NL=en
Command-line arguments:  -os win32 -ws win32 -arch x86

!ENTRY org.jkiss.dbeaver.model 4 0 2017-03-30 15:39:06.867
!MESSAGE SQL Error [17023]: Unsupported feature
!STACK 0
org.jkiss.dbeaver.model.impl.jdbc.JDBCException: SQL Error [17023]: Unsupported feature
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCConnectionImpl.prepareStatement(JDBCConnectionImpl.java:162)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCConnectionImpl.prepareStatement(JDBCConnectionImpl.java:1)
	at org.jkiss.dbeaver.model.impl.jdbc.struct.JDBCTable$1.prepareStatement(JDBCTable.java:339)
	at org.jkiss.dbeaver.model.impl.data.ExecuteBatchImpl.processBatch(ExecuteBatchImpl.java:144)
	at org.jkiss.dbeaver.model.impl.data.ExecuteBatchImpl.execute(ExecuteBatchImpl.java:77)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetPersister$DataUpdaterJob.executeStatements(ResultSetPersister.java:521)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetPersister$DataUpdaterJob.run(ResultSetPersister.java:410)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:95)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)
Caused by: java.sql.SQLException: Unsupported feature
	at oracle.jdbc.driver.DatabaseError.throwSqlException(DatabaseError.java:125)
	at oracle.jdbc.driver.DatabaseError.throwSqlException(DatabaseError.java:162)
	at oracle.jdbc.driver.DatabaseError.throwSqlException(DatabaseError.java:227)
	at oracle.jdbc.driver.DatabaseError.throwUnsupportedFeatureSqlException(DatabaseError.java:537)
	at oracle.jdbc.driver.PhysicalConnection.prepareStatement(PhysicalConnection.java:2995)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCConnectionImpl.prepareStatement(JDBCConnectionImpl.java:487)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCConnectionImpl.prepareStatement(JDBCConnectionImpl.java:141)
	... 8 more

**Comment by serge-rider** [comment]
What Oracle driver version do you use? Most likely it is quite old and doesn't support many features.

You could try to download Oracle 11 or 12 drivers from here: http://www.oracle.com/technetwork/apps-tech/jdbc-112010-090769.html

**Comment by luisalb85** [comment]
I use 10.2.0.1.0 client
With 10.2.0.2, 10.2.0.3, 10.2.0.4, 10.2.0.5 the error changes to: SQL Error [17412]: Bigger type length than Maximum
With 11 and newer I can´t connect to Oracle DB
Unexpected driver error occurred while connecting to database
  java.lang.ArrayIndexOutOfBoundsException: 4


org.jkiss.dbeaver.model.exec.DBCException: SQL Error [17412]: Bigger type length than Maximum
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCPreparedStatementImpl.executeStatement(JDBCPreparedStatementImpl.java:205)
	at org.jkiss.dbeaver.model.impl.data.ExecuteBatchImpl.executeStatement(ExecuteBatchImpl.java:258)
	at org.jkiss.dbeaver.model.impl.data.ExecuteBatchImpl.processBatch(ExecuteBatchImpl.java:156)
	at org.jkiss.dbeaver.model.impl.data.ExecuteBatchImpl.execute(ExecuteBatchImpl.java:77)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetPersister$DataUpdaterJob.executeStatements(ResultSetPersister.java:521)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetPersister$DataUpdaterJob.run(ResultSetPersister.java:410)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:95)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)
Caused by: java.sql.SQLException: Bigger type length than Maximum
	at oracle.jdbc.driver.DatabaseError.throwSqlException(DatabaseError.java:112)
	at oracle.jdbc.driver.DatabaseError.throwSqlException(DatabaseError.java:146)
	at oracle.jdbc.driver.DatabaseError.throwSqlException(DatabaseError.java:208)
	at oracle.jdbc.driver.T4CMAREngine.buffer2Value(T4CMAREngine.java:2493)
	at oracle.jdbc.driver.T4CMAREngine.unmarshalUB2(T4CMAREngine.java:1177)
	at oracle.jdbc.driver.T4CMAREngine.unmarshalSB2(T4CMAREngine.java:1149)
	at oracle.jdbc.driver.T4CRowidAccessor.processIndicator(T4CRowidAccessor.java:78)
	at oracle.jdbc.driver.T4CRowidAccessor.unmarshalOneRow(T4CRowidAccessor.java:224)
	at oracle.jdbc.driver.T4C8Oall.receive(T4C8Oall.java:610)
	at oracle.jdbc.driver.T4CPreparedStatement.doOall8(T4CPreparedStatement.java:216)
	at oracle.jdbc.driver.T4CPreparedStatement.executeForRows(T4CPreparedStatement.java:955)
	at oracle.jdbc.driver.OracleStatement.doExecuteWithTimeout(OracleStatement.java:1168)
	at oracle.jdbc.driver.OraclePreparedStatement.executeInternal(OraclePreparedStatement.java:3316)
	at oracle.jdbc.driver.OraclePreparedStatement.execute(OraclePreparedStatement.java:3422)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCPreparedStatementImpl.execute(JDBCPreparedStatementImpl.java:258)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCPreparedStatementImpl.executeStatement(JDBCPreparedStatementImpl.java:202)
	... 7 more

**Comment by serge-rider** [comment]
I think I can add some workaround for this..

**Comment by serge-rider** [comment]
Hopefully this fix will resolve problems with incorrect driver exceptions.
