### ISSUE TITLE
Integration with eGit error when checkout another branch (EE 4.0.4)

### ISSUE THREAD

**Issue by ilyacoos** [serge-rider/dbeaver#1545]
Hi,

I've faced with an error when using DBeaver with eGit plugin: namely when checkouting another branch I got NoClassDefFoundError exception.

My details: fresh DBeaver Enterprise 4.0.4 WINx32 (zip archive) got from http://dbeaver.jkiss.org/download/enterprise/
I've installed eGit from an update site http://download.eclipse.org/releases/neon (according to http://www.eclipse.org/egit/download/). Items installed: "Git integration for Eclipse" and "Java implementation for Eclipse".
All eGit functionality works perfect, except checkouting another branch. Stack trace follows.

Why does the error pointing to org.jkiss.dbeaver.model ?  Thanks in advance.

!ENTRY org.jkiss.dbeaver.model 4 0 2017-04-07 09:38:17.410
!MESSAGE Event loop exception
!SUBENTRY 1 org.jkiss.dbeaver.model 4 0 2017-04-07 09:38:17.410
!MESSAGE org/eclipse/debug/core/ILaunchConfiguration
!STACK 0
java.lang.NoClassDefFoundError: org/eclipse/debug/core/ILaunchConfiguration
                at org.eclipse.egit.ui.internal.branch.LaunchFinder.getRunningLaunchConfiguration(LaunchFinder.java:73)
                at org.eclipse.egit.ui.internal.branch.LaunchFinder.shouldCancelBecauseOfRunningLaunches(LaunchFinder.java:207)
                at org.eclipse.egit.ui.internal.branch.LaunchFinder.shouldCancelBecauseOfRunningLaunches(LaunchFinder.java:179)
                at org.eclipse.egit.ui.internal.branch.BranchOperationUI.confirmTarget(BranchOperationUI.java:123)
                at org.eclipse.egit.ui.internal.branch.BranchOperationUI.start(BranchOperationUI.java:163)
                at org.eclipse.egit.ui.internal.repository.tree.command.CheckoutCommand.execute(CheckoutCommand.java:42)
                at org.eclipse.ui.internal.handlers.HandlerProxy.execute(HandlerProxy.java:295)
                at org.eclipse.ui.internal.handlers.E4HandlerProxy.execute(E4HandlerProxy.java:90)
                at sun.reflect.GeneratedMethodAccessor48.invoke(Unknown Source)
                at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
                at java.lang.reflect.Method.invoke(Unknown Source)
                at org.eclipse.e4.core.internal.di.MethodRequestor.execute(MethodRequestor.java:55)
                at org.eclipse.e4.core.internal.di.InjectorImpl.invokeUsingClass(InjectorImpl.java:282)
                at org.eclipse.e4.core.internal.di.InjectorImpl.invoke(InjectorImpl.java:264)
                at org.eclipse.e4.core.contexts.ContextInjectionFactory.invoke(ContextInjectionFactory.java:132)
                at org.eclipse.e4.core.commands.internal.HandlerServiceHandler.execute(HandlerServiceHandler.java:152)
                at org.eclipse.core.commands.Command.executeWithChecks(Command.java:494)
                at org.eclipse.core.commands.ParameterizedCommand.executeWithChecks(ParameterizedCommand.java:488)
                at org.eclipse.e4.core.commands.internal.HandlerServiceImpl.executeHandler(HandlerServiceImpl.java:210)
                at org.eclipse.e4.ui.workbench.renderers.swt.HandledContributionItem.executeItem(HandledContributionItem.java:433)
                at org.eclipse.e4.ui.workbench.renderers.swt.AbstractContributionItem.handleWidgetSelection(AbstractContributionItem.java:454)
                at org.eclipse.e4.ui.workbench.renderers.swt.AbstractContributionItem$3.handleEvent(AbstractContributionItem.java:482)
                at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:84)
                at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4418)
                at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1079)
                at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4236)
                at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3824)
                at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$4.run(PartRenderingEngine.java:1121)
                at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:336)
                at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1022)
                at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:150)
                at org.eclipse.ui.internal.Workbench$5.run(Workbench.java:693)
                at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:336)
                at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:610)
                at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:148)
                at org.jkiss.dbeaver.core.application.DBeaverApplication.start(DBeaverApplication.java:166)
                at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
                at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
                at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
                at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:388)
                at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:243)
                at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
                at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
                at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
                at java.lang.reflect.Method.invoke(Unknown Source)
                at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:673)
                at org.eclipse.equinox.launcher.Main.basicRun(Main.java:610)
                at org.eclipse.equinox.launcher.Main.run(Main.java:1519)

**Comment by serge-rider** [comment]
It say org.jkiss.dbeaver.model because ALL DBeaver error logs are written by model plugin. This means nothing.

In regards to EGit. Looks like it depends on eclipse.debug.core module which wasn't installed. I'm not sure why. Maybe org.eclipse.debug.core should be shipped with DBeaver (as a part of core framework) or maybe something went wrong during eGit install.

**Comment by ilyacoos** [comment]
Thank you very much!  Installing "Dynamic Languages Toolkit - Mylyn Integration" helps.
Please close the issue.

**Comment by serge-rider** [comment]
Ok
