### ISSUE TITLE
[3.5.8] Oracle data table exception

### ISSUE THREAD

**Issue by NullpointerForever** [serge-rider/dbeaver#157]
Hi,

When I have created table in Oracle 11g with:
```sql
  CREATE TABLE "TEST"."_DBMAINTAIN2" 
   (	
    "FILE_NAME" VARCHAR2(150 BYTE), 
	"FILE_LAST_MODIFIED_AT" NUMBER(*,0), 
	"CHECKSUM" VARCHAR2(50 BYTE), 
	"EXECUTED_AT" VARCHAR2(20 BYTE), 
	"SUCCEEDED" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
```
then I can't preview data table in DBeaver. There is an exception:

`DBCException: SQL Error [911] [22019]: ORA-00911:`

Regards

**Comment by codebling** [comment]
If you open the Error Log, you should be able to click on the exception and open it up to get a full stack trace. Would you mind doing so?   You can find the Error Log in the lower right hand corner if it's currently shown, otherwise you can show it by selecting it from the Window menu.

**Comment by NullpointerForever** [comment]
Here it is:
`
java.sql.SQLSyntaxErrorException: ORA-00911: niepoprawny znak
	at oracle.jdbc.driver.T4CTTIoer.processError(T4CTTIoer.java:447)
	at oracle.jdbc.driver.T4CTTIoer.processError(T4CTTIoer.java:396)
	at oracle.jdbc.driver.T4C8Oall.processError(T4C8Oall.java:951)
	at oracle.jdbc.driver.T4CTTIfun.receive(T4CTTIfun.java:513)
	at oracle.jdbc.driver.T4CTTIfun.doRPC(T4CTTIfun.java:227)
	at oracle.jdbc.driver.T4C8Oall.doOALL(T4C8Oall.java:531)
	at oracle.jdbc.driver.T4CStatement.doOall8(T4CStatement.java:195)
	at oracle.jdbc.driver.T4CStatement.executeForDescribe(T4CStatement.java:876)
	at oracle.jdbc.driver.OracleStatement.executeMaybeDescribe(OracleStatement.java:1175)
	at oracle.jdbc.driver.OracleStatement.doExecuteWithTimeout(OracleStatement.java:1296)
	at oracle.jdbc.driver.OracleStatement.doScrollExecuteCommon(OracleStatement.java:4721)
	at oracle.jdbc.driver.OracleStatement.doScrollStmtExecuteQuery(OracleStatement.java:4854)
	at oracle.jdbc.driver.OracleStatement.executeInternal(OracleStatement.java:1920)
	at oracle.jdbc.driver.OracleStatement.execute(OracleStatement.java:1878)
	at oracle.jdbc.driver.OracleStatementWrapper.execute(OracleStatementWrapper.java:318)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCStatementImpl.execute(JDBCStatementImpl.java:345)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCStatementImpl.executeStatement(JDBCStatementImpl.java:138)
	at org.jkiss.dbeaver.model.impl.jdbc.struct.JDBCTable.readData(JDBCTable.java:173)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetDataPumpJob.run(ResultSetDataPumpJob.java:137)
	at org.jkiss.dbeaver.runtime.AbstractJob.run(AbstractJob.java:100)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)`

**Comment by codebling** [comment]
Thanks!  (Markdown tip: you can use triple backticks followed by a newline, then paste your code, add a newline and close the triple backticks. Should save you some effort!)

**Comment by codebling** [comment]
I believe that this is a bug in DBeaver whereby table names are not enclosed in quotation marks, thus leading to a query such as `SELECT x.* FROM TEST._DBMAINTAIN2 x LIMIT 0, 100` , which fails due to the underscore.

**Comment by NullpointerForever** [comment]
Thanks for the tip. I've updated stack trace.

**Comment by serge-rider** [comment]
Fixed. Thanks for report!
