### ISSUE TITLE
java.lang.NullPointerException in Refresh Transaction Monitor after closing all perspectives

### ISSUE THREAD

**Issue by GiantCrocodile** [serge-rider/dbeaver#1598]
see title

**Comment by serge-rider** [comment]
Please post error stacktrace (from error log)

**Comment by GiantCrocodile** [comment]
```
Conflicting handlers for org.eclipse.team.ui.synchronizeAll: {org.eclipse.team.internal.ui.synchronize.actions.GlobalRefreshAction$2@f10d055} vs {org.eclipse.team.internal.ui.synchronize.actions.GlobalRefreshAction$2@542ff147}
Conflicting handlers for org.eclipse.team.ui.synchronizeLast: {org.eclipse.team.internal.ui.synchronize.actions.GlobalRefreshAction$3@3c27f72} vs {org.eclipse.team.internal.ui.synchronize.actions.GlobalRefreshAction$3@5cbe95b1}

java.lang.NullPointerException
	at org.jkiss.dbeaver.ui.controls.txn.TransactionMonitorToolbar$MonitorPanel.getActiveExecutionContext(TransactionMonitorToolbar.java:222)
	at org.jkiss.dbeaver.ui.controls.txn.TransactionMonitorToolbar$MonitorPanel.updateTransactionsInfo(TransactionMonitorToolbar.java:201)
	at org.jkiss.dbeaver.ui.controls.txn.TransactionMonitorToolbar$RefreshJob.run(TransactionMonitorToolbar.java:105)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)
```

is what I can get from Error Log View.

**Comment by GiantCrocodile** [comment]
Steps to reproduce:
1) Open a PostgreSQL schema
2) Open perspective Team synchronizing
3) Close Team Synchronizing  perspective
4) Close DBeaver default perspective

NPE occurs.

**Comment by serge-rider** [comment]
Thanks for details. See fix in the next version.
