### ISSUE TITLE
Database compare throws DBException: Can't read parameters (Postgres)

### ISSUE THREAD

**Issue by tcmj** [serge-rider/dbeaver#161]
Made two connections, selected both top most nodes and chose 'compare' in the context dialog.
After a huge data loading it stops with following exception:
<pre>
org.jkiss.dbeaver.DBException: Can't read parameters
	at org.jkiss.dbeaver.model.navigator.DBNDatabaseNode.extractPropertyValue(DBNDatabaseNode.java:711)
	at org.jkiss.dbeaver.model.navigator.DBNDatabaseNode.loadTreeItems(DBNDatabaseNode.java:427)
	at org.jkiss.dbeaver.model.navigator.DBNDatabaseNode.loadChildren(DBNDatabaseNode.java:353)
	at org.jkiss.dbeaver.model.navigator.DBNDatabaseNode.getChildren(DBNDatabaseNode.java:184)
	at org.jkiss.dbeaver.tools.compare.CompareObjectsExecutor.compareChildren(CompareObjectsExecutor.java:270)
	at org.jkiss.dbeaver.tools.compare.CompareObjectsExecutor.compareNodes(CompareObjectsExecutor.java:181)
	at org.jkiss.dbeaver.tools.compare.CompareObjectsExecutor.compareChildren(CompareObjectsExecutor.java:318)
	at org.jkiss.dbeaver.tools.compare.CompareObjectsExecutor.compareNodes(CompareObjectsExecutor.java:181)
	at org.jkiss.dbeaver.tools.compare.CompareObjectsExecutor.compareChildren(CompareObjectsExecutor.java:318)
	at org.jkiss.dbeaver.tools.compare.CompareObjectsExecutor.compareNodes(CompareObjectsExecutor.java:181)
	at org.jkiss.dbeaver.tools.compare.CompareObjectsExecutor.compareChildren(CompareObjectsExecutor.java:318)
	at org.jkiss.dbeaver.tools.compare.CompareObjectsExecutor.compareNodes(CompareObjectsExecutor.java:181)
	at org.jkiss.dbeaver.tools.compare.CompareObjectsExecutor.compareObjects(CompareObjectsExecutor.java:165)
	at org.jkiss.dbeaver.tools.compare.CompareObjectsWizard.generateReport(CompareObjectsWizard.java:138)
	at org.jkiss.dbeaver.tools.compare.CompareObjectsWizard.access$0(CompareObjectsWizard.java:135)
	at org.jkiss.dbeaver.tools.compare.CompareObjectsWizard$1.run(CompareObjectsWizard.java:107)
	at org.jkiss.dbeaver.runtime.RuntimeUtils$1.run(RuntimeUtils.java:78)
	at org.eclipse.jface.operation.ModalContext$ModalContextThread.run(ModalContext.java:119)
Caused by: java.lang.NullPointerException
	at org.postgresql.jdbc2.TypeInfoCache.getSQLType(TypeInfoCache.java:185)
	at org.postgresql.jdbc2.TypeInfoCache.getSQLType(TypeInfoCache.java:180)
	at org.postgresql.jdbc2.AbstractJdbc2DatabaseMetaData.getProcedureColumns(AbstractJdbc2DatabaseMetaData.java:1944)
	at org.postgresql.jdbc4.AbstractJdbc4DatabaseMetaData.getProcedureColumns(AbstractJdbc4DatabaseMetaData.java:112)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCDatabaseMetaDataImpl.getProcedureColumns(JDBCDatabaseMetaDataImpl.java:1111)
	at org.jkiss.dbeaver.ext.generic.model.GenericProcedure.loadProcedureColumns(GenericProcedure.java:125)
	at org.jkiss.dbeaver.ext.generic.model.GenericProcedure.getParameters(GenericProcedure.java:107)
	at sun.reflect.GeneratedMethodAccessor44.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.jkiss.dbeaver.model.navigator.DBNDatabaseNode.extractPropertyValue(DBNDatabaseNode.java:697)
	... 17 more
</pre>

Java 1.8.0_65 (Oracle) on Win 7 64 bit
Postgres Version 9.3
DBever Version: 3.5.8

**Comment by serge-rider** [comment]
Seems to be a bug in PostgreSQL JDBC driver. I can't fix this bug but I can add workaround in DBeaver compare function.
