### ISSUE TITLE
SSH connect to PostgreSQL fails

### ISSUE THREAD

**Issue by serge-rider** [serge-rider/dbeaver#1613]
Maybe it is a result of upgrading JSch to 0.1.54 in the last version
```
2017-04-27 15:19:07.488 - Instantiate SSH tunnel
2017-04-27 15:19:07.489 - Connect to tunnel host
2017-04-27 15:19:07.489 - SSH INFO: Connecting to xxx.xxx.xxx.xxx port 22
2017-04-27 15:19:07.491 - SSH INFO: Connection established
2017-04-27 15:19:07.497 - SSH INFO: Remote version string: SSH-2.0-OpenSSH_6.6.1
2017-04-27 15:19:07.498 - SSH INFO: Local version string: SSH-2.0-JSCH-0.1.54
2017-04-27 15:19:07.499 - SSH INFO: CheckCiphers: aes256-ctr,aes192-ctr,aes128-ctr,aes256-cbc,aes192-cbc,aes128-cbc,3des-ctr,arcfour,arcfour128,arcfour256
2017-04-27 15:19:07.502 - SSH INFO: aes256-ctr is not available.
2017-04-27 15:19:07.502 - SSH INFO: aes192-ctr is not available.
2017-04-27 15:19:07.503 - SSH INFO: aes256-cbc is not available.
2017-04-27 15:19:07.504 - SSH INFO: aes192-cbc is not available.
2017-04-27 15:19:07.505 - SSH INFO: CheckKexes: diffie-hellman-group14-sha1,ecdh-sha2-nistp256,ecdh-sha2-nistp384,ecdh-sha2-nistp521
2017-04-27 15:19:07.537 - SSH INFO: CheckSignatures: ecdsa-sha2-nistp256,ecdsa-sha2-nistp384,ecdsa-sha2-nistp521
2017-04-27 15:19:07.538 - SSH INFO: SSH_MSG_KEXINIT sent
2017-04-27 15:19:07.539 - SSH INFO: SSH_MSG_KEXINIT received
2017-04-27 15:19:07.539 - SSH INFO: kex: server: curve25519-sha256@libssh.org,ecdh-sha2-nistp256,ecdh-sha2-nistp384,ecdh-sha2-nistp521,diffie-hellman-group-exchange-sha256,diffie-hellman-group-exchange-sha1,diffie-hellman-group14-sha1,diffie-hellman-group1-sha1
2017-04-27 15:19:07.542 - SSH INFO: kex: server: ssh-rsa,ecdsa-sha2-nistp256,ssh-ed25519
2017-04-27 15:19:07.543 - SSH INFO: kex: server: aes128-ctr,aes192-ctr,aes256-ctr,arcfour256,arcfour128,aes128-gcm@openssh.com,aes256-gcm@openssh.com,chacha20-poly1305@openssh.com,aes128-cbc,3des-cbc,blowfish-cbc,cast128-cbc,aes192-cbc,aes256-cbc,arcfour,rijndael-cbc@lysator.liu.se
2017-04-27 15:19:07.546 - SSH INFO: kex: server: aes128-ctr,aes192-ctr,aes256-ctr,arcfour256,arcfour128,aes128-gcm@openssh.com,aes256-gcm@openssh.com,chacha20-poly1305@openssh.com,aes128-cbc,3des-cbc,blowfish-cbc,cast128-cbc,aes192-cbc,aes256-cbc,arcfour,rijndael-cbc@lysator.liu.se
2017-04-27 15:19:07.549 - SSH INFO: kex: server: hmac-md5-etm@openssh.com,hmac-sha1-etm@openssh.com,umac-64-etm@openssh.com,umac-128-etm@openssh.com,hmac-sha2-256-etm@openssh.com,hmac-sha2-512-etm@openssh.com,hmac-ripemd160-etm@openssh.com,hmac-sha1-96-etm@openssh.com,hmac-md5-96-etm@openssh.com,hmac-md5,hmac-sha1,umac-64@openssh.com,umac-128@openssh.com,hmac-sha2-256,hmac-sha2-512,hmac-ripemd160,hmac-ripemd160@openssh.com,hmac-sha1-96,hmac-md5-96
2017-04-27 15:19:07.553 - SSH INFO: kex: server: hmac-md5-etm@openssh.com,hmac-sha1-etm@openssh.com,umac-64-etm@openssh.com,umac-128-etm@openssh.com,hmac-sha2-256-etm@openssh.com,hmac-sha2-512-etm@openssh.com,hmac-ripemd160-etm@openssh.com,hmac-sha1-96-etm@openssh.com,hmac-md5-96-etm@openssh.com,hmac-md5,hmac-sha1,umac-64@openssh.com,umac-128@openssh.com,hmac-sha2-256,hmac-sha2-512,hmac-ripemd160,hmac-ripemd160@openssh.com,hmac-sha1-96,hmac-md5-96
2017-04-27 15:19:07.557 - SSH INFO: kex: server: none,zlib@openssh.com
2017-04-27 15:19:07.558 - SSH INFO: kex: server: none,zlib@openssh.com
2017-04-27 15:19:07.559 - SSH INFO: kex: server: 
2017-04-27 15:19:07.559 - SSH INFO: kex: server: 
2017-04-27 15:19:07.560 - SSH INFO: kex: client: ecdh-sha2-nistp256,ecdh-sha2-nistp384,ecdh-sha2-nistp521,diffie-hellman-group14-sha1,diffie-hellman-group-exchange-sha256,diffie-hellman-group-exchange-sha1,diffie-hellman-group1-sha1
2017-04-27 15:19:07.562 - SSH INFO: kex: client: ssh-rsa,ssh-dss,ecdsa-sha2-nistp256,ecdsa-sha2-nistp384,ecdsa-sha2-nistp521
2017-04-27 15:19:07.563 - SSH INFO: kex: client: aes128-ctr,aes128-cbc,3des-ctr,3des-cbc,blowfish-cbc
2017-04-27 15:19:07.564 - SSH INFO: kex: client: aes128-ctr,aes128-cbc,3des-ctr,3des-cbc,blowfish-cbc
2017-04-27 15:19:07.565 - SSH INFO: kex: client: hmac-md5,hmac-sha1,hmac-sha2-256,hmac-sha1-96,hmac-md5-96
2017-04-27 15:19:07.566 - SSH INFO: kex: client: hmac-md5,hmac-sha1,hmac-sha2-256,hmac-sha1-96,hmac-md5-96
2017-04-27 15:19:07.567 - SSH INFO: kex: client: none
2017-04-27 15:19:07.568 - SSH INFO: kex: client: none
2017-04-27 15:19:07.568 - SSH INFO: kex: client: 
2017-04-27 15:19:07.569 - SSH INFO: kex: client: 
2017-04-27 15:19:07.569 - SSH INFO: kex: server->client aes128-ctr hmac-md5 none
2017-04-27 15:19:07.570 - SSH INFO: kex: client->server aes128-ctr hmac-md5 none
2017-04-27 15:19:07.575 - SSH INFO: SSH_MSG_KEX_ECDH_INIT sent
2017-04-27 15:19:07.575 - SSH INFO: expecting SSH_MSG_KEX_ECDH_REPLY
2017-04-27 15:19:07.581 - SSH INFO: ssh_rsa_verify: signature true
2017-04-27 15:19:07.582 - SSH INFO: Host 'xxx.xxx.xxx.xxx' is known and matches the RSA host key
2017-04-27 15:19:07.583 - SSH INFO: SSH_MSG_NEWKEYS sent
2017-04-27 15:19:07.583 - SSH INFO: SSH_MSG_NEWKEYS received
2017-04-27 15:19:07.584 - SSH INFO: SSH_MSG_SERVICE_REQUEST sent
2017-04-27 15:19:07.585 - SSH INFO: SSH_MSG_SERVICE_ACCEPT received
2017-04-27 15:19:07.587 - SSH INFO: Authentications that can continue: password
2017-04-27 15:19:07.588 - SSH INFO: Next authentication method: password
2017-04-27 15:19:07.606 - SSH INFO: Authentication succeeded (password).
2017-04-27 15:19:07.617 - Connection failed (postgres-jdbc-15baf59c453-2d46ffba728a8464)
2017-04-27 15:19:07.618 - SSH INFO: Disconnecting from xxx.xxx.xxx.xxx port 22
2017-04-27 15:19:07.619 - SSH INFO: Caught an exception, leaving main loop due to Socket closed
2017-04-27 15:19:07.670 - org.jkiss.dbeaver.model.exec.DBCConnectException: The connection attempt failed.
org.jkiss.dbeaver.model.exec.DBCConnectException: The connection attempt failed.
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.openConnection(JDBCDataSource.java:190)
	at org.jkiss.dbeaver.ext.postgresql.model.PostgreDataSource.openConnection(PostgreDataSource.java:348)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCExecutionContext.connect(JDBCExecutionContext.java:72)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.initializeMainContext(JDBCDataSource.java:115)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.<init>(JDBCDataSource.java:109)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.<init>(JDBCDataSource.java:98)
	at org.jkiss.dbeaver.ext.postgresql.model.PostgreDataSource.<init>(PostgreDataSource.java:73)
	at org.jkiss.dbeaver.ext.postgresql.PostgreDataSourceProvider.openDataSource(PostgreDataSourceProvider.java:96)
	at org.jkiss.dbeaver.registry.DataSourceDescriptor.connect(DataSourceDescriptor.java:719)
	at org.jkiss.dbeaver.runtime.jobs.ConnectJob.run(ConnectJob.java:73)
	at org.jkiss.dbeaver.ui.dialogs.connection.ConnectionWizard$ConnectionTester.run(ConnectionWizard.java:214)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:95)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)
Caused by: org.postgresql.util.PSQLException: The connection attempt failed.
	at org.postgresql.Driver$ConnectThread.getResult(Driver.java:355)
	at org.postgresql.Driver.connect(Driver.java:279)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.openConnection(JDBCDataSource.java:176)
	... 12 more
Caused by: java.net.SocketException: Connection reset
	at java.net.SocketInputStream.read(SocketInputStream.java:210)
	at java.net.SocketInputStream.read(SocketInputStream.java:141)
	at org.postgresql.core.VisibleBufferedInputStream.readMore(VisibleBufferedInputStream.java:140)
	at org.postgresql.core.VisibleBufferedInputStream.ensureBytes(VisibleBufferedInputStream.java:109)
	at org.postgresql.core.VisibleBufferedInputStream.read(VisibleBufferedInputStream.java:67)
	at org.postgresql.core.PGStream.receiveChar(PGStream.java:280)
	at org.postgresql.core.v3.ConnectionFactoryImpl.doAuthentication(ConnectionFactoryImpl.java:421)
	at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:217)
	at org.postgresql.core.ConnectionFactory.openConnection(ConnectionFactory.java:51)
	at org.postgresql.jdbc.PgConnection.<init>(PgConnection.java:215)
	at org.postgresql.Driver.makeConnection(Driver.java:404)
	at org.postgresql.Driver.access$100(Driver.java:52)
	at org.postgresql.Driver$ConnectThread.run(Driver.java:314)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by serge-rider** [comment]
Can't reproduce anymore. Probably it was some kind of of misconfiguration.
