### ISSUE TITLE
New record doesnt get committed when adding using the "Data" UI for "production" connections

### ISSUE THREAD

**Issue by antonmos** [serge-rider/dbeaver#1623]
1. Connect to a db and designate connection as Production (or disable auto-commit)
2. double click a table, go to 'Data' tab
3. click + to create a new record, enter the data and hit 'save'
4. Click 'Commit' in the Tool bar
5. Refresh the 'Data' tab - the new record will be gone.

if you refresh before hitting commit, the following error occurs "SQL Error [25P02]: ERROR: current transaction is aborted, commands ignored until end of transaction block
  ERROR: current transaction is aborted, commands ignored until end of transaction block
    org.postgresql.util.PSQLException: ERROR: syntax error at or near "d27"
  Position: 68"

**Comment by serge-rider** [comment]
Looks like some error happened during value save. Although there should be an error dialog..

Check Error Log view for exact error stacktrace.
Also you can see in Query Manager view to see all queries executed by DBeaver (you can find there errors too).

**Comment by antonmos** [comment]
After hitting the "save" button, the Error Log view is showing: "Error refreshing rows" -> "org.jkiss.dbeaver.model
Warning
Tue May 02 13:53:55 CDT 2017
SQL Error [42601]: ERROR: syntax error at or near "d9"
  Position: 69

org.jkiss.dbeaver.model.exec.DBCException: SQL Error [42601]: ERROR: syntax error at or near "d9"
  Position: 69
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCStatementImpl.executeStatement(JDBCStatementImpl.java:141)
	at org.jkiss.dbeaver.model.impl.jdbc.struct.JDBCTable.readData(JDBCTable.java:181)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetPersister$RowRefreshJob.run(ResultSetPersister.java:824)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:95)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)
Caused by: org.postgresql.util.PSQLException: ERROR: syntax error at or near "d9"
  Position: 69
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2455)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2155)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:288)
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:430)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:356)
	at org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:303)
	at org.postgresql.jdbc.PgStatement.executeCachedSql(PgStatement.java:289)
	at org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:266)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:262)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCStatementImpl.execute(JDBCStatementImpl.java:345)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCStatementImpl.executeStatement(JDBCStatementImpl.java:138)
	... 4 more"

**Comment by antonmos** [comment]
Then if i right click the grid and do "Refresh", i get:
SQL Error [25P02]: ERROR: current transaction is aborted, commands ignored until end of transaction block
  ERROR: current transaction is aborted, commands ignored until end of transaction block
    org.postgresql.util.PSQLException: ERROR: syntax error at or near "d9"
  Position: 69

**Comment by antonmos** [comment]
Ah, found something in the 'query manager' after i enabled Utility functions:
```
13:56:21	SQL / USER	SELECT * FROM public.api_tokens	34 ms		ERROR: current transaction is aborted, commands ignored until end of transaction block	lips_jv	Main
13:53:54	SQL / UTIL	SELECT x.* FROM public.api_tokens x
WHERE x.token = db8fa9f1-2272-49d9-897e-b25f7d21ecaa	308 ms		ERROR: syntax error at or near "d9"
  Position: 69	lips_jv	Main
```

i think it's not handling the GUID field correctly

**Comment by serge-rider** [comment]
This is a bug in data refresh (after insert/update). Will be fixed in the next version.

Workaround: switch to auto-commit mode.
