### ISSUE TITLE
Can't click Next Button when import data

### ISSUE THREAD

**Issue by tzwickl** [serge-rider/dbeaver#165]
Sorry I just realised that we are suppose to leave bug reports at GitHub and not in the Forum. So here I go again:
I'm using DBeaver Version 3.5.8 Standalone on my MacBook and when I try to import a table from a Flat CSV file to a Derby database I get the following exception when clicking the Next Button after the Data load setting.

My table mapping looks like this:

![Table Mapping](http://s10.postimg.org/sixopjz21/Screen_Shot_2016_01_19_at_17_03_24.png)

I posted all informations regarding the exception here:

**Message:**
```java
Unhandled event loop exception
```

**Exception Stack Trace:**
```java
java.lang.NullPointerException
   at org.jkiss.dbeaver.tools.transfer.wizard.DataTransferPageFinal.activatePage(DataTransferPageFinal.java:108)
   at org.jkiss.dbeaver.ui.dialogs.ActiveWizardPage.setVisible(ActiveWizardPage.java:58)
   at org.eclipse.jface.wizard.WizardDialog.updateForPage(WizardDialog.java:1229)
   at org.eclipse.jface.wizard.WizardDialog.access$4(WizardDialog.java:1208)
   at org.eclipse.jface.wizard.WizardDialog$8.run(WizardDialog.java:1197)
   at org.eclipse.swt.custom.BusyIndicator.showWhile(BusyIndicator.java:70)
   at org.eclipse.jface.wizard.WizardDialog.showPage(WizardDialog.java:1194)
   at org.eclipse.jface.wizard.WizardDialog.nextPressed(WizardDialog.java:885)
   at org.eclipse.jface.wizard.WizardDialog.buttonPressed(WizardDialog.java:425)
   at org.eclipse.jface.dialogs.Dialog$2.widgetSelected(Dialog.java:619)
   at org.eclipse.swt.widgets.TypedListener.handleEvent(TypedListener.java:248)
   at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:84)
   at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4230)
   at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1491)
   at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1514)
   at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1499)
   at org.eclipse.swt.widgets.Widget.notifyListeners(Widget.java:1299)
   at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4072)
   at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3698)
   at org.eclipse.jface.window.Window.runEventLoop(Window.java:827)
   at org.eclipse.jface.window.Window.open(Window.java:803)
   at org.jkiss.dbeaver.tools.transfer.handlers.DataTransferHandler.execute(DataTransferHandler.java:78)
   at org.eclipse.ui.internal.handlers.HandlerProxy.execute(HandlerProxy.java:295)
   at org.eclipse.ui.internal.handlers.E4HandlerProxy.execute(E4HandlerProxy.java:90)
   at sun.reflect.GeneratedMethodAccessor103.invoke(Unknown Source)
   at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
   at java.lang.reflect.Method.invoke(Method.java:483)
   at org.eclipse.e4.core.internal.di.MethodRequestor.execute(MethodRequestor.java:56)
   at org.eclipse.e4.core.internal.di.InjectorImpl.invokeUsingClass(InjectorImpl.java:252)
   at org.eclipse.e4.core.internal.di.InjectorImpl.invoke(InjectorImpl.java:234)
   at org.eclipse.e4.core.contexts.ContextInjectionFactory.invoke(ContextInjectionFactory.java:132)
   at org.eclipse.e4.core.commands.internal.HandlerServiceHandler.execute(HandlerServiceHandler.java:152)
   at org.eclipse.core.commands.Command.executeWithChecks(Command.java:493)
   at org.eclipse.core.commands.ParameterizedCommand.executeWithChecks(ParameterizedCommand.java:486)
   at org.eclipse.e4.core.commands.internal.HandlerServiceImpl.executeHandler(HandlerServiceImpl.java:210)
   at org.eclipse.e4.ui.workbench.renderers.swt.HandledContributionItem.executeItem(HandledContributionItem.java:799)
   at org.eclipse.e4.ui.workbench.renderers.swt.HandledContributionItem.handleWidgetSelection(HandledContributionItem.java:675)
   at org.eclipse.e4.ui.workbench.renderers.swt.HandledContributionItem.access$7(HandledContributionItem.java:659)
   at org.eclipse.e4.ui.workbench.renderers.swt.HandledContributionItem$4.handleEvent(HandledContributionItem.java:592)
   at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:84)
   at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4230)
   at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1491)
   at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1514)
   at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1499)
   at org.eclipse.swt.widgets.Widget.notifyListeners(Widget.java:1299)
   at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4072)
   at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3698)
   at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$4.run(PartRenderingEngine.java:1127)
   at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:337)
   at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1018)
   at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:156)
   at org.eclipse.ui.internal.Workbench$5.run(Workbench.java:654)
   at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:337)
   at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:598)
   at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:150)
   at org.jkiss.dbeaver.core.application.DBeaverApplication.start(DBeaverApplication.java:110)
   at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
   at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
   at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
   at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:380)
   at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:235)
   at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
   at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
   at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
   at java.lang.reflect.Method.invoke(Method.java:483)
   at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:669)
   at org.eclipse.equinox.launcher.Main.basicRun(Main.java:608)
   at org.eclipse.equinox.launcher.Main.run(Main.java:1515)
```

**Session data:**
```java
eclipse.buildId=unknown
java.version=1.8.0_25
java.vendor=Oracle Corporation
BootLoader constants: OS=macosx, ARCH=x86_64, WS=cocoa, NL=en_US
Framework arguments:  -keyring /Users/tzwickl/.eclipse_keyring -showlocation
Command-line arguments:  -os macosx -ws cocoa -arch x86_64 -keyring /Users/tzwickl/.eclipse_keyring -showlocation
```

Hope you can fix this bug as soon as possible as I really like this tool but without this import feature I cannot use it at the moment and I'm forced to use a different tool.

**Comment by serge-rider** [comment]
Thanks for report.
Next version (with fix of this issue) will be released in the beginning of the next week.

**Comment by serge-rider** [comment]
As a workaround you could use "Export" instead of "Import".

**Comment by tzwickl** [comment]
Thanks for the workaround worked like a charm. Why didn't I think of that ^^
