### ISSUE TITLE
Ucanaccess driver stopped working 2 days ago - Hsql Exception precision or scale out of range

### ISSUE THREAD

**Issue by peter-harrison** [serge-rider/dbeaver#1742]
running nicely two days ago connecting to a local 500MB accdb, now cannot connect in either CE or EE fresh installs and driver downloads
any help would be much appreciated as this is a blocker
cheers

**Comment by serge-rider** [comment]
Please provide more info.
Do you see any errors, warnings, etc. What driver version do you use.
Post error/debug logs (https://github.com/serge-rider/dbeaver/wiki/Log-files)

**Comment by peter-harrison** [comment]
thanks here is the latest log entry, thanks for info on where to find.

2017-06-06 08:21:01.031 - Finish initialization
2017-06-06 08:21:02.375 - Connect with 'MS Access - Report_Analysis_Data.accdb' (msaccess_ucanaccess-15c76394ad2-700ffd13f0196f87)
2017-06-06 08:21:03.437 - Connection failed (msaccess_ucanaccess-15c76394ad2-700ffd13f0196f87)
2017-06-06 08:21:03.437 - org.jkiss.dbeaver.model.exec.DBCConnectException: UCAExc:::4.0.2 precision or scale out of range
org.jkiss.dbeaver.model.exec.DBCConnectException: UCAExc:::4.0.2 precision or scale out of range
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.openConnection(JDBCDataSource.java:190)
	at org.jkiss.dbeaver.ext.generic.model.GenericDataSource.openConnection(GenericDataSource.java:124)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCExecutionContext.connect(JDBCExecutionContext.java:72)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.initializeMainContext(JDBCDataSource.java:115)
	at org.jkiss.dbeaver.ext.generic.model.GenericDataSource.<init>(GenericDataSource.java:106)
	at org.jkiss.dbeaver.ext.generic.model.meta.GenericMetaModel.createDataSource(GenericMetaModel.java:60)
	at org.jkiss.dbeaver.ext.generic.GenericDataSourceProvider.openDataSource(GenericDataSourceProvider.java:130)
	at org.jkiss.dbeaver.registry.DataSourceDescriptor.connect(DataSourceDescriptor.java:680)
	at org.jkiss.dbeaver.runtime.jobs.ConnectJob.run(ConnectJob.java:73)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:95)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)
Caused by: net.ucanaccess.jdbc.UcanaccessSQLException: UCAExc:::4.0.2 precision or scale out of range
	at net.ucanaccess.jdbc.UcanaccessDriver.connect(UcanaccessDriver.java:264)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.openConnection(JDBCDataSource.java:176)
	... 10 more
Caused by: java.sql.SQLSyntaxErrorException: precision or scale out of range
	at org.hsqldb.jdbc.JDBCUtil.sqlException(Unknown Source)
	at org.hsqldb.jdbc.JDBCUtil.sqlException(Unknown Source)
	at org.hsqldb.jdbc.JDBCStatement.fetchResult(Unknown Source)
	at org.hsqldb.jdbc.JDBCStatement.executeUpdate(Unknown Source)
	at net.ucanaccess.converters.LoadJet.exec(LoadJet.java:1560)
	at net.ucanaccess.converters.LoadJet.access$000(LoadJet.java:71)

**Comment by serge-rider** [comment]
Try to use older UCanAccess driver version (you can change it in driver editor dialog->Download/Update then click on version number.

**Comment by peter-harrison** [comment]
fresh install and worked only just once using previous versions of drivers. Once application has been closed and then reopened the same error as above occurs.

**Comment by peter-harrison** [comment]
it is a real pity experiencing this issue as the software looks great. does not work more than once on 64 bit windows across multiple test PCs

**Comment by serge-rider** [comment]
Can't reproduce. 
This seems to be related to your particular mdb and UcanAccess driver version. Did you try older version?

**Comment by tati-kru** [comment]
There isn't any activity about this ticket very long time. It will be closed. However, if you think that it is actual just let us know.
