### ISSUE TITLE
Trying to import CSV into a MS SQL Server instance crashes with an NPE

### ISSUE THREAD

**Issue by gintas** [serge-rider/dbeaver#177]
When I try to import CSV data into a table on an MS SQL Server instance, the following NullPointerException occurs:

eclipse.buildId=unknown
java.version=1.8.0_66
java.vendor=Oracle Corporation
BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=en_GB
Command-line arguments:  -os win32 -ws win32 -arch x86_64

org.jkiss.dbeaver.model
Error
Thu Jan 28 15:56:52 GMT 2016
NullPointerException

java.lang.NullPointerException
	at org.jkiss.dbeaver.registry.datatype.DataTypeAbstractDescriptor.supportsType(DataTypeAbstractDescriptor.java:147)
	at org.jkiss.dbeaver.registry.datatype.DataTypeProviderRegistry.getDataTypeProvider(DataTypeProviderRegistry.java:105)
	at org.jkiss.dbeaver.model.DBUtils.findValueHandler(DBUtils.java:499)
	at org.jkiss.dbeaver.model.DBUtils.findValueHandler(DBUtils.java:485)
	at org.jkiss.dbeaver.tools.transfer.database.DatabaseTransferConsumer.fetchStart(DatabaseTransferConsumer.java:100)
	at org.jkiss.dbeaver.model.impl.jdbc.struct.JDBCTable.readData(JDBCTable.java:194)
	at org.jkiss.dbeaver.tools.transfer.database.DatabaseTransferProducer.transferData(DatabaseTransferProducer.java:113)
	at org.jkiss.dbeaver.tools.transfer.database.DatabaseTransferProducer.transferData(DatabaseTransferProducer.java:1)
	at org.jkiss.dbeaver.tools.transfer.wizard.DataTransferJob.transferData(DataTransferJob.java:104)
	at org.jkiss.dbeaver.tools.transfer.wizard.DataTransferJob.run(DataTransferJob.java:66)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:99)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)

**Comment by gintas** [comment]
I also see another error in the log, also an NPE.

java.lang.NullPointerException
	at org.jkiss.dbeaver.tools.transfer.database.DatabaseTransferConsumer.fetchEnd(DatabaseTransferConsumer.java:189)
	at org.jkiss.dbeaver.model.impl.jdbc.struct.JDBCTable.readData(JDBCTable.java:221)
	at org.jkiss.dbeaver.tools.transfer.database.DatabaseTransferProducer.transferData(DatabaseTransferProducer.java:113)
	at org.jkiss.dbeaver.tools.transfer.database.DatabaseTransferProducer.transferData(DatabaseTransferProducer.java:1)
	at org.jkiss.dbeaver.tools.transfer.wizard.DataTransferJob.transferData(DataTransferJob.java:104)
	at org.jkiss.dbeaver.tools.transfer.wizard.DataTransferJob.run(DataTransferJob.java:66)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:99)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)


And by the way, this is all on version 3.5.9.

**Comment by serge-rider** [comment]
Looks like one of table columns wasn't mapped to a target table column (for some reason).
I can't reproduce this issue so I just added extra columns validations/checks. Hopefully it will give more valuable information next time..

**Comment by serge-rider** [comment]
If it is still happens - please reopen with new stacktrace.
