### ISSUE TITLE
Problem when exporting results on Clickhouse

### ISSUE THREAD

**Issue by blackseaboy** [serge-rider/dbeaver#1834]
Hello! Help me please.
Trying to export Select * from the table below and getting the error no the screenshot. Changed name to kinda variables cause I'm unsure if I'm allowd to show the actual names.
![image](https://user-images.githubusercontent.com/6443132/27736017-eff0844a-5daa-11e7-9864-743bb097ea3a.png)

![image](https://user-images.githubusercontent.com/6443132/27735820-188edb3c-5daa-11e7-9c51-ae16b50bcd9e.png)

Thanks!

**Comment by serge-rider** [comment]
Please post error stacktrace (you can get it in Error Log view or in log files: https://github.com/serge-rider/dbeaver/wiki/Log-files)

**Comment by blackseaboy** [comment]
Here is the entries which appear after export. And there're some parse exception issues during the query execution, I can post it here if it will do some help.
**log:**
!ENTRY org.jkiss.dbeaver.model 4 0 2017-07-03 13:30:55.822
!MESSAGE Error while exporting table row
!STACK 0
org.jkiss.dbeaver.model.exec.DBCException: Error while exporting table row
	at org.jkiss.dbeaver.tools.transfer.stream.StreamTransferConsumer.fetchRow(StreamTransferConsumer.java:155)
	at org.jkiss.dbeaver.runtime.sql.SQLQueryJob.fetchQueryData(SQLQueryJob.java:695)
	at org.jkiss.dbeaver.runtime.sql.SQLQueryJob.executeSingleQuery(SQLQueryJob.java:411)
	at org.jkiss.dbeaver.runtime.sql.SQLQueryJob.extractData(SQLQueryJob.java:788)
	at org.jkiss.dbeaver.ui.editors.sql.SQLEditor$QueryResultsContainer.readData(SQLEditor.java:1925)
	at org.jkiss.dbeaver.tools.transfer.database.DatabaseTransferProducer.transferData(DatabaseTransferProducer.java:120)
	at org.jkiss.dbeaver.tools.transfer.database.DatabaseTransferProducer.transferData(DatabaseTransferProducer.java:1)
	at org.jkiss.dbeaver.tools.transfer.wizard.DataTransferJob.transferData(DataTransferJob.java:102)
	at org.jkiss.dbeaver.tools.transfer.wizard.DataTransferJob.run(DataTransferJob.java:65)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:95)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)
Caused by: org.jkiss.dbeaver.model.exec.DBCException: String data type 'VARCHAR' not supported by database
	at org.jkiss.dbeaver.model.impl.jdbc.data.JDBCCollection.makeCollectionFromString(JDBCCollection.java:319)
	at org.jkiss.dbeaver.model.impl.jdbc.data.handlers.JDBCArrayValueHandler.getValueFromObject(JDBCArrayValueHandler.java:63)
	at org.jkiss.dbeaver.model.impl.jdbc.data.handlers.JDBCArrayValueHandler.getValueFromObject(JDBCArrayValueHandler.java:1)
	at org.jkiss.dbeaver.model.impl.jdbc.data.handlers.JDBCComplexValueHandler.fetchColumnValue(JDBCComplexValueHandler.java:50)
	at org.jkiss.dbeaver.model.impl.jdbc.data.handlers.JDBCAbstractValueHandler.fetchValueObject(JDBCAbstractValueHandler.java:49)
	at org.jkiss.dbeaver.tools.transfer.stream.StreamTransferConsumer.fetchRow(StreamTransferConsumer.java:129)
	... 10 more
!SUBENTRY 1 org.jkiss.dbeaver.model 4 0 2017-07-03 13:30:55.822
!MESSAGE String data type 'VARCHAR' not supported by database
!STACK 0
org.jkiss.dbeaver.model.exec.DBCException: String data type 'VARCHAR' not supported by database
	at org.jkiss.dbeaver.model.impl.jdbc.data.JDBCCollection.makeCollectionFromString(JDBCCollection.java:319)
	at org.jkiss.dbeaver.model.impl.jdbc.data.handlers.JDBCArrayValueHandler.getValueFromObject(JDBCArrayValueHandler.java:63)
	at org.jkiss.dbeaver.model.impl.jdbc.data.handlers.JDBCArrayValueHandler.getValueFromObject(JDBCArrayValueHandler.java:1)
	at org.jkiss.dbeaver.model.impl.jdbc.data.handlers.JDBCComplexValueHandler.fetchColumnValue(JDBCComplexValueHandler.java:50)
	at org.jkiss.dbeaver.model.impl.jdbc.data.handlers.JDBCAbstractValueHandler.fetchValueObject(JDBCAbstractValueHandler.java:49)
	at org.jkiss.dbeaver.tools.transfer.stream.StreamTransferConsumer.fetchRow(StreamTransferConsumer.java:129)
	at org.jkiss.dbeaver.runtime.sql.SQLQueryJob.fetchQueryData(SQLQueryJob.java:695)
	at org.jkiss.dbeaver.runtime.sql.SQLQueryJob.executeSingleQuery(SQLQueryJob.java:411)
	at org.jkiss.dbeaver.runtime.sql.SQLQueryJob.extractData(SQLQueryJob.java:788)
	at org.jkiss.dbeaver.ui.editors.sql.SQLEditor$QueryResultsContainer.readData(SQLEditor.java:1925)
	at org.jkiss.dbeaver.tools.transfer.database.DatabaseTransferProducer.transferData(DatabaseTransferProducer.java:120)
	at org.jkiss.dbeaver.tools.transfer.database.DatabaseTransferProducer.transferData(DatabaseTransferProducer.java:1)
	at org.jkiss.dbeaver.tools.transfer.wizard.DataTransferJob.transferData(DataTransferJob.java:102)
	at org.jkiss.dbeaver.tools.transfer.wizard.DataTransferJob.run(DataTransferJob.java:65)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:95)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)

**dbeaver-debug.log:**
2017-07-03 13:30:55.722 - null
org.jkiss.dbeaver.model.exec.DBCException: Error while exporting table row
	at org.jkiss.dbeaver.tools.transfer.stream.StreamTransferConsumer.fetchRow(StreamTransferConsumer.java:155)
	at org.jkiss.dbeaver.runtime.sql.SQLQueryJob.fetchQueryData(SQLQueryJob.java:695)
	at org.jkiss.dbeaver.runtime.sql.SQLQueryJob.executeSingleQuery(SQLQueryJob.java:411)
	at org.jkiss.dbeaver.runtime.sql.SQLQueryJob.extractData(SQLQueryJob.java:788)
	at org.jkiss.dbeaver.ui.editors.sql.SQLEditor$QueryResultsContainer.readData(SQLEditor.java:1925)
	at org.jkiss.dbeaver.tools.transfer.database.DatabaseTransferProducer.transferData(DatabaseTransferProducer.java:120)
	at org.jkiss.dbeaver.tools.transfer.database.DatabaseTransferProducer.transferData(DatabaseTransferProducer.java:1)
	at org.jkiss.dbeaver.tools.transfer.wizard.DataTransferJob.transferData(DataTransferJob.java:102)
	at org.jkiss.dbeaver.tools.transfer.wizard.DataTransferJob.run(DataTransferJob.java:65)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:95)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)
Caused by: org.jkiss.dbeaver.model.exec.DBCException: String data type 'VARCHAR' not supported by database
	at org.jkiss.dbeaver.model.impl.jdbc.data.JDBCCollection.makeCollectionFromString(JDBCCollection.java:319)
	at org.jkiss.dbeaver.model.impl.jdbc.data.handlers.JDBCArrayValueHandler.getValueFromObject(JDBCArrayValueHandler.java:63)
	at org.jkiss.dbeaver.model.impl.jdbc.data.handlers.JDBCArrayValueHandler.getValueFromObject(JDBCArrayValueHandler.java:1)
	at org.jkiss.dbeaver.model.impl.jdbc.data.handlers.JDBCComplexValueHandler.fetchColumnValue(JDBCComplexValueHandler.java:50)
	at org.jkiss.dbeaver.model.impl.jdbc.data.handlers.JDBCAbstractValueHandler.fetchValueObject(JDBCAbstractValueHandler.java:49)
	at org.jkiss.dbeaver.tools.transfer.stream.StreamTransferConsumer.fetchRow(StreamTransferConsumer.java:129)
	... 10 more

**Comment by serge-rider** [comment]
Thanks,
I can't test it with Clickhouse but I've added some general fix.

**Comment by serge-rider** [comment]
If it won't help - please reopen.

**Comment by blackseaboy** [comment]
OK, waiting for the update. Thank you!

**Comment by blackseaboy** [comment]
Managed to export data through select * limit 10. But there're some strange values in array columns like in examples below:
array1 | [Ljava.lang.String;@4b710e83
array2 | [Ljava.lang.String;@3ffd963d
array3 | [Ljava.math.BigInteger;@1f6e8d46

![image](https://user-images.githubusercontent.com/6443132/28581133-21b052da-716a-11e7-843b-2c57838af3d5.png)

Or may be that's just a feature of an array exporting?

**Comment by serge-rider** [comment]
What type these columns have (you can get it in metadata panel)?
Actually the main problem is that I don't have access to live instance of Clickhouse to test/fix this..

**Comment by blackseaboy** [comment]
Those columns are Arrays with some type: String, Float64, Uint8 or Uint64
![image](https://user-images.githubusercontent.com/6443132/28584571-de6b0da6-7175-11e7-8696-f00ea876fb28.png)
I believe that problem is with array type itself.


> Actually the main problem is that I don't have access to live instance of Clickhouse to test/fix this..

I understand this. If you need any addtional information feel free to ask.
Anyway It's not a big problem and there's no need for an instant solution because we can get an array content with these function of ClickHouse: **arrayElement(array1, 2)** and it works fine.
Thank you very much for your great software and fast support!
