### ISSUE TITLE
DB Navigator > table/view name filer > NPE

### ISSUE THREAD

**Issue by GiantCrocodile** [serge-rider/dbeaver#1840]
1. Type something into table/view name filter of DB Navigator
2. press enter

```
java.lang.NullPointerException
	at org.jkiss.dbeaver.ui.navigator.database.DatabaseNavigatorLabelProvider.getText(DatabaseNavigatorLabelProvider.java:84)
	at org.eclipse.ui.dialogs.PatternFilter.isLeafMatch(PatternFilter.java:271)
	at org.eclipse.ui.dialogs.FilteredTree.getFirstMatchingItem(FilteredTree.java:454)
	at org.eclipse.ui.dialogs.FilteredTree.getFirstMatchingItem(FilteredTree.java:458)
	at org.eclipse.ui.dialogs.FilteredTree.updateTreeSelection(FilteredTree.java:809)
	at org.eclipse.ui.dialogs.FilteredTree$7.keyTraversed(FilteredTree.java:753)
	at org.eclipse.swt.widgets.TypedListener.handleEvent(TypedListener.java:266)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:84)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4418)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1079)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1103)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1088)
	at org.eclipse.swt.widgets.Control.traverse(Control.java:4286)
	at org.eclipse.swt.widgets.Control.translateTraversal(Control.java:4268)
	at org.eclipse.swt.widgets.Display.translateTraversal(Display.java:4928)
	at org.eclipse.swt.widgets.Display.filterMessage(Display.java:1288)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3820)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$4.run(PartRenderingEngine.java:1121)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:336)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1022)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:150)
	at org.eclipse.ui.internal.Workbench$5.run(Workbench.java:693)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:336)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:610)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:148)
	at org.jkiss.dbeaver.core.application.DBeaverApplication.start(DBeaverApplication.java:170)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:388)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:243)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:673)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:610)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1519)
```

```
java.lang.NullPointerException
	at org.jkiss.dbeaver.ui.navigator.database.DatabaseNavigatorLabelProvider.getText(DatabaseNavigatorLabelProvider.java:84)
	at org.eclipse.ui.dialogs.PatternFilter.isLeafMatch(PatternFilter.java:271)
	at org.eclipse.ui.dialogs.FilteredTree.getFirstMatchingItem(FilteredTree.java:454)
	at org.eclipse.ui.dialogs.FilteredTree.getFirstMatchingItem(FilteredTree.java:458)
	at org.eclipse.ui.dialogs.FilteredTree.updateTreeSelection(FilteredTree.java:809)
	at org.eclipse.ui.dialogs.FilteredTree$7.keyTraversed(FilteredTree.java:753)
	at org.eclipse.swt.widgets.TypedListener.handleEvent(TypedListener.java:266)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:84)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4418)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1079)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1103)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1088)
	at org.eclipse.swt.widgets.Control.traverse(Control.java:4286)
	at org.eclipse.swt.widgets.Control.translateTraversal(Control.java:4268)
	at org.eclipse.swt.widgets.Display.translateTraversal(Display.java:4928)
	at org.eclipse.swt.widgets.Display.filterMessage(Display.java:1288)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3820)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$4.run(PartRenderingEngine.java:1121)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:336)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1022)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:150)
	at org.eclipse.ui.internal.Workbench$5.run(Workbench.java:693)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:336)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:610)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:148)
	at org.jkiss.dbeaver.core.application.DBeaverApplication.start(DBeaverApplication.java:170)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:388)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:243)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:673)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:610)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1519)
```

**Comment by serge-rider** [comment]
Thanks for report
