### ISSUE TITLE
SSH Tunnel Issue: DBCException: Can't initialize tunnel

### ISSUE THREAD

**Issue by Jacobihi** [serge-rider/dbeaver#1858]
Had been using this same server connection until SSL requirement was added, but not I cannot connect. Using 4.1.0 to connect to a postrgresql database on an AWS server. Works on PgAdmin but not DBeaver. The debug log:
```
2017-07-07 16:25:07.880 - SSH INFO: Host 'IP#' is known and matches the RSA host key
2017-07-07 16:25:07.881 - SSH INFO: SSH_MSG_NEWKEYS sent
2017-07-07 16:25:07.882 - SSH INFO: SSH_MSG_NEWKEYS received
2017-07-07 16:25:07.884 - SSH INFO: SSH_MSG_SERVICE_REQUEST sent
2017-07-07 16:25:07.889 - SSH INFO: SSH_MSG_SERVICE_ACCEPT received
2017-07-07 16:25:07.914 -  
======================================================================
You are connected to  company network. Unauthorized 
access to and use of this system is prohibited. Use of this system is 
limited to current  Company authorized individuals only. 
 Company reserves the right to monitor this system's 
use as necessary to ensure its stability, availability, and security.
======================================================================


2017-07-07 16:25:07.924 - SSH INFO: Disconnecting from [IP#] port 22
2017-07-07 16:25:07.926 - Connection failed (postgres-jdbc-15d1eba3b31-529272730f513309)
2017-07-07 16:25:07.981 - org.jkiss.dbeaver.model.exec.DBCException: Can't initialize tunnel
org.jkiss.dbeaver.model.exec.DBCException: Can't initialize tunnel
	at org.jkiss.dbeaver.registry.DataSourceDescriptor.connect(DataSourceDescriptor.java:676)
	at org.jkiss.dbeaver.runtime.jobs.ConnectJob.run(ConnectJob.java:70)
	at org.jkiss.dbeaver.ui.dialogs.connection.ConnectionWizard$ConnectionTester.run(ConnectionWizard.java:213)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:95)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)
Caused by: org.jkiss.dbeaver.DBException: Cannot establish tunnel
	at org.jkiss.dbeaver.model.impl.net.SSHTunnelImpl.initializeTunnel(SSHTunnelImpl.java:161)
	at org.jkiss.dbeaver.registry.DataSourceDescriptor.connect(DataSourceDescriptor.java:674)
	... 4 more
Caused by: com.jcraft.jsch.JSchException: Auth fail
	at com.jcraft.jsch.Session.connect(Session.java:519)
	at org.jkiss.dbeaver.model.impl.net.SSHTunnelImpl.initializeTunnel(SSHTunnelImpl.java:153)
	... 5 more
```

**Comment by serge-rider** [comment]
> Had been using this same server connection until SSL requirement was added

How did you configure SSL?

Workaround is to use external SSH tunnel (e.g. Putty)
