### ISSUE TITLE
Connection to MySQL 8.0.1 failed

### ISSUE THREAD

**Issue by markuman** [serge-rider/dbeaver#1864]
I'm using the MySQL Docker file mysql:8.0.1

    docker run --name some-mysql -p 3306:3306 -e MYSQL_ROOT_PASSWORD=password -d mysql:8.0.1

While mysql-workbench works fine with that, Dbeaver failed to connect with a Null pointer exceptoin

    Could not create connection to database server.
      java.lang.NullPointerException: 

Version Output from workbench

    SELECT version();
    
    # version()
    '8.0.1-dmr'

**Comment by serge-rider** [comment]
Please post error stacktrace (you can get it in Error Log view or in log file: https://github.com/serge-rider/dbeaver/wiki/Log-files)

**Comment by markuman** [comment]
2017-07-13 10:32:26.747 - Connect with 'MySQL Docker' (mysql5-158fddc22f8-4dd05a0f119f16c9)
    2017-07-13 10:32:26.775 - Connection failed (mysql5-158fddc22f8-4dd05a0f119f16c9)
    2017-07-13 10:32:26.777 - org.jkiss.dbeaver.model.exec.DBCConnectException: Could not create connection to database server.
    org.jkiss.dbeaver.model.exec.DBCConnectException: Could not create connection to database server.
            at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.openConnection(JDBCDataSource.java:190)
            at org.jkiss.dbeaver.ext.mysql.model.MySQLDataSource.openConnection(MySQLDataSource.java:383)
            at org.jkiss.dbeaver.model.impl.jdbc.JDBCExecutionContext.connect(JDBCExecutionContext.java:72)
            at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.initializeMainContext(JDBCDataSource.java:115)
            at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.<init>(JDBCDataSource.java:109)
            at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.<init>(JDBCDataSource.java:98)
            at org.jkiss.dbeaver.ext.mysql.model.MySQLDataSource.<init>(MySQLDataSource.java:83)
            at org.jkiss.dbeaver.ext.mysql.MySQLDataSourceProvider.openDataSource(MySQLDataSourceProvider.java:123)
            at org.jkiss.dbeaver.registry.DataSourceDescriptor.connect(DataSourceDescriptor.java:682)
            at org.jkiss.dbeaver.runtime.jobs.ConnectJob.run(ConnectJob.java:70)
            at org.jkiss.dbeaver.runtime.jobs.ConnectJob.runSync(ConnectJob.java:98)
            at org.jkiss.dbeaver.ui.actions.datasource.DataSourceHandler.connectToDataSource(DataSourceHandler.java:105)
            at org.jkiss.dbeaver.registry.DataSourceDescriptor.initConnection(DataSourceDescriptor.java:607)
            at org.jkiss.dbeaver.model.navigator.DBNDataSource.initializeNode(DBNDataSource.java:121)
            at org.jkiss.dbeaver.model.navigator.DBNDatabaseNode.getChildren(DBNDatabaseNode.java:188)
            at org.jkiss.dbeaver.model.navigator.DBNDatabaseNode.getChildren(DBNDatabaseNode.java:1)
            at org.jkiss.dbeaver.ui.navigator.NavigatorUtils.getNodeChildrenFiltered(NavigatorUtils.java:563)
            at org.jkiss.dbeaver.ui.navigator.database.load.TreeLoadService.evaluate(TreeLoadService.java:49)
            at org.jkiss.dbeaver.ui.navigator.database.load.TreeLoadService.evaluate(TreeLoadService.java:1)
            at org.jkiss.dbeaver.ui.LoadingJob.run(LoadingJob.java:86)
            at org.jkiss.dbeaver.ui.LoadingJob.run(LoadingJob.java:71)
            at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:95)
            at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)
    Caused by: com.mysql.jdbc.exceptions.jdbc4.MySQLNonTransientConnectionException: Could not create connection to database server.
            at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
            at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
            at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
            at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
            at com.mysql.jdbc.Util.handleNewInstance(Util.java:425)
            at com.mysql.jdbc.Util.getInstance(Util.java:408)
            at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:918)
            at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:897)
            at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:886)
            at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:860)
            at com.mysql.jdbc.ConnectionImpl.connectOneTryOnly(ConnectionImpl.java:2330)
            at com.mysql.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:2083)
            at com.mysql.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:806)
            at com.mysql.jdbc.JDBC4Connection.<init>(JDBC4Connection.java:47)
            at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
            at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
            at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
            at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
            at com.mysql.jdbc.Util.handleNewInstance(Util.java:425)
            at com.mysql.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:410)
            at com.mysql.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:328)
            at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.openConnection(JDBCDataSource.java:176)
            ... 22 more
    Caused by: java.lang.NullPointerException
            at com.mysql.jdbc.ConnectionImpl.getServerCharset(ConnectionImpl.java:2997)
            at com.mysql.jdbc.MysqlIO.sendConnectionAttributes(MysqlIO.java:1934)
            at com.mysql.jdbc.MysqlIO.proceedHandshakeWithPluggableAuthentication(MysqlIO.java:1863)
            at com.mysql.jdbc.MysqlIO.doHandshake(MysqlIO.java:1226)
            at com.mysql.jdbc.ConnectionImpl.coreConnect(ConnectionImpl.java:2253)
            at com.mysql.jdbc.ConnectionImpl.connectOneTryOnly(ConnectionImpl.java:2284)
            ... 33 more

**Comment by serge-rider** [comment]
Actual error happens in MySQL JDBC driver.
And this seems to be related to characterEncoding property.
Do you specify it in settings? if then try to set it to UTF-8 (or any other suitable value).

**Comment by panquanyi** [comment]
https://bugs.mysql.com/bug.php?id=86221

update driver version to 5.1.41

**Comment by chriscohoat** [comment]
What worked for me was downloading the JDBC driver 8.0.11 from here: https://mvnrepository.com/artifact/mysql/mysql-connector-java/8.0.11 ([direct download link](http://central.maven.org/maven2/mysql/mysql-connector-java/8.0.11/mysql-connector-java-8.0.11.jar))

Then in the driver manager:

![image](https://user-images.githubusercontent.com/566461/40818710-b816851a-6515-11e8-9166-aca966a1df2c.png)

Then in the MySQL driver dialog I added the 8.0.11 connector:

![image](https://user-images.githubusercontent.com/566461/40818750-e7aa8592-6515-11e8-92dd-9aae537eede7.png)

**Comment by serge-rider** [comment]
Note: DBeaver 5.0.6 and later use MySQL driver 8.x by default.

**Comment by devon-whil** [comment]
@chriscohoat Your download link is broken. Here's the link to the latest driver download:
https://search.maven.org/remotecontent?filepath=mysql/mysql-connector-java/8.0.19/mysql-connector-java-8.0.19.jar
