### ISSUE TITLE
mongo select count with group by failing

### ISSUE THREAD

**Issue by ssnyder** [serge-rider/dbeaver#1873]
I have a connection to my database: journal with a collection: messages.  A field in my collection is: payload.annoLg

I execute the query:
select payload.annoLg,count(*) from journal.messages group by payload.annoLg;

it returns with an empty document when I know there should be at least 17 unique values for payload.annoLg field.

I get the following "warning":

!ENTRY org.jkiss.dbeaver.model 2 0 2017-07-12 14:42:39.872
!MESSAGE Can't read column 'document' value
!SUBENTRY 1 org.jkiss.dbeaver.model 2 0 2017-07-12 14:42:39.872
!MESSAGE java.lang.Long cannot be cast to com.mongodb.DBObject
!STACK 0
java.lang.ClassCastException: java.lang.Long cannot be cast to com.mongodb.DBObject
	at com.dbeaver.ent.mongodb.data.handlers.MongoDocumentValueHandler.fetchValueObject(MongoDocumentValueHandler.java:95)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetDataReceiver.fetchRow(ResultSetDataReceiver.java:106)
	at org.jkiss.dbeaver.runtime.sql.SQLQueryJob.fetchQueryData(SQLQueryJob.java:685)
	at org.jkiss.dbeaver.runtime.sql.SQLQueryJob.executeSingleQuery(SQLQueryJob.java:406)
	at org.jkiss.dbeaver.runtime.sql.SQLQueryJob.extractData(SQLQueryJob.java:778)
	at org.jkiss.dbeaver.ui.editors.sql.SQLEditor$QueryResultsContainer.readData(SQLEditor.java:1820)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetJobDataRead.run(ResultSetJobDataRead.java:91)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:95)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)

**Comment by serge-rider** [comment]
Thanks for report

**Comment by serge-rider** [comment]
There are two issues actually:
1. Broken SELECT count(*)  - it will be fixed in 4.2
2. GROUP BY support - it is not yet supported by DBeaver Mongo SQL dialect. Mostly because it is not easy to map Mongo aggregation model (which involves map reduce) into plain relational model.

Hopefully GROUP BY support will be added in future releases (after 4.3).
