### ISSUE TITLE
mongo - how to use javascript instead of SQL

### ISSUE THREAD

**Issue by ssnyder** [serge-rider/dbeaver#1874]
I can't seem to get the system to accept javascript:
database: journal, collection: messages

journal.messages.find();

does not execute.  Something about authorizations - but running the query "select * from journal.messages" works fine.

The error is:
!ENTRY org.jkiss.dbeaver.model 4 0 2017-07-12 14:47:51.742
!MESSAGE Command failed with error 13: 'not authorized on journal to execute command { $eval: "journal.messages.findOne()", args: [] }' on server mtl-nluapp-rabbit.nuance.com:27017. The full response is { "ok" : 0.0, "errmsg" : "not authorized on journal to execute command { $eval: \"journal.messages.findOne()\", args: [] }", "code" : 13 }
!STACK 0
com.mongodb.MongoCommandException: Command failed with error 13: 'not authorized on journal to execute command { $eval: "journal.messages.findOne()", args: [] }' on server mtl-nluapp-rabbit.nuance.com:27017. The full response is { "ok" : 0.0, "errmsg" : "not authorized on journal to execute command { $eval: \"journal.messages.findOne()\", args: [] }", "code" : 13 }
	at com.mongodb.connection.ProtocolHelper.getCommandFailureException(ProtocolHelper.java:115)
	at com.mongodb.connection.CommandProtocol.execute(CommandProtocol.java:114)
	at com.mongodb.connection.DefaultServer$DefaultServerProtocolExecutor.execute(DefaultServer.java:159)
	at com.mongodb.connection.DefaultServerConnection.executeProtocol(DefaultServerConnection.java:286)
	at com.mongodb.connection.DefaultServerConnection.command(DefaultServerConnection.java:173)
	at com.mongodb.operation.CommandOperationHelper.executeWrappedCommandProtocol(CommandOperationHelper.java:215)
	at com.mongodb.operation.CommandOperationHelper.executeWrappedCommandProtocol(CommandOperationHelper.java:186)
	at com.mongodb.operation.CommandOperationHelper.executeWrappedCommandProtocol(CommandOperationHelper.java:160)
	at com.mongodb.operation.CommandOperationHelper.executeWrappedCommandProtocol(CommandOperationHelper.java:133)
	at com.mongodb.operation.CommandOperationHelper.executeWrappedCommandProtocol(CommandOperationHelper.java:123)
	at com.mongodb.operation.CommandWriteOperation.execute(CommandWriteOperation.java:55)
	at com.mongodb.Mongo.execute(Mongo.java:781)
	at com.mongodb.Mongo$2.execute(Mongo.java:764)
	at com.mongodb.DB.executeCommand(DB.java:648)
	at com.mongodb.DB.doEval(DB.java:497)
	at com.dbeaver.ent.mongodb.exec.MongoEvalStatement.executeStatement(MongoEvalStatement.java:43)
	at org.jkiss.dbeaver.runtime.sql.SQLQueryJob.executeSingleQuery(SQLQueryJob.java:394)
	at org.jkiss.dbeaver.runtime.sql.SQLQueryJob.extractData(SQLQueryJob.java:778)
	at org.jkiss.dbeaver.ui.editors.sql.SQLEditor$QueryResultsContainer.readData(SQLEditor.java:1820)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetJobDataRead.run(ResultSetJobDataRead.java:91)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:95)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)

**Comment by serge-rider** [comment]
Check this article: https://github.com/serge-rider/dbeaver/wiki/NoSQL-MongoDB

You could try 
```
db.messages.find().toArray();
```

**Comment by ssnyder** [comment]
Same error:
Caused by: com.mongodb.MongoCommandException: Command failed with error 13: 'not authorized on journal to execute command { $eval: "db.messages.find().toArray()", args: [] }' on server mtl-nluapp-rabbit.nuance.com:27017. The full response is { "ok" : 0.0, "errmsg" : "not authorized on journal to execute command { $eval: \"db.messages.find().toArray()\", args: [] }", "code" : 13 }
        at com.mongodb.connection.ProtocolHelper.getCommandFailureException(ProtocolHelper.java:115)
        at com.mongodb.connection.CommandProtocol.execute(CommandProtocol.java:114)
        at com.mongodb.connection.DefaultServer$DefaultServerProtocolExecutor.execute(DefaultServer.java:159)
        at com.mongodb.connection.DefaultServerConnection.executeProtocol(DefaultServerConnection.java:286)
        at com.mongodb.connection.DefaultServerConnection.command(DefaultServerConnection.java:173)
        at com.mongodb.operation.CommandOperationHelper.executeWrappedCommandProtocol(CommandOperationHelper.java:215)
        at com.mongodb.operation.CommandOperationHelper.executeWrappedCommandProtocol(CommandOperationHelper.java:186)
        at com.mongodb.operation.CommandOperationHelper.executeWrappedCommandProtocol(CommandOperationHelper.java:160)
        at com.mongodb.operation.CommandOperationHelper.executeWrappedCommandProtocol(CommandOperationHelper.java:133)
        at com.mongodb.operation.CommandOperationHelper.executeWrappedCommandProtocol(CommandOperationHelper.java:123)
        at com.mongodb.operation.CommandWriteOperation.execute(CommandWriteOperation.java:55)
        at com.mongodb.Mongo.execute(Mongo.java:781)
        at com.mongodb.Mongo$2.execute(Mongo.java:764)
        at com.mongodb.DB.executeCommand(DB.java:648)
        at com.mongodb.DB.doEval(DB.java:497)
        at com.dbeaver.ent.mongodb.exec.MongoEvalStatement.executeStatement(MongoEvalStatement.java:43)
        ... 6 more

**Comment by serge-rider** [comment]
It looks like you are not authorized to execute `eval` command on server (DBeaver uses eval to execute JS code).
References:
https://stackoverflow.com/questions/42492856/mongo-error-not-authorized-on-dbname-to-execute-command
https://dzone.com/articles/grant-right-to-use-eval-on-mongodb-32

**Comment by ssnyder** [comment]
I have no problem executing that very JS code using other utilities (i.e. Toad For Eclipse, RoboMongo, etc.) (and the same user), it makes no sense that this program is the only one not able execute.  However, I will still attempt to resolve it by explicitly authorizing it using the method in the dzone article when I am back from vacation.

**Comment by serge-rider** [comment]
Interesting.

As far as I know both Toad and RoboMongo use eval to process JS as well.
Is it possible that you use a bit different connection option in DBeaver (user, host name, node name, auth mechanism)?

**Comment by ssnyder** [comment]
I am using the same user and connection options in all of the tools.

**Comment by serge-rider** [comment]
What auth mechanism do you use in DBeaver? 
Sometimes it is the reason.

**Comment by ssnyder** [comment]
SCRAM-SHA-1

**Comment by eassymo** [comment]
i think we getting time out error because URL template:
mongo://{host}[:{port}]/{database}

i have seen other clients using 
mongodb://{host}[:{port}]/{database}

but Driver Manager locks MongoDB Edition.

**Comment by huineng** [comment]
i confirm , same credentials, same connection ..studio 3T works , dbeaver not

**Comment by Kenigmatic** [comment]
Same situation here. 
S3T works. 
NoSQLBooster works. 
DBeaver gives me:
`Command failed with error 13 (Unauthorized): 'not authorized on testDBeaver to execute command { $eval: "db.getCollection("beavers") ", args: [], $db: "testDBeaver" }' on server arduvgoiisw03.univ.rdn:27017. The full response is { "ok" : 0.0, "errmsg" : "not authorized on testDBeaver to execute command { $eval: \"db.getCollection(\"beavers\") \", args: [], $db: \"testDBeaver\" }", "code" : 13, "codeName" : "Unauthorized" }`

**Comment by huineng** [comment]
dbeaver never progressed on this ?  i still have to use  NoSQLBooster (which by the way is not bad) but i like really to have all in one place .

**Comment by mr-moon** [comment]
I'm having same issue on v21.
