### ISSUE TITLE
Save diagram in external format results in 0 byte files and display corruption

### ISSUE THREAD

**Issue by mrmuskrat** [serge-rider/dbeaver#1879]
I have a Sybase database that contains 33 tables (not counting system tables). The Diagram loads and I can see all of the tables. When I try to save the diagram in an external format (doesn't matter which) it just works.

I also have a Sybase database that contains 364 tables (not counting system tables). The Diagram loads and I can see all of the tables. When I try to save the diagram in an external format (doesn't matter which) I get an empty file. 

This seems to cause display corruption of the Diagram tabs that are open.
![20170713_161747](https://user-images.githubusercontent.com/24446/28188281-3ea00642-67e7-11e7-93ba-4e83615e06da.png)

In fact, it seems to cause display corruptions of all inputs.
![20170713_162141](https://user-images.githubusercontent.com/24446/28188372-8fd8e6dc-67e7-11e7-94c7-9317b025a259.png)

I'm running DBeaver 4.1.0 on Fedora release 25 (kernel 4.11.6-201.fc25.x86_64) with the Sybase JDBC driver (net.sourceforge.jtds.jdbc.Driver).

**Comment by serge-rider** [comment]
Can't reproduce.
I can export (save in external format) schema with 1000+ tables. It takes some time (10-20 seconds) but eventually I have 5mb png file.
Please check error log view or error log (https://github.com/serge-rider/dbeaver/wiki/Log-files) for any errors which may happen during export.

**Comment by mrmuskrat** [comment]
!SESSION 2017-07-19 10:44:35.282 -----------------------------------------------
eclipse.buildId=unknown
java.version=1.8.0_131
java.vendor=Oracle Corporation
BootLoader constants: OS=linux, ARCH=x86_64, WS=gtk, NL=en_US
Command-line arguments:  -os linux -ws gtk -arch x86_64

!ENTRY org.eclipse.equinox.event 4 0 2017-07-19 10:44:39.175
!MESSAGE Exception while dispatching event org.osgi.service.event.Event [topic=org/eclipse/e4/ui/model/ui/UIElement/visible/SET] {ChangedElement=org.eclipse.e4.ui.model.application.ui.menu.impl.HandledMenuItemImpl@6e9a0bea (elementId: org.jkiss.dbeaver.ui.editors.sql.run.statement, tags: null, contributorURI: null) (widget: null, renderer: org.eclipse.e4.ui.workbench.renderers.swt.MenuManagerRenderer@608cd501, toBeRendered: true, onTop: false, visible: false, containerData: null, accessibilityPhrase: null) (label: null, iconURI: platform:/plugin/org.jkiss.dbeaver.core/icons/sql/sql_exec.png, tooltip: null, enabled: true, selected: false, type: Push) (mnemonics: null) (wbCommand: ParameterizedCommand(Command(org.jkiss.dbeaver.ui.editors.sql.run.statement,Execute SQL Statement,
		Execute SQL statement,
		Category(org.jkiss.dbeaver.core.sql,SQL Editor,SQL Editor Commands,true),
		org.eclipse.ui.internal.WorkbenchHandlerServiceHandler@19fec3d6,
		,,true),null)), org.eclipse.e4.data={ChangedElement=org.eclipse.e4.ui.model.application.ui.menu.impl.HandledMenuItemImpl@6e9a0bea (elementId: org.jkiss.dbeaver.ui.editors.sql.run.statement, tags: null, contributorURI: null) (widget: null, renderer: org.eclipse.e4.ui.workbench.renderers.swt.MenuManagerRenderer@608cd501, toBeRendered: true, onTop: false, visible: false, containerData: null, accessibilityPhrase: null) (label: null, iconURI: platform:/plugin/org.jkiss.dbeaver.core/icons/sql/sql_exec.png, tooltip: null, enabled: true, selected: false, type: Push) (mnemonics: null) (wbCommand: ParameterizedCommand(Command(org.jkiss.dbeaver.ui.editors.sql.run.statement,Execute SQL Statement,
		Execute SQL statement,
		Category(org.jkiss.dbeaver.core.sql,SQL Editor,SQL Editor Commands,true),
		org.eclipse.ui.internal.WorkbenchHandlerServiceHandler@19fec3d6,
		,,true),null)), AttName=visible, EventType=SET, OldValue=true, Widget=null, NewValue=false}, AttName=visible, EventType=SET, OldValue=true, Widget=null, NewValue=false} to handler org.eclipse.e4.ui.services.internal.events.UIEventHandler@45cd8607
!STACK 0
org.eclipse.core.runtime.AssertionFailedException: null argument:
	at org.eclipse.core.runtime.Assert.isNotNull(Assert.java:85)
	at org.eclipse.core.runtime.Assert.isNotNull(Assert.java:73)
	at org.eclipse.core.internal.runtime.AdapterManager.getAdapter(AdapterManager.java:289)
	at org.jkiss.dbeaver.utils.RuntimeUtils.getObjectAdapter(RuntimeUtils.java:51)
	at org.jkiss.dbeaver.ui.editors.sql.handlers.MaximizeResultsPanelHandler.updateElement(MaximizeResultsPanelHandler.java:49)
	at org.eclipse.ui.internal.handlers.HandlerProxy.updateElement(HandlerProxy.java:460)
	at org.eclipse.ui.internal.handlers.E4HandlerProxy.updateElement(E4HandlerProxy.java:115)
	at org.eclipse.ui.internal.WorkbenchHandlerServiceHandler.updateElement(WorkbenchHandlerServiceHandler.java:43)
	at org.eclipse.ui.internal.commands.CommandService.registerElement(CommandService.java:331)
	at org.eclipse.ui.internal.commands.SlaveCommandService.registerElement(SlaveCommandService.java:243)
	at org.eclipse.ui.internal.commands.SlaveCommandService.registerElementForCommand(SlaveCommandService.java:235)
	at org.eclipse.ui.internal.commands.SlaveCommandService.registerElementForUpdate(SlaveCommandService.java:290)
	at org.eclipse.e4.ui.workbench.renderers.swt.HandledContributionItem.postMenuFill(HandledContributionItem.java:193)
	at org.eclipse.e4.ui.workbench.renderers.swt.AbstractContributionItem.fill(AbstractContributionItem.java:268)
	at org.eclipse.jface.action.MenuManager.doItemFill(MenuManager.java:728)
	at org.eclipse.jface.action.MenuManager.update(MenuManager.java:810)
	at org.eclipse.jface.action.MenuManager.update(MenuManager.java:669)
	at org.eclipse.e4.ui.workbench.renderers.swt.MenuManagerRenderer.scheduleManagerUpdate(MenuManagerRenderer.java:1185)
	at org.eclipse.e4.ui.workbench.renderers.swt.MenuManagerRenderer.access$3(MenuManagerRenderer.java:1180)
	at org.eclipse.e4.ui.workbench.renderers.swt.MenuManagerRenderer$3.handleEvent(MenuManagerRenderer.java:247)
	at org.eclipse.e4.ui.services.internal.events.UIEventHandler$1.run(UIEventHandler.java:40)
	at org.eclipse.swt.widgets.Synchronizer.syncExec(Synchronizer.java:233)
	at org.eclipse.ui.internal.UISynchronizer.syncExec(UISynchronizer.java:145)
	at org.eclipse.swt.widgets.Display.syncExec(Display.java:5414)
	at org.eclipse.e4.ui.internal.workbench.swt.E4Application$1.syncExec(E4Application.java:211)
	at org.eclipse.e4.ui.services.internal.events.UIEventHandler.handleEvent(UIEventHandler.java:36)
	at org.eclipse.equinox.internal.event.EventHandlerWrapper.handleEvent(EventHandlerWrapper.java:201)
	at org.eclipse.equinox.internal.event.EventHandlerTracker.dispatchEvent(EventHandlerTracker.java:197)
	at org.eclipse.equinox.internal.event.EventHandlerTracker.dispatchEvent(EventHandlerTracker.java:1)
	at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:230)
	at org.eclipse.osgi.framework.eventmgr.ListenerQueue.dispatchEventSynchronous(ListenerQueue.java:148)
	at org.eclipse.equinox.internal.event.EventAdminImpl.dispatchEvent(EventAdminImpl.java:135)
	at org.eclipse.equinox.internal.event.EventAdminImpl.sendEvent(EventAdminImpl.java:78)
	at org.eclipse.equinox.internal.event.EventComponent.sendEvent(EventComponent.java:39)
	at org.eclipse.e4.ui.services.internal.events.EventBroker.send(EventBroker.java:94)
	at org.eclipse.e4.ui.internal.workbench.UIEventPublisher.notifyChanged(UIEventPublisher.java:60)
	at org.eclipse.emf.common.notify.impl.BasicNotifierImpl.eNotify(BasicNotifierImpl.java:374)
	at org.eclipse.e4.ui.model.application.ui.impl.UIElementImpl.setVisible(UIElementImpl.java:345)
	at org.eclipse.e4.ui.workbench.renderers.swt.ContributionRecord.updateVisibility(ContributionRecord.java:102)
	at org.eclipse.e4.ui.workbench.renderers.swt.MenuManagerRendererFilter.updateElementVisibility(MenuManagerRendererFilter.java:189)
	at org.eclipse.e4.ui.workbench.renderers.swt.MenuManagerRendererFilter.updateElementVisibility(MenuManagerRendererFilter.java:200)
	at org.eclipse.ui.internal.WorkbenchWindow$8.run(WorkbenchWindow.java:704)
	at org.eclipse.swt.widgets.RunnableLock.run(RunnableLock.java:35)
	at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Synchronizer.java:182)
	at org.eclipse.swt.widgets.Display.runAsyncMessages(Display.java:4536)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:4154)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$4.run(PartRenderingEngine.java:1121)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:336)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1022)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:150)
	at org.eclipse.ui.internal.Workbench$5.run(Workbench.java:693)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:336)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:610)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:148)
	at org.jkiss.dbeaver.core.application.DBeaverApplication.start(DBeaverApplication.java:170)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:388)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:243)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:673)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:610)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1519)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1492)

!ENTRY org.eclipse.ui 4 0 2017-07-19 10:45:42.195
!MESSAGE Unhandled event loop exception
!STACK 0
java.lang.OutOfMemoryError: Java heap space
	at org.eclipse.swt.graphics.ImageData.<init>(ImageData.java:449)
	at org.eclipse.swt.graphics.ImageData.<init>(ImageData.java:260)
	at org.jkiss.dbeaver.ui.ImageUtils.get8BitPaletteImageData(ImageUtils.java:262)
	at org.jkiss.dbeaver.ui.ImageUtils.makeWebImageData(ImageUtils.java:236)
	at org.jkiss.dbeaver.ext.erd.editor.ERDEditorPart.saveDiagramAs(ERDEditorPart.java:696)
	at org.jkiss.dbeaver.ext.erd.editor.ERDEditorPart.doSaveAs(ERDEditorPart.java:261)
	at org.jkiss.dbeaver.ui.editors.entity.EntityEditor.doSaveAs(EntityEditor.java:204)
	at org.eclipse.ui.internal.handlers.SaveAsHandler.execute(SaveAsHandler.java:42)
	at org.eclipse.ui.internal.handlers.HandlerProxy.execute(HandlerProxy.java:295)
	at org.eclipse.ui.internal.handlers.E4HandlerProxy.execute(E4HandlerProxy.java:90)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.eclipse.e4.core.internal.di.MethodRequestor.execute(MethodRequestor.java:55)
	at org.eclipse.e4.core.internal.di.InjectorImpl.invokeUsingClass(InjectorImpl.java:282)
	at org.eclipse.e4.core.internal.di.InjectorImpl.invoke(InjectorImpl.java:264)
	at org.eclipse.e4.core.contexts.ContextInjectionFactory.invoke(ContextInjectionFactory.java:132)
	at org.eclipse.e4.core.commands.internal.HandlerServiceHandler.execute(HandlerServiceHandler.java:152)
	at org.eclipse.core.commands.Command.executeWithChecks(Command.java:494)
	at org.eclipse.core.commands.ParameterizedCommand.executeWithChecks(ParameterizedCommand.java:488)
	at org.eclipse.e4.core.commands.internal.HandlerServiceImpl.executeHandler(HandlerServiceImpl.java:210)
	at org.eclipse.ui.internal.handlers.LegacyHandlerService.executeCommand(LegacyHandlerService.java:353)
	at org.eclipse.ui.menus.CommandContributionItem.handleWidgetSelection(CommandContributionItem.java:830)
	at org.eclipse.ui.menus.CommandContributionItem.access$21(CommandContributionItem.java:816)
	at org.eclipse.ui.menus.CommandContributionItem$5.handleEvent(CommandContributionItem.java:806)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:84)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:5227)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1340)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4561)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:4151)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$4.run(PartRenderingEngine.java:1121)

!ENTRY org.jkiss.dbeaver.model 4 0 2017-07-19 10:45:42.199
!MESSAGE Event loop exception
!SUBENTRY 1 org.jkiss.dbeaver.model 4 0 2017-07-19 10:45:42.199
!MESSAGE Java heap space
!STACK 0
java.lang.OutOfMemoryError: Java heap space
	at org.eclipse.swt.graphics.ImageData.<init>(ImageData.java:449)
	at org.eclipse.swt.graphics.ImageData.<init>(ImageData.java:260)
	at org.jkiss.dbeaver.ui.ImageUtils.get8BitPaletteImageData(ImageUtils.java:262)
	at org.jkiss.dbeaver.ui.ImageUtils.makeWebImageData(ImageUtils.java:236)
	at org.jkiss.dbeaver.ext.erd.editor.ERDEditorPart.saveDiagramAs(ERDEditorPart.java:696)
	at org.jkiss.dbeaver.ext.erd.editor.ERDEditorPart.doSaveAs(ERDEditorPart.java:261)
	at org.jkiss.dbeaver.ui.editors.entity.EntityEditor.doSaveAs(EntityEditor.java:204)
	at org.eclipse.ui.internal.handlers.SaveAsHandler.execute(SaveAsHandler.java:42)
	at org.eclipse.ui.internal.handlers.HandlerProxy.execute(HandlerProxy.java:295)
	at org.eclipse.ui.internal.handlers.E4HandlerProxy.execute(E4HandlerProxy.java:90)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.eclipse.e4.core.internal.di.MethodRequestor.execute(MethodRequestor.java:55)
	at org.eclipse.e4.core.internal.di.InjectorImpl.invokeUsingClass(InjectorImpl.java:282)
	at org.eclipse.e4.core.internal.di.InjectorImpl.invoke(InjectorImpl.java:264)
	at org.eclipse.e4.core.contexts.ContextInjectionFactory.invoke(ContextInjectionFactory.java:132)
	at org.eclipse.e4.core.commands.internal.HandlerServiceHandler.execute(HandlerServiceHandler.java:152)
	at org.eclipse.core.commands.Command.executeWithChecks(Command.java:494)
	at org.eclipse.core.commands.ParameterizedCommand.executeWithChecks(ParameterizedCommand.java:488)
	at org.eclipse.e4.core.commands.internal.HandlerServiceImpl.executeHandler(HandlerServiceImpl.java:210)
	at org.eclipse.ui.internal.handlers.LegacyHandlerService.executeCommand(LegacyHandlerService.java:353)
	at org.eclipse.ui.menus.CommandContributionItem.handleWidgetSelection(CommandContributionItem.java:830)
	at org.eclipse.ui.menus.CommandContributionItem.access$21(CommandContributionItem.java:816)
	at org.eclipse.ui.menus.CommandContributionItem$5.handleEvent(CommandContributionItem.java:806)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:84)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:5227)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1340)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4561)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:4151)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$4.run(PartRenderingEngine.java:1121)

**Comment by serge-rider** [comment]
DBeaver is out of memory because image is too big.
Check this topic for max memory increase: https://github.com/serge-rider/dbeaver/wiki/Command-Line#vm-arguments

**Comment by mrmuskrat** [comment]
Thank you.

**Comment by matkosoric** [comment]
I have a similar problem with star schema without any data in it. When I try to 'Save diagram in external format', image is partially cut off, regardless of the zoom. Also, there is a message from automatically started Image Viewer "No image found."

Database is Postgres 10.6 with Ubuntu 18.04.2 LTS. Logs are empty.
