### ISSUE TITLE
Freeze dBeaver for some time by copying multiple connections

### ISSUE THREAD

**Issue by GiantCrocodile** [serge-rider/dbeaver#1880]
1. create 1 connection
2. copy it and paste it a few times
3. copy all of them now
4. paste all of them some times

You get critical errors about preference node <some id> have been removed.

**Comment by GiantCrocodile** [comment]
```
java.lang.IllegalStateException: Preference node "postgres-jdbc-15d3e0188c3-53e7415bf3ba5c9d" has been removed.
	at org.eclipse.equinox.internal.security.storage.SecurePreferences.checkRemoved(SecurePreferences.java:354)
	at org.eclipse.equinox.internal.security.storage.SecurePreferences.removeNode(SecurePreferences.java:328)
	at org.eclipse.equinox.internal.security.storage.SecurePreferencesWrapper.removeNode(SecurePreferencesWrapper.java:99)
	at org.jkiss.dbeaver.registry.DataSourceRegistry.clearSecuredPasswords(DataSourceRegistry.java:892)
	at org.jkiss.dbeaver.registry.DataSourceRegistry.saveDataSource(DataSourceRegistry.java:648)
	at org.jkiss.dbeaver.registry.DataSourceRegistry.saveDataSources(DataSourceRegistry.java:559)
	at org.jkiss.dbeaver.registry.DataSourceRegistry.addDataSource(DataSourceRegistry.java:317)
	at org.jkiss.dbeaver.registry.DataSourceDescriptorManager.createNewObject(DataSourceDescriptorManager.java:101)
	at org.jkiss.dbeaver.registry.DataSourceDescriptorManager.createNewObject(DataSourceDescriptorManager.java:1)
	at org.jkiss.dbeaver.ui.actions.navigator.NavigatorHandlerObjectCreateBase$CreateJob.run(NavigatorHandlerObjectCreateBase.java:127)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:95)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)

```

**Comment by serge-rider** [comment]
Thanks for report

**Comment by GiantCrocodile** [comment]
I just tested your fix @serge-rider. When I do the same as before I get this now:

`Can't save password in secure storage`

```
java.lang.IllegalStateException: Preference node "postgres-jdbc-15d46579688-35fb970a610b38ae" has been removed.
	at org.eclipse.equinox.internal.security.storage.SecurePreferences.checkRemoved(SecurePreferences.java:354)
	at org.eclipse.equinox.internal.security.storage.SecurePreferences.removeNode(SecurePreferences.java:328)
	at org.eclipse.equinox.internal.security.storage.SecurePreferencesWrapper.removeNode(SecurePreferencesWrapper.java:99)
	at org.jkiss.dbeaver.registry.DataSourceRegistry.saveSecuredCredentials(DataSourceRegistry.java:851)
	at org.jkiss.dbeaver.registry.DataSourceRegistry.saveDataSource(DataSourceRegistry.java:685)
	at org.jkiss.dbeaver.registry.DataSourceRegistry.saveDataSources(DataSourceRegistry.java:559)
	at org.jkiss.dbeaver.registry.DataSourceRegistry.addDataSource(DataSourceRegistry.java:317)
	at org.jkiss.dbeaver.registry.DataSourceDescriptorManager.createNewObject(DataSourceDescriptorManager.java:101)
	at org.jkiss.dbeaver.registry.DataSourceDescriptorManager.createNewObject(DataSourceDescriptorManager.java:1)
	at org.jkiss.dbeaver.ui.actions.navigator.NavigatorHandlerObjectCreateBase$CreateJob.run(NavigatorHandlerObjectCreateBase.java:127)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:95)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)
```

This happens after DBeaver inserted some of the new connections, not instantly.

**Comment by serge-rider** [comment]
That's ok, it is just a warning (happens when DBeaver clears secured credentials twice). Anyhow I'll fix it too.

**Comment by GiantCrocodile** [comment]
Is it possible to introduce next to ERROR and INFO a WARNING symbol/log info? Right now, I don't see how a warning and error can be distinguished.

**Comment by serge-rider** [comment]
Sure. But this particular error won't happen after fix.

**Comment by GiantCrocodile** [comment]
After this I get `Dispose of already disposed data source` in combination with:

```
java.lang.IllegalStateException: Preference node "postgres-jdbc-15d4814fe8b-473bb54b81c566ac" has been removed.
	at org.eclipse.equinox.internal.security.storage.SecurePreferences.checkRemoved(SecurePreferences.java:354)
	at org.eclipse.equinox.internal.security.storage.SecurePreferences.removeNode(SecurePreferences.java:328)
	at org.eclipse.equinox.internal.security.storage.SecurePreferencesWrapper.removeNode(SecurePreferencesWrapper.java:99)
	at org.jkiss.dbeaver.registry.DataSourceRegistry.saveSecuredCredentials(DataSourceRegistry.java:849)
	at org.jkiss.dbeaver.registry.DataSourceRegistry.saveDataSource(DataSourceRegistry.java:683)
	at org.jkiss.dbeaver.registry.DataSourceRegistry.saveDataSources(DataSourceRegistry.java:559)
	at org.jkiss.dbeaver.registry.DataSourceRegistry.addDataSource(DataSourceRegistry.java:317)
	at org.jkiss.dbeaver.registry.DataSourceDescriptorManager.createNewObject(DataSourceDescriptorManager.java:101)
	at org.jkiss.dbeaver.registry.DataSourceDescriptorManager.createNewObject(DataSourceDescriptorManager.java:1)
	at org.jkiss.dbeaver.ui.actions.navigator.NavigatorHandlerObjectCreateBase$CreateJob.run(NavigatorHandlerObjectCreateBase.java:127)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:95)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)

```
