### ISSUE TITLE
Exception after using Last Edit location in combination with connection switcher

### ISSUE THREAD

**Issue by GiantCrocodile** [serge-rider/dbeaver#1889]
1. open an editor
2. close it
3. press last edit location button in toolbar
4. click on connection switcher and switch it:

```
org.eclipse.swt.SWTException: Invalid thread access
	at org.eclipse.swt.SWT.error(SWT.java:4533)
	at org.eclipse.swt.SWT.error(SWT.java:4448)
	at org.eclipse.swt.SWT.error(SWT.java:4419)
	at org.eclipse.swt.widgets.Widget.error(Widget.java:482)
	at org.eclipse.swt.widgets.Widget.checkWidget(Widget.java:373)
	at org.eclipse.swt.widgets.Control.setEnabled(Control.java:3410)
	at org.jkiss.dbeaver.ui.perspective.DataSourceManagementToolbar.updateControls(DataSourceManagementToolbar.java:467)
	at org.jkiss.dbeaver.ui.perspective.DataSourceManagementToolbar.access$1(DataSourceManagementToolbar.java:458)
	at org.jkiss.dbeaver.ui.perspective.DataSourceManagementToolbar$8.done(DataSourceManagementToolbar.java:639)
	at org.eclipse.core.internal.jobs.JobListeners$3.notify(JobListeners.java:42)
	at org.eclipse.core.internal.jobs.JobListeners.doNotify(JobListeners.java:106)
	at org.eclipse.core.internal.jobs.JobListeners.done(JobListeners.java:144)
	at org.eclipse.core.internal.jobs.JobManager.endJob(JobManager.java:694)
	at org.eclipse.core.internal.jobs.WorkerPool.endJob(WorkerPool.java:105)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:72)

```

**Comment by serge-rider** [comment]
This was fixed as a part of #1921
Thanks for report anyway
