### ISSUE TITLE
Lose connection with mysql and it hangs

### ISSUE THREAD

**Issue by mariogaitan** [serge-rider/dbeaver#1904]
Every time I wait a little moment after working with mysql, the application is locked. 
After some minutes, appear this in logs:

2017-07-20 13:21:29.060 - Shutdown Core...
2017-07-20 13:21:32.120 - Statement 97 (select * from codigos_suscripcion.palabras_clave where codigo_suscripcion = 23) is not closed
2017-07-20 13:21:34.078 - Some data source connections wasn't closed on shutdown in 5000ms. Probably network timeout occurred.
2017-07-20 13:21:34.080 - Some sessions are still open: [SESSION Zunil [Metadata]]
2017-07-20 13:21:34.196 - Shutdown completed in 5136ms
2017-07-20 13:21:34.224 - java.lang.IllegalStateException: Job manager has been shut down.
java.lang.IllegalStateException: Job manager has been shut down.
	at org.eclipse.core.internal.jobs.JobManager.schedule(JobManager.java:1240)
	at org.eclipse.core.internal.jobs.InternalJob.schedule(InternalJob.java:382)
	at org.eclipse.core.runtime.jobs.Job.schedule(Job.java:668)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.canceling(AbstractJob.java:135)
	at org.eclipse.core.internal.jobs.JobManager.cancel(JobManager.java:341)
	at org.eclipse.core.internal.jobs.JobManager.doShutdown(JobManager.java:613)
	at org.eclipse.core.internal.jobs.JobManager.shutdown(JobManager.java:277)
	at org.eclipse.core.internal.jobs.JobActivator.stop(JobActivator.java:57)
	at org.eclipse.osgi.internal.framework.BundleContextImpl$4.run(BundleContextImpl.java:830)
	at org.eclipse.osgi.internal.framework.BundleContextImpl$4.run(BundleContextImpl.java:1)
	at java.security.AccessController.doPrivileged(Native Method)
	at org.eclipse.osgi.internal.framework.BundleContextImpl.stop(BundleContextImpl.java:823)
	at org.eclipse.osgi.internal.framework.EquinoxBundle.stopWorker0(EquinoxBundle.java:946)
	at org.eclipse.osgi.internal.framework.EquinoxBundle$EquinoxModule.stopWorker(EquinoxBundle.java:314)
	at org.eclipse.osgi.container.Module.doStop(Module.java:636)
	at org.eclipse.osgi.container.Module.stop(Module.java:498)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.decStartLevel(ModuleContainer.java:1661)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.doContainerStartLevel(ModuleContainer.java:1580)
	at org.eclipse.osgi.container.SystemModule.stopWorker(SystemModule.java:270)
	at org.eclipse.osgi.internal.framework.EquinoxBundle$SystemBundle$EquinoxSystemModule.stopWorker(EquinoxBundle.java:147)
	at org.eclipse.osgi.container.Module.doStop(Module.java:636)
	at org.eclipse.osgi.container.Module.stop(Module.java:498)
	at org.eclipse.osgi.container.SystemModule.stop(SystemModule.java:202)
	at org.eclipse.osgi.internal.framework.EquinoxBundle$SystemBundle$EquinoxSystemModule$1.run(EquinoxBundle.java:165)
	at java.lang.Thread.run(Thread.java:745)
2017-07-20 13:21:34.228 - java.lang.IllegalStateException: Job manager has been shut down.
java.lang.IllegalStateException: Job manager has been shut down.
	at org.eclipse.core.internal.jobs.JobManager.schedule(JobManager.java:1240)
	at org.eclipse.core.internal.jobs.InternalJob.schedule(InternalJob.java:382)
	at org.eclipse.core.runtime.jobs.Job.schedule(Job.java:668)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.canceling(AbstractJob.java:135)
	at org.eclipse.core.internal.jobs.JobManager.cancel(JobManager.java:341)
	at org.eclipse.core.internal.jobs.JobManager.doShutdown(JobManager.java:613)
	at org.eclipse.core.internal.jobs.JobManager.shutdown(JobManager.java:277)
	at org.eclipse.core.internal.jobs.JobActivator.stop(JobActivator.java:57)
	at org.eclipse.osgi.internal.framework.BundleContextImpl$4.run(BundleContextImpl.java:830)
	at org.eclipse.osgi.internal.framework.BundleContextImpl$4.run(BundleContextImpl.java:1)
	at java.security.AccessController.doPrivileged(Native Method)
	at org.eclipse.osgi.internal.framework.BundleContextImpl.stop(BundleContextImpl.java:823)
	at org.eclipse.osgi.internal.framework.EquinoxBundle.stopWorker0(EquinoxBundle.java:946)
	at org.eclipse.osgi.internal.framework.EquinoxBundle$EquinoxModule.stopWorker(EquinoxBundle.java:314)
	at org.eclipse.osgi.container.Module.doStop(Module.java:636)
	at org.eclipse.osgi.container.Module.stop(Module.java:498)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.decStartLevel(ModuleContainer.java:1661)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.doContainerStartLevel(ModuleContainer.java:1580)
	at org.eclipse.osgi.container.SystemModule.stopWorker(SystemModule.java:270)
	at org.eclipse.osgi.internal.framework.EquinoxBundle$SystemBundle$EquinoxSystemModule.stopWorker(EquinoxBundle.java:147)
	at org.eclipse.osgi.container.Module.doStop(Module.java:636)
	at org.eclipse.osgi.container.Module.stop(Module.java:498)
	at org.eclipse.osgi.container.SystemModule.stop(SystemModule.java:202)
	at org.eclipse.osgi.internal.framework.EquinoxBundle$SystemBundle$EquinoxSystemModule$1.run(EquinoxBundle.java:165)
	at java.lang.Thread.run(Thread.java:745)
Job found still running after platform shutdown.  Jobs should be canceled by the plugin that scheduled them during shutdown: org.jkiss.dbeaver.ui.controls.resultset.ResultSetJobDataRead
Job found still running after platform shutdown.  Jobs should be canceled by the plugin that scheduled them during shutdown: org.jkiss.dbeaver.utils.RuntimeUtils$1
Job found still running after platform shutdown.  Jobs should be canceled by the plugin that scheduled them during shutdown: org.jkiss.dbeaver.utils.RuntimeUtils$1

**Comment by serge-rider** [comment]
Maybe this was fixed as a part of #1918 but maybe it is different.
Please make a thread dump (https://github.com/serge-rider/dbeaver/wiki/Making-a-thread-dump) next time DBeaver will freeze.
Thanks for report.

**Comment by tati-kru** [comment]
Hi @mariogaitan. Could you< please, check that it can be reproduced or not on the latest version?

**Comment by serge-rider** [comment]
Closing as non reproducible.
