### ISSUE TITLE
Cannot run query on AWS Athena

### ISSUE THREAD

**Issue by ckljohn** [serge-rider/dbeaver#1950]
I am connecting to AWS Athena with JDBC following the guide on http://docs.aws.amazon.com/athena/latest/ug/connect-with-jdbc.html

I am able to see the metadata and preview data in the table tab.
However, when I try to run query (e.g. select * from my_table limit 100), this error pops out.
`SQL Error: Method Connection.prepareStatement is not yet implemented`

> org.jkiss.dbeaver.model.impl.jdbc.JDBCException: SQL Error: Method Connection.prepareStatement is not yet implemented
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCConnectionImpl.prepareStatement(JDBCConnectionImpl.java:178)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCConnectionImpl.prepareStatement(JDBCConnectionImpl.java:1)
	at org.jkiss.dbeaver.model.DBUtils.prepareStatement(DBUtils.java:979)
	at org.jkiss.dbeaver.model.DBUtils.prepareStatement(DBUtils.java:922)
	at org.jkiss.dbeaver.runtime.sql.SQLQueryJob.executeSingleQuery(SQLQueryJob.java:325)
	at org.jkiss.dbeaver.runtime.sql.SQLQueryJob.extractData(SQLQueryJob.java:708)
	at org.jkiss.dbeaver.ui.editors.sql.SQLEditor$QueryResultsContainer.readData(SQLEditor.java:1655)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetDataPumpJob.run(ResultSetDataPumpJob.java:139)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:103)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)
Caused by: com.amazonaws.athena.jdbc.NotImplementedException: Method Connection.prepareStatement is not yet implemented
	at com.amazonaws.athena.jdbc.AthenaConnection.prepareStatement(AthenaConnection.java:114)
	at com.amazonaws.athena.jdbc.AthenaConnection.prepareStatement(AthenaConnection.java:269)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCConnectionImpl.prepareStatement(JDBCConnectionImpl.java:376)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCConnectionImpl.prepareStatement(JDBCConnectionImpl.java:164)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCConnectionImpl.prepareStatement(JDBCConnectionImpl.java:1)
	at org.jkiss.dbeaver.model.DBUtils.prepareStatement(DBUtils.java:979)
	at org.jkiss.dbeaver.model.DBUtils.prepareStatement(DBUtils.java:922)
	at org.jkiss.dbeaver.runtime.sql.SQLQueryJob.executeSingleQuery(SQLQueryJob.java:325)
	at org.jkiss.dbeaver.runtime.sql.SQLQueryJob.extractData(SQLQueryJob.java:708)
	at org.jkiss.dbeaver.ui.editors.sql.SQLEditor$QueryResultsContainer.readData(SQLEditor.java:1655)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetDataPumpJob.run(ResultSetDataPumpJob.java:139)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:103)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)

Is there a way to bypass the prepareStatement in Dbeaver?

**Comment by ckljohn** [comment]
I was using version 3.8
After upgrading to 4.1.1, problem solved.

**Comment by serge-rider** [comment]
Thanks for info
