### ISSUE TITLE
Error when trying to look at triggers

### ISSUE THREAD

**Issue by jmccay-work** [serge-rider/dbeaver#1968]
I love this product, and it makes working with the database I am connecting to is Informix (unfortunately) better.  I am using version 4.1.0 Enterprise Edition; June 26, 2017; (C) JKISS project, 2017.  When I try to view the triggers tab of a table, I get the following error:

`
SQL Error [IX000]: Number of input values does not match number of question marks
  java.sql.SQLException: Number of input values does not match number of question marks
`

This is not a show stopper for me, but I did want to report it.  It looks like there is wrong number of arguments in a prepared statement.

**Comment by serge-rider** [comment]
Please post error stacktrace (you can get it in Error Log view or in log files).

However errors looks like some Informix JDBC driver error. You could try to use different version of it.

**Comment by jmccay-work** [comment]
Here are the 2 log files.  After looking at them, it might be internal to
the JDBC driver.  It appears that it can't find 4 bits of meta information
which causes the actual error that is displayed.  Thanks for replying so
quickly, and I will look for new Informix drivers sometime later.

Joe M.

Sincerely,

Joseph L. McCay
Queues Enforth Development, Inc.
92 Montvale Avenue, Suite 4350
Stoneham, MA  02180-3647
Telephone Main: 781-870-1100
Telephone Direct: 781-870-1103

**Comment by serge-rider** [comment]
GitHub doesn't add email attachments to tickets.

Please add logs to GitHub issue (by drag-b-drop) or send them on serge@jkiss.org.

**Comment by jmccay-work** [comment]
I have attached the log files from the error.

[the log files.zip](https://github.com/serge-rider/dbeaver/files/1205846/the.log.files.zip)

**Comment by serge-rider** [comment]
This is a bug in DBeaver. 
Thanks for report.

**Comment by alexi-courieux** [comment]
Hello, I have a similar bug with my DB2 database, when I try to open the triggers 'folder', I have this error: `Internal driver error`.

here is the log file :
```
!ENTRY org.jkiss.dbeaver.model 4 0 2021-02-25 15:39:19.527
!MESSAGE 
!SUBENTRY 1 org.jkiss.dbeaver.model 4 0 2021-02-25 15:39:19.527
!MESSAGE 
!STACK 0
java.lang.NullPointerException
	at org.jkiss.dbeaver.ext.db2.model.DB2Trigger.<init>(DB2Trigger.java:90)
	at org.jkiss.dbeaver.ext.db2.model.cache.DB2TriggerCache.fetchObject(DB2TriggerCache.java:64)
	at org.jkiss.dbeaver.ext.db2.model.cache.DB2TriggerCache.fetchObject(DB2TriggerCache.java:1)
	at org.jkiss.dbeaver.model.impl.jdbc.cache.JDBCObjectCache.loadObjects(JDBCObjectCache.java:117)
	at org.jkiss.dbeaver.model.impl.jdbc.cache.JDBCObjectCache.getAllObjects(JDBCObjectCache.java:73)
	at org.jkiss.dbeaver.ext.db2.model.DB2Schema.getTriggers(DB2Schema.java:363)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at org.jkiss.dbeaver.model.navigator.DBNDatabaseNode.extractPropertyValue(DBNDatabaseNode.java:872)
	at org.jkiss.dbeaver.model.navigator.DBNDatabaseNode.access$1(DBNDatabaseNode.java:853)
	at org.jkiss.dbeaver.model.navigator.DBNDatabaseNode$PropertyValueReader.run(DBNDatabaseNode.java:915)
	at org.jkiss.dbeaver.model.navigator.DBNDatabaseNode$PropertyValueReader.run(DBNDatabaseNode.java:1)
	at org.jkiss.dbeaver.model.exec.DBExecUtils.tryExecuteRecover(DBExecUtils.java:168)
	at org.jkiss.dbeaver.model.navigator.DBNDatabaseNode.loadTreeItems(DBNDatabaseNode.java:539)
	at org.jkiss.dbeaver.model.navigator.DBNDatabaseNode.loadChildren(DBNDatabaseNode.java:429)
	at org.jkiss.dbeaver.model.navigator.DBNDatabaseNode.getChildren(DBNDatabaseNode.java:205)
	at org.jkiss.dbeaver.model.navigator.DBNDatabaseNode.getChildren(DBNDatabaseNode.java:1)
	at org.jkiss.dbeaver.model.navigator.DBNUtils.getNodeChildrenFiltered(DBNUtils.java:70)
	at org.jkiss.dbeaver.ui.navigator.database.load.TreeLoadService.evaluate(TreeLoadService.java:49)
	at org.jkiss.dbeaver.ui.navigator.database.load.TreeLoadService.evaluate(TreeLoadService.java:1)
	at org.jkiss.dbeaver.ui.LoadingJob.run(LoadingJob.java:88)
	at org.jkiss.dbeaver.ui.LoadingJob.run(LoadingJob.java:72)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:105)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
```

I don't know if I should have started a new ticket, but this bug seems close enough to me.
