### ISSUE TITLE
DBeaver stop to show connections tree and freeze with NullPointerException in the log

### ISSUE THREAD

**Issue by mstup** [serge-rider/dbeaver#1985]
DBeaver 4.1.2 (Fedora 23 64bit) in the log:
P.S. PRODUCT_FAMILY in the table name.
```
-------------
сер 08 14:39:39 localhost dbeaver.desktop[28449]: 2017-08-08 14:39:39.268 - org.jkiss.dbeaver.DBException: Bad child object specified as active: PRODUCT_FAMILY
сер 08 14:39:39 localhost dbeaver.desktop[28449]: org.jkiss.dbeaver.DBException: Bad child object specified as active: PRODUCT_FAMILY
сер 08 14:39:39 localhost dbeaver.desktop[28449]: at org.jkiss.dbeaver.ext.generic.model.GenericDataSource.setDefaultObject(GenericDataSource.java:740)
сер 08 14:39:39 localhost dbeaver.desktop[28449]: at org.jkiss.dbeaver.ui.navigator.NavigatorUtils.syncEditorWithNavigator(NavigatorUtils.java:543)
сер 08 14:39:39 localhost dbeaver.desktop[28449]: at org.jkiss.dbeaver.ui.navigator.database.NavigatorViewBase.onSelectionChange(NavigatorViewBase.java:192)
сер 08 14:39:39 localhost dbeaver.desktop[28449]: at org.jkiss.dbeaver.ui.navigator.database.NavigatorViewBase$1.selectionChanged(NavigatorViewBase.java:115)
сер 08 14:39:39 localhost dbeaver.desktop[28449]: at org.eclipse.jface.viewers.Viewer$1.run(Viewer.java:158)
сер 08 14:39:39 localhost dbeaver.desktop[28449]: at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
сер 08 14:39:39 localhost dbeaver.desktop[28449]: at org.eclipse.ui.internal.JFaceUtil$1.run(JFaceUtil.java:50)
сер 08 14:39:39 localhost dbeaver.desktop[28449]: at org.eclipse.jface.util.SafeRunnable.run(SafeRunnable.java:173)
сер 08 14:39:39 localhost dbeaver.desktop[28449]: at org.eclipse.jface.viewers.Viewer.fireSelectionChanged(Viewer.java:155)
сер 08 14:39:39 localhost dbeaver.desktop[28449]: at org.eclipse.jface.viewers.StructuredViewer.updateSelection(StructuredViewer.java:2191)
сер 08 14:39:39 localhost dbeaver.desktop[28449]: at org.eclipse.jface.viewers.StructuredViewer.handleSelect(StructuredViewer.java:1229)
сер 08 14:39:39 localhost dbeaver.desktop[28449]: at org.eclipse.jface.viewers.StructuredViewer$4.widgetSelected(StructuredViewer.java:1258)
сер 08 14:39:39 localhost dbeaver.desktop[28449]: at org.eclipse.jface.util.OpenStrategy.fireSelectionEvent(OpenStrategy.java:242)
сер 08 14:39:39 localhost dbeaver.desktop[28449]: at org.eclipse.jface.util.OpenStrategy.access$4(OpenStrategy.java:236)
сер 08 14:39:39 localhost dbeaver.desktop[28449]: at org.eclipse.jface.util.OpenStrategy$1.handleEvent(OpenStrategy.java:405)
сер 08 14:39:39 localhost dbeaver.desktop[28449]: at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:84)
сер 08 14:39:39 localhost dbeaver.desktop[28449]: at org.eclipse.swt.widgets.Display.sendEvent(Display.java:5227)
сер 08 14:39:39 localhost dbeaver.desktop[28449]: at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1340)
сер 08 14:39:39 localhost dbeaver.desktop[28449]: at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4561)
сер 08 14:39:39 localhost dbeaver.desktop[28449]: at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:4151)
сер 08 14:39:39 localhost dbeaver.desktop[28449]: at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$4.run(PartRenderingEngine.java:1121)
сер 08 14:39:39 localhost dbeaver.desktop[28449]: at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:336)
сер 08 14:39:39 localhost dbeaver.desktop[28449]: at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1022)
сер 08 14:39:39 localhost dbeaver.desktop[28449]: at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:150)
сер 08 14:39:39 localhost dbeaver.desktop[28449]: at org.eclipse.ui.internal.Workbench$5.run(Workbench.java:693)
сер 08 14:39:39 localhost dbeaver.desktop[28449]: at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:336)
сер 08 14:39:39 localhost dbeaver.desktop[28449]: at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:610)
сер 08 14:39:39 localhost dbeaver.desktop[28449]: at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:148)
сер 08 14:39:39 localhost dbeaver.desktop[28449]: at org.jkiss.dbeaver.core.application.DBeaverApplication.start(DBeaverApplication.java:164)
сер 08 14:39:39 localhost dbeaver.desktop[28449]: at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
сер 08 14:39:39 localhost dbeaver.desktop[28449]: at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
сер 08 14:39:39 localhost dbeaver.desktop[28449]: at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
сер 08 14:39:39 localhost dbeaver.desktop[28449]: at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:388)
сер 08 14:39:39 localhost dbeaver.desktop[28449]: at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:243)
сер 08 14:39:39 localhost dbeaver.desktop[28449]: at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
сер 08 14:39:39 localhost dbeaver.desktop[28449]: at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
сер 08 14:39:39 localhost dbeaver.desktop[28449]: at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
сер 08 14:39:39 localhost dbeaver.desktop[28449]: at java.lang.reflect.Method.invoke(Method.java:498)
сер 08 14:39:39 localhost dbeaver.desktop[28449]: at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:673)
сер 08 14:39:39 localhost dbeaver.desktop[28449]: at org.eclipse.equinox.launcher.Main.basicRun(Main.java:610)
сер 08 14:39:39 localhost dbeaver.desktop[28449]: at org.eclipse.equinox.launcher.Main.run(Main.java:1519)
сер 08 14:39:39 localhost dbeaver.desktop[28449]: at org.eclipse.equinox.launcher.Main.main(Main.java:1492)
сер 08 14:39:39 localhost dbeaver.desktop[28449]: 2017-08-08 14:39:39.510 - Event loop exception
сер 08 14:39:39 localhost dbeaver.desktop[28449]: java.lang.NullPointerException
сер 08 14:39:39 localhost dbeaver.desktop[28449]: at com.xored.glance.ui.controls.decor.StructSource.getCell(StructSource.java:53)
сер 08 14:39:39 localhost dbeaver.desktop[28449]: at com.xored.glance.ui.controls.decor.StructDecorator.paint(StructDecorator.java:83)
сер 08 14:39:39 localhost dbeaver.desktop[28449]: at com.xored.glance.ui.controls.decor.StructDecorator.handleEvent(StructDecorator.java:68)
сер 08 14:39:39 localhost dbeaver.desktop[28449]: at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:84)
сер 08 14:39:39 localhost dbeaver.desktop[28449]: at org.eclipse.swt.widgets.Display.sendEvent(Display.java:5227)
сер 08 14:39:39 localhost dbeaver.desktop[28449]: at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1340)
сер 08 14:39:39 localhost dbeaver.desktop[28449]: at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1366)
сер 08 14:39:39 localhost dbeaver.desktop[28449]: at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1349)
сер 08 14:39:39 localhost dbeaver.desktop[28449]: at org.eclipse.swt.widgets.Tree.rendererRender(Tree.java:2968)
сер 08 14:39:39 localhost dbeaver.desktop[28449]: at org.eclipse.swt.widgets.Tree.rendererRenderProc(Tree.java:2736)
сер 08 14:39:39 localhost dbeaver.desktop[28449]: at org.eclipse.swt.widgets.Display.rendererRenderProc(Display.java:1419)
сер 08 14:39:39 localhost dbeaver.desktop[28449]: at org.eclipse.swt.internal.gtk.OS._gtk_main_do_event(Native Method)
сер 08 14:39:39 localhost dbeaver.desktop[28449]: at org.eclipse.swt.internal.gtk.OS.gtk_main_do_event(OS.java:9545)
сер 08 14:39:39 localhost dbeaver.desktop[28449]: at org.eclipse.swt.widgets.Display.eventProc(Display.java:1275)
сер 08 14:39:39 localhost dbeaver.desktop[28449]: at org.eclipse.swt.internal.gtk.OS._gdk_window_process_all_updates(Native Method)
сер 08 14:39:39 localhost dbeaver.desktop[28449]: at org.eclipse.swt.internal.gtk.OS.gdk_window_process_all_updates(OS.java:6110)
сер 08 14:39:39 localhost dbeaver.desktop[28449]: at org.eclipse.swt.widgets.Display.update(Display.java:5450)
сер 08 14:39:39 localhost dbeaver.desktop[28449]: at org.eclipse.swt.widgets.Display.runDeferredLayouts(Display.java:4587)
сер 08 14:39:39 localhost dbeaver.desktop[28449]: at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:4138)
сер 08 14:39:39 localhost dbeaver.desktop[28449]: at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$4.run(PartRenderingEngine.java:1121)
сер 08 14:39:39 localhost dbeaver.desktop[28449]: at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:336)
сер 08 14:39:39 localhost dbeaver.desktop[28449]: at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1022)
сер 08 14:39:39 localhost dbeaver.desktop[28449]: at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:150)
сер 08 14:39:39 localhost dbeaver.desktop[28449]: at org.eclipse.ui.internal.Workbench$5.run(Workbench.java:693)
сер 08 14:39:39 localhost dbeaver.desktop[28449]: at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:336)
сер 08 14:39:39 localhost dbeaver.desktop[28449]: at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:610)
сер 08 14:39:39 localhost dbeaver.desktop[28449]: at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:148)
сер 08 14:39:39 localhost dbeaver.desktop[28449]: at org.jkiss.dbeaver.core.application.DBeaverApplication.start(DBeaverApplication.java:164)
сер 08 14:39:39 localhost dbeaver.desktop[28449]: at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
сер 08 14:39:39 localhost dbeaver.desktop[28449]: at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
сер 08 14:39:39 localhost dbeaver.desktop[28449]: at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
сер 08 14:39:39 localhost dbeaver.desktop[28449]: at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:388)
сер 08 14:39:39 localhost dbeaver.desktop[28449]: at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:243)
сер 08 14:39:39 localhost dbeaver.desktop[28449]: at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
сер 08 14:39:39 localhost dbeaver.desktop[28449]: at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
сер 08 14:39:39 localhost dbeaver.desktop[28449]: at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
сер 08 14:39:39 localhost dbeaver.desktop[28449]: at java.lang.reflect.Method.invoke(Method.java:498)
сер 08 14:39:39 localhost dbeaver.desktop[28449]: at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:673)
сер 08 14:39:39 localhost dbeaver.desktop[28449]: at org.eclipse.equinox.launcher.Main.basicRun(Main.java:610)
сер 08 14:39:39 localhost dbeaver.desktop[28449]: at org.eclipse.equinox.launcher.Main.run(Main.java:1519)
сер 08 14:39:39 localhost dbeaver.desktop[28449]: at org.eclipse.equinox.launcher.Main.main(Main.java:1492)
сер 08 14:39:41 localhost dbeaver.desktop[28449]: 2017-08-08 14:39:41.169 - Event loop exception
сер 08 14:39:41 localhost dbeaver.desktop[28449]: java.lang.NullPointerException
сер 08 14:39:41 localhost dbeaver.desktop[28449]: at com.xored.glance.ui.controls.decor.StructSource.getCell(StructSource.java:53)
сер 08 14:39:41 localhost dbeaver.desktop[28449]: at com.xored.glance.ui.controls.decor.StructDecorator.paint(StructDecorator.java:83)
сер 08 14:39:41 localhost dbeaver.desktop[28449]: at com.xored.glance.ui.controls.decor.StructDecorator.handleEvent(StructDecorator.java:68)
сер 08 14:39:41 localhost dbeaver.desktop[28449]: at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:84)
сер 08 14:39:41 localhost dbeaver.desktop[28449]: at org.eclipse.swt.widgets.Display.sendEvent(Display.java:5227)
сер 08 14:39:41 localhost dbeaver.desktop[28449]: at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1340)
сер 08 14:39:41 localhost dbeaver.desktop[28449]: at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1366)
сер 08 14:39:41 localhost dbeaver.desktop[28449]: at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1349)
сер 08 14:39:41 localhost dbeaver.desktop[28449]: at org.eclipse.swt.widgets.Tree.rendererRender(Tree.java:2968)
сер 08 14:39:41 localhost dbeaver.desktop[28449]: at org.eclipse.swt.widgets.Tree.rendererRenderProc(Tree.java:2736)
сер 08 14:39:41 localhost dbeaver.desktop[28449]: at org.eclipse.swt.widgets.Display.rendererRenderProc(Display.java:1419)
сер 08 14:39:41 localhost dbeaver.desktop[28449]: at org.eclipse.swt.internal.gtk.OS._gtk_main_do_event(Native Method)
сер 08 14:39:41 localhost dbeaver.desktop[28449]: at org.eclipse.swt.internal.gtk.OS.gtk_main_do_event(OS.java:9545)
сер 08 14:39:41 localhost dbeaver.desktop[28449]: at org.eclipse.swt.widgets.Display.eventProc(Display.java:1275)
сер 08 14:39:41 localhost dbeaver.desktop[28449]: at org.eclipse.swt.internal.gtk.OS._g_main_context_iteration(Native Method)
сер 08 14:39:41 localhost dbeaver.desktop[28449]: at org.eclipse.swt.internal.gtk.OS.g_main_context_iteration(OS.java:2495)
сер 08 14:39:41 localhost dbeaver.desktop[28449]: at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:4149)
сер 08 14:39:41 localhost dbeaver.desktop[28449]: at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$4.run(PartRenderingEngine.java:1121)
сер 08 14:39:41 localhost dbeaver.desktop[28449]: at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:336)
сер 08 14:39:41 localhost dbeaver.desktop[28449]: at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1022)
сер 08 14:39:41 localhost dbeaver.desktop[28449]: at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:150)
сер 08 14:39:41 localhost dbeaver.desktop[28449]: at org.eclipse.ui.internal.Workbench$5.run(Workbench.java:693)
сер 08 14:39:41 localhost dbeaver.desktop[28449]: at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:336)
сер 08 14:39:41 localhost dbeaver.desktop[28449]: at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:610)
сер 08 14:39:41 localhost dbeaver.desktop[28449]: at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:148)
сер 08 14:39:41 localhost dbeaver.desktop[28449]: at org.jkiss.dbeaver.core.application.DBeaverApplication.start(DBeaverApplication.java:164)
сер 08 14:39:41 localhost dbeaver.desktop[28449]: at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
сер 08 14:39:41 localhost dbeaver.desktop[28449]: at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
сер 08 14:39:41 localhost dbeaver.desktop[28449]: at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
сер 08 14:39:41 localhost dbeaver.desktop[28449]: at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:388)
сер 08 14:39:41 localhost dbeaver.desktop[28449]: at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:243)
сер 08 14:39:41 localhost dbeaver.desktop[28449]: at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
сер 08 14:39:41 localhost dbeaver.desktop[28449]: at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
сер 08 14:39:41 localhost dbeaver.desktop[28449]: at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
сер 08 14:39:41 localhost dbeaver.desktop[28449]: at java.lang.reflect.Method.invoke(Method.java:498)
сер 08 14:39:41 localhost dbeaver.desktop[28449]: at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:673)
сер 08 14:39:41 localhost dbeaver.desktop[28449]: at org.eclipse.equinox.launcher.Main.basicRun(Main.java:610)
сер 08 14:39:41 localhost dbeaver.desktop[28449]: at org.eclipse.equinox.launcher.Main.run(Main.java:1519)
сер 08 14:39:41 localhost dbeaver.desktop[28449]: at org.eclipse.equinox.launcher.Main.main(Main.java:1492)
сер 08 14:39:41 localhost dbeaver.desktop[28449]: 2017-08-08 14:39:41.191 - Event loop exception
сер 08 14:39:41 localhost dbeaver.desktop[28449]: java.lang.NullPointerException
сер 08 14:39:41 localhost dbeaver.desktop[28449]: at com.xored.glance.ui.controls.decor.StructSource.getCell(StructSource.java:53)
сер 08 14:39:41 localhost dbeaver.desktop[28449]: at com.xored.glance.ui.controls.decor.StructDecorator.paint(StructDecorator.java:83)
сер 08 14:39:41 localhost dbeaver.desktop[28449]: at com.xored.glance.ui.controls.decor.StructDecorator.handleEvent(StructDecorator.java:68)
сер 08 14:39:41 localhost dbeaver.desktop[28449]: at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:84)
сер 08 14:39:41 localhost dbeaver.desktop[28449]: at org.eclipse.swt.widgets.Display.sendEvent(Display.java:5227)
сер 08 14:39:41 localhost dbeaver.desktop[28449]: at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1340)
сер 08 14:39:41 localhost dbeaver.desktop[28449]: at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1366)
сер 08 14:39:41 localhost dbeaver.desktop[28449]: at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1349)
сер 08 14:39:41 localhost dbeaver.desktop[28449]: at org.eclipse.swt.widgets.Tree.rendererRender(Tree.java:2968)
сер 08 14:39:41 localhost dbeaver.desktop[28449]: at org.eclipse.swt.widgets.Tree.rendererRenderProc(Tree.java:2736)
сер 08 14:39:41 localhost dbeaver.desktop[28449]: at org.eclipse.swt.widgets.Display.rendererRenderProc(Display.java:1419)
сер 08 14:39:41 localhost dbeaver.desktop[28449]: at org.eclipse.swt.internal.gtk.OS._gtk_main_do_event(Native Method)
сер 08 14:39:41 localhost dbeaver.desktop[28449]: at org.eclipse.swt.internal.gtk.OS.gtk_main_do_event(OS.java:9545)
сер 08 14:39:41 localhost dbeaver.desktop[28449]: at org.eclipse.swt.widgets.Display.eventProc(Display.java:1275)
сер 08 14:39:41 localhost dbeaver.desktop[28449]: at org.eclipse.swt.internal.gtk.OS._g_main_context_iteration(Native Method)
сер 08 14:39:41 localhost dbeaver.desktop[28449]: at org.eclipse.swt.internal.gtk.OS.g_main_context_iteration(OS.java:2495)
сер 08 14:39:41 localhost dbeaver.desktop[28449]: at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:4149)
сер 08 14:39:41 localhost dbeaver.desktop[28449]: at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$4.run(PartRenderingEngine.java:1121)
сер 08 14:39:41 localhost dbeaver.desktop[28449]: at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:336)
сер 08 14:39:41 localhost dbeaver.desktop[28449]: at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1022)
сер 08 14:39:41 localhost dbeaver.desktop[28449]: at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:150)
сер 08 14:39:41 localhost dbeaver.desktop[28449]: at org.eclipse.ui.internal.Workbench$5.run(Workbench.java:693)
сер 08 14:39:41 localhost dbeaver.desktop[28449]: at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:336)
сер 08 14:39:41 localhost dbeaver.desktop[28449]: at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:610)
сер 08 14:39:41 localhost dbeaver.desktop[28449]: at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:148)
сер 08 14:39:41 localhost dbeaver.desktop[28449]: at org.jkiss.dbeaver.core.application.DBeaverApplication.start(DBeaverApplication.java:164)
сер 08 14:39:41 localhost dbeaver.desktop[28449]: at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
сер 08 14:39:41 localhost dbeaver.desktop[28449]: at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
сер 08 14:39:41 localhost dbeaver.desktop[28449]: at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
сер 08 14:39:41 localhost dbeaver.desktop[28449]: at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:388)
сер 08 14:39:41 localhost dbeaver.desktop[28449]: at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:243)
сер 08 14:39:41 localhost dbeaver.desktop[28449]: at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
сер 08 14:39:41 localhost dbeaver.desktop[28449]: at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
сер 08 14:39:41 localhost dbeaver.desktop[28449]: at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
сер 08 14:39:41 localhost dbeaver.desktop[28449]: at java.lang.reflect.Method.invoke(Method.java:498)
сер 08 14:39:41 localhost dbeaver.desktop[28449]: at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:673)
сер 08 14:39:41 localhost dbeaver.desktop[28449]: at org.eclipse.equinox.launcher.Main.basicRun(Main.java:610)
сер 08 14:39:41 localhost dbeaver.desktop[28449]: at org.eclipse.equinox.launcher.Main.run(Main.java:1519)
сер 08 14:39:41 localhost dbeaver.desktop[28449]: at org.eclipse.equinox.launcher.Main.main(Main.java:1492)
сер 08 14:39:41 localhost dbeaver.desktop[28449]: 2017-08-08 14:39:41.215 - Event loop exception
сер 08 14:39:41 localhost dbeaver.desktop[28449]: java.lang.NullPointerException
сер 08 14:39:41 localhost dbeaver.desktop[28449]: at com.xored.glance.ui.controls.decor.StructSource.getCell(StructSource.java:53)
сер 08 14:39:41 localhost dbeaver.desktop[28449]: at com.xored.glance.ui.controls.decor.StructDecorator.paint(StructDecorator.java:83)
сер 08 14:39:41 localhost dbeaver.desktop[28449]: at com.xored.glance.ui.controls.decor.StructDecorator.handleEvent(StructDecorator.java:68)
сер 08 14:39:41 localhost dbeaver.desktop[28449]: at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:84)
сер 08 14:39:41 localhost dbeaver.desktop[28449]: at org.eclipse.swt.widgets.Display.sendEvent(Display.java:5227)
сер 08 14:39:41 localhost dbeaver.desktop[28449]: at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1340)
сер 08 14:39:41 localhost dbeaver.desktop[28449]: at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1366)
сер 08 14:39:41 localhost dbeaver.desktop[28449]: at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1349)
сер 08 14:39:41 localhost dbeaver.desktop[28449]: at org.eclipse.swt.widgets.Tree.rendererRender(Tree.java:2968)
сер 08 14:39:41 localhost dbeaver.desktop[28449]: at org.eclipse.swt.widgets.Tree.rendererRenderProc(Tree.java:2736)
сер 08 14:39:41 localhost dbeaver.desktop[28449]: at org.eclipse.swt.widgets.Display.rendererRenderProc(Display.java:1419)
сер 08 14:39:41 localhost dbeaver.desktop[28449]: at org.eclipse.swt.internal.gtk.OS._gtk_main_do_event(Native Method)
сер 08 14:39:41 localhost dbeaver.desktop[28449]: at org.eclipse.swt.internal.gtk.OS.gtk_main_do_event(OS.java:9545)
сер 08 14:39:41 localhost dbeaver.desktop[28449]: at org.eclipse.swt.widgets.Display.eventProc(Display.java:1275)
сер 08 14:39:41 localhost dbeaver.desktop[28449]: at org.eclipse.swt.internal.gtk.OS._g_main_context_iteration(Native Method)
сер 08 14:39:41 localhost dbeaver.desktop[28449]: at org.eclipse.swt.internal.gtk.OS.g_main_context_iteration(OS.java:2495)
сер 08 14:39:41 localhost dbeaver.desktop[28449]: at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:4149)
сер 08 14:39:41 localhost dbeaver.desktop[28449]: at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$4.run(PartRenderingEngine.java:1121)
сер 08 14:39:41 localhost dbeaver.desktop[28449]: at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:336)
сер 08 14:39:41 localhost dbeaver.desktop[28449]: at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1022)
сер 08 14:39:41 localhost dbeaver.desktop[28449]: at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:150)
сер 08 14:39:41 localhost dbeaver.desktop[28449]: at org.eclipse.ui.internal.Workbench$5.run(Workbench.java:693)
сер 08 14:39:41 localhost dbeaver.desktop[28449]: at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:336)
сер 08 14:39:41 localhost dbeaver.desktop[28449]: at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:610)
сер 08 14:39:41 localhost dbeaver.desktop[28449]: at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:148)
сер 08 14:39:41 localhost dbeaver.desktop[28449]: at org.jkiss.dbeaver.core.application.DBeaverApplication.start(DBeaverApplication.java:164)
сер 08 14:39:41 localhost dbeaver.desktop[28449]: at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
сер 08 14:39:41 localhost dbeaver.desktop[28449]: at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
сер 08 14:39:41 localhost dbeaver.desktop[28449]: at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
сер 08 14:39:41 localhost dbeaver.desktop[28449]: at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:388)
сер 08 14:39:41 localhost dbeaver.desktop[28449]: at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:243)
сер 08 14:39:41 localhost dbeaver.desktop[28449]: at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
сер 08 14:39:41 localhost dbeaver.desktop[28449]: at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
сер 08 14:39:41 localhost dbeaver.desktop[28449]: at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
сер 08 14:39:41 localhost dbeaver.desktop[28449]: at java.lang.reflect.Method.invoke(Method.java:498)
сер 08 14:39:41 localhost dbeaver.desktop[28449]: at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:673)
сер 08 14:39:41 localhost dbeaver.desktop[28449]: at org.eclipse.equinox.launcher.Main.basicRun(Main.java:610)
сер 08 14:39:41 localhost dbeaver.desktop[28449]: at org.eclipse.equinox.launcher.Main.run(Main.java:1519)
сер 08 14:39:41 localhost dbeaver.desktop[28449]: at org.eclipse.equinox.launcher.Main.main(Main.java:1492)
```

**Comment by serge-rider** [comment]
Thanks for report.
There are a few different error in the log.
Try to disable "Auto-sync connection with navigator" option in the main toolbar.

Also, if UI still freezes - please make a thread dump (https://github.com/serge-rider/dbeaver/wiki/Making-a-thread-dump) and post it here.

**Comment by tati-kru** [comment]
There isn't any activity about this ticket very long time. It will be closed. However, if you think that it is actual just let us know.
