### ISSUE TITLE
Oracle. NullPointerException

### ISSUE THREAD

**Issue by vcollado** [serge-rider/dbeaver#2020]
DBeaver 4.1.1 on Debian stretch using Oracle

Hi, everytime I make an "inline" insert into the data tab, this is what I get

![1](https://user-images.githubusercontent.com/2774617/29351535-6583fc64-8263-11e7-8a09-865b3dafb885.png)

The row is inserted, but the message it's so annoying,

Steps to reproduce: 
- select the table of an schema
- open the Data tab
- click the "Add new row" button
- write the data into each row
- click the "Save" button

**Comment by serge-rider** [comment]
Seems to be a bug but I can't reproduce it.

Please post error stacktrace (you can get in Error Log view or in log files: https://github.com/serge-rider/dbeaver/wiki/Log-files)

**Comment by vcollado** [comment]
this is the output from the .log file, fresh from a minute ago

```
!ENTRY org.jkiss.dbeaver.model 4 0 2017-08-16 09:50:28.015
!MESSAGE 
!STACK 0
java.lang.NullPointerException
	at oracle.jdbc.driver.AutoKeyInfo.initMetaDataKeyFlag(AutoKeyInfo.java:404)
	at oracle.jdbc.driver.AutoKeyInfo.initMetaData(AutoKeyInfo.java:392)
	at oracle.jdbc.driver.OracleReturnResultSet.getMetaData(OracleReturnResultSet.java:77)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCResultSetMetaDataImpl.<init>(JDBCResultSetMetaDataImpl.java:48)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCFactoryDefault.createResultSetMetaData(JDBCFactoryDefault.java:58)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCResultSetImpl.createMetaDataImpl(JDBCResultSetImpl.java:1682)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCResultSetImpl.getMeta(JDBCResultSetImpl.java:228)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCResultSetImpl.getMeta(JDBCResultSetImpl.java:1)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetPersister$KeyDataReceiver.fetchRow(ResultSetPersister.java:631)
	at org.jkiss.dbeaver.model.impl.data.ExecuteBatchImpl.readKeys(ExecuteBatchImpl.java:240)
	at org.jkiss.dbeaver.model.impl.data.ExecuteBatchImpl.processBatch(ExecuteBatchImpl.java:167)
	at org.jkiss.dbeaver.model.impl.data.ExecuteBatchImpl.execute(ExecuteBatchImpl.java:77)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetPersister$DataUpdaterJob.executeStatements(ResultSetPersister.java:520)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetPersister$DataUpdaterJob.run(ResultSetPersister.java:409)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:95)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)
```

**Comment by serge-rider** [comment]
This looks like internal Oracle driver error.
What Oracle JDBC driver version do you use?

**Comment by vcollado** [comment]
@serge-rider tomorrow I will look for it, thanks for following the bug!

**Comment by vcollado** [comment]
@serge-rider looking at the driver manager, I was using the ojdbc7.jar, changed to ojdbc6 solves the problem
