### ISSUE TITLE
Every menu option grayed out

### ISSUE THREAD

**Issue by AstroBoy269** [serge-rider/dbeaver#2025]
I'm a new user, so this could certainly be something I've done, but when I start Dbeaver on my Mac (running the High Sierra beta 5) every menu option across the top of the Mac menu bar is grayed out.  I uploaded a picture of the File Menu option.  Oddly enough, every menu option looks the same.

I also don't have the DB Navigator but I can at least get a SQL Editor started and can query the database.  

Is there a way to destroy all my preferences and restart to see if that will correct the issue?  

I appreciate any help or advice anyone can provide.
Thanks

![screen shot 2017-08-16 at 11 34 19 am](https://user-images.githubusercontent.com/10376292/29371714-1620ee34-8277-11e7-979a-3f3251c020a7.png)

**Comment by serge-rider** [comment]
1. Please check error logs: https://github.com/serge-rider/dbeaver/wiki/Log-files and post error stacktrace here (if there are any errors there)
2. You could try to reset workspace: https://github.com/serge-rider/dbeaver/wiki/Reset-workspace
3. If this doesn't help - you could try to delete directory $HOME/.dbeaver/.metadata/

**Comment by AstroBoy269** [comment]
Thanks serge-rider for the quick response.  I didn't see much that appeared interesting in the log files.  So I reset my workspace and did get my DBNavigator to return.  But still the menus were all grayed out.  So next I deleted the `.metadata` directory and got the same results.  I've included my dbeaver-debug.log below [way down below] which also doesn't look super weird although there is a java.io.IOExecption there near the top.

Here's my **.log** file, again it doesn't look super worrisome but there appears to be a keybinding error:
`!SESSION 2017-08-16 16:04:18.275 -----------------------------------------------
eclipse.buildId=unknown
java.version=1.8.0_111
java.vendor=Oracle Corporation
BootLoader constants: OS=macosx, ARCH=x86_64, WS=cocoa, NL=en_US
Framework arguments:  -keyring /Users/lance/.eclipse_keyring
Command-line arguments:  -os macosx -ws cocoa -arch x86_64 -keyring /Users/lance/.eclipse_keyring

!ENTRY org.eclipse.jface 2 0 2017-08-16 16:04:38.229
!MESSAGE Keybinding conflicts occurred.  They may interfere with normal accelerator operation.
!SUBENTRY 1 org.eclipse.jface 2 0 2017-08-16 16:04:38.229
!MESSAGE A conflict occurred for ALT+DEL:
Binding(ALT+DEL,
	ParameterizedCommand(Command(org.jkiss.dbeaver.core.resultset.row.delete,Delete current row,
		Delete current row,
		Category(org.jkiss.dbeaver.core.rs,Result Set,Result Set Commands,true),
		org.eclipse.ui.internal.WorkbenchHandlerServiceHandler@a1cb94,
		,,true),null),
	org.eclipse.ui.defaultAcceleratorConfiguration,
	org.jkiss.dbeaver.ui.context.resultset,,,system)
Binding(ALT+DEL,
	ParameterizedCommand(Command(org.eclipse.ui.edit.text.deleteNextWord,Delete Next Word,
		Delete the next word,
		Category(org.eclipse.ui.category.textEditor,Text Editing,Text Editing Commands,true),
		org.eclipse.ui.internal.WorkbenchHandlerServiceHandler@46d148bd,
		,,true),null),
	org.eclipse.ui.defaultAcceleratorConfiguration,
	org.eclipse.ui.textEditorScope,,cocoa,system)
`

Are there any other suggestions you'd like for me to try before I delete all the hidden .dbeaver directories and give it another go?  I think I mentioned in my first report that I'm running the beta version of the new Mac OS High Sierra so I understand if you want to "punt" this bug until the official release of High Sierra is released.
**dbeavber-debug.log**
`2017-08-16 16:04:19.319 - DBeaver 4.1.2 is starting
2017-08-16 16:04:19.321 - Install path: '/Applications/DBeaver.app/Contents/Eclipse'
2017-08-16 16:04:19.322 - Instance path: 'file:/Users/lance/.dbeaver4/'
2017-08-16 16:04:19.323 - Memory available 77Mb/910Mb
2017-08-16 16:04:19.341 - Starting RMI server at 32212
2017-08-16 16:04:24.410 - Create display
2017-08-16 16:04:24.656 - Run workbench
2017-08-16 16:04:27.054 - Initializing DBeaver 4.1.2
2017-08-16 16:04:27.060 - Host plugin: org.jkiss.dbeaver.core.application 4.1.2
2017-08-16 16:04:27.065 - Initialize Core...
2017-08-16 16:04:27.289 - Core initialized (224ms)
2017-08-16 16:04:27.294 - Configure workbench window
2017-08-16 16:04:27.386 - Create actions
2017-08-16 16:04:27.395 - Disable Eclipse action set 'org.eclipse.ui.edit.text.actionSet.annotationNavigation'
2017-08-16 16:04:27.400 - Disable Eclipse action set 'org.eclipse.ui.WorkingSetActionSet'
2017-08-16 16:04:28.414 - Initialize workbench window
2017-08-16 16:04:28.421 - Finish initialization
2017-08-16 16:04:31.462 - Open [http://dbeaver.jkiss.org/product/version.xml]
2017-08-16 16:04:31.535 - java.io.IOException: Can't open 'http://dbeaver.jkiss.org/product/version.xml': Moved Permanently
java.io.IOException: Can't open 'http://dbeaver.jkiss.org/product/version.xml': Moved Permanently
	at org.jkiss.dbeaver.runtime.WebUtils.openConnection(WebUtils.java:83)
	at org.jkiss.dbeaver.runtime.WebUtils.openConnection(WebUtils.java:41)
	at org.jkiss.dbeaver.registry.updater.VersionDescriptor.<init>(VersionDescriptor.java:50)
	at org.jkiss.dbeaver.core.application.update.DBeaverVersionChecker.run(DBeaverVersionChecker.java:89)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:95)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)
2017-08-16 16:04:38.544 - Connect with 'Vagrant' (mysql5-15d50820de2-6e0c0bf6903c0ecc)
2017-08-16 16:04:38.583 - Instantiate SSH tunnel
2017-08-16 16:04:38.596 - Connect to tunnel host
2017-08-16 16:04:38.599 - SSH INFO: Connecting to localhost port 2222
2017-08-16 16:04:38.603 - SSH INFO: Connection established
2017-08-16 16:04:38.621 - SSH INFO: Remote version string: SSH-2.0-OpenSSH_6.6.1
2017-08-16 16:04:38.624 - SSH INFO: Local version string: SSH-2.0-JSCH-0.1.54
2017-08-16 16:04:38.626 - SSH INFO: CheckCiphers: aes256-ctr,aes192-ctr,aes128-ctr,aes256-cbc,aes192-cbc,aes128-cbc,3des-ctr,arcfour,arcfour128,arcfour256
2017-08-16 16:04:38.845 - SSH INFO: aes256-ctr is not available.
2017-08-16 16:04:38.847 - SSH INFO: aes192-ctr is not available.
2017-08-16 16:04:38.848 - SSH INFO: aes256-cbc is not available.
2017-08-16 16:04:38.849 - SSH INFO: aes192-cbc is not available.
2017-08-16 16:04:38.850 - SSH INFO: CheckKexes: diffie-hellman-group14-sha1,ecdh-sha2-nistp256,ecdh-sha2-nistp384,ecdh-sha2-nistp521
2017-08-16 16:04:39.029 - SSH INFO: CheckSignatures: ecdsa-sha2-nistp256,ecdsa-sha2-nistp384,ecdsa-sha2-nistp521
2017-08-16 16:04:39.035 - SSH INFO: SSH_MSG_KEXINIT sent
2017-08-16 16:04:39.036 - SSH INFO: SSH_MSG_KEXINIT received
2017-08-16 16:04:39.039 - SSH INFO: kex: server: curve25519-sha256@libssh.org,ecdh-sha2-nistp256,ecdh-sha2-nistp384,ecdh-sha2-nistp521,diffie-hellman-group-exchange-sha256,diffie-hellman-group-exchange-sha1,diffie-hellman-group14-sha1,diffie-hellman-group1-sha1
2017-08-16 16:04:39.044 - SSH INFO: kex: server: ssh-rsa,ecdsa-sha2-nistp256,ssh-ed25519
2017-08-16 16:04:39.046 - SSH INFO: kex: server: aes128-ctr,aes192-ctr,aes256-ctr,arcfour256,arcfour128,aes128-gcm@openssh.com,aes256-gcm@openssh.com,chacha20-poly1305@openssh.com,aes128-cbc,3des-cbc,blowfish-cbc,cast128-cbc,aes192-cbc,aes256-cbc,arcfour,rijndael-cbc@lysator.liu.se
2017-08-16 16:04:39.049 - SSH INFO: kex: server: aes128-ctr,aes192-ctr,aes256-ctr,arcfour256,arcfour128,aes128-gcm@openssh.com,aes256-gcm@openssh.com,chacha20-poly1305@openssh.com,aes128-cbc,3des-cbc,blowfish-cbc,cast128-cbc,aes192-cbc,aes256-cbc,arcfour,rijndael-cbc@lysator.liu.se
2017-08-16 16:04:39.054 - SSH INFO: kex: server: hmac-md5-etm@openssh.com,hmac-sha1-etm@openssh.com,umac-64-etm@openssh.com,umac-128-etm@openssh.com,hmac-sha2-256-etm@openssh.com,hmac-sha2-512-etm@openssh.com,hmac-ripemd160-etm@openssh.com,hmac-sha1-96-etm@openssh.com,hmac-md5-96-etm@openssh.com,hmac-md5,hmac-sha1,umac-64@openssh.com,umac-128@openssh.com,hmac-sha2-256,hmac-sha2-512,hmac-ripemd160,hmac-ripemd160@openssh.com,hmac-sha1-96,hmac-md5-96
2017-08-16 16:04:39.059 - SSH INFO: kex: server: hmac-md5-etm@openssh.com,hmac-sha1-etm@openssh.com,umac-64-etm@openssh.com,umac-128-etm@openssh.com,hmac-sha2-256-etm@openssh.com,hmac-sha2-512-etm@openssh.com,hmac-ripemd160-etm@openssh.com,hmac-sha1-96-etm@openssh.com,hmac-md5-96-etm@openssh.com,hmac-md5,hmac-sha1,umac-64@openssh.com,umac-128@openssh.com,hmac-sha2-256,hmac-sha2-512,hmac-ripemd160,hmac-ripemd160@openssh.com,hmac-sha1-96,hmac-md5-96
2017-08-16 16:04:39.064 - SSH INFO: kex: server: none,zlib@openssh.com
2017-08-16 16:04:39.065 - SSH INFO: kex: server: none,zlib@openssh.com
2017-08-16 16:04:39.066 - SSH INFO: kex: server:
2017-08-16 16:04:39.067 - SSH INFO: kex: server:
2017-08-16 16:04:39.068 - SSH INFO: kex: client: ecdh-sha2-nistp256,ecdh-sha2-nistp384,ecdh-sha2-nistp521,diffie-hellman-group14-sha1,diffie-hellman-group-exchange-sha256,diffie-hellman-group-exchange-sha1,diffie-hellman-group1-sha1
2017-08-16 16:04:39.071 - SSH INFO: kex: client: ssh-rsa,ssh-dss,ecdsa-sha2-nistp256,ecdsa-sha2-nistp384,ecdsa-sha2-nistp521
2017-08-16 16:04:39.072 - SSH INFO: kex: client: aes128-ctr,aes128-cbc,3des-ctr,3des-cbc,blowfish-cbc
2017-08-16 16:04:39.074 - SSH INFO: kex: client: aes128-ctr,aes128-cbc,3des-ctr,3des-cbc,blowfish-cbc
2017-08-16 16:04:39.076 - SSH INFO: kex: client: hmac-md5,hmac-sha1,hmac-sha2-256,hmac-sha1-96,hmac-md5-96
2017-08-16 16:04:39.077 - SSH INFO: kex: client: hmac-md5,hmac-sha1,hmac-sha2-256,hmac-sha1-96,hmac-md5-96
2017-08-16 16:04:39.078 - SSH INFO: kex: client: none
2017-08-16 16:04:39.079 - SSH INFO: kex: client: none
2017-08-16 16:04:39.080 - SSH INFO: kex: client:
2017-08-16 16:04:39.081 - SSH INFO: kex: client:
2017-08-16 16:04:39.081 - SSH INFO: kex: server->client aes128-ctr hmac-md5 none
2017-08-16 16:04:39.082 - SSH INFO: kex: client->server aes128-ctr hmac-md5 none
2017-08-16 16:04:39.088 - SSH INFO: SSH_MSG_KEX_ECDH_INIT sent
2017-08-16 16:04:39.091 - SSH INFO: expecting SSH_MSG_KEX_ECDH_REPLY
2017-08-16 16:04:39.103 - SSH INFO: ssh_rsa_verify: signature true
2017-08-16 16:04:39.127 - SSH WARN: Permanently added 'localhost' (RSA) to the list of known hosts.
2017-08-16 16:04:39.139 - SSH INFO: SSH_MSG_NEWKEYS sent
2017-08-16 16:04:39.148 - SSH INFO: SSH_MSG_NEWKEYS received
2017-08-16 16:04:39.168 - SSH INFO: SSH_MSG_SERVICE_REQUEST sent
2017-08-16 16:04:39.175 - SSH INFO: SSH_MSG_SERVICE_ACCEPT received
2017-08-16 16:04:39.188 - SSH INFO: Authentications that can continue: publickey
2017-08-16 16:04:39.192 - SSH INFO: Next authentication method: publickey
2017-08-16 16:04:39.348 - SSH INFO: Authentication succeeded (publickey).
2017-08-16 16:04:47.628 - Open [https://repo1.maven.org/maven2/mysql/mysql-connector-java/5.1.39/mysql-connector-java-5.1.39.jar]
2017-08-16 16:04:49.172 - Connected (mysql5-15d50820de2-6e0c0bf6903c0ecc, MySQL Connector Java [mysql-connector-java-5.1.39 ( Revision: 3289a357af6d09ecc1a10fd3c26e95183e5790ad )])
2017-08-16 16:05:46.398 - Shutdown Core...
2017-08-16 16:05:46.512 - SSH INFO: Disconnecting from localhost port 2222
2017-08-16 16:05:46.515 - SSH INFO: Caught an exception, leaving main loop due to Socket closed
2017-08-16 16:05:46.566 - Disconnected (mysql5-15d50820de2-6e0c0bf6903c0ecc)
2017-08-16 16:05:46.828 - Shutdown completed in 430ms`

**Comment by Phenmod** [comment]
https://bugs.eclipse.org/bugs/show_bug.cgi?id=519724

**Comment by serge-rider** [comment]
@Phenmod Thanks!
I'll remove all locales bu `en`. Hopefully it will resolve the issue.

**Comment by serge-rider** [comment]
Please reopen if problem will appear again in 4.2.3
