### ISSUE TITLE
Issue #2075 still not working

### ISSUE THREAD

**Issue by ceesvl** [serge-rider/dbeaver#2144]
Hi,

After upgrading to version 4.2.0. The bug from issue #2075 is still there.

Please see previous issue for an example.

BR,
Cees

**Comment by serge-rider** [comment]
Please post error stacktrace (there were some fixes in SQL formatting, this error can't be exactly the same as in #2075).

**Comment by ceesvl** [comment]
You right. The new trace:

java.lang.StringIndexOutOfBoundsException: String index out of range: -1
	at java.lang.String.substring(String.java:1967)
	at org.jkiss.dbeaver.model.sql.SQLUtils.splitFullIdentifier(SQLUtils.java:782)
	at org.jkiss.dbeaver.ui.editors.sql.syntax.SQLCompletionAnalyzer.getTableFromAlias(SQLCompletionAnalyzer.java:326)
	at org.jkiss.dbeaver.ui.editors.sql.syntax.SQLCompletionAnalyzer.runAnalyzer(SQLCompletionAnalyzer.java:120)
	at org.jkiss.dbeaver.ui.editors.sql.syntax.SQLCompletionProcessor$ProposalSearchJob.run(SQLCompletionProcessor.java:363)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:95)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)



at org.jkiss.dbeaver.model.sql.SQLUtils.splitFullIdentifier(SQLUtils.java:782) is 2 rows further from 780.

**Comment by serge-rider** [comment]
Thanks for details.
It was fixed in #2169.
