### ISSUE TITLE
ClassCastException when reading integer column with IgniteJdbcThinDriver

### ISSUE THREAD

**Issue by Inverness** [serge-rider/dbeaver#2151]
When trying to display a simple integer column its values are all null and I get this error:
````
java.lang.ClassCastException: java.lang.Integer cannot be cast to java.lang.Long
	at org.apache.ignite.internal.jdbc.thin.JdbcThinResultSet.getLong(JdbcThinResultSet.java:282)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCResultSetImpl.getLong(JDBCResultSetImpl.java:379)
	at org.jkiss.dbeaver.model.impl.jdbc.data.handlers.JDBCNumberValueHandler.fetchColumnValue(JDBCNumberValueHandler.java:112)
	at org.jkiss.dbeaver.model.impl.jdbc.data.handlers.JDBCAbstractValueHandler.fetchValueObject(JDBCAbstractValueHandler.java:49)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetDataReceiver.fetchRow(ResultSetDataReceiver.java:106)
	at org.jkiss.dbeaver.runtime.sql.SQLQueryJob.fetchQueryData(SQLQueryJob.java:694)
	at org.jkiss.dbeaver.runtime.sql.SQLQueryJob.executeSingleQuery(SQLQueryJob.java:411)
	at org.jkiss.dbeaver.runtime.sql.SQLQueryJob.extractData(SQLQueryJob.java:787)
	at org.jkiss.dbeaver.ui.editors.sql.SQLEditor$QueryResultsContainer.readData(SQLEditor.java:1961)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetJobDataRead.run(ResultSetJobDataRead.java:91)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:95)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)
````
I see in JDBCNumberValueHandler.fetchColumnValue() that it catches a SQLException, but not a ClassCastException.

The exception is from a bug in JdbcThinResultSet.getTypedValue() where it tries to catch a generic cast exception and rethrow it as SQLException, but this is useless since the generic information is erased upon compile so the exception happens in getLong() instead where the ClassCastException can escape.

Proper conversion support has been added to the driver repository a few days ago but I do not know when that will be released. It could be weeks or months. I'm currently using Ignite 2.1.0.

My current workaround for DBeaver is to use _CAST(columnname AS BIGINT)_.

**Comment by serge-rider** [comment]
Thanks for report.
I thin DBeaver should also try `getInt` function for integer types (if getLong will fail).
Will try this in the next CE version.

**Comment by Inverness** [comment]
@serge-rider it does try it if getLong fails, the problem is that only happens if it catches SQLException. The bug in the driver throws a ClassCastException instead.

**Comment by serge-rider** [comment]
I've added extra exceptions catches, hopefully it'll resolve the issue.
