### ISSUE TITLE
Oracle - String index out of range: -4 when using bind variables and subquery factoring (WITH clauses)

### ISSUE THREAD

**Issue by quiescer** [serge-rider/dbeaver#2184]
Given a query that combines subquery factoring and bind variables, such as the below example, I'm seeing _String index out of range: -4_ errors. Replacing the bind variable :REVIEWER_ID with a hard-coded integer works. The issue also doesn't seem to occur in queries that don't use WITH clauses.

I'm using DBeaver CE 4.2.1 and have not encountered this error on any previous DBeaver version.

```
    WITH best_name AS (
        SELECT
            ROW_NUMBER() OVER (PARTITION BY id ORDER BY id, DECODE(name_type_code, 'PREFERRED', 0, 'PRIMARY', 1), name_seq DESC) AS seqnum_newest
            , id
            , first_name
        FROM
            names_table
    ),
    SELECT DISTINCT
           full_name
           , surname
           , first_name
    FROM   staff_table st
           JOIN best_name bn
             ON bn.id = cs.id
             ON bn.seqnum_newest = 1
    WHERE  st.end_date > SYSDATE
    AND    st.id = :REVIEWER_ID;
```

Stack trace:
```
java.lang.StringIndexOutOfBoundsException: String index out of range: -4
	at java.lang.String.substring(String.java:1931)
	at org.jkiss.dbeaver.runtime.sql.SQLQueryJob.prepareStatementParameters(SQLQueryJob.java:574)
	at org.jkiss.dbeaver.runtime.sql.SQLQueryJob.executeSingleQuery(SQLQueryJob.java:334)
	at org.jkiss.dbeaver.runtime.sql.SQLQueryJob.extractData(SQLQueryJob.java:787)
	at org.jkiss.dbeaver.ui.editors.sql.SQLEditor$QueryResultsContainer.readData(SQLEditor.java:1963)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetJobDataRead.run(ResultSetJobDataRead.java:91)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:95)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)
```

**Comment by serge-rider** [comment]
Thanks for report. 
This is a bug in parameters replacement procedure. But I can't reproduce it.
- Does this happen always? 
- Even after editor reopening? 
- With any parameter value?

**Comment by quiescer** [comment]
You're right. I have tried with a contrived example (2 very simple tables), and it doesn't happen. I will try to see if I can trigger the error "from scratch".

**Comment by serge-rider** [comment]
Still can't reproduce this. The worst thing is that I don't have a clue how could this happen.
Any news?

**Comment by serge-rider** [comment]
Please check in 4.2.2.
Reopen if it still exists.
