### ISSUE TITLE
Oracle DB - Locale not recognized in 4.2.2

### ISSUE THREAD

**Issue by rythym05** [serge-rider/dbeaver#2243]
Connecting to Database fails with the below error after upgrading to 4.2.2

2017-10-01 19:12:31.878 - Connection failed (oracle_thin-15c69ca1fd0-221877dcdfbf21d9)
2017-10-01 19:12:31.881 - org.jkiss.dbeaver.model.exec.DBCConnectException: Locale not recognized
org.jkiss.dbeaver.model.exec.DBCConnectException: Locale not recognized
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.openConnection(JDBCDataSource.java:190)
	at org.jkiss.dbeaver.ext.oracle.model.OracleDataSource.openConnection(OracleDataSource.java:131)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCExecutionContext.connect(JDBCExecutionContext.java:79)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.initializeMainContext(JDBCDataSource.java:115)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.<init>(JDBCDataSource.java:109)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.<init>(JDBCDataSource.java:98)
	at org.jkiss.dbeaver.ext.oracle.model.OracleDataSource.<init>(OracleDataSource.java:82)
	at org.jkiss.dbeaver.ext.oracle.OracleDataSourceProvider.openDataSource(OracleDataSourceProvider.java:131)
	at org.jkiss.dbeaver.registry.DataSourceDescriptor.connect(DataSourceDescriptor.java:700)
	at org.jkiss.dbeaver.runtime.jobs.ConnectJob.run(ConnectJob.java:70)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:95)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:56)

**Comment by MadhuriKankurte** [comment]
I got this very same issue. 
Trying to conenct  remote oracle 11g .
Checked the listener port , service id etc .
Remote server are reachable too.
Guessed Dbeaver 4.4.2 doesn't pull old (installed and connections established ) connections.
So tried reconnecting with  new connections for the same users.
But doesn't help either.

**Comment by serge-rider** [comment]
It is a bug in DBeaver config (which appears only with Oracle driver).
Open `dbeaver.ini` and change 
`-Duser.language=en_US` on `-Duser.language=en`
Or just remove this line.
