### ISSUE TITLE
Postgis geometry columns not shown

### ISSUE THREAD

**Issue by gandolfwizard** [serge-rider/dbeaver#2250]
Hi,

I am using DBeaver 4.2.2 (Mac), I realized that on Postgres 9.5 with Postgis the geometry columns are not shown in the columns section and in the DDL. It works on DBeaver 4.2.1 (Windows)

Could you help me to figure out what I have to change to see them?

Best

Anselm

**Comment by serge-rider** [comment]
All columns should be visible.
Maybe they are missing because of some bug.
Please check debug/error logs for any related messages (https://github.com/serge-rider/dbeaver/wiki/Log-files).

**Comment by gandolfwizard** [comment]
Hi Serge,

there are errors related to that.
here some infos from the log:
`2017-10-02 15:56:25.172 - Connect with 'Processing - dbname' (postgres-jdbc-15edc5e0c2a-1e7065370c2f3022)
2017-10-02 15:56:27.191 - Connected (postgres-jdbc-15edc5e0c2a-1e7065370c2f3022, PostgreSQL Native Driver [PostgreSQL 9.4.1212.jre7])
2017-10-02 16:00:47.699 - org.jkiss.dbeaver.model.exec.DBCException: Can't determine transaction isolation - timeout
org.jkiss.dbeaver.model.exec.DBCException: Can't determine transaction isolation - timeout
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCExecutionContext.getTransactionIsolation(JDBCExecutionContext.java:258)
	at org.jkiss.dbeaver.ui.actions.datasource.DataSourceAutoCommitHandler.updateElement(DataSourceAutoCommitHandler.java:92)
	at org.eclipse.ui.internal.handlers.HandlerProxy.updateElement(HandlerProxy.java:449)
	at org.eclipse.ui.internal.handlers.E4HandlerProxy.updateElement(E4HandlerProxy.java:117)
	at org.eclipse.ui.internal.WorkbenchHandlerServiceHandler.updateElement(WorkbenchHandlerServiceHandler.java:43)
	at org.eclipse.ui.internal.commands.CommandService.registerElement(CommandService.java:329)
	at org.eclipse.ui.internal.commands.SlaveCommandService.registerElement(SlaveCommandService.java:243)
	at org.eclipse.ui.internal.commands.SlaveCommandService.registerElementForCommand(SlaveCommandService.java:235)
	at org.eclipse.ui.internal.commands.SlaveCommandService.registerElementForUpdate(SlaveCommandService.java:290)
	at org.eclipse.e4.ui.workbench.renderers.swt.HandledContributionItem.postToolbarFill(HandledContributionItem.java:203)
	at org.eclipse.e4.ui.workbench.renderers.swt.AbstractContributionItem.fill(AbstractContributionItem.java:316)
	at org.eclipse.jface.action.ToolBarManager.update(ToolBarManager.java:343)
	at org.eclipse.e4.ui.workbench.renderers.swt.ToolBarManagerRenderer.subscribeTopicUpdateToBeRendered(ToolBarManagerRenderer.java:212)
	at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at org.eclipse.e4.core.internal.di.MethodRequestor.execute(MethodRequestor.java:55)
	at org.eclipse.e4.ui.internal.di.UIEventObjectSupplier$UIEventHandler$1.run(UIEventObjectSupplier.java:64)
	at org.eclipse.swt.widgets.Synchronizer.syncExec(Synchronizer.java:233)
	at org.eclipse.ui.internal.UISynchronizer.syncExec(UISynchronizer.java:144)
	at org.eclipse.swt.widgets.Display.syncExec(Display.java:4870)
	at org.eclipse.e4.ui.internal.workbench.swt.E4Application$1.syncExec(E4Application.java:212)
	at org.eclipse.e4.ui.internal.di.UIEventObjectSupplier$UIEventHandler.handleEvent(UIEventObjectSupplier.java:61)
	at org.eclipse.equinox.internal.event.EventHandlerWrapper.handleEvent(EventHandlerWrapper.java:201)
	at org.eclipse.equinox.internal.event.EventHandlerTracker.dispatchEvent(EventHandlerTracker.java:197)
	at org.eclipse.equinox.internal.event.EventHandlerTracker.dispatchEvent(EventHandlerTracker.java:1)
	at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:230)
	at org.eclipse.osgi.framework.eventmgr.ListenerQueue.dispatchEventSynchronous(ListenerQueue.java:148)
	at org.eclipse.equinox.internal.event.EventAdminImpl.dispatchEvent(EventAdminImpl.java:135)
	at org.eclipse.equinox.internal.event.EventAdminImpl.sendEvent(EventAdminImpl.java:78)
	at org.eclipse.equinox.internal.event.EventComponent.sendEvent(EventComponent.java:39)
	at org.eclipse.e4.ui.services.internal.events.EventBroker.send(EventBroker.java:52)
	at org.eclipse.e4.ui.internal.workbench.UIEventPublisher.notifyChanged(UIEventPublisher.java:60)
	at org.eclipse.emf.common.notify.impl.BasicNotifierImpl.eNotify(BasicNotifierImpl.java:374)
	at org.eclipse.e4.ui.model.application.ui.impl.UIElementImpl.setVisible(UIElementImpl.java:345)
	at org.eclipse.e4.ui.workbench.renderers.swt.ToolBarContributionRecord.updateVisibility(ToolBarContributionRecord.java:70)
	at org.eclipse.e4.ui.workbench.renderers.swt.ToolBarManagerRenderer$2.changed(ToolBarManagerRenderer.java:478)
	at org.eclipse.e4.core.internal.contexts.TrackableComputationExt.update(TrackableComputationExt.java:114)
	at org.eclipse.e4.core.internal.contexts.EclipseContext.processScheduled(EclipseContext.java:355)
	at org.eclipse.e4.core.internal.contexts.EclipseContext.set(EclipseContext.java:370)
	at org.eclipse.ui.internal.WorkbenchPage.updateActiveEditorSources(WorkbenchPage.java:413)
	at org.eclipse.ui.internal.WorkbenchPage.updateBroughtToTop(WorkbenchPage.java:464)
	at org.eclipse.ui.internal.WorkbenchPage.access$20(WorkbenchPage.java:463)
	at org.eclipse.ui.internal.WorkbenchPage$E4PartListener.partBroughtToTop(WorkbenchPage.java:218)
	at org.eclipse.e4.ui.internal.workbench.PartServiceImpl$7.run(PartServiceImpl.java:314)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.eclipse.e4.ui.internal.workbench.PartServiceImpl.firePartBroughtToTop(PartServiceImpl.java:311)
	at org.eclipse.e4.ui.internal.workbench.PartServiceImpl.access$4(PartServiceImpl.java:309)
	at org.eclipse.e4.ui.internal.workbench.PartServiceImpl$1.handleEvent(PartServiceImpl.java:106)
	at org.eclipse.e4.ui.services.internal.events.UIEventHandler$1.run(UIEventHandler.java:40)
	at org.eclipse.swt.widgets.Synchronizer.syncExec(Synchronizer.java:233)
	at org.eclipse.ui.internal.UISynchronizer.syncExec(UISynchronizer.java:144)
	at org.eclipse.swt.widgets.Display.syncExec(Display.java:4870)
	at org.eclipse.e4.ui.internal.workbench.swt.E4Application$1.syncExec(E4Application.java:212)
	at org.eclipse.e4.ui.services.internal.events.UIEventHandler.handleEvent(UIEventHandler.java:36)
	at org.eclipse.equinox.internal.event.EventHandlerWrapper.handleEvent(EventHandlerWrapper.java:201)
	at org.eclipse.equinox.internal.event.EventHandlerTracker.dispatchEvent(EventHandlerTracker.java:197)
	at org.eclipse.equinox.internal.event.EventHandlerTracker.dispatchEvent(EventHandlerTracker.java:1)
	at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:230)
	at org.eclipse.osgi.framework.eventmgr.ListenerQueue.dispatchEventSynchronous(ListenerQueue.java:148)
	at org.eclipse.equinox.internal.event.EventAdminImpl.dispatchEvent(EventAdminImpl.java:135)
	at org.eclipse.equinox.internal.event.EventAdminImpl.sendEvent(EventAdminImpl.java:78)
	at org.eclipse.equinox.internal.event.EventComponent.sendEvent(EventComponent.java:39)
	at org.eclipse.e4.ui.services.internal.events.EventBroker.send(EventBroker.java:52)
	at org.eclipse.e4.ui.internal.workbench.UIEventPublisher.notifyChanged(UIEventPublisher.java:60)
	at org.eclipse.emf.common.notify.impl.BasicNotifierImpl.eNotify(BasicNotifierImpl.java:374)
	at org.eclipse.e4.ui.model.application.ui.impl.ElementContainerImpl.setSelectedElement(ElementContainerImpl.java:173)
	at org.eclipse.e4.ui.internal.workbench.ModelServiceImpl.showElementInWindow(ModelServiceImpl.java:620)
	at org.eclipse.e4.ui.internal.workbench.ModelServiceImpl.bringToTop(ModelServiceImpl.java:584)
	at org.eclipse.e4.ui.internal.workbench.PartServiceImpl.delegateBringToTop(PartServiceImpl.java:769)
	at org.eclipse.e4.ui.internal.workbench.PartServiceImpl.bringToTop(PartServiceImpl.java:401)
	at org.eclipse.e4.ui.internal.workbench.PartServiceImpl.showPart(PartServiceImpl.java:1188)
	at org.eclipse.ui.internal.WorkbenchPage.busyOpenEditor(WorkbenchPage.java:3261)
	at org.eclipse.ui.internal.WorkbenchPage.access$25(WorkbenchPage.java:3176)
	at org.eclipse.ui.internal.WorkbenchPage$10.run(WorkbenchPage.java:3158)
	at org.eclipse.swt.custom.BusyIndicator.showWhile(BusyIndicator.java:70)
	at org.eclipse.ui.internal.WorkbenchPage.openEditor(WorkbenchPage.java:3153)
	at org.eclipse.ui.internal.WorkbenchPage.openEditor(WorkbenchPage.java:3117)
	at org.eclipse.ui.internal.WorkbenchPage.openEditor(WorkbenchPage.java:3098)
	at org.jkiss.dbeaver.ui.resources.ScriptsHandlerImpl.openResource(ScriptsHandlerImpl.java:99)
	at org.jkiss.dbeaver.ui.actions.navigator.NavigatorHandlerObjectOpen.openResource(NavigatorHandlerObjectOpen.java:106)
	at org.jkiss.dbeaver.ui.controls.ScriptSelectorPanel$2.widgetSelected(ScriptSelectorPanel.java:140)
	at org.eclipse.swt.widgets.TypedListener.handleEvent(TypedListener.java:249)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:86)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4257)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1502)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1525)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1510)
	at org.eclipse.swt.widgets.Widget.notifyListeners(Widget.java:1314)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4081)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3698)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1150)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:336)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1039)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:153)
	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:680)
	at org.eclipse.ui.internal.Workbench$$Lambda$15/1951963537.run(Unknown Source)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:336)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:594)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:148)
	at org.jkiss.dbeaver.core.application.DBeaverApplication.start(DBeaverApplication.java:167)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:388)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:243)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:653)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:590)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1499)
2017-10-02 16:05:20.855 - Delete empty SQL script '/General/Scripts/Script-15.sql'
2017-10-02 16:05:54.379 - Delete empty SQL script '/General/Scripts/Script-14.sql'
2017-10-02 16:08:09.665 - Data type '9328462' not found
2017-10-02 16:08:09.666 - Error reading attribute info
org.jkiss.dbeaver.DBException: Attribute data type '9328462' not found
	at org.jkiss.dbeaver.ext.postgresql.model.PostgreAttribute.loadInfo(PostgreAttribute.java:85)
	at org.jkiss.dbeaver.ext.postgresql.model.PostgreAttribute.<init>(PostgreAttribute.java:69)
	at org.jkiss.dbeaver.ext.postgresql.model.PostgreTableColumn.<init>(PostgreTableColumn.java:32)
	at org.jkiss.dbeaver.ext.postgresql.model.PostgreSchema$TableCache.fetchChild(PostgreSchema.java:474)
	at org.jkiss.dbeaver.ext.postgresql.model.PostgreSchema$TableCache.fetchChild(PostgreSchema.java:1)
	at org.jkiss.dbeaver.model.impl.jdbc.cache.JDBCStructCache.loadChildren(JDBCStructCache.java:128)
	at org.jkiss.dbeaver.model.impl.jdbc.cache.JDBCStructCache.getChildren(JDBCStructCache.java:220)
	at org.jkiss.dbeaver.ext.postgresql.model.PostgreTableBase.getAttributes(PostgreTableBase.java:136)
	at org.jkiss.dbeaver.ui.editors.sql.syntax.SQLCompletionAnalyzer.makeProposalsFromChildren(SQLCompletionAnalyzer.java:404)
	at org.jkiss.dbeaver.ui.editors.sql.syntax.SQLCompletionAnalyzer.runAnalyzer(SQLCompletionAnalyzer.java:123)
	at org.jkiss.dbeaver.ui.editors.sql.syntax.SQLCompletionProcessor$ProposalSearchJob.run(SQLCompletionProcessor.java:363)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:95)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:56)
2017-10-02 16:08:47.145 - Data type 'geometry' not found in database 'dbname'
2017-10-02 16:09:04.661 - Data type '9328462' not found
2017-10-02 16:09:04.662 - Error reading attribute info
org.jkiss.dbeaver.DBException: Attribute data type '9328462' not found
	at org.jkiss.dbeaver.ext.postgresql.model.PostgreAttribute.loadInfo(PostgreAttribute.java:85)
	at org.jkiss.dbeaver.ext.postgresql.model.PostgreAttribute.<init>(PostgreAttribute.java:69)
	at org.jkiss.dbeaver.ext.postgresql.model.PostgreTableColumn.<init>(PostgreTableColumn.java:32)
	at org.jkiss.dbeaver.ext.postgresql.model.PostgreSchema$TableCache.fetchChild(PostgreSchema.java:474)
	at org.jkiss.dbeaver.ext.postgresql.model.PostgreSchema$TableCache.fetchChild(PostgreSchema.java:1)
	at org.jkiss.dbeaver.model.impl.jdbc.cache.JDBCStructCache.loadChildren(JDBCStructCache.java:128)
	at org.jkiss.dbeaver.model.impl.jdbc.cache.JDBCStructCache.getChildren(JDBCStructCache.java:220)
	at org.jkiss.dbeaver.ext.postgresql.model.PostgreTableBase.getAttributes(PostgreTableBase.java:136)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at org.jkiss.dbeaver.model.navigator.DBNDatabaseNode.extractPropertyValue(DBNDatabaseNode.java:798)
	at org.jkiss.dbeaver.model.navigator.DBNDatabaseNode.loadTreeItems(DBNDatabaseNode.java:484)
	at org.jkiss.dbeaver.model.navigator.DBNDatabaseNode.loadChildren(DBNDatabaseNode.java:408)
	at org.jkiss.dbeaver.model.navigator.DBNDatabaseNode.reloadChildren(DBNDatabaseNode.java:693)
	at org.jkiss.dbeaver.model.navigator.DBNDatabaseNode.loadChildren(DBNDatabaseNode.java:422)
	at org.jkiss.dbeaver.model.navigator.DBNDatabaseNode.reloadChildren(DBNDatabaseNode.java:693)
	at org.jkiss.dbeaver.model.navigator.DBNDatabaseNode.refreshNodeContent(DBNDatabaseNode.java:360)
	at org.jkiss.dbeaver.model.navigator.DBNDatabaseNode.refreshNode(DBNDatabaseNode.java:334)
	at org.jkiss.dbeaver.ui.actions.navigator.NavigatorHandlerRefresh$1.run(NavigatorHandlerRefresh.java:138)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:95)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:56)
2017-10-02 16:09:16.834 - Data type 'geometry' not found in database 'dbname'
2017-10-02 16:11:32.850 - Data type '9328462' not found
2017-10-02 16:11:32.852 - Error reading attribute info
org.jkiss.dbeaver.DBException: Attribute data type '9328462' not found
	at org.jkiss.dbeaver.ext.postgresql.model.PostgreAttribute.loadInfo(PostgreAttribute.java:85)
	at org.jkiss.dbeaver.ext.postgresql.model.PostgreAttribute.<init>(PostgreAttribute.java:69)
	at org.jkiss.dbeaver.ext.postgresql.model.PostgreTableColumn.<init>(PostgreTableColumn.java:32)
	at org.jkiss.dbeaver.ext.postgresql.model.PostgreSchema$TableCache.fetchChild(PostgreSchema.java:474)
	at org.jkiss.dbeaver.ext.postgresql.model.PostgreSchema$TableCache.fetchChild(PostgreSchema.java:1)
	at org.jkiss.dbeaver.model.impl.jdbc.cache.JDBCStructCache.loadChildren(JDBCStructCache.java:128)
	at org.jkiss.dbeaver.model.impl.jdbc.cache.JDBCStructCache.getChildren(JDBCStructCache.java:220)
	at org.jkiss.dbeaver.ext.postgresql.model.PostgreTableBase.getAttributes(PostgreTableBase.java:136)
	at org.jkiss.dbeaver.ui.editors.sql.syntax.SQLCompletionAnalyzer.makeProposalsFromChildren(SQLCompletionAnalyzer.java:404)
	at org.jkiss.dbeaver.ui.editors.sql.syntax.SQLCompletionAnalyzer.runAnalyzer(SQLCompletionAnalyzer.java:123)
	at org.jkiss.dbeaver.ui.editors.sql.syntax.SQLCompletionProcessor$ProposalSearchJob.run(SQLCompletionProcessor.java:363)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:95)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:56)
2017-10-02 16:11:42.280 - null
org.jkiss.dbeaver.model.exec.DBCException: SQL Error [42P16]: ERROR: cannot change name of view column "oa_zip4post" to "geom_intersect"
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCStatementImpl.executeStatement(JDBCStatementImpl.java:142)
	at org.jkiss.dbeaver.runtime.sql.SQLQueryJob.executeSingleQuery(SQLQueryJob.java:397)
	at org.jkiss.dbeaver.runtime.sql.SQLQueryJob.extractData(SQLQueryJob.java:790)
	at org.jkiss.dbeaver.ui.editors.sql.SQLEditor$QueryResultsContainer.readData(SQLEditor.java:1985)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetJobDataRead.run(ResultSetJobDataRead.java:91)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:95)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:56)
Caused by: org.postgresql.util.PSQLException: ERROR: cannot change name of view column "oa_zip4post" to "geom_intersect"
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2455)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2155)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:288)
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:430)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:356)
	at org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:303)
	at org.postgresql.jdbc.PgStatement.executeCachedSql(PgStatement.java:289)
	at org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:266)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:262)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCStatementImpl.execute(JDBCStatementImpl.java:346)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCStatementImpl.executeStatement(JDBCStatementImpl.java:139)
	... 6 more
2017-10-02 16:14:47.673 - Data type '9328462' not found
2017-10-02 16:14:47.675 - Error reading attribute info
org.jkiss.dbeaver.DBException: Attribute data type '9328462' not found
	at org.jkiss.dbeaver.ext.postgresql.model.PostgreAttribute.loadInfo(PostgreAttribute.java:85)
	at org.jkiss.dbeaver.ext.postgresql.model.PostgreAttribute.<init>(PostgreAttribute.java:69)
	at org.jkiss.dbeaver.ext.postgresql.model.PostgreTableColumn.<init>(PostgreTableColumn.java:32)
	at org.jkiss.dbeaver.ext.postgresql.model.PostgreSchema$TableCache.fetchChild(PostgreSchema.java:474)
	at org.jkiss.dbeaver.ext.postgresql.model.PostgreSchema$TableCache.fetchChild(PostgreSchema.java:1)
	at org.jkiss.dbeaver.model.impl.jdbc.cache.JDBCStructCache.loadChildren(JDBCStructCache.java:128)
	at org.jkiss.dbeaver.model.impl.jdbc.cache.JDBCStructCache.getChildren(JDBCStructCache.java:220)
	at org.jkiss.dbeaver.ext.postgresql.model.PostgreTableBase.getAttributes(PostgreTableBase.java:136)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at org.jkiss.dbeaver.model.navigator.DBNDatabaseNode.extractPropertyValue(DBNDatabaseNode.java:798)
	at org.jkiss.dbeaver.model.navigator.DBNDatabaseNode.loadTreeItems(DBNDatabaseNode.java:484)
	at org.jkiss.dbeaver.model.navigator.DBNDatabaseNode.loadChildren(DBNDatabaseNode.java:408)
	at org.jkiss.dbeaver.model.navigator.DBNDatabaseNode.reloadChildren(DBNDatabaseNode.java:693)
	at org.jkiss.dbeaver.model.navigator.DBNDatabaseNode.loadChildren(DBNDatabaseNode.java:422)
	at org.jkiss.dbeaver.model.navigator.DBNDatabaseNode.reloadChildren(DBNDatabaseNode.java:693)
	at org.jkiss.dbeaver.model.navigator.DBNDatabaseNode.refreshNodeContent(DBNDatabaseNode.java:360)
	at org.jkiss.dbeaver.model.navigator.DBNDatabaseNode.refreshNode(DBNDatabaseNode.java:334)
	at org.jkiss.dbeaver.ui.actions.navigator.NavigatorHandlerRefresh$1.run(NavigatorHandlerRefresh.java:138)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:95)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:56)
2017-10-02 16:14:58.212 - Data type 'geometry' not found in database 'dbname'
2017-10-02 16:28:42.566 - Data type 'geometry' not found in database 'dbname'`

Thank you for your help.

**Comment by oi-io** [comment]
same on 4.2.2 windows, had to revert to 4.2.1 to get it working. Log file attached. 
[.log](https://github.com/serge-rider/dbeaver/files/1352530/default.log)

**Comment by serge-rider** [comment]
DBeaver can't resolve `geometry` data type (9328462) in your database.
I'll add a workaround (so all attributes will visible). But this won't solve original problem (geometry type resolution).

- Is there anything special about your database? 
- What schema holds `geometry` type definition?
- Is this schema visible for DBeaver?
- Do you have any schema filters (so this schema was filtered out in navigator)? If yes then you can just remove this filter. This is also a workaround, not a solution.

**Comment by gandolfwizard** [comment]
Hi Serge,

it is a standard database with postgis extension. The geometry  type is hold by public. 
I have no filters in place.

Thank you for your help :-)

**Comment by serge-rider** [comment]
Please check version 4.2.3 (at least columns should be visible always).

Reopen if problem is still there. 
And could you make a short gif movie (e.g. with ScreenToGif tool) with this error. Maybe I can't catch this issue because you do some special/untypical (for me) actions.

**Comment by latitudehopper** [comment]
Possibly related to this. In Dbeaver, my PostGIS geometry columns with a data type of "geometry" are listed as varchar. In PGAdmin4 they appear as "geometry" - is this a bug?

**Comment by serge-rider** [comment]
@latitudehopper sounds like a bug. And I can't reproduce this.
Could you post the debug log? https://github.com/dbeaver/dbeaver/wiki/Log-files

**Comment by latitudehopper** [comment]
Oddly, I have just tried from another machine and do not have the same issue.... I will check again and report back.

**Comment by latitudehopper** [comment]
OK - the issue is also not evident on the other machine. It was either my imagination or some very odd edge case.

**Comment by serge-rider** [comment]
I saw similar issue after new schema creation (so DBeaver didn't refresh metadata cache and thus didn't see geometry data type). But this can be resolved by simple reconnecting.

**Comment by latitudehopper** [comment]
Ah. I'll test this as that sounds plausible in my case.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by latitudehopper** [comment]
Bingo. If you create a table or alter it to have a geometry datatype it will show it as varchar until you reconnect.

**Comment by nsssayom** [comment]
I don't see my PostGIS columns in the DB. Version 22.0.4.202205022238.
