### ISSUE TITLE
Unable to display schemas of a postgres connection

### ISSUE THREAD

**Issue by instcode** [serge-rider/dbeaver#228]
I was able to connect to my postgres server (version 8.0.2) using the latest postgres driver (version 9.5) successfully. However, as I tried to browse the db schemas, the following error appears in the error logs:

```
org.jkiss.dbeaver.DBException: Can't read schemas
	at org.jkiss.dbeaver.model.navigator.DBNDatabaseNode.extractPropertyValue(DBNDatabaseNode.java:728)
	at org.jkiss.dbeaver.model.navigator.DBNDatabaseNode.loadTreeItems(DBNDatabaseNode.java:444)
	at org.jkiss.dbeaver.model.navigator.DBNDatabaseNode.loadChildren(DBNDatabaseNode.java:370)
	at org.jkiss.dbeaver.model.navigator.DBNDatabaseNode.getChildren(DBNDatabaseNode.java:189)
	at org.jkiss.dbeaver.ui.navigator.database.load.TreeLoadService.evaluate(TreeLoadService.java:57)
	at org.jkiss.dbeaver.ui.navigator.database.load.TreeLoadService.evaluate(TreeLoadService.java:1)
	at org.jkiss.dbeaver.ui.LoadingJob.run(LoadingJob.java:82)
	at org.jkiss.dbeaver.ui.LoadingJob.run(LoadingJob.java:69)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:99)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)
Caused by: java.lang.NullPointerException: Name is null
	at java.lang.Enum.valueOf(Unknown Source)
	at org.jkiss.dbeaver.ext.postgresql.model.PostgreTypeCategory.valueOf(PostgreTypeCategory.java:1)
	at org.jkiss.dbeaver.ext.postgresql.model.PostgreDataType.readDataType(PostgreDataType.java:359)
	at org.jkiss.dbeaver.ext.postgresql.model.PostgreDataTypeCache.fetchObject(PostgreDataTypeCache.java:85)
	at org.jkiss.dbeaver.ext.postgresql.model.PostgreDataTypeCache.fetchObject(PostgreDataTypeCache.java:1)
	at org.jkiss.dbeaver.model.impl.jdbc.cache.JDBCObjectCache.loadObjects(JDBCObjectCache.java:100)
	at org.jkiss.dbeaver.model.impl.jdbc.cache.JDBCObjectCache.getAllObjects(JDBCObjectCache.java:59)
	at org.jkiss.dbeaver.ext.postgresql.model.PostgreDatabase.cacheDataTypes(PostgreDatabase.java:252)
	at org.jkiss.dbeaver.ext.postgresql.model.PostgreDatabase.getSchemas(PostgreDatabase.java:245)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.jkiss.dbeaver.model.navigator.DBNDatabaseNode.extractPropertyValue(DBNDatabaseNode.java:714)
	... 9 more
```
More details:
```
java.lang.NullPointerException: Name is null
	at java.lang.Enum.valueOf(Unknown Source)
	at org.jkiss.dbeaver.ext.postgresql.model.PostgreTypeCategory.valueOf(PostgreTypeCategory.java:1)
	at org.jkiss.dbeaver.ext.postgresql.model.PostgreDataType.readDataType(PostgreDataType.java:359)
	at org.jkiss.dbeaver.ext.postgresql.model.PostgreDataTypeCache.fetchObject(PostgreDataTypeCache.java:85)
	at org.jkiss.dbeaver.ext.postgresql.model.PostgreDataTypeCache.fetchObject(PostgreDataTypeCache.java:1)
	at org.jkiss.dbeaver.model.impl.jdbc.cache.JDBCObjectCache.loadObjects(JDBCObjectCache.java:100)
	at org.jkiss.dbeaver.model.impl.jdbc.cache.JDBCObjectCache.getAllObjects(JDBCObjectCache.java:59)
	at org.jkiss.dbeaver.ext.postgresql.model.PostgreDatabase.cacheDataTypes(PostgreDatabase.java:252)
	at org.jkiss.dbeaver.ext.postgresql.model.PostgreDatabase.getSchemas(PostgreDatabase.java:245)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.jkiss.dbeaver.model.navigator.DBNDatabaseNode.extractPropertyValue(DBNDatabaseNode.java:714)
	at org.jkiss.dbeaver.model.navigator.DBNDatabaseNode.loadTreeItems(DBNDatabaseNode.java:444)
	at org.jkiss.dbeaver.model.navigator.DBNDatabaseNode.loadChildren(DBNDatabaseNode.java:370)
	at org.jkiss.dbeaver.model.navigator.DBNDatabaseNode.getChildren(DBNDatabaseNode.java:189)
	at org.jkiss.dbeaver.ui.navigator.database.load.TreeLoadService.evaluate(TreeLoadService.java:57)
	at org.jkiss.dbeaver.ui.navigator.database.load.TreeLoadService.evaluate(TreeLoadService.java:1)
	at org.jkiss.dbeaver.ui.LoadingJob.run(LoadingJob.java:82)
	at org.jkiss.dbeaver.ui.LoadingJob.run(LoadingJob.java:69)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:99)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)

```

**Comment by serge-rider** [comment]
It is a bug in data type resolve in old (older than 8.4) PostgreSQL.
Will be fixed in the next hotfix version.
Thanks for report.
