### ISSUE TITLE
Oracle: "java.lang.NullPointerException"

### ISSUE THREAD

**Issue by progsurfer** [serge-rider/dbeaver#2295]
Hi in the last Version 4.2.2,

I get "java.lang.NullPointerException" when I try to preview in "DB Navigator" columns of a table, it happens when table consists lot of columns.

![grafik](https://user-images.githubusercontent.com/24592280/31328720-cf69274c-acd6-11e7-88c6-f9860047889f.png)

I use Win 7 and the Oracle DB.

In the previous Version the error doesn't appear.

Best regards 

Denis

**Comment by serge-rider** [comment]
Please port error stacktrace. You can get it in Error Log view or in log files (https://github.com/serge-rider/dbeaver/wiki/Log-files)

**Comment by dikei** [comment]
Here's the stack trace. For me, it's caused by a NUMBER column without precision.

```
java.lang.NullPointerException
	at org.jkiss.dbeaver.model.impl.sql.BasicSQLDialect.getColumnTypeModifiers(BasicSQLDialect.java:499)
	at org.jkiss.dbeaver.model.sql.SQLUtils.getColumnTypeModifiers(SQLUtils.java:581)
	at org.jkiss.dbeaver.model.DBUtils.getFullTypeName(DBUtils.java:1195)
	at org.jkiss.dbeaver.model.impl.struct.AbstractAttribute.getObjectToolTip(AbstractAttribute.java:203)
	at org.jkiss.dbeaver.model.navigator.DBNDatabaseNode.getNodeBriefInfo(DBNDatabaseNode.java:124)
	at org.jkiss.dbeaver.ui.navigator.database.DatabaseNavigatorLabelProvider.getText(DatabaseNavigatorLabelProvider.java:86)
	at org.eclipse.jface.viewers.ColumnLabelProvider.update(ColumnLabelProvider.java:34)
	at org.eclipse.jface.viewers.ViewerColumn.refresh(ViewerColumn.java:141)
	at org.eclipse.jface.viewers.AbstractTreeViewer.doUpdateItem(AbstractTreeViewer.java:946)
	at org.eclipse.jface.viewers.AbstractTreeViewer$UpdateItemSafeRunnable.run(AbstractTreeViewer.java:117)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.eclipse.ui.internal.JFaceUtil.lambda$0(JFaceUtil.java:44)
	at org.eclipse.jface.util.SafeRunnable.run(SafeRunnable.java:173)
	at org.eclipse.jface.viewers.AbstractTreeViewer.doUpdateItem(AbstractTreeViewer.java:1025)
	at org.eclipse.jface.viewers.StructuredViewer$UpdateItemSafeRunnable.run(StructuredViewer.java:475)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.eclipse.ui.internal.JFaceUtil.lambda$0(JFaceUtil.java:44)
	at org.eclipse.jface.util.SafeRunnable.run(SafeRunnable.java:173)
	at org.eclipse.jface.viewers.StructuredViewer.updateItem(StructuredViewer.java:2159)
	at org.eclipse.jface.viewers.AbstractTreeViewer.createTreeItem(AbstractTreeViewer.java:840)
	at org.eclipse.jface.viewers.AbstractTreeViewer.createAddedElements(AbstractTreeViewer.java:360)
	at org.eclipse.jface.viewers.AbstractTreeViewer.internalAdd(AbstractTreeViewer.java:283)
	at org.eclipse.jface.viewers.TreeViewer.internalAdd(TreeViewer.java:614)
	at org.eclipse.jface.viewers.AbstractTreeViewer.add(AbstractTreeViewer.java:159)
	at org.jkiss.dbeaver.ui.navigator.database.load.TreeLoadVisualizer.completeLoading(TreeLoadVisualizer.java:82)
	at org.jkiss.dbeaver.ui.navigator.database.load.TreeLoadVisualizer.completeLoading(TreeLoadVisualizer.java:1)
	at org.jkiss.dbeaver.ui.LoadingJob$LoadFinisher.run(LoadingJob.java:124)
	at org.eclipse.swt.widgets.RunnableLock.run(RunnableLock.java:37)
	at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Synchronizer.java:182)
	at org.eclipse.swt.widgets.Display.runAsyncMessages(Display.java:4497)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:4110)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1150)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:336)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1039)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:153)
	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:680)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:336)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:594)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:148)
	at org.jkiss.dbeaver.core.application.DBeaverApplication.start(DBeaverApplication.java:167)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:388)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:243)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:653)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:590)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1499)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1472)
```

**Comment by serge-rider** [comment]
This is a bug in 4.2.2 (problem with NULL scale in numeric columns). It is already fixed.
Thanks for report anyway.
