### ISSUE TITLE
java.lang.NullPointerException: null values not allowed

### ISSUE THREAD

**Issue by nobicycle** [serge-rider/dbeaver#23]
(Thanks for dbeaver)
Arch/Manjaro Linux
dbeaver-ee  3.5.2-1

!SESSION 2015-10-28 01:09:45.815 -----------------------------------------------
eclipse.buildId=unknown
java.version=1.8.0_65
java.vendor=Oracle Corporation
BootLoader constants: OS=linux, ARCH=x86_64, WS=gtk, NL=en_GB
Command-line arguments:  -os linux -ws gtk -arch x86_64

!ENTRY org.eclipse.osgi 4 0 2015-10-28 01:09:46.826
!MESSAGE Application error
!STACK 1
java.lang.NullPointerException: null values not allowed
	at org.eclipse.core.internal.registry.ReferenceMap.put(ReferenceMap.java:351)
	at org.eclipse.core.internal.registry.osgi.RegistryStrategyOSGI.getBundle(RegistryStrategyOSGI.java:151)
	at org.eclipse.core.internal.registry.osgi.RegistryStrategyOSGI.createExecutableExtension(RegistryStrategyOSGI.java:166)
	at org.eclipse.core.internal.registry.ExtensionRegistry.createExecutableExtension(ExtensionRegistry.java:905)
	at org.eclipse.core.internal.registry.ConfigurationElement.createExecutableExtension(ConfigurationElement.java:243)
	at org.eclipse.core.internal.registry.ConfigurationElementHandle.createExecutableExtension(ConfigurationElementHandle.java:55)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:191)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:380)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:235)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:669)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:608)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1515)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1488)

**Comment by serge-rider** [comment]
If you have upgraded from some previous version: run dbeaver (once) with command line parameter "-clean".

**Comment by serge-rider** [comment]
Or (maybe better) just remove previous version completely. 
If it was instaleld from deb them something like "rm -rf /use/share/dbeaver" should help.

**Comment by nobicycle** [comment]
-clean worked, but then there were problems with the database drivers. After removing user configuration with "rm ~/.eclipse ~/.dbeaver", all worked fine.

Thanks again
