### ISSUE TITLE
"Workbench has not been created yet"

### ISSUE THREAD

**Issue by nebiros** [serge-rider/dbeaver#2324]
I got this error trying to start dbeaver, I'm on macos high sierra 10.13 (17A405), java version "9", dbeaver 4.2.2:

```
✔ /Applications/DBeaver.app/Contents/MacOS
16:48 $ ./dbeaver
2017-10-12 16:48:41.896 - Create display
2017-10-12 16:48:42.251 - DBeaver 4.2.2 is starting
2017-10-12 16:48:42.253 - Install path: '/Applications/DBeaver.app/Contents/Eclipse'
2017-10-12 16:48:42.255 - Instance path: 'file:/Users/nebiros/.dbeaver4/'
2017-10-12 16:48:42.256 - Memory available 64Mb/1024Mb
2017-10-12 16:48:42.287 - Starting RMI server at 25363
2017-10-12 16:48:42.557 - Run workbench
2017-10-12 16:48:42.616 - DBeaver is stopping
2017-10-12 16:48:42.617 - null
java.lang.IllegalStateException: Workbench has not been created yet.
	at org.eclipse.ui.PlatformUI.getWorkbench(PlatformUI.java:93)
	at org.jkiss.dbeaver.core.application.DBeaverApplication.shutdown(DBeaverApplication.java:347)
	at org.jkiss.dbeaver.core.application.DBeaverApplication.start(DBeaverApplication.java:173)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:388)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:243)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:653)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:590)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1499)
```

**Comment by qoalu** [comment]
getting same error, MacOS Sierra 10.12.6, java 9, dbeaver 4.2.2

May be java 9 is the problem? [https://github.com/serge-rider/dbeaver/issues/2325](url)

**Comment by serge-rider** [comment]
Yes, maybe it is Java 9 related (also see #2247). We'll check.
Thanks for report.

**Comment by serge-rider** [comment]
Please test with DBeaver 4.2.3

**Comment by qoalu** [comment]
works for me now!

**Comment by serge-rider** [comment]
Great, thanks for information.
