### ISSUE TITLE
Bug? Mysql connection with proxysql server on MariaDB cluster

### ISSUE THREAD

**Issue by scippie75** [serge-rider/dbeaver#2371]
We have a DB cluster of one MariaDB master and one MariaDB slave. Both servers share an IP with keepalived and have a ProxySQL server configured to find the correct master DB.

When I use HeidiSQL to connect to this cluster on the floating IP and the ProxySQL port (the only port that is open for the public), it works fine. When I try to use dbeaver to do the same, it doesn't work:

Popup window: `Connect to '<ip>': Unknown system variable 'transaction_isolation'` after which the connection is marked as impossible.

Is there a solution for this?

**Comment by serge-rider** [comment]
Please check Error Log view (main menu Window->Show View->Error Log). 
If this error is there - please post stacktrace.

Possible solution: force auto-commit mode (connection properties, page General).

**Comment by scippie75** [comment]
Nothing is logged in the error log and disabling auto-commit doesn't help.
Anything else I can do/test/check?

**Comment by serge-rider** [comment]
There should be something at least in debug log: https://github.com/serge-rider/dbeaver/wiki/Log-files

**Comment by scippie75** [comment]
This is in the debug-log file:

```
2017-10-23 09:01:05.738 - DBeaver 4.2.3 is starting
2017-10-23 09:01:05.739 - Install path: '/usr/share/dbeaver'
2017-10-23 09:01:05.739 - Instance path: 'file:/home/dirk/.dbeaver4/'
2017-10-23 09:01:05.739 - Memory available 77Mb/910Mb
2017-10-23 09:01:05.750 - Starting RMI server at 54613
2017-10-23 09:01:05.778 - Run workbench
2017-10-23 09:01:07.216 - Initializing DBeaver 4.2.3
2017-10-23 09:01:07.219 - Host plugin: org.jkiss.dbeaver.core.application 4.2.3
2017-10-23 09:01:07.221 - Initialize Core...
2017-10-23 09:01:07.341 - Core initialized (120ms)
2017-10-23 09:01:07.343 - Configure workbench window
2017-10-23 09:01:07.378 - Create actions
2017-10-23 09:01:07.380 - Disable Eclipse action set 'org.eclipse.ui.edit.text.actionSet.annotationNavigation'
2017-10-23 09:01:07.383 - Disable Eclipse action set 'org.eclipse.ui.WorkingSetActionSet'
2017-10-23 09:01:07.710 - Initialize workbench window
2017-10-23 09:01:07.717 - Finish initialization
2017-10-23 09:01:11.022 - Open [https://dbeaver.jkiss.org/product/version.xml]
2017-10-23 09:01:30.576 - Connect with 'fip-sql-001 (sql 031/032)' (mysql5-15f340c22e6-4cebbf5046d9a2b6)
2017-10-23 09:01:30.792 - Connection failed (mysql5-15f340c22e6-4cebbf5046d9a2b6)
2017-10-23 09:01:30.793 - org.jkiss.dbeaver.model.exec.DBCConnectException: Unknown system variable 'transaction_isolation'
org.jkiss.dbeaver.model.exec.DBCConnectException: Unknown system variable 'transaction_isolation'
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.openConnection(JDBCDataSource.java:190)
	at org.jkiss.dbeaver.ext.mysql.model.MySQLDataSource.openConnection(MySQLDataSource.java:383)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCExecutionContext.connect(JDBCExecutionContext.java:79)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.initializeMainContext(JDBCDataSource.java:115)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.<init>(JDBCDataSource.java:109)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.<init>(JDBCDataSource.java:98)
	at org.jkiss.dbeaver.ext.mysql.model.MySQLDataSource.<init>(MySQLDataSource.java:83)
	at org.jkiss.dbeaver.ext.mysql.MySQLDataSourceProvider.openDataSource(MySQLDataSourceProvider.java:123)
	at org.jkiss.dbeaver.registry.DataSourceDescriptor.connect(DataSourceDescriptor.java:714)
	at org.jkiss.dbeaver.runtime.jobs.ConnectJob.run(ConnectJob.java:70)
	at org.jkiss.dbeaver.runtime.jobs.ConnectJob.runSync(ConnectJob.java:98)
	at org.jkiss.dbeaver.ui.actions.datasource.DataSourceHandler.connectToDataSource(DataSourceHandler.java:105)
	at org.jkiss.dbeaver.registry.DataSourceDescriptor.initConnection(DataSourceDescriptor.java:639)
	at org.jkiss.dbeaver.model.navigator.DBNDataSource.initializeNode(DBNDataSource.java:147)
	at org.jkiss.dbeaver.model.navigator.DBNDatabaseNode.getChildren(DBNDatabaseNode.java:197)
	at org.jkiss.dbeaver.model.navigator.DBNDatabaseNode.getChildren(DBNDatabaseNode.java:1)
	at org.jkiss.dbeaver.ui.navigator.NavigatorUtils.getNodeChildrenFiltered(NavigatorUtils.java:560)
	at org.jkiss.dbeaver.ui.navigator.database.load.TreeLoadService.evaluate(TreeLoadService.java:49)
	at org.jkiss.dbeaver.ui.navigator.database.load.TreeLoadService.evaluate(TreeLoadService.java:1)
	at org.jkiss.dbeaver.ui.LoadingJob.run(LoadingJob.java:86)
	at org.jkiss.dbeaver.ui.LoadingJob.run(LoadingJob.java:71)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:95)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:56)
Caused by: java.sql.SQLException: Unknown system variable 'transaction_isolation'
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:964)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3973)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3909)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2527)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2680)
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2483)
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2441)
	at com.mysql.jdbc.StatementImpl.executeQuery(StatementImpl.java:1381)
	at com.mysql.jdbc.ConnectionImpl.loadServerVariables(ConnectionImpl.java:3790)
	at com.mysql.jdbc.ConnectionImpl.initializePropsFromServer(ConnectionImpl.java:3227)
	at com.mysql.jdbc.ConnectionImpl.connectOneTryOnly(ConnectionImpl.java:2235)
	at com.mysql.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:2017)
	at com.mysql.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:779)
	at com.mysql.jdbc.JDBC4Connection.<init>(JDBC4Connection.java:47)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:425)
	at com.mysql.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:389)
	at com.mysql.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:330)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.openConnection(JDBCDataSource.java:176)
	... 22 more
```

**Comment by serge-rider** [comment]
This doesn't looks like DBeaver issue. Try another driver.
You can use MariaDB driver 2.x or 1.x. Or MySQL driver.

To choose driver version go to driver edit dialog->Download/Update->Click on version number in library list.

**Comment by scippie75** [comment]
I did use the MySQL driver. I have now switched to MariaDB and it works. Thanks!
MySQL was first in the list, so I didn't try search to find MariaDB (because that's what I am actually using).

Thanks!
