### ISSUE TITLE
Explain Execution Plan error

### ISSUE THREAD

**Issue by Magador** [serge-rider/dbeaver#2422]
I got this exception on version 4.2.3 dated of October 16, 2017

I tried to explain a SQL query containing dynamic parameters on an Oracle 11g DB.
If I replace the dynamic parameters by their values, the explanation successfully execute.

Plug-in : `org.jkiss.dbeaver.model`
Severity : `Error`
Message : `Missing IN or OUT parameter at index:: 1`
Exception Stack Trace : 
```
java.sql.SQLException: Missing IN or OUT parameter at index:: 1
	at oracle.jdbc.driver.OraclePreparedStatement.processCompletedBindRow(OraclePreparedStatement.java:1821)
	at oracle.jdbc.driver.OraclePreparedStatement.executeInternal(OraclePreparedStatement.java:3571)
	at oracle.jdbc.driver.OraclePreparedStatement.execute(OraclePreparedStatement.java:3677)
	at oracle.jdbc.driver.OraclePreparedStatementWrapper.execute(OraclePreparedStatementWrapper.java:1374)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCPreparedStatementImpl.execute(JDBCPreparedStatementImpl.java:258)
	at org.jkiss.dbeaver.ext.oracle.model.plan.OraclePlanAnalyser.explain(OraclePlanAnalyser.java:107)
	at org.jkiss.dbeaver.ext.oracle.model.OracleDataSource.planQueryExecution(OracleDataSource.java:464)
	at org.jkiss.dbeaver.ui.views.plan.PlanNodesTree$ExplainPlanService.evaluate(PlanNodesTree.java:151)
	at org.jkiss.dbeaver.ui.views.plan.PlanNodesTree$ExplainPlanService.evaluate(PlanNodesTree.java:1)
	at org.jkiss.dbeaver.ui.LoadingJob.run(LoadingJob.java:86)
	at org.jkiss.dbeaver.ui.LoadingJob.run(LoadingJob.java:71)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:95)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:56)
```
Session Data : 
```
eclipse.buildId=unknown
java.version=1.8.0_144
java.vendor=Oracle Corporation
BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=en_FR
Command-line arguments:  -os win32 -ws win32 -arch x86_64
```

**Comment by serge-rider** [comment]
It is a bug in explain plan processing.
Thanks for report.
