### ISSUE TITLE
FIX dbeaver -closeTabs -disconnectAll fails sometimes

### ISSUE THREAD

**Issue by allanlaal** [serge-rider/dbeaver#2430]
$ dbeaver -closeTabs -disconnectAll
	2017-10-29 11:37:45.908 - Create display
	2017-10-29 11:37:46.114 - Close all open editor tabs
	2017-10-29 11:37:46.156 - Error while calling remote server
	java.lang.IllegalStateException: Workbench has not been created yet.
		at org.eclipse.ui.PlatformUI.getWorkbench(PlatformUI.java:93)
		at org.jkiss.dbeaver.core.DBeaverUI.getActiveWorkbenchWindow(DBeaverUI.java:171)
		at org.jkiss.dbeaver.core.application.DBeaverApplication.closeAllEditors(DBeaverApplication.java:451)
		at org.jkiss.dbeaver.core.application.DBeaverApplication.executeCommandLineCommands(DBeaverApplication.java:440)
		at org.jkiss.dbeaver.core.application.DBeaverApplication.handleCommandLine(DBeaverApplication.java:319)
		at org.jkiss.dbeaver.core.application.DBeaverApplication.setDefaultWorkspacePath(DBeaverApplication.java:214)
		at org.jkiss.dbeaver.core.application.DBeaverApplication.start(DBeaverApplication.java:123)
		at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
		at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
		at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
		at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:388)
		at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:243)
		at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
		at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
		at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
		at java.lang.reflect.Method.invoke(Method.java:498)
		at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:653)
		at org.eclipse.equinox.launcher.Main.basicRun(Main.java:590)
		at org.eclipse.equinox.launcher.Main.run(Main.java:1499)
		at org.eclipse.equinox.launcher.Main.main(Main.java:1472)

but running just dbeaver works:

	$ dbeaver
	2017-10-29 11:38:06.236 - Create display
	2017-10-29 11:38:08.905 - DBeaver 4.2.3 is starting
	2017-10-29 11:38:08.915 - Install path: '/usr/share/dbeaver'
	2017-10-29 11:38:08.915 - Instance path: 'file:/home/allan/.dbeaver4/'
	2017-10-29 11:38:08.915 - Memory available 77Mb/910Mb
	2017-10-29 11:38:08.960 - Starting RMI server at 54931
	2017-10-29 11:38:09.058 - Run workbench
	2017-10-29 11:38:14.664 - Initializing DBeaver 4.2.3
	2017-10-29 11:38:14.669 - Host plugin: org.jkiss.dbeaver.core.application 4.2.3
	2017-10-29 11:38:14.672 - Initialize Core...
	2017-10-29 11:38:15.217 - Core initialized (545ms)
	2017-10-29 11:38:15.222 - Configure workbench window
	2017-10-29 11:38:15.355 - Create actions
	2017-10-29 11:38:15.359 - Disable Eclipse action set 'org.eclipse.ui.edit.text.actionSet.annotationNavigation'
	2017-10-29 11:38:15.361 - Disable Eclipse action set 'org.eclipse.ui.WorkingSetActionSet'
	2017-10-29 11:38:16.208 - Initialize workbench window
	2017-10-29 11:38:16.219 - Finish initialization

**Comment by allanlaal** [comment]
dbeaver -closeTabs -disconnectAll works intermittedly

**Comment by serge-rider** [comment]
Thanks for report.
This is not just about these commands. Whole command line processing was significantly refactored.
