### ISSUE TITLE
org.eclipse.swt.SWTException: Invalid thread access

### ISSUE THREAD

**Issue by marcmuel** [serge-rider/dbeaver#2579]
I have a lot of Exceptions like this in my Eclipse log. 

org.eclipse.swt.SWTException: Invalid thread access
	at org.eclipse.swt.SWT.error(SWT.java:4533)
	at org.eclipse.swt.SWT.error(SWT.java:4448)
	at org.eclipse.swt.SWT.error(SWT.java:4419)
	at org.eclipse.swt.widgets.Widget.error(Widget.java:482)
	at org.eclipse.swt.widgets.Widget.checkWidget(Widget.java:373)
	at org.eclipse.swt.widgets.Decorations.getText(Decorations.java:760)
	at org.eclipse.ui.internal.WorkbenchWindowConfigurer.getTitle(WorkbenchWindowConfigurer.java:268)
	at org.eclipse.ui.internal.ide.application.IDEWorkbenchWindowAdvisor.recomputeTitle(IDEWorkbenchWindowAdvisor.java:432)
	at org.eclipse.ui.internal.ide.application.IDEWorkbenchWindowAdvisor.access$2(IDEWorkbenchWindowAdvisor.java:430)
	at org.eclipse.ui.internal.ide.application.IDEWorkbenchWindowAdvisor$1.propertyChanged(IDEWorkbenchWindowAdvisor.java:113)
	at org.eclipse.ui.part.WorkbenchPart.firePropertyChange(WorkbenchPart.java:119)
	at org.eclipse.ui.texteditor.AbstractTextEditor.firePropertyChange(AbstractTextEditor.java:6345)
	at org.eclipse.ui.part.WorkbenchPart.setTitleImage(WorkbenchPart.java:300)
	at org.jkiss.dbeaver.ui.editors.sql.SQLEditor.access$19(SQLEditor.java:1)
	at org.jkiss.dbeaver.ui.editors.sql.SQLEditor$SQLEditorQueryListener.onStartQuery(SQLEditor.java:2157)
	at org.jkiss.dbeaver.runtime.sql.SQLQueryJob.executeSingleQuery(SQLQueryJob.java:372)
	at org.jkiss.dbeaver.runtime.sql.SQLQueryJob.run(SQLQueryJob.java:197)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:95)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:56)

eclipse.buildId=4.7.1.M20171009-0410
java.version=1.8.0_151
java.vendor=Oracle Corporation
BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=de_DE
Framework arguments:  -product org.eclipse.epp.package.java.product -product org.eclipse.epp.package.java.product

  DBeaver Core	4.2.6	org.jkiss.dbeaver.core.feature.feature.group	JKISS
  DBeaver DB2 Extension	2.1.55	org.jkiss.dbeaver.ext.db2.feature.feature.group	JKISS
  DBeaver Generic Extension	2.1.56	org.jkiss.dbeaver.ext.generic.feature.feature.group	JKISS
  DBeaver MySQL Extension	2.1.55	org.jkiss.dbeaver.ext.mysql.feature.feature.group	JKISS
  DBeaver Runtime	4.2.6	org.jkiss.dbeaver.runtime.feature.feature.group	JKISS

**Comment by serge-rider** [comment]
This is a bug in editor icon rendering. 
Thanks for report.
