### ISSUE TITLE
Out of memory error when trying to connecto to MS Access MDB file using UCanAccess driver

### ISSUE THREAD

**Issue by steromano87** [serge-rider/dbeaver#26]
I tried to connect to an Access MDB file using DBeaver and the UCanAccess driver downloaded from Maven repo.
However, when you create the connection and click on *Test Connection*, DBeaver goes out of memory trying to connect to DB.

I don't know if this issue is caused by the file dimension (the file size is about 75 MB).
Here you can find the content of *.log* file:
```
!SESSION 2015-10-28 16:22:43.335 -----------------------------------------------
eclipse.buildId=unknown
java.version=1.8.0_25
java.vendor=Oracle Corporation
BootLoader constants: OS=win32, ARCH=x86, WS=win32, NL=it
Command-line arguments:  -os win32 -ws win32 -arch x86

!ENTRY org.eclipse.ui 4 0 2015-10-28 16:34:31.076
!MESSAGE Unhandled event loop exception
!STACK 0
java.lang.OutOfMemoryError: Java heap space

!ENTRY org.eclipse.ui 4 4 2015-10-28 16:35:31.948
!MESSAGE An internal error has occurred.
!STACK 0
java.lang.OutOfMemoryError: Java heap space

!ENTRY org.eclipse.ui 4 0 2015-10-28 16:35:46.140
!MESSAGE Unhandled event loop exception
!STACK 0
org.eclipse.swt.SWTException: Failed to execute runnable (java.lang.OutOfMemoryError: Java heap space)
	at org.eclipse.swt.SWT.error(SWT.java:4491)
	at org.eclipse.swt.SWT.error(SWT.java:4406)
	at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Synchronizer.java:138)
	at org.eclipse.swt.widgets.Display.runAsyncMessages(Display.java:4155)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3772)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$4.run(PartRenderingEngine.java:1127)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:337)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1018)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:156)
	at org.eclipse.ui.internal.Workbench$5.run(Workbench.java:654)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:337)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:598)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:150)
	at org.jkiss.dbeaver.core.application.DBeaverApplication.start(DBeaverApplication.java:106)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:380)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:235)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:669)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:608)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1515)
Caused by: java.lang.OutOfMemoryError: Java heap space
!SESSION 2015-10-28 16:36:52.398 -----------------------------------------------
eclipse.buildId=unknown
java.version=1.8.0_25
java.vendor=Oracle Corporation
BootLoader constants: OS=win32, ARCH=x86, WS=win32, NL=it
Command-line arguments:  -os win32 -ws win32 -arch x86
```

**Comment by serge-rider** [comment]
Can't reproduce that.
I'm pretty sure that this problem is a result of some bug in UCanAccess. There were too many different mdb formats so I think some of them are not fully supported.
You could try to address this issue to https://sourceforge.net/p/ucanaccess/discussion/

Possible workaround: try to increase amount of memory available to DBeaver (start dbeaver with command line parameter "-vmargs -Xmx1024M")

**Comment by steromano87** [comment]
Hi Serge,

I verified that using a fresh MDB database created using MS Access 2010, the problem does not appear.
I found the issue trying to open a MDB file crated by HP LoadRunner. I don't know which is the exact version of the DB file.

**Comment by frbelotto** [comment]
> Possible workaround: try to increase amount of memory available to DBeaver (start dbeaver with command line parameter "-vmargs -Xmx1024M")

Hello! Very long time ago an this issue still happens here. Setting up as suggested solve, but shouldn't this being somehow automatically handled but Dbeaver? 

Obs : Additional question. How to edit start parameter in Dbeaver that is installed from MS Store?
