### ISSUE TITLE
Oracle ref cursor not show result

### ISSUE THREAD

**Issue by Crutchmaster** [serge-rider/dbeaver#2629]
Query: select my_refcur_function(1) from dual;
Result of query - one null row. Type - REFCURSOR.
Query executed with warning:
SQL Error [17001] [99999]: Internal error: need resolution: do we want to handle ResultSet?
Stacktrace:
org.jkiss.dbeaver.model.exec.DBCException: SQL Error [17001] [99999]:  Internal error: need resolution: do we want to handle ResultSet?
	at org.jkiss.dbeaver.model.impl.jdbc.data.handlers.JDBCAbstractValueHandler.fetchValueObject(JDBCAbstractValueHandler.java:55)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetDataReceiver.fetchRow(ResultSetDataReceiver.java:107)
	at org.jkiss.dbeaver.runtime.sql.SQLQueryJob.fetchQueryData(SQLQueryJob.java:701)
	at org.jkiss.dbeaver.runtime.sql.SQLQueryJob.executeSingleQuery(SQLQueryJob.java:418)
	at org.jkiss.dbeaver.runtime.sql.SQLQueryJob.extractData(SQLQueryJob.java:794)
	at org.jkiss.dbeaver.ui.editors.sql.SQLEditor$QueryResultsContainer.readData(SQLEditor.java:1958)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetJobDataRead.run(ResultSetJobDataRead.java:91)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:95)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:56)
Caused by: java.sql.SQLException:  Internal error: need resolution: do we want to handle ResultSet?
	at oracle.jdbc.driver.SQLUtil.makeDatum(SQLUtil.java:613)
	at oracle.jdbc.driver.ScrollableResultSet.getCachedDatumValueAt(ScrollableResultSet.java:2574)
	at oracle.jdbc.driver.ScrollableResultSet.getOracleObject(ScrollableResultSet.java:634)
	at oracle.jdbc.driver.ScrollableResultSet.getObject(ScrollableResultSet.java:1173)
	at oracle.jdbc.driver.ScrollableResultSet.getObject(ScrollableResultSet.java:1119)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCResultSetImpl.getObject(JDBCResultSetImpl.java:628)
	at org.jkiss.dbeaver.model.impl.jdbc.data.handlers.JDBCObjectValueHandler.fetchColumnValue(JDBCObjectValueHandler.java:60)
	at org.jkiss.dbeaver.model.impl.jdbc.data.handlers.JDBCAbstractValueHandler.fetchValueObject(JDBCAbstractValueHandler.java:49)
	... 8 more

**Comment by serge-rider** [comment]
Hello,

- What Oracle server version do you have?
- What Oracle client driver version do you use? 

(hint: perhaps you need to try another driver version)

**Comment by Crutchmaster** [comment]
Oracle Database 11g Enterprise Edition Release 11.2.0.4.0 - 64bit Production
JDBC mainfest.mf:
Implementation-Vendor: Oracle Corporation
Implementation-Title: JDBC
Implementation-Version: 11.2.0.4.0

**Comment by serge-rider** [comment]
Try driver for Oracle 12g. 
At least it works fine with ref cursors in my test environment.

**Comment by Crutchmaster** [comment]
11g not work with 12g jdbc drivers for me.

**Comment by serge-rider** [comment]
Thanks for info
