### ISSUE TITLE
Error reading procedure Body

### ISSUE THREAD

**Issue by fjavier** [serge-rider/dbeaver#266]
Dbeaver version 3.6.0 and 3.6.1 when click on the function name.
DBException: Error reading procedure body
  org.postgresql.util.PSQLException: PSQLException: ERROR: cache lookup failed for function 0

![image](https://cloud.githubusercontent.com/assets/3578372/13539321/4208efaa-e215-11e5-8713-81f865713874.png)

**Comment by serge-rider** [comment]
Please post error stacktrace (from Error Log view).
And what is your PostgreSQL server version?

**Comment by fjavier** [comment]
> **Postgresql version 9.4**
> **Linux Environment.**

!SESSION 2016-03-04 15:00:08.080 -----------------------------------------------
eclipse.buildId=unknown
java.version=1.7.0_95
java.vendor=Oracle Corporation
BootLoader constants: OS=linux, ARCH=x86_64, WS=gtk, NL=es_NI
Command-line arguments:  -os linux -ws gtk -arch x86_64

!ENTRY org.jkiss.dbeaver.model 2 0 2016-03-04 15:00:36.168
!MESSAGE Unsupported PostgreClass 'f'

!ENTRY org.jkiss.dbeaver.model 2 0 2016-03-04 15:00:36.199
!MESSAGE Unsupported PostgreClass 'f'

!ENTRY org.jkiss.dbeaver.model 4 0 2016-03-04 15:01:03.956
!MESSAGE org.jkiss.dbeaver.DBException: Error reading procedure body
!SUBENTRY 1 org.jkiss.dbeaver.model 4 0 2016-03-04 15:01:03.956
!MESSAGE DBException: Error reading procedure body
!STACK 0
org.jkiss.dbeaver.DBException: Error reading procedure body
	at org.jkiss.dbeaver.ext.postgresql.model.PostgreProcedure.getObjectDefinitionText(PostgreProcedure.java:268)
	at org.jkiss.dbeaver.ui.editors.sql.SQLSourceViewer.getSourceText(SQLSourceViewer.java:34)
	at org.jkiss.dbeaver.ui.editors.sql.SQLEditorNested$ObjectDocumentProvider$1.run(SQLEditorNested.java:230)
	at org.jkiss.dbeaver.runtime.TasksJob.run(TasksJob.java:61)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:99)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)
Caused by: org.postgresql.util.PSQLException: ERROR: cache lookup failed for function 0
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2182)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:1911)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:173)
	at org.postgresql.jdbc2.AbstractJdbc2Statement.execute(AbstractJdbc2Statement.java:645)
	at org.postgresql.jdbc2.AbstractJdbc2Statement.executeWithFlags(AbstractJdbc2Statement.java:495)
	at org.postgresql.jdbc2.AbstractJdbc2Statement.executeQuery(AbstractJdbc2Statement.java:380)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCPreparedStatementImpl.executeQuery(JDBCPreparedStatementImpl.java:221)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCUtils.queryString(JDBCUtils.java:608)
	at org.jkiss.dbeaver.ext.postgresql.model.PostgreProcedure.getObjectDefinitionText(PostgreProcedure.java:266)
	... 5 more
!SUBENTRY 2 org.jkiss.dbeaver.model 4 0 2016-03-04 15:01:03.957
!MESSAGE PSQLException: ERROR: cache lookup failed for function 0
!STACK 0
org.postgresql.util.PSQLException: ERROR: cache lookup failed for function 0
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2182)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:1911)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:173)
	at org.postgresql.jdbc2.AbstractJdbc2Statement.execute(AbstractJdbc2Statement.java:645)
	at org.postgresql.jdbc2.AbstractJdbc2Statement.executeWithFlags(AbstractJdbc2Statement.java:495)
	at org.postgresql.jdbc2.AbstractJdbc2Statement.executeQuery(AbstractJdbc2Statement.java:380)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCPreparedStatementImpl.executeQuery(JDBCPreparedStatementImpl.java:221)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCUtils.queryString(JDBCUtils.java:608)
	at org.jkiss.dbeaver.ext.postgresql.model.PostgreProcedure.getObjectDefinitionText(PostgreProcedure.java:266)
	at org.jkiss.dbeaver.ui.editors.sql.SQLSourceViewer.getSourceText(SQLSourceViewer.java:34)
	at org.jkiss.dbeaver.ui.editors.sql.SQLEditorNested$ObjectDocumentProvider$1.run(SQLEditorNested.java:230)
	at org.jkiss.dbeaver.runtime.TasksJob.run(TasksJob.java:61)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:99)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)

!ENTRY org.jkiss.dbeaver.model 1 0 2016-03-04 15:21:02.151
!MESSAGE All connections (2) are alive!

!ENTRY org.jkiss.dbeaver.model 4 0 2016-03-04 15:33:58.451
!MESSAGE org.jkiss.dbeaver.DBException: Error reading procedure body
!SUBENTRY 1 org.jkiss.dbeaver.model 4 0 2016-03-04 15:33:58.451
!MESSAGE DBException: Error reading procedure body
!STACK 0
org.jkiss.dbeaver.DBException: Error reading procedure body
	at org.jkiss.dbeaver.ext.postgresql.model.PostgreProcedure.getObjectDefinitionText(PostgreProcedure.java:268)
	at org.jkiss.dbeaver.ui.editors.sql.SQLSourceViewer.getSourceText(SQLSourceViewer.java:34)
	at org.jkiss.dbeaver.ui.editors.sql.SQLEditorNested$ObjectDocumentProvider$1.run(SQLEditorNested.java:230)
	at org.jkiss.dbeaver.runtime.TasksJob.run(TasksJob.java:61)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:99)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)
Caused by: org.postgresql.util.PSQLException: ERROR: cache lookup failed for function 0
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2182)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:1911)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:173)
	at org.postgresql.jdbc2.AbstractJdbc2Statement.execute(AbstractJdbc2Statement.java:645)
	at org.postgresql.jdbc2.AbstractJdbc2Statement.executeWithFlags(AbstractJdbc2Statement.java:495)
	at org.postgresql.jdbc2.AbstractJdbc2Statement.executeQuery(AbstractJdbc2Statement.java:380)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCPreparedStatementImpl.executeQuery(JDBCPreparedStatementImpl.java:221)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCUtils.queryString(JDBCUtils.java:608)
	at org.jkiss.dbeaver.ext.postgresql.model.PostgreProcedure.getObjectDefinitionText(PostgreProcedure.java:266)
	... 5 more
!SUBENTRY 2 org.jkiss.dbeaver.model 4 0 2016-03-04 15:33:58.451
!MESSAGE PSQLException: ERROR: cache lookup failed for function 0
!STACK 0
org.postgresql.util.PSQLException: ERROR: cache lookup failed for function 0
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2182)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:1911)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:173)
	at org.postgresql.jdbc2.AbstractJdbc2Statement.execute(AbstractJdbc2Statement.java:645)
	at org.postgresql.jdbc2.AbstractJdbc2Statement.executeWithFlags(AbstractJdbc2Statement.java:495)
	at org.postgresql.jdbc2.AbstractJdbc2Statement.executeQuery(AbstractJdbc2Statement.java:380)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCPreparedStatementImpl.executeQuery(JDBCPreparedStatementImpl.java:221)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCUtils.queryString(JDBCUtils.java:608)
	at org.jkiss.dbeaver.ext.postgresql.model.PostgreProcedure.getObjectDefinitionText(PostgreProcedure.java:266)
	at org.jkiss.dbeaver.ui.editors.sql.SQLSourceViewer.getSourceText(SQLSourceViewer.java:34)
	at org.jkiss.dbeaver.ui.editors.sql.SQLEditorNested$ObjectDocumentProvider$1.run(SQLEditorNested.java:230)
	at org.jkiss.dbeaver.runtime.TasksJob.run(TasksJob.java:61)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:99)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)

**Comment by serge-rider** [comment]
That's odd.
I assume that you are using PG 9.2 or earlier. In that version pg_proc system table had no oid column making such error possible.
I'll add some workaround in the next version.
