### ISSUE TITLE
Not connected to database

### ISSUE THREAD

**Issue by infectormp** [serge-rider/dbeaver#273]
I have strange issue. 

When i try persist changes (for mysql user privileges) i get 
```org.jkiss.dbeaver.DBException: DBException: Not connected to database```

here details from Error log:
```
org.jkiss.dbeaver.DBException: Not connected to database 
at org.jkiss.dbeaver.model.impl.edit.AbstractCommandContext.saveChanges(AbstractCommandContext.java:82)
	at org.jkiss.dbeaver.ui.editors.entity.EntityEditor.saveCommandContext(EntityEditor.java:267)
	at org.jkiss.dbeaver.ui.editors.entity.EntityEditor.access$1(EntityEditor.java:252)
	at org.jkiss.dbeaver.ui.editors.entity.EntityEditor$SaveJob.run(EntityEditor.java:851)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:99)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)
```
And i get this error even i Invalidate connection for this DB.

But when i copy code from SQL Preview to SQL Editor and run, all fine, i not get ```Not connected to database```

**Comment by infectormp** [comment]
can't reproduce this to 100%, but i get this problem two times, after play with mysql user rights

**Comment by infectormp** [comment]
yes, it's hard to reproduce.

**Comment by serge-rider** [comment]
Will close it for now.
Reopen on any new info.
