### ISSUE TITLE
ctrl-v pasting into wrong tab

### ISSUE THREAD

**Issue by Lonniebiz** [serge-rider/dbeaver#280]
When copying and pasting using the ctrl-c and ctrl-v keyboard-shortcuts, dbeaver 3.6.1 is pasting into the wrong tab (a tab that is not even currently visible).

Watch this video where I showcase this behavior:
[https://youtu.be/4fuPHHOJ_QM](https://youtu.be/4fuPHHOJ_QM)

**Comment by Lonniebiz** [comment]
This issue is not limited to ctrl-v. I've just experienced  another example where hitting the delete key in one tab actually deleted characters from another non-visible tab.

**Comment by serge-rider** [comment]
That's really weird. I think it is somehow related to Remmina RDP.
And generally it is not a DBeaver issue, text editors are part of Eclipse framework. Looks like something wrong happens with focus/command chain.
Can you try any other RDP client or any other environment?

**Comment by Lonniebiz** [comment]
Upon logging into that Windows 10 machine directly, I was immediately able to reproduce the issue without Remmina being involved.

The issue only happens with one of the tabs I have open, as though it was somehow corrupted at the time of tab-initialization in manner that persist this behavior for the life of that particular tab.

Right now, as I create new tabs, they are not exhibiting this behavior. But I have not yet closed that tab shown in the video, and that tab still exhibits the same behavior as shown in the video (even now -- logged directly into the workstation with physical mouse, keyboard and monitor).

Perhaps this is just a rare-weirdness, but I thought I'd report it anyway in case you might be able to conceive a cause of this strange behavior.

**Comment by serge-rider** [comment]
Interesting.
I think this is the same: https://bugs.eclipse.org/bugs/show_bug.cgi?id=401835
But apparently it still happens (DBeaver is based on Eclipse Mars).
Can you check error log for any related errors/warnings?

**Comment by Lonniebiz** [comment]
It seems you've discovered the exact issue.

Here's a screen-shot of recent errors:
http://neartalk.com/ss/2016-03-14_001_1817x1020.bmp

And here are a few of their details:

`eclipse.buildId=unknown
java.version=1.7.0_60
java.vendor=Oracle Corporation
BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=en_US
Command-line arguments:  -os win32 -ws win32 -arch x86_64

org.eclipse.e4.ui.workbench.swt
Error
Mon Mar 14 13:05:58 CDT 2016
Problems occurred when invoking code from plug-in: "org.eclipse.e4.ui.workbench.swt".

java.lang.ArrayIndexOutOfBoundsException

-------------------------------------------------------------------------------------

eclipse.buildId=unknown
java.version=1.7.0_60
java.vendor=Oracle Corporation
BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=en_US
Command-line arguments:  -os win32 -ws win32 -arch x86_64

org.eclipse.e4.ui.workbench
Error
Mon Mar 14 13:02:20 CDT 2016
Problems occurred when invoking code from plug-in: "org.eclipse.e4.ui.workbench".

java.lang.ArrayIndexOutOfBoundsException

--------------------------------------------------------------------------------------

eclipse.buildId=unknown
java.version=1.7.0_60
java.vendor=Oracle Corporation
BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=en_US
Command-line arguments:  -os win32 -ws win32 -arch x86_64

org.eclipse.e4.ui.workbench

----------------------------------------------------------------------------------------------------------
Error
Mon Mar 14 13:01:31 CDT 2016
An exception occurred while notifying part listeners

java.lang.ArrayIndexOutOfBoundsException


eclipse.buildId=unknown
java.version=1.7.0_60
java.vendor=Oracle Corporation
BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=en_US
Command-line arguments:  -os win32 -ws win32 -arch x86_64

org.eclipse.ui.workbench
Error
Mon Mar 14 12:54:41 CDT 2016
1

java.lang.ArrayIndexOutOfBoundsException: 1
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetModel.getCellValue(ResultSetModel.java:324)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetPropertyTester.checkResultSetProperty(ResultSetPropertyTester.java:123)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetPropertyTester.test(ResultSetPropertyTester.java:50)
	at org.eclipse.core.internal.expressions.Property.test(Property.java:58)
	at org.eclipse.core.internal.expressions.TestExpression.evaluate(TestExpression.java:100)
	at org.eclipse.core.internal.expressions.CompositeExpression.evaluateAnd(CompositeExpression.java:53)
	at org.eclipse.core.internal.expressions.WithExpression.evaluate(WithExpression.java:75)
	at org.eclipse.ui.internal.services.EvaluationReference.evaluate(EvaluationReference.java:98)
	at org.eclipse.ui.internal.services.EvaluationReference.evaluate(EvaluationReference.java:137)
	at org.eclipse.ui.internal.services.EvaluationService.requestEvaluation(EvaluationService.java:356)
	at org.eclipse.ui.internal.handlers.DirtyStateTracker.update(DirtyStateTracker.java:45)
	at org.eclipse.ui.internal.handlers.DirtyStateTracker.propertyChanged(DirtyStateTracker.java:107)
	at org.eclipse.ui.part.WorkbenchPart.firePropertyChange(WorkbenchPart.java:129)
	at org.eclipse.ui.texteditor.AbstractTextEditor.firePropertyChange(AbstractTextEditor.java:6387)
	at org.eclipse.ui.texteditor.AbstractTextEditor$3.run(AbstractTextEditor.java:436)
	at org.eclipse.ui.texteditor.AbstractTextEditor$ElementStateListener.execute(AbstractTextEditor.java:600)
	at org.eclipse.ui.texteditor.AbstractTextEditor$ElementStateListener.elementDirtyStateChanged(AbstractTextEditor.java:439)
	at org.eclipse.ui.texteditor.AbstractDocumentProvider.fireElementDirtyStateChanged(AbstractDocumentProvider.java:681)
	at org.eclipse.ui.texteditor.AbstractDocumentProvider$ElementInfo.documentChanged(AbstractDocumentProvider.java:149)
	at org.eclipse.jface.text.AbstractDocument.doFireDocumentChanged2(AbstractDocument.java:769)
	at org.eclipse.jface.text.AbstractDocument.doFireDocumentChanged(AbstractDocument.java:736)
	at org.eclipse.jface.text.AbstractDocument.doFireDocumentChanged(AbstractDocument.java:721)
	at org.eclipse.jface.text.AbstractDocument.fireDocumentChanged(AbstractDocument.java:796)
	at org.eclipse.jface.text.AbstractDocument.replace(AbstractDocument.java:1191)
	at org.eclipse.jface.text.AbstractDocument.replace(AbstractDocument.java:1210)
	at org.eclipse.jface.text.projection.ProjectionTextStore.replace(ProjectionTextStore.java:111)
	at org.eclipse.jface.text.AbstractDocument.replace(AbstractDocument.java:1184)
	at org.eclipse.jface.text.AbstractDocument.replace(AbstractDocument.java:1210)
	at org.eclipse.jface.text.projection.ProjectionDocument.replace(ProjectionDocument.java:629)
	at org.eclipse.jface.text.DefaultDocumentAdapter.replaceTextRange(DefaultDocumentAdapter.java:248)
	at org.eclipse.swt.custom.StyledText.modifyContent(StyledText.java:7308)
	at org.eclipse.swt.custom.StyledText.sendKeyEvent(StyledText.java:8159)
	at org.eclipse.swt.custom.StyledText.paste(StyledText.java:7372)
	at org.eclipse.jface.text.TextViewer.paste(TextViewer.java:4100)
	at org.eclipse.jface.text.TextViewer.doOperation(TextViewer.java:4029)
	at org.eclipse.jface.text.source.SourceViewer.doOperation(SourceViewer.java:1053)
	at org.eclipse.jface.text.source.projection.ProjectionViewer.doOperation(ProjectionViewer.java:1501)
	at org.eclipse.ui.texteditor.TextOperationAction$1.run(TextOperationAction.java:128)
	at org.eclipse.swt.custom.BusyIndicator.showWhile(BusyIndicator.java:70)
	at org.eclipse.ui.texteditor.TextOperationAction.run(TextOperationAction.java:126)
	at org.eclipse.jface.action.Action.runWithEvent(Action.java:473)
	at org.eclipse.jface.commands.ActionHandler.execute(ActionHandler.java:122)
	at org.eclipse.ui.internal.handlers.E4HandlerProxy.execute(E4HandlerProxy.java:90)
	at sun.reflect.GeneratedMethodAccessor46.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.eclipse.e4.core.internal.di.MethodRequestor.execute(MethodRequestor.java:56)
	at org.eclipse.e4.core.internal.di.InjectorImpl.invokeUsingClass(InjectorImpl.java:252)
	at org.eclipse.e4.core.internal.di.InjectorImpl.invoke(InjectorImpl.java:234)
	at org.eclipse.e4.core.contexts.ContextInjectionFactory.invoke(ContextInjectionFactory.java:132)
	at org.eclipse.e4.core.commands.internal.HandlerServiceHandler.execute(HandlerServiceHandler.java:152)
	at org.eclipse.core.commands.Command.executeWithChecks(Command.java:493)
	at org.eclipse.core.commands.ParameterizedCommand.executeWithChecks(ParameterizedCommand.java:486)
	at org.eclipse.e4.core.commands.internal.HandlerServiceImpl.executeHandler(HandlerServiceImpl.java:210)
	at org.eclipse.e4.ui.bindings.keys.KeyBindingDispatcher.executeCommand(KeyBindingDispatcher.java:286)
	at org.eclipse.e4.ui.bindings.keys.KeyBindingDispatcher.press(KeyBindingDispatcher.java:507)
	at org.eclipse.e4.ui.bindings.keys.KeyBindingDispatcher.processKeyEvent(KeyBindingDispatcher.java:558)
	at org.eclipse.e4.ui.bindings.keys.KeyBindingDispatcher.filterKeySequenceBindings(KeyBindingDispatcher.java:378)
	at org.eclipse.e4.ui.bindings.keys.KeyBindingDispatcher.access$0(KeyBindingDispatcher.java:324)
	at org.eclipse.e4.ui.bindings.keys.KeyBindingDispatcher$KeyDownFilter.handleEvent(KeyBindingDispatcher.java:86)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:84)
	at org.eclipse.swt.widgets.Display.filterEvent(Display.java:1266)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1112)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1137)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1122)
	at org.eclipse.swt.widgets.Widget.sendKeyEvent(Widget.java:1164)
	at org.eclipse.swt.widgets.Widget.sendKeyEvent(Widget.java:1160)
	at org.eclipse.swt.widgets.Widget.wmChar(Widget.java:1581)
	at org.eclipse.swt.widgets.Control.WM_CHAR(Control.java:4795)
	at org.eclipse.swt.widgets.Canvas.WM_CHAR(Canvas.java:343)
	at org.eclipse.swt.widgets.Control.windowProc(Control.java:4676)
	at org.eclipse.swt.widgets.Canvas.windowProc(Canvas.java:339)
	at org.eclipse.swt.widgets.Display.windowProc(Display.java:5050)
	at org.eclipse.swt.internal.win32.OS.DispatchMessageW(Native Method)
	at org.eclipse.swt.internal.win32.OS.DispatchMessage(OS.java:2549)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3767)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$4.run(PartRenderingEngine.java:1127)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:337)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1018)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:156)
	at org.eclipse.ui.internal.Workbench$5.run(Workbench.java:694)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:337)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:606)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:150)
	at org.jkiss.dbeaver.core.application.DBeaverApplication.start(DBeaverApplication.java:110)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:380)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:235)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:669)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:608)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1515)
`

**Comment by serge-rider** [comment]
This particular error is fixed, thanks for report.
Although I still can't realize how it is related to copy/paste issue.
Maybe just a side effect..

**Comment by Lonniebiz** [comment]
I wasn't trying to imply that this issue was related issue 204. I consider this issue more of a sandboxing issue; only the visible-tab should ever be effected by any keystroke combination. Yet, I've personally experienced 2 keys leaking into other tabs: ctrl-v and the delete key.

Thanks for looking into this.

**Comment by serge-rider** [comment]
Ok. Hopefully the fix above will help.

If you will see other suspicious errors in log please post them.
Thanks for report.
