### ISSUE TITLE
postgresql: Can't read schemas

### ISSUE THREAD

**Issue by gwenn** [serge-rider/dbeaver#289]
```
org.jkiss.dbeaver.DBException: Can't read schemas
	at org.jkiss.dbeaver.model.navigator.DBNDatabaseNode.extractPropertyValue(DBNDatabaseNode.java:728)
	at org.jkiss.dbeaver.model.navigator.DBNDatabaseNode.loadTreeItems(DBNDatabaseNode.java:444)
	at org.jkiss.dbeaver.model.navigator.DBNDatabaseNode.loadChildren(DBNDatabaseNode.java:370)
	at org.jkiss.dbeaver.model.navigator.DBNDatabaseNode.getChildren(DBNDatabaseNode.java:189)
	at org.jkiss.dbeaver.ui.navigator.database.load.TreeLoadService.evaluate(TreeLoadService.java:57)
	at org.jkiss.dbeaver.ui.navigator.database.load.TreeLoadService.evaluate(TreeLoadService.java:1)
	at org.jkiss.dbeaver.ui.LoadingJob.run(LoadingJob.java:82)
	at org.jkiss.dbeaver.ui.LoadingJob.run(LoadingJob.java:69)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:99)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)
Caused by: java.lang.NullPointerException: Name is null
	at java.lang.Enum.valueOf(Enum.java:236)
	at org.jkiss.dbeaver.ext.postgresql.model.PostgreTypeCategory.valueOf(PostgreTypeCategory.java:1)
	at org.jkiss.dbeaver.ext.postgresql.model.PostgreDataType.<init>(PostgreDataType.java:116)
	at org.jkiss.dbeaver.ext.postgresql.model.PostgreDataType.readDataType(PostgreDataType.java:516)
	at org.jkiss.dbeaver.ext.postgresql.model.PostgreDataTypeCache.fetchObject(PostgreDataTypeCache.java:85)
	at org.jkiss.dbeaver.ext.postgresql.model.PostgreDataTypeCache.fetchObject(PostgreDataTypeCache.java:1)
	at org.jkiss.dbeaver.model.impl.jdbc.cache.JDBCObjectCache.loadObjects(JDBCObjectCache.java:101)
	at org.jkiss.dbeaver.model.impl.jdbc.cache.JDBCObjectCache.getAllObjects(JDBCObjectCache.java:59)
	at org.jkiss.dbeaver.ext.postgresql.model.PostgreDatabase.cacheDataTypes(PostgreDatabase.java:264)
	at org.jkiss.dbeaver.ext.postgresql.model.PostgreDatabase.getSchemas(PostgreDatabase.java:257)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.jkiss.dbeaver.model.navigator.DBNDatabaseNode.extractPropertyValue(DBNDatabaseNode.java:714)
	... 9 more
```
The postgresql server is old (version 8.0.0).
DBeaver 3.6.2

**Comment by serge-rider** [comment]
Thanks for report. Will be fixed in the next version.
Also, to support older PG version I'll add Generic PostgreSQL driver in the standard configuration. It will be more stable but it won't support most of PG-specific features.
