### ISSUE TITLE
[3.6.3] Oracle - Unknown SQL on comment

### ISSUE THREAD

**Issue by NullpointerForever** [serge-rider/dbeaver#315]
When I execute script SQL and the last line of this script has a comment:
```sql
select 1+1 from dual;
-- abc
```

 then exception is thrown:
```
java.sql.SQLException: Unknown SQL Type: sqlKind = UNINITIALIZED
	at oracle.jdbc.driver.T4CStatement.doOall8(T4CStatement.java:65)
	at oracle.jdbc.driver.T4CStatement.executeForRows(T4CStatement.java:1036)
	at oracle.jdbc.driver.OracleStatement.doExecuteWithTimeout(OracleStatement.java:1336)
	at oracle.jdbc.driver.OracleStatement.executeInternal(OracleStatement.java:1916)
	at oracle.jdbc.driver.OracleStatement.execute(OracleStatement.java:1878)
	at oracle.jdbc.driver.OracleStatementWrapper.execute(OracleStatementWrapper.java:318)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCStatementImpl.execute(JDBCStatementImpl.java:345)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCStatementImpl.executeStatement(JDBCStatementImpl.java:138)
	at org.jkiss.dbeaver.runtime.sql.SQLQueryJob.executeSingleQuery(SQLQueryJob.java:342)
	at org.jkiss.dbeaver.runtime.sql.SQLQueryJob.run(SQLQueryJob.java:183)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:99)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)
```

**Comment by serge-rider** [comment]
Thanks for report
