### ISSUE TITLE
Oracle - Cannot generate explain plan as non admin user due to insufficient privileges (but TOAD can)

### ISSUE THREAD

**Issue by steromano87** [serge-rider/dbeaver#341]
If you try to get an explain plain using a non admin user, DBeaver raises an "Insufficient privileges" error and does not output anything:

![image](https://cloud.githubusercontent.com/assets/8759452/14313312/219eacf0-fbf1-11e5-9fb8-5fda0b9faa1f.png)

However, if I try to get the eplain plan for the same query using the same user in TOAD, the explain plan is calculated normally:

![image](https://cloud.githubusercontent.com/assets/8759452/14313336/59bea75c-fbf1-11e5-8817-1d502a71ef1a.png)

Here are listed all the user permissions from USER_ROLE_PRIVS (USER_SYS_PRIVS and USER_TAB_PRIVS are empty for the given user):

| GRANTED_ROLE | ADMIN_OPTION | DEFAULT_ROLE | OS_GRANTED |
| -------------- | -------------- | -------------- | ------------ |
| UTE_READ     | NO           | YES          | NO         |

**Comment by serge-rider** [comment]
Can't reproduce that.
Please post error with stacktrace

**Comment by steromano87** [comment]
Hi Serge,

here you can find the output of the log:
!SESSION 2016-04-08 11:02:35.426 -----------------------------------------------
eclipse.buildId=unknown
java.version=1.8.0_25
java.vendor=Oracle Corporation
BootLoader constants: OS=win32, ARCH=x86, WS=win32, NL=it
Command-line arguments:  -os win32 -ws win32 -arch x86

!ENTRY org.jkiss.dbeaver.model 4 0 2016-04-08 11:16:19.817
!MESSAGE org.jkiss.dbeaver.model.exec.DBCException: Errore SQL [1031] [42000]: ORA-01031: privilegi insufficienti

!SUBENTRY 1 org.jkiss.dbeaver.model 4 0 2016-04-08 11:16:19.817
!MESSAGE DBCException: Errore SQL [1031] [42000]: ORA-01031: privilegi insufficienti
!STACK 0
org.jkiss.dbeaver.model.exec.DBCException: Errore SQL [1031] [42000]: ORA-01031: privilegi insufficienti

	at org.jkiss.dbeaver.ext.oracle.model.plan.OraclePlanAnalyser.explain(OraclePlanAnalyser.java:121)
	at org.jkiss.dbeaver.ext.oracle.model.OracleDataSource.planQueryExecution(OracleDataSource.java:398)
	at org.jkiss.dbeaver.ui.views.plan.PlanNodesTree$ExplainPlanService.evaluate(PlanNodesTree.java:139)
	at org.jkiss.dbeaver.ui.views.plan.PlanNodesTree$ExplainPlanService.evaluate(PlanNodesTree.java:1)
	at org.jkiss.dbeaver.ui.LoadingJob.run(LoadingJob.java:82)
	at org.jkiss.dbeaver.ui.LoadingJob.run(LoadingJob.java:69)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:99)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)
Caused by: java.sql.SQLSyntaxErrorException: ORA-01031: privilegi insufficienti

	at oracle.jdbc.driver.T4CTTIoer.processError(T4CTTIoer.java:450)
	at oracle.jdbc.driver.T4CTTIoer.processError(T4CTTIoer.java:399)
	at oracle.jdbc.driver.T4C8Oall.processError(T4C8Oall.java:1059)
	at oracle.jdbc.driver.T4CTTIfun.receive(T4CTTIfun.java:522)
	at oracle.jdbc.driver.T4CTTIfun.doRPC(T4CTTIfun.java:257)
	at oracle.jdbc.driver.T4C8Oall.doOALL(T4C8Oall.java:587)
	at oracle.jdbc.driver.T4CPreparedStatement.doOall8(T4CPreparedStatement.java:225)
	at oracle.jdbc.driver.T4CPreparedStatement.doOall8(T4CPreparedStatement.java:53)
	at oracle.jdbc.driver.T4CPreparedStatement.executeForRows(T4CPreparedStatement.java:943)
	at oracle.jdbc.driver.OracleStatement.doExecuteWithTimeout(OracleStatement.java:1150)
	at oracle.jdbc.driver.OraclePreparedStatement.executeInternal(OraclePreparedStatement.java:4798)
	at oracle.jdbc.driver.OraclePreparedStatement.execute(OraclePreparedStatement.java:4901)
	at oracle.jdbc.driver.OraclePreparedStatementWrapper.execute(OraclePreparedStatementWrapper.java:1385)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCPreparedStatementImpl.execute(JDBCPreparedStatementImpl.java:249)
	at org.jkiss.dbeaver.ext.oracle.model.plan.OraclePlanAnalyser.explain(OraclePlanAnalyser.java:80)
	... 7 more
!SUBENTRY 2 org.jkiss.dbeaver.model 4 0 2016-04-08 11:16:19.817
!MESSAGE SQLSyntaxErrorException: ORA-01031: privilegi insufficienti
!STACK 0
java.sql.SQLSyntaxErrorException: ORA-01031: privilegi insufficienti

	at oracle.jdbc.driver.T4CTTIoer.processError(T4CTTIoer.java:450)
	at oracle.jdbc.driver.T4CTTIoer.processError(T4CTTIoer.java:399)
	at oracle.jdbc.driver.T4C8Oall.processError(T4C8Oall.java:1059)
	at oracle.jdbc.driver.T4CTTIfun.receive(T4CTTIfun.java:522)
	at oracle.jdbc.driver.T4CTTIfun.doRPC(T4CTTIfun.java:257)
	at oracle.jdbc.driver.T4C8Oall.doOALL(T4C8Oall.java:587)
	at oracle.jdbc.driver.T4CPreparedStatement.doOall8(T4CPreparedStatement.java:225)
	at oracle.jdbc.driver.T4CPreparedStatement.doOall8(T4CPreparedStatement.java:53)
	at oracle.jdbc.driver.T4CPreparedStatement.executeForRows(T4CPreparedStatement.java:943)
	at oracle.jdbc.driver.OracleStatement.doExecuteWithTimeout(OracleStatement.java:1150)
	at oracle.jdbc.driver.OraclePreparedStatement.executeInternal(OraclePreparedStatement.java:4798)
	at oracle.jdbc.driver.OraclePreparedStatement.execute(OraclePreparedStatement.java:4901)
	at oracle.jdbc.driver.OraclePreparedStatementWrapper.execute(OraclePreparedStatementWrapper.java:1385)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCPreparedStatementImpl.execute(JDBCPreparedStatementImpl.java:249)
	at org.jkiss.dbeaver.ext.oracle.model.plan.OraclePlanAnalyser.explain(OraclePlanAnalyser.java:80)
	at org.jkiss.dbeaver.ext.oracle.model.OracleDataSource.planQueryExecution(OracleDataSource.java:398)
	at org.jkiss.dbeaver.ui.views.plan.PlanNodesTree$ExplainPlanService.evaluate(PlanNodesTree.java:139)
	at org.jkiss.dbeaver.ui.views.plan.PlanNodesTree$ExplainPlanService.evaluate(PlanNodesTree.java:1)
	at org.jkiss.dbeaver.ui.LoadingJob.run(LoadingJob.java:82)
	at org.jkiss.dbeaver.ui.LoadingJob.run(LoadingJob.java:69)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:99)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)


The insufficient privileges is due to the query in this screenshot (the user has no delete permission in this schema):
![image](https://cloud.githubusercontent.com/assets/8759452/14379724/c331ec90-fd7b-11e5-961b-16736481d5f0.png)

**Comment by serge-rider** [comment]
Try to change plan table. 
Preferences->Database->Drivers->Oracle, change Plan table to some existing and accessible plan table.
E.g. TOAD_PLAN_TABLE (TOAD creates it on demand).

**Comment by steromano87** [comment]
Hi Serge,

I changed the table in order to use the one created by TOAD (TOAD.TOAD_PLAN_TABLE) and it works!

Thanks a lot!

**Comment by serge-rider** [comment]
:sunglasses:
