### ISSUE TITLE
DBeaver MongoDB Update doesn't work

### ISSUE THREAD

**Issue by Davilink** [serge-rider/dbeaver#365]
I tried to update some data in a document but it failed. When i try to use the JSON view get :

>  Can't find a codec for class com.jkiss.dbeaver.ent.mongodb.data.MongoMapValue.

When i try with the grid view i get : 

> com.mongodb.WriteConcernException: Write failed with error code 16837 and error message 'cannot use the part (recipients of recipients.address) to traverse the element ({recipients: [ { address: "tew@example.com", name: "Fanny Fannie Pierce", _id: ObjectId('56be7774a67c63c41de2c528') } ]})' the problem seem to be related with the array update. I tried to edit an not array element and it worked.

**Comment by serge-rider** [comment]
Please post error stacktrace (both).
You can get it in Error Log view.

**Comment by Davilink** [comment]
com.mongodb.WriteConcernException: Write failed with error code 16837 and error message 'cannot use the part (recipients of recipients.address) to traverse the element ({recipients: [ { address: "hij@example.com", name: "Bessie Theresa Harmon", _id: ObjectId('570fa6be9aea6dd83337d634') } ]})'
	at com.mongodb.operation.BaseWriteOperation.convertBulkWriteException(BaseWriteOperation.java:239)
	at com.mongodb.operation.BaseWriteOperation.access$300(BaseWriteOperation.java:60)
	at com.mongodb.operation.BaseWriteOperation$1.call(BaseWriteOperation.java:146)
	at com.mongodb.operation.BaseWriteOperation$1.call(BaseWriteOperation.java:133)
	at com.mongodb.operation.OperationHelper.withConnectionSource(OperationHelper.java:230)
	at com.mongodb.operation.OperationHelper.withConnection(OperationHelper.java:221)
	at com.mongodb.operation.BaseWriteOperation.execute(BaseWriteOperation.java:133)
	at com.mongodb.operation.BaseWriteOperation.execute(BaseWriteOperation.java:60)
	at com.mongodb.Mongo.execute(Mongo.java:781)
	at com.mongodb.Mongo$2.execute(Mongo.java:764)
	at com.mongodb.DBCollection.executeWriteOperation(DBCollection.java:333)
	at com.mongodb.DBCollection.updateImpl(DBCollection.java:495)
	at com.mongodb.DBCollection.update(DBCollection.java:455)
	at com.mongodb.DBCollection.update(DBCollection.java:432)
	at com.mongodb.DBCollection.update(DBCollection.java:522)
	at com.jkiss.dbeaver.ent.mongodb.exec.MongoUpdateStatement.executeStatement(MongoUpdateStatement.java:64)
	at org.jkiss.dbeaver.model.impl.data.ExecuteBatchImpl.executeStatement(ExecuteBatchImpl.java:222)
	at org.jkiss.dbeaver.model.impl.data.ExecuteBatchImpl.execute(ExecuteBatchImpl.java:134)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetPersister$DataUpdaterJob.executeStatements(ResultSetPersister.java:501)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetPersister$DataUpdaterJob.run(ResultSetPersister.java:367)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:99)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)

**Comment by serge-rider** [comment]
10x for report
