### ISSUE TITLE
Can't initialize tunnel after upgrade to 3.6.5

### ISSUE THREAD

**Issue by MatyCZ** [serge-rider/dbeaver#373]
```
2016-04-15 08:02:30.235 - Connect with 'Vagrant' (mariaDB-15123f3a379-5da1515b22f58f4e)
2016-04-15 08:02:30.248 - Instantiate SSH tunnel
2016-04-15 08:02:30.253 - Connect to tunnel host
2016-04-15 08:02:30.254 - SSH INFO: Connecting to 192.168.56.101 port 22
2016-04-15 08:02:30.255 - SSH INFO: Connection established
2016-04-15 08:02:30.259 - SSH INFO: Remote version string: SSH-2.0-OpenSSH_6.6.1p1 Ubuntu-2ubuntu2.6
2016-04-15 08:02:30.259 - SSH INFO: Local version string: SSH-2.0-JSCH-0.1.53
2016-04-15 08:02:30.259 - SSH INFO: CheckCiphers: aes256-ctr,aes192-ctr,aes128-ctr,aes256-cbc,aes192-cbc,aes128-cbc,3des-ctr,arcfour,arcfour128,arcfour256
2016-04-15 08:02:30.299 - SSH INFO: aes256-ctr is not available.
2016-04-15 08:02:30.299 - SSH INFO: aes192-ctr is not available.
2016-04-15 08:02:30.299 - SSH INFO: aes128-ctr is not available.
2016-04-15 08:02:30.299 - SSH INFO: aes256-cbc is not available.
2016-04-15 08:02:30.299 - SSH INFO: aes192-cbc is not available.
2016-04-15 08:02:30.299 - SSH INFO: aes128-cbc is not available.
2016-04-15 08:02:30.300 - SSH INFO: 3des-ctr is not available.
2016-04-15 08:02:30.300 - SSH INFO: CheckKexes: diffie-hellman-group14-sha1,ecdh-sha2-nistp256,ecdh-sha2-nistp384,ecdh-sha2-nistp521
2016-04-15 08:02:30.306 - SSH INFO: diffie-hellman-group14-sha1 is not available.
2016-04-15 08:02:30.306 - SSH INFO: ecdh-sha2-nistp256 is not available.
2016-04-15 08:02:30.306 - SSH INFO: ecdh-sha2-nistp384 is not available.
2016-04-15 08:02:30.306 - SSH INFO: ecdh-sha2-nistp521 is not available.
2016-04-15 08:02:30.306 - SSH INFO: CheckSignatures: ecdsa-sha2-nistp256,ecdsa-sha2-nistp384,ecdsa-sha2-nistp521
2016-04-15 08:02:30.309 - SSH INFO: ecdsa-sha2-nistp256 is not available.
2016-04-15 08:02:30.309 - SSH INFO: ecdsa-sha2-nistp384 is not available.
2016-04-15 08:02:30.309 - SSH INFO: ecdsa-sha2-nistp521 is not available.
2016-04-15 08:02:30.309 - SSH INFO: SSH_MSG_KEXINIT sent
2016-04-15 08:02:30.310 - SSH INFO: SSH_MSG_KEXINIT received
2016-04-15 08:02:30.310 - SSH INFO: kex: server: curve25519-sha256@libssh.org,ecdh-sha2-nistp256,ecdh-sha2-nistp384,ecdh-sha2-nistp521,diffie-hellman-group-exchange-sha256,diffie-hellman-group-exchange-sha1,diffie-hellman-group14-sha1,diffie-hellman-group1-sha1
2016-04-15 08:02:30.310 - SSH INFO: kex: server: ssh-rsa,ssh-dss,ecdsa-sha2-nistp256,ssh-ed25519
2016-04-15 08:02:30.310 - SSH INFO: kex: server: aes128-ctr,aes192-ctr,aes256-ctr,arcfour256,arcfour128,aes128-gcm@openssh.com,aes256-gcm@openssh.com,chacha20-poly1305@openssh.com,aes128-cbc,3des-cbc,blowfish-cbc,cast128-cbc,aes192-cbc,aes256-cbc,arcfour,rijndael-cbc@lysator.liu.se
2016-04-15 08:02:30.310 - SSH INFO: kex: server: aes128-ctr,aes192-ctr,aes256-ctr,arcfour256,arcfour128,aes128-gcm@openssh.com,aes256-gcm@openssh.com,chacha20-poly1305@openssh.com,aes128-cbc,3des-cbc,blowfish-cbc,cast128-cbc,aes192-cbc,aes256-cbc,arcfour,rijndael-cbc@lysator.liu.se
2016-04-15 08:02:30.310 - SSH INFO: kex: server: hmac-md5-etm@openssh.com,hmac-sha1-etm@openssh.com,umac-64-etm@openssh.com,umac-128-etm@openssh.com,hmac-sha2-256-etm@openssh.com,hmac-sha2-512-etm@openssh.com,hmac-ripemd160-etm@openssh.com,hmac-sha1-96-etm@openssh.com,hmac-md5-96-etm@openssh.com,hmac-md5,hmac-sha1,umac-64@openssh.com,umac-128@openssh.com,hmac-sha2-256,hmac-sha2-512,hmac-ripemd160,hmac-ripemd160@openssh.com,hmac-sha1-96,hmac-md5-96
2016-04-15 08:02:30.311 - SSH INFO: kex: server: hmac-md5-etm@openssh.com,hmac-sha1-etm@openssh.com,umac-64-etm@openssh.com,umac-128-etm@openssh.com,hmac-sha2-256-etm@openssh.com,hmac-sha2-512-etm@openssh.com,hmac-ripemd160-etm@openssh.com,hmac-sha1-96-etm@openssh.com,hmac-md5-96-etm@openssh.com,hmac-md5,hmac-sha1,umac-64@openssh.com,umac-128@openssh.com,hmac-sha2-256,hmac-sha2-512,hmac-ripemd160,hmac-ripemd160@openssh.com,hmac-sha1-96,hmac-md5-96
2016-04-15 08:02:30.311 - SSH INFO: kex: server: none,zlib@openssh.com
2016-04-15 08:02:30.311 - SSH INFO: kex: server: none,zlib@openssh.com
2016-04-15 08:02:30.311 - SSH INFO: kex: server: 
2016-04-15 08:02:30.311 - SSH INFO: kex: server: 
2016-04-15 08:02:30.311 - SSH INFO: kex: client: diffie-hellman-group-exchange-sha256,diffie-hellman-group-exchange-sha1,diffie-hellman-group1-sha1
2016-04-15 08:02:30.311 - SSH INFO: kex: client: ssh-rsa,ssh-dss
2016-04-15 08:02:30.311 - SSH INFO: kex: client: 3des-cbc,blowfish-cbc
2016-04-15 08:02:30.312 - SSH INFO: kex: client: 3des-cbc,blowfish-cbc
2016-04-15 08:02:30.312 - SSH INFO: kex: client: hmac-md5,hmac-sha1,hmac-sha2-256,hmac-sha1-96,hmac-md5-96
2016-04-15 08:02:30.312 - SSH INFO: kex: client: hmac-md5,hmac-sha1,hmac-sha2-256,hmac-sha1-96,hmac-md5-96
2016-04-15 08:02:30.312 - SSH INFO: kex: client: none
2016-04-15 08:02:30.312 - SSH INFO: kex: client: none
2016-04-15 08:02:30.312 - SSH INFO: kex: client: 
2016-04-15 08:02:30.312 - SSH INFO: kex: client: 
2016-04-15 08:02:30.312 - SSH INFO: kex: server->client 3des-cbc hmac-md5 none
2016-04-15 08:02:30.313 - SSH INFO: kex: client->server 3des-cbc hmac-md5 none
2016-04-15 08:02:30.314 - SSH INFO: Disconnecting from 192.168.56.101 port 22
2016-04-15 08:02:30.321 - Connection failed (mariaDB-15123f3a379-5da1515b22f58f4e)
2016-04-15 08:02:30.329 - org.jkiss.dbeaver.model.exec.DBCException: Can't initialize tunnel
org.jkiss.dbeaver.model.exec.DBCException: Can't initialize tunnel
	at org.jkiss.dbeaver.registry.DataSourceDescriptor.connect(DataSourceDescriptor.java:603)
	at org.jkiss.dbeaver.runtime.jobs.ConnectJob.run(ConnectJob.java:71)
	at org.jkiss.dbeaver.runtime.jobs.ConnectJob.runSync(ConnectJob.java:101)
	at org.jkiss.dbeaver.ui.actions.datasource.DataSourceHandler.connectToDataSource(DataSourceHandler.java:129)
	at org.jkiss.dbeaver.registry.DataSourceDescriptor.initConnection(DataSourceDescriptor.java:566)
	at org.jkiss.dbeaver.model.navigator.DBNDataSource.initializeNode(DBNDataSource.java:123)
	at org.jkiss.dbeaver.model.navigator.DBNDatabaseNode.getChildren(DBNDatabaseNode.java:190)
	at org.jkiss.dbeaver.model.navigator.DBNDatabaseNode.getChildren(DBNDatabaseNode.java:1)
	at org.jkiss.dbeaver.ui.navigator.database.load.TreeLoadService.evaluate(TreeLoadService.java:57)
	at org.jkiss.dbeaver.ui.navigator.database.load.TreeLoadService.evaluate(TreeLoadService.java:1)
	at org.jkiss.dbeaver.ui.LoadingJob.run(LoadingJob.java:82)
	at org.jkiss.dbeaver.ui.LoadingJob.run(LoadingJob.java:69)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:99)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)
Caused by: org.jkiss.dbeaver.DBException: Cannot establish tunnel
	at org.jkiss.dbeaver.model.impl.net.SSHTunnelImpl.initializeTunnel(SSHTunnelImpl.java:144)
	at org.jkiss.dbeaver.registry.DataSourceDescriptor.connect(DataSourceDescriptor.java:601)
	... 13 more
Caused by: com.jcraft.jsch.JSchException: Session.connect: java.security.NoSuchAlgorithmException: DH KeyPairGenerator not available
	at com.jcraft.jsch.Session.connect(Session.java:558)
	at org.jkiss.dbeaver.model.impl.net.SSHTunnelImpl.initializeTunnel(SSHTunnelImpl.java:133)
	... 14 more
```

**Comment by MatyCZ** [comment]
DBeaver 3.6.5 with JRE from 3.6.4 (1.7.0) works fine.

**Comment by serge-rider** [comment]
Yep, problem is in JRE included in Windows installer.
I just repackaged 3.6.5 version - can you confirm that now it works ok?

**Comment by MatyCZ** [comment]
Yes, it works. Thanks.
