### ISSUE TITLE
PostgreSQL - support function-based indexes metadata

### ISSUE THREAD

**Issue by ced75** [serge-rider/dbeaver#411]
After a double-clic on a table in the database navigator, if I clic on the DDL tab, I get the following error message: "java.lang.NullPointerException:"
No more details in the error message. The DDL then looks like this:
/* ERROR WHILE READING SOURCE:

null
*/

Configuration:
- DBeaver 3.6.6
- PostgreSQL 9.5.2

**Comment by serge-rider** [comment]
Please post error stacktrace (you can get it in Error Log view)

**Comment by ced75** [comment]
java.lang.NullPointerException
	at org.jkiss.dbeaver.model.impl.sql.edit.struct.SQLIndexManager.makeObjectCreateActions(SQLIndexManager.java:68)
	at org.jkiss.dbeaver.model.impl.sql.edit.SQLObjectEditor$ObjectCreateCommand.getPersistActions(SQLObjectEditor.java:252)
	at org.jkiss.dbeaver.model.impl.sql.edit.struct.SQLTableManager.makeStructObjectCreateActions(SQLTableManager.java:97)
	at org.jkiss.dbeaver.model.impl.sql.edit.SQLStructEditor$StructCreateCommand.getPersistActions(SQLStructEditor.java:118)
	at org.jkiss.dbeaver.model.impl.sql.edit.struct.SQLTableManager.getTableDDL(SQLTableManager.java:199)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCUtils.generateTableDDL(JDBCUtils.java:745)
	at org.jkiss.dbeaver.ext.postgresql.model.PostgreTable.getObjectDefinitionText(PostgreTable.java:114)
	at org.jkiss.dbeaver.ui.editors.sql.SQLSourceViewer.getSourceText(SQLSourceViewer.java:34)
	at org.jkiss.dbeaver.ui.editors.sql.SQLEditorNested$ObjectDocumentProvider$1.run(SQLEditorNested.java:230)
	at org.jkiss.dbeaver.runtime.TasksJob.run(TasksJob.java:61)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:99)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)


The problem seems to occur partially: some tables are not affected.

**Comment by ced75** [comment]
I think the problem is due to an index issue.
On the table with the problem, there is a btree index without any column.

**Comment by ced75** [comment]
OK, I think I know why. It is a particular index declared with a function call (which is possible with PostgreSQL).
Here is the DDL of the index:
CREATE INDEX s5s_am_idx0
  ON inv_exp_am.s5strate
  USING btree
  (inv_exp_am.r5_dctoblock(substr(stratif::text, 3, 2)::character(2), substr(stratif::text, 5, 1)::character(1)) COLLATE pg_catalog."default");

In its definition, it refers to r5_dctoblock function. That is why there is no column in the index view in DBeaver and why a null pointer exception is raiser, isn'it?

**Comment by serge-rider** [comment]
Thanks for details.
