### ISSUE TITLE
Grid editing sometimes fails with Invalid thread access

### ISSUE THREAD

**Issue by ihabunek** [serge-rider/dbeaver#434]
In some cases editing data in the grid fails with "Invalid thread access" exception. In some other cases it works as expected.

This seems to fail consistently: create a small table, add a row, try to edit it in the grid. When i save i get the exception.

![image](https://cloud.githubusercontent.com/assets/482138/15176085/b9f6c31e-1769-11e6-9339-d07c3ad0a83c.png)

Running 3.6.7 on Ubuntu 16.04 with openjdk version 1.8.0_91.

From the error log:
```
!ENTRY org.jkiss.dbeaver.model 4 0 2016-05-11 11:12:49.479
!MESSAGE Invalid thread access
!STACK 0
org.eclipse.swt.SWTException: Invalid thread access
	at org.eclipse.swt.SWT.error(SWT.java:4491)
	at org.eclipse.swt.SWT.error(SWT.java:4406)
	at org.eclipse.swt.SWT.error(SWT.java:4377)
	at org.eclipse.swt.widgets.Widget.error(Widget.java:482)
	at org.eclipse.swt.widgets.Widget.checkWidget(Widget.java:420)
	at org.eclipse.swt.widgets.Control.getShell(Control.java:2924)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetViewer.applyChanges(ResultSetViewer.java:1835)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetViewer.applyChanges(ResultSetViewer.java:1804)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetViewer.doSave(ResultSetViewer.java:942)
	at org.jkiss.dbeaver.ui.editors.sql.SQLEditor$SaveJob.run(SQLEditor.java:1765)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:99)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)
```

**Comment by ihabunek** [comment]
In a real-world example with a relatively large table, if I `select *` from a table then grid edit works, but if i select only some of the fields, then it does not and i get the exception.

**Comment by serge-rider** [comment]
This error happens when DBeaver tries to show error dialog.
