### ISSUE TITLE
script text editor using query parameters error occured

### ISSUE THREAD

**Issue by RichieHsu** [serge-rider/dbeaver#436]
I encounter a  problem when executing a single query statement with parameter.
It always get error "**SQL 错误 [102] [S0001]: 接近 '?' **”.I have tried Informix Database and SQL Server none of them works. Don't know where is going wrong.

example statment as below:
![v3 6 7](https://cloud.githubusercontent.com/assets/12066066/15201540/8e78a714-1824-11e6-81f9-9b5db00c65e2.png)

the same statment works fine on v3.4.1:
![v3 4 1](https://cloud.githubusercontent.com/assets/12066066/15201541/9291a242-1824-11e6-9f5d-5ce9784e5d5b.png)

Running 3.6.7 on Windows 7 SP1 Home Edition with java version 7.7.0_79
Database: SQL Server
From the error log:

> !ENTRY org.jkiss.dbeaver.model 4 0 2016-05-12 09:28:24.397
!MESSAGE org.jkiss.dbeaver.model.exec.DBCException: SQL 错误 [102] [S0001]: 接近 '?' 之處的語法不正確。
!SUBENTRY 1 org.jkiss.dbeaver.model 4 0 2016-05-12 09:28:24.397
!MESSAGE DBCException: SQL 错误 [102] [S0001]: 接近 '?' 之處的語法不正確。
!STACK 0
org.jkiss.dbeaver.model.exec.DBCException: SQL 错误 [102] [S0001]: 接近 '?' 之處的語法不正確。
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCStatementImpl.executeStatement(JDBCStatementImpl.java:141)
	at org.jkiss.dbeaver.runtime.sql.SQLQueryJob.executeSingleQuery(SQLQueryJob.java:341)
	at org.jkiss.dbeaver.runtime.sql.SQLQueryJob.extractData(SQLQueryJob.java:712)
	at org.jkiss.dbeaver.ui.editors.sql.SQLEditor$QueryResultsContainer.readData(SQLEditor.java:1413)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetDataPumpJob.run(ResultSetDataPumpJob.java:137)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:99)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)
Caused by: com.microsoft.sqlserver.jdbc.SQLServerException: 接近 '?' 之處的語法不正確。
	at com.microsoft.sqlserver.jdbc.SQLServerException.makeFromDatabaseError(SQLServerException.java:216)
	at com.microsoft.sqlserver.jdbc.SQLServerStatement.getNextResult(SQLServerStatement.java:1515)
	at com.microsoft.sqlserver.jdbc.SQLServerStatement.doExecuteStatement(SQLServerStatement.java:792)
	at com.microsoft.sqlserver.jdbc.SQLServerStatement$StmtExecCmd.doExecute(SQLServerStatement.java:689)
	at com.microsoft.sqlserver.jdbc.TDSCommand.execute(IOBuffer.java:5696)
	at com.microsoft.sqlserver.jdbc.SQLServerConnection.executeCommand(SQLServerConnection.java:1715)
	at com.microsoft.sqlserver.jdbc.SQLServerStatement.executeCommand(SQLServerStatement.java:180)
	at com.microsoft.sqlserver.jdbc.SQLServerStatement.executeStatement(SQLServerStatement.java:155)
	at com.microsoft.sqlserver.jdbc.SQLServerStatement.execute(SQLServerStatement.java:662)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCStatementImpl.execute(JDBCStatementImpl.java:345)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCStatementImpl.executeStatement(JDBCStatementImpl.java:138)
	... 6 more

**Comment by serge-rider** [comment]
Anonymous parameters (?) were disabled by default (in some 3.5.x version).
You can:
- Enable anonymous parameters  (on Preferences->General->Editors->SQL Editor->SQL Processing)
- Use named parameters (like `:param`)

**Comment by RichieHsu** [comment]
It works very well. Thank you.
