### ISSUE TITLE
[Hsqldb] Empty values after 400+ rows 

### ISSUE THREAD

**Issue by mrkeuz** [serge-rider/dbeaver#459]
### Steps
* Double click on table 
* Open Data tab
* Scroll 400+ rows 
* All cell's in each column are '[Null]'  istead values

![screenshot](https://cloud.githubusercontent.com/assets/6247921/15380316/947145ce-1d86-11e6-9e93-4345ca5e304f.png)

Note: With other driver (I tried PG) all ok

### Version:
* DBeaver 3.6.7 (devel:96d6a25a8198d7192fbe4650f4d6ed5f35d17da2)
* Mac OS 10.9.5
* Driver: org.hsqldb:hsqldb-2.3.4

### Error 
Warning: org.jkiss.dbeaver.model
Can't read column '\<column_name\>' value

java.lang.ArrayIndexOutOfBoundsException

**Comment by carlosjrcabello** [comment]
It's sounds as table scroll refresh that isn't triggered (I think).

**Comment by serge-rider** [comment]
Please post full error stacktrace

**Comment by mrkeuz** [comment]
In logs many exceptions like:

```
 java.lang.ArrayIndexOutOfBoundsException: 584
	at org.hsqldb.navigator.RowSetNavigatorClient.getCurrent(Unknown Source)
	at org.hsqldb.jdbc.JDBCResultSet.getCurrent(Unknown Source)
	at org.hsqldb.jdbc.JDBCResultSet.getColumnInType(Unknown Source)
	at org.hsqldb.jdbc.JDBCResultSet.getString(Unknown Source)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCResultSetImpl.getString(JDBCResultSetImpl.java:340)
	at org.jkiss.dbeaver.model.impl.jdbc.data.handlers.JDBCStringValueHandler.fetchColumnValue(JDBCStringValueHandler.java:48)
	at org.jkiss.dbeaver.model.impl.jdbc.data.handlers.JDBCAbstractValueHandler.fetchValueObject(JDBCAbstractValueHandler.java:50)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetDataReceiver.fetchRow(ResultSetDataReceiver.java:99)
	at org.jkiss.dbeaver.model.impl.jdbc.struct.JDBCTable.readData(JDBCTable.java:208)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetDataPumpJob.run(ResultSetDataPumpJob.java:136)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:103)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)
```

**Comment by serge-rider** [comment]
Looks like a bug in HSQLDB driver.
But I still can't reproduce that (I don't have big enough test database so I'm checking it on system tables)..

**Comment by mrkeuz** [comment]
ok. It's not stopped bug for me. Just want to improve DBeaver.

And just FYI. Stacktrace with highlighted line numbers for  *org.hsqldb* sources.
Driver verrsion (org.hsqldb:hsqldb-2.3.4):
```
java.lang.ArrayIndexOutOfBoundsException: 784
	at org.hsqldb.navigator.RowSetNavigatorClient.getCurrent(RowSetNavigatorClient.java:119)
	at org.hsqldb.jdbc.JDBCResultSet.getCurrent(JDBCResultSet.java:7178)
	at org.hsqldb.jdbc.JDBCResultSet.getColumnInType(JDBCResultSet.java:7248)
	at org.hsqldb.jdbc.JDBCResultSet.getObject(JDBCResultSet.java:1692)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCResultSetImpl.getObject(JDBCResultSetImpl.java:629)
	at org.jkiss.dbeaver.model.impl.jdbc.data.handlers.JDBCNumberValueHandler.fetchColumnValue(JDBCNumberValueHandler.java:123)
	at org.jkiss.dbeaver.model.impl.jdbc.data.handlers.JDBCAbstractValueHandler.fetchValueObject(JDBCAbstractValueHandler.java:50)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetDataReceiver.fetchRow(ResultSetDataReceiver.java:99)
	at org.jkiss.dbeaver.model.impl.jdbc.struct.JDBCTable.readData(JDBCTable.java:208)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetDataPumpJob.run(ResultSetDataPumpJob.java:136)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:103)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)
```

**Comment by mrkeuz** [comment]
Also little note. This bug reproduces only from navigator browser. 
All work fine from plain sql editor.

**Comment by serge-rider** [comment]
Can you reproduce it with INFORMATION_SCHEMA.COLUMNS table scrolling?
What happens if you click on "Fetch all rows" (ctrl+alt+end)?

**Comment by mrkeuz** [comment]
1. Yes, I can reproduces with INFORMATION_SCHEMA.COLUMNS 
2. When I click 'fetch all' previous fetched values still empty. But all next rows fetched correct :)

![2016-05-19 17 22 36](https://cloud.githubusercontent.com/assets/6247921/15396808/be7d08e0-1dee-11e6-99aa-f75a3a725c1a.png)

**Comment by mrkeuz** [comment]
@serge-rider Here is script with create big enough table for you test. Just in case.

[issue_459.sql.zip](https://github.com/serge-rider/dbeaver/files/272757/issue_459.sql.zip)

**Comment by serge-rider** [comment]
Well, I reproduced that. It is definitely a HSQLDB driver bug, but I'll try to find some workaround..

**Comment by serge-rider** [comment]
Fixed. HSQL driver incorrectly evaluates fetch size with scrolling.
Thanks for report.

**Comment by mrkeuz** [comment]
Worked! Many thanks for all you efforts! DBeaver is great!
