### ISSUE TITLE
Intersystems Caché - GlobalCharacterStream

### ISSUE THREAD

**Issue by douglasdtc** [serge-rider/dbeaver#469]
I'm running DBeaver Enterprise Edition x64 v3.6.7. I'm trying to read data from a table that contains GlobalCharacterStream fields. Everything, except the streams, are shown. I'm using the default JDBC driver that comes with DBeaver, however, I already tried using the JDBC driver that comes with Caché installation with no success.

The same JDBC driver works for streams on DBVisualizer.

P.S.: I'm using DBeaver since v3.0 and it never worked.

**Comment by serge-rider** [comment]
Are there any errors/warnings in the Error Log?

**Comment by douglasdtc** [comment]
Yes, it shows:

`eclipse.buildId=unknown
java.version=1.8.0_77
java.vendor=Oracle Corporation
BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=en
Command-line arguments:  -os win32 -ws win32 -arch x86_64

org.jkiss.dbeaver.model
Warning
Tue May 24 15:33:25 BRT 2016
Unsupported value type: com.intersys.jdbc.CacheInputStream

org.jkiss.dbeaver.model.exec.DBCException: Unsupported value type: com.intersys.jdbc.CacheInputStream
	at org.jkiss.dbeaver.model.impl.jdbc.data.handlers.JDBCContentValueHandler.getValueFromObject(JDBCContentValueHandler.java:192)
	at org.jkiss.dbeaver.model.impl.jdbc.data.handlers.JDBCContentValueHandler.fetchColumnValue(JDBCContentValueHandler.java:97)
	at org.jkiss.dbeaver.model.impl.jdbc.data.handlers.JDBCContentValueHandler.fetchColumnValue(JDBCContentValueHandler.java:1)
	at org.jkiss.dbeaver.model.impl.jdbc.data.handlers.JDBCAbstractValueHandler.fetchValueObject(JDBCAbstractValueHandler.java:50)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetDataReceiver.fetchRow(ResultSetDataReceiver.java:99)
	at org.jkiss.dbeaver.runtime.sql.SQLQueryJob.fetchQueryData(SQLQueryJob.java:622)
	at org.jkiss.dbeaver.runtime.sql.SQLQueryJob.executeSingleQuery(SQLQueryJob.java:354)
	at org.jkiss.dbeaver.runtime.sql.SQLQueryJob.extractData(SQLQueryJob.java:716)
	at org.jkiss.dbeaver.ui.editors.sql.SQLEditor$QueryResultsContainer.readData(SQLEditor.java:1490)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetDataPumpJob.run(ResultSetDataPumpJob.java:139)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:103)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)`

for every Stream it tries to read. Thank you.

**Comment by serge-rider** [comment]
That's more clear now, thanks for details.
I've just pushed the fix. Can you test ea version? (http://dbeaver.jkiss.org/files/ea/)

**Comment by douglasdtc** [comment]
Just tested the EA version and it works flawlessly now (using the JDBC driver provided by DBeaver). Thank you for the fast support.
