### ISSUE TITLE
select row count   from partition table

### ISSUE THREAD

**Issue by yhykoc** [serge-rider/dbeaver#486]
SELECT * FROM TMP_TABLE PARTITION (SYS_P117) and ctrl+Alt+C

org.jkiss.dbeaver.DBException: Can't transform query to SELECT count(*)
	at org.jkiss.dbeaver.ui.editors.sql.handlers.ExecuteStatementCountHandler.transformQuery(ExecuteStatementCountHandler.java:77)
	at org.jkiss.dbeaver.ui.editors.sql.SQLEditor.processSQL(SQLEditor.java:748)
	at org.jkiss.dbeaver.ui.editors.sql.handlers.ExecuteStatementCountHandler.execute(ExecuteStatementCountHandler.java:54)
	at org.eclipse.ui.internal.handlers.HandlerProxy.execute(HandlerProxy.java:295)
	at org.eclipse.ui.internal.handlers.E4HandlerProxy.execute(E4HandlerProxy.java:90)
	at sun.reflect.GeneratedMethodAccessor60.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.eclipse.e4.core.internal.di.MethodRequestor.execute(MethodRequestor.java:56)
	at org.eclipse.e4.core.internal.di.InjectorImpl.invokeUsingClass(InjectorImpl.java:252)
	at org.eclipse.e4.core.internal.di.InjectorImpl.invoke(InjectorImpl.java:234)
	at org.eclipse.e4.core.contexts.ContextInjectionFactory.invoke(ContextInjectionFactory.java:132)
	at org.eclipse.e4.core.commands.internal.HandlerServiceHandler.execute(HandlerServiceHandler.java:152)
	at org.eclipse.core.commands.Command.executeWithChecks(Command.java:493)
	at org.eclipse.core.commands.ParameterizedCommand.executeWithChecks(ParameterizedCommand.java:486)
	at org.eclipse.e4.core.commands.internal.HandlerServiceImpl.executeHandler(HandlerServiceImpl.java:210)
	at org.eclipse.e4.ui.workbench.renderers.swt.HandledContributionItem.executeItem(HandledContributionItem.java:799)
	at org.eclipse.e4.ui.workbench.renderers.swt.HandledContributionItem.handleWidgetSelection(HandledContributionItem.java:675)
	at org.eclipse.e4.ui.workbench.renderers.swt.HandledContributionItem.access$7(HandledContributionItem.java:659)
	at org.eclipse.e4.ui.workbench.renderers.swt.HandledContributionItem$4.handleEvent(HandledContributionItem.java:592)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:84)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4362)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1113)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4180)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3769)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$4.run(PartRenderingEngine.java:1127)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:337)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1018)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:156)
	at org.eclipse.ui.internal.Workbench$5.run(Workbench.java:694)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:337)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:606)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:150)
	at org.jkiss.dbeaver.core.application.DBeaverApplication.start(DBeaverApplication.java:130)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:380)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:235)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:669)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:608)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1515)
Caused by: net.sf.jsqlparser.JSQLParserException
	at net.sf.jsqlparser.parser.CCJSqlParserUtil.parse(CCJSqlParserUtil.java:51)
	at org.jkiss.dbeaver.ui.editors.sql.handlers.ExecuteStatementCountHandler.transformQuery(ExecuteStatementCountHandler.java:62)
	... 45 more
Caused by: net.sf.jsqlparser.parser.ParseException: Encountered " "(" "( "" at line 1, column 35.
Was expecting one of:
    <EOF> 
    "JOIN" ...
    "LEFT" ...
    "CROSS" ...
    "FULL" ...
    "WHERE" ...
    "FOR" ...
    "GROUP" ...
    "INNER" ...
    "RIGHT" ...
    "HAVING" ...
    "NATURAL" ...
    "START" ...
    "CONNECT" ...
    ";" ...
    "," ...
    "LEFT" ...
    "RIGHT" ...
    "FULL" ...
    "INNER" ...
    "NATURAL" ...
    "CROSS" ...
    "JOIN" ...
    "," ...
    "WHERE" ...
    "START" ...
    "CONNECT" ...
    "GROUP" ...
    "HAVING" ...
    "FOR" ...
    
	at net.sf.jsqlparser.parser.CCJSqlParser.generateParseException(CCJSqlParser.java:12109)
	at net.sf.jsqlparser.parser.CCJSqlParser.jj_consume_token(CCJSqlParser.java:11965)
	at net.sf.jsqlparser.parser.CCJSqlParser.Statement(CCJSqlParser.java:64)
	at net.sf.jsqlparser.parser.CCJSqlParserUtil.parse(CCJSqlParserUtil.java:49)
	... 46 more

**Comment by serge-rider** [comment]
What database?

**Comment by yhykoc** [comment]
Oracle 10g, 11g

**Comment by serge-rider** [comment]
DBeaver uses [JSqlParser](https://github.com/JSQLParser/JSqlParser) for queries transformation.
It doesn't (yet?) support Oracle-style partitioned tables queries.
I'm afraid there is nothing I can do. Maybe it makes sense to write a feature request to JSqlParser project..

**Comment by yhykoc** [comment]
Ok minor problem but i don't understand. It support Oracle-style partitioned tables queries with select count(*) in Dbeaver.

![dbeaver_partition](https://cloud.githubusercontent.com/assets/16175023/15577429/3372fd5a-2365-11e6-87e2-f6b18dd07df3.JPG)

When executing Ctrl+Alt-C, transformation from "select * " or  "select columns"   to "select count( * )" or "select count(columns)" ,Is not it enough as a workaround?

![dbeaver_partition1](https://cloud.githubusercontent.com/assets/16175023/15578652/fd1b8ce0-2369-11e6-9e58-5264f1d35dc0.JPG)

![dbeaver_partition3](https://cloud.githubusercontent.com/assets/16175023/15577842/d21decca-2366-11e6-8103-77375a111edd.JPG)
