### ISSUE TITLE
Chinese characters problem

### ISSUE THREAD

**Issue by opxdo** [serge-rider/dbeaver#499]
OS: WIN10

JAVA: 
Java(TM) SE Runtime Environment (build 1.8.0_91-b14)
Java HotSpot(TM) 64-Bit Server VM (build 25.91-b14, mixed mode)

DBeaver: dbeaver-ce-3.6.8-win32.win32.x86_64.zip & dbeaver-ce-3.6.9-win32.win32.x86_64.zip

1. Input chinese characters and save,  seems ok
![1](https://cloud.githubusercontent.com/assets/19682814/15702363/42dc5820-2812-11e6-8510-61fcf8034f97.jpg)

2. Close DBeaver

3. Reopen DBeaver, not ok
![3](https://cloud.githubusercontent.com/assets/19682814/15702378/5424e912-2812-11e6-8ebb-4467293b6dcf.jpg)

**Comment by serge-rider** [comment]
Can't reproduce that.
A couple of questions:
1. This script was created by DBeaver or it is an external file (linked to scripts folder or opened with Open command).
2. When you are in SQL editor press Alt+Enter. What encoding is set in "Text file encoding" field on the Resource tab?

**Comment by opxdo** [comment]
1. Script create by DBeaver

2. I do some test

**DBeaver  3.6.7** , new install, all properties default, 
1.Create a new SQL file
2.Input Chinese characters
3.Save
4.Close SQL file
5.Reopen SQL file
**everything is ok.**

select "Scripts" folder, press Alt+Enter, 
![7](https://cloud.githubusercontent.com/assets/19682814/15705823/6daa6e46-2823-11e6-9d51-8250b364d24b.jpg)

select "Script" sql file, press Alt+Enter,
![7f](https://cloud.githubusercontent.com/assets/19682814/15705877/9d5bfbf0-2823-11e6-9a5d-f9e495a12f4c.jpg)


**DBeaver  3.6.8 & DBeaver  3.6.9**  new install, all properties default,
select "SQL Scripts" folder, press Alt+Enter, 
select "Script" SQL file, press Alt+Enter
It is same as version 3.6.7

1.Create a new SQL file
2.Input Chinese characters
3.Save, seems ok
4.Close SQL file
**5.Reopen SQL file, it is not ok. 
6. Change "Text file encoding" of "Script" SQL file to "GBK" , it is ok now**

or
**1. Change "Text file encoding" of "SQL Scripts" folder  to "utf-8",**
2. Create a new SQL file
3. Input Chinese characters
4. Save
5. Close SQL file
6. Reopen SQL file
everything is ok

**Comment by serge-rider** [comment]
Please test EA version (http://dbeaver.jkiss.org/files/ea/). 
It is possible that this issue was fixed along with #502

**Comment by opxdo** [comment]
EA version does not work

**Comment by serge-rider** [comment]
I have reproduced and fixed that. 
Please check in the new EA version.

**Comment by opxdo** [comment]
I download from   http://dbeaver.jkiss.org/files/ea/dbeaver-ee-3.6.9-win32.win32.x86_64.zip
Can't start . 



!SESSION 2016-06-02 18:14:01.134 -----------------------------------------------
eclipse.buildId=unknown
java.version=1.8.0_91
java.vendor=Oracle Corporation
BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=zh_CN
Command-line arguments:  -os win32 -ws win32 -arch x86_64 -data d:\test2

!ENTRY org.eclipse.ui 4 0 2016-06-02 18:14:03.712
!MESSAGE Unhandled event loop exception
!STACK 0
java.lang.IllegalArgumentException: Argument cannot be null
	at org.eclipse.swt.SWT.error(SWT.java:4472)
	at org.eclipse.swt.SWT.error(SWT.java:4406)
	at org.eclipse.swt.SWT.error(SWT.java:4377)
	at org.eclipse.swt.graphics.GC.setForeground(GC.java:4431)
	at org.jkiss.dbeaver.core.application.DBeaverSplashHandler$1.paintControl(DBeaverSplashHandler.java:114)
	at org.eclipse.swt.widgets.TypedListener.handleEvent(TypedListener.java:230)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:84)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4362)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1113)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1137)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1122)
	at org.eclipse.swt.widgets.Composite.WM_PAINT(Composite.java:1613)
	at org.eclipse.swt.widgets.Control.windowProc(Control.java:4733)
	at org.eclipse.swt.widgets.Display.windowProc(Display.java:5063)
	at org.eclipse.swt.internal.win32.OS.DispatchMessageW(Native Method)
	at org.eclipse.swt.internal.win32.OS.DispatchMessage(OS.java:2549)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3767)
	at org.eclipse.ui.internal.Workbench.runUI(Workbench.java:2989)
	at org.eclipse.ui.internal.Workbench.access$9(Workbench.java:2894)
	at org.eclipse.ui.internal.Workbench$5.run(Workbench.java:685)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:337)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:606)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:150)
	at org.jkiss.dbeaver.core.application.DBeaverApplication.start(DBeaverApplication.java:160)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:380)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:235)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:669)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:608)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1515)

!ENTRY org.eclipse.ui 4 0 2016-06-02 18:14:03.712
!MESSAGE Error occurred during status handling
!STACK 0
java.lang.NullPointerException
	at org.eclipse.ui.internal.statushandlers.StatusHandlerRegistry.<init>(StatusHandlerRegistry.java:72)
	at org.eclipse.ui.internal.statushandlers.StatusHandlerRegistry.getDefault(StatusHandlerRegistry.java:91)
	at org.eclipse.ui.statushandlers.StatusManager.getStatusHandler(StatusManager.java:135)
	at org.eclipse.ui.statushandlers.StatusManager.handle(StatusManager.java:189)
	at org.eclipse.ui.statushandlers.StatusManager.handle(StatusManager.java:231)
	at org.eclipse.ui.statushandlers.StatusManager.handle(StatusManager.java:242)
	at org.eclipse.ui.application.WorkbenchAdvisor.eventLoopException(WorkbenchAdvisor.java:330)
	at org.eclipse.ui.internal.ExceptionHandler.handleException(ExceptionHandler.java:66)
	at org.eclipse.ui.internal.Workbench.runUI(Workbench.java:3089)
	at org.eclipse.ui.internal.Workbench.access$9(Workbench.java:2894)
	at org.eclipse.ui.internal.Workbench$5.run(Workbench.java:685)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:337)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:606)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:150)
	at org.jkiss.dbeaver.core.application.DBeaverApplication.start(DBeaverApplication.java:160)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:380)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:235)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:669)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:608)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1515)

**Comment by serge-rider** [comment]
Oops, sorry, that's a completely different issue.
Just fixed and rebuild EA again.

**Comment by opxdo** [comment]
Bug is gone, thanks !

**Comment by serge-rider** [comment]
Great

**Comment by kid1412621** [comment]
version 5.2.0.201809092115 meets this bug.
And I already set script encoding to the UTF-8.
