### ISSUE TITLE
Error when connecting

### ISSUE THREAD

**Issue by Jeetah** [serge-rider/dbeaver#501]
I often get this error when connecting to a Postgres DB:

SQL Error [42501]: ERROR: permission denied for relation pg_authid
  org.postgresql.util.PSQLException: ERROR: permission denied for relation pg_authid

Wrong configuration? Or bug?

**Comment by serge-rider** [comment]
Please post error stacktrace (from Error Log view).
does this error just appear in the Error Log or you see the error dialog which block UI?
This error may happen with databases with limited permissions. But it shouldn't lead to any problems, it's a kind of warning.

**Comment by serge-rider** [comment]
I've added an extra workaround for PG security errors.
Please check it in EA version (http://dbeaver.jkiss.org/files/ea/).

**Comment by Jeetah** [comment]
Stacktrace:

org.postgresql.util.PSQLException: ERROR: permission denied for relation pg_authid
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2284)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2003)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:200)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:424)
	at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:161)
	at org.postgresql.jdbc.PgPreparedStatement.execute(PgPreparedStatement.java:155)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCPreparedStatementImpl.execute(JDBCPreparedStatementImpl.java:252)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCPreparedStatementImpl.executeStatement(JDBCPreparedStatementImpl.java:196)
	at org.jkiss.dbeaver.model.impl.jdbc.cache.JDBCObjectCache.loadObjects(JDBCObjectCache.java:103)
	at org.jkiss.dbeaver.model.impl.jdbc.cache.JDBCObjectCache.getAllObjects(JDBCObjectCache.java:70)
	at org.jkiss.dbeaver.ext.postgresql.PostgreUtils.getObjectById(PostgreUtils.java:127)
	at org.jkiss.dbeaver.ext.postgresql.model.PostgreDatabase.getDBA(PostgreDatabase.java:150)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.jkiss.dbeaver.runtime.properties.ObjectPropertyDescriptor.readValue(ObjectPropertyDescriptor.java:227)
	at org.jkiss.dbeaver.runtime.properties.PropertySourceAbstract$PropertySheetLoadService.evaluate(PropertySourceAbstract.java:330)
	at org.jkiss.dbeaver.runtime.properties.PropertySourceAbstract$PropertySheetLoadService.evaluate(PropertySourceAbstract.java:1)
	at org.jkiss.dbeaver.ui.LoadingJob.run(LoadingJob.java:82)
	at org.jkiss.dbeaver.ui.LoadingJob.run(LoadingJob.java:69)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:103)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)

**Comment by conceptrat** [comment]
Looking at the [PostgreSQL documentation the "pg_authid" catalog paragraph 2](https://www.postgresql.org/docs/9.5/static/catalog-pg-authid.html)...

> Since this catalog contains passwords, it must not be publicly readable. pg_roles is a publicly readable view on pg_authid that blanks out the password field.

I think perhaps the correct way to access the roles is via the ["pg_roles" catalog](https://www.postgresql.org/docs/9.5/static/view-pg-roles.html).  I can see a [comment in the Dbeaver codebase](https://github.com/serge-rider/dbeaver/search?utf8=%E2%9C%93&q=pg_authid) about fixing this.  Perhaps this would be it?

**Comment by serge-rider** [comment]
Many PG system objects refers pg_authid (by oid), pg_roles can't substitute it.
I've just suppressed error dialog but actually this "access denied" error will happen on some databases. Generally it won't lead to any significant troubles.
