### ISSUE TITLE
cassandra export table error

### ISSUE THREAD

**Issue by evildecay** [serge-rider/dbeaver#508]
### error
```
java.lang.NullPointerException
	at com.jkiss.dbeaver.ent.cassandra.CasUtils.transformCQL(CasUtils.java:111)
	at com.jkiss.dbeaver.ent.cassandra.model.CasTableBase.readData(CasTableBase.java:127)
	at org.jkiss.dbeaver.tools.transfer.database.DatabaseTransferProducer.transferData(DatabaseTransferProducer.java:119)
	at org.jkiss.dbeaver.tools.transfer.database.DatabaseTransferProducer.transferData(DatabaseTransferProducer.java:1)
	at org.jkiss.dbeaver.tools.transfer.wizard.DataTransferJob.transferData(DataTransferJob.java:104)
	at org.jkiss.dbeaver.tools.transfer.wizard.DataTransferJob.run(DataTransferJob.java:66)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:103)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)
```

dbeaver version 3.6.x

**Comment by serge-rider** [comment]
Thanks for report
