### ISSUE TITLE
DBCException: Unsupported value type on cell edit commit

### ISSUE THREAD

**Issue by codebling** [serge-rider/dbeaver#51]
When hitting the green checkmark to commit my edit, I get this error: `org.jkiss.dbeaver.model.exec.DBCException: DBCException: Unsupported value type: bla`. 

I get the exception with any value I enter. Column DDL is `longtext COLLATE utf8mb4_unicode_ci NOT NULL,`

Let me know if I can get you any other information

**Comment by serge-rider** [comment]
What database, what driver?

**Comment by serge-rider** [comment]
Also please post full stacktrace of the error.

**Comment by codebling** [comment]
I was looking for it, though it would be in 'details' -- where do I find it?

**Comment by codebling** [comment]
Driver is mysql:mysql-connector-java:RELEASE ...Just the default MySQL JDBC driver.

**Comment by codebling** [comment]
Found it. ```!ENTRY org.jkiss.dbeaver.model 4 0 2015-11-12 20:09:20.952
!MESSAGE org.jkiss.dbeaver.model.exec.DBCException: Unsupported value type: http://192.168.2.139/
!SUBENTRY 1 org.jkiss.dbeaver.model 4 0 2015-11-12 20:09:20.952
!MESSAGE DBCException: Unsupported value type: http://192.168.2.139/
!STACK 0
org.jkiss.dbeaver.model.exec.DBCException: Unsupported value type: http://192.168.2.139/
	at org.jkiss.dbeaver.model.impl.jdbc.data.handlers.JDBCContentValueHandler.bindParameter(JDBCContentValueHandler.java:109)
	at org.jkiss.dbeaver.model.impl.jdbc.data.handlers.JDBCAbstractValueHandler.bindValueObject(JDBCAbstractValueHandler.java:65)
	at org.jkiss.dbeaver.model.impl.jdbc.struct.JDBCTable$2.bindStatement(JDBCTable.java:425)
	at org.jkiss.dbeaver.model.impl.data.ExecuteBatchImpl.execute(ExecuteBatchImpl.java:122)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetPersister$DataUpdaterJob.executeStatements(ResultSetPersister.java:463)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetPersister$DataUpdaterJob.run(ResultSetPersister.java:329)
	at org.jkiss.dbeaver.runtime.AbstractJob.run(AbstractJob.java:100)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)
```

**Comment by serge-rider** [comment]
It is a bug in column editor.
Thanks for report!
