### ISSUE TITLE
Can't Consume 64bit  ODBC System DSN using 64bit Pervasive Client

### ISSUE THREAD

**Issue by Lonniebiz** [serge-rider/dbeaver#522]
In Dbeaver 3.6.10 64bit, I'm trying to connect to a 64-bit Pervasive 11 database via a 64-bit ODBC System DSN which uses the 64-bit Pervasive 11 Client driver. The server is Windows 2008 R2.

On this setup, via PHP scripts, I have no issue consuming this 64bit ODBC System DSN. However, each time I try to connect using Dbeaver, I get the following error ([Parameter out of range](http://neartalk.com/ss/2016-06-09_004_841x406.png)):
http://neartalk.com/ss/2016-06-09_004_841x406.png

On another machine (Windows 10 64bit), the only way I've been able to connect Dbeaver to this database is by using the following:
1) The 32-bit version of Dbeaver
2) A 32-bit ODBC System DSN
3) The 32-bit Pervasive 11 client is being used by ODBC

Since PHP has no issue consuming the 64-bit ODBC with 64-bit Pervasive Client, it makes me think there's a bug in Dbeaver. I mean, the whole purpose of ODBC is to abstract away all the driver and connection details and just allow you to connect to a database by specifying the DSN.

For example, in PHP, this is all I have to do to consume this 64bit DSN connection:
odbc_connect("DSNname", "username", "password");

Yet, after over an hour of trying, I cannot get Dbeaver to consume this 64bit ODBC connection that PHP is easily consuming. At this point I'm thinking there has to be some type of bug going on here.

I'm also getting this error in the log:

!ENTRY org.eclipse.jface 4 2 2016-06-09 04:09:41.270
!MESSAGE Problems occurred when invoking code from plug-in: "org.eclipse.jface".
!STACK 0
java.lang.NullPointerException
	at java.util.TreeMap.getEntry(TreeMap.java:347)
	at java.util.TreeMap.get(TreeMap.java:278)
	at org.jkiss.dbeaver.runtime.properties.PropertySourceCustom.getPropertyValue(PropertySourceCustom.java:113)
	at org.jkiss.dbeaver.runtime.properties.PropertySourceCustom.isPropertySet(PropertySourceCustom.java:129)
	at org.jkiss.dbeaver.ui.properties.PropertyTreeViewer.isPropertyChanged(PropertyTreeViewer.java:549)
	at org.jkiss.dbeaver.ui.properties.PropertyTreeViewer.access$2(PropertyTreeViewer.java:547)
	at org.jkiss.dbeaver.ui.properties.PropertyTreeViewer$PropsLabelProvider.update(PropertyTreeViewer.java:755)
	at org.eclipse.jface.viewers.ViewerColumn.refresh(ViewerColumn.java:154)
	at org.eclipse.jface.viewers.AbstractTreeViewer.doUpdateItem(AbstractTreeViewer.java:949)
	at org.eclipse.jface.viewers.AbstractTreeViewer$UpdateItemSafeRunnable.run(AbstractTreeViewer.java:114)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.eclipse.ui.internal.JFaceUtil$1.run(JFaceUtil.java:50)
	at org.eclipse.jface.util.SafeRunnable.run(SafeRunnable.java:173)
	at org.eclipse.jface.viewers.AbstractTreeViewer.doUpdateItem(AbstractTreeViewer.java:1029)
	at org.eclipse.jface.viewers.StructuredViewer$UpdateItemSafeRunnable.run(StructuredViewer.java:473)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.eclipse.ui.internal.JFaceUtil$1.run(JFaceUtil.java:50)
	at org.eclipse.jface.util.SafeRunnable.run(SafeRunnable.java:173)
	at org.eclipse.jface.viewers.StructuredViewer.updateItem(StructuredViewer.java:2176)
	at org.eclipse.jface.viewers.AbstractTreeViewer.createTreeItem(AbstractTreeViewer.java:843)
	at org.eclipse.jface.viewers.AbstractTreeViewer$1.run(AbstractTreeViewer.java:818)
	at org.eclipse.swt.custom.BusyIndicator.showWhile(BusyIndicator.java:70)
	at org.eclipse.jface.viewers.AbstractTreeViewer.createChildren(AbstractTreeViewer.java:791)
	at org.eclipse.jface.viewers.TreeViewer.createChildren(TreeViewer.java:611)
	at org.eclipse.jface.viewers.AbstractTreeViewer.internalExpandToLevel(AbstractTreeViewer.java:1763)
	at org.eclipse.jface.viewers.AbstractTreeViewer.internalExpandToLevel(AbstractTreeViewer.java:1773)
	at org.eclipse.jface.viewers.AbstractTreeViewer.expandToLevel(AbstractTreeViewer.java:1071)
	at org.eclipse.jface.viewers.AbstractTreeViewer.expandToLevel(AbstractTreeViewer.java:1052)
	at org.eclipse.jface.viewers.AbstractTreeViewer.expandAll(AbstractTreeViewer.java:1041)
	at org.jkiss.dbeaver.ui.properties.PropertyTreeViewer.loadProperties(PropertyTreeViewer.java:209)
	at org.jkiss.dbeaver.ui.properties.PropertyTreeViewer.loadProperties(PropertyTreeViewer.java:182)
	at org.jkiss.dbeaver.ui.dialogs.connection.DriverPropertiesDialogPage.refreshDriverProperties(DriverPropertiesDialogPage.java:93)
	at org.jkiss.dbeaver.ui.dialogs.connection.DriverPropertiesDialogPage$1.run(DriverPropertiesDialogPage.java:68)
	at org.jkiss.dbeaver.core.DBeaverUI$2.runInUIThread(DBeaverUI.java:159)
	at org.jkiss.dbeaver.ui.AbstractUIJob.runInUIThread(AbstractUIJob.java:42)
	at org.eclipse.ui.progress.UIJob$1.run(UIJob.java:97)
	at org.eclipse.swt.widgets.RunnableLock.run(RunnableLock.java:35)
	at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Synchronizer.java:135)
	at org.eclipse.swt.widgets.Display.runAsyncMessages(Display.java:4155)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3772)
	at org.eclipse.jface.window.Window.runEventLoop(Window.java:827)
	at org.eclipse.jface.window.Window.open(Window.java:803)
	at org.jkiss.dbeaver.ui.actions.navigator.NavigatorHandlerObjectOpen.openEntityEditor(NavigatorHandlerObjectOpen.java:135)
	at org.jkiss.dbeaver.ui.actions.navigator.NavigatorHandlerObjectOpen.openEntityEditor(NavigatorHandlerObjectOpen.java:122)
	at org.jkiss.dbeaver.ui.actions.navigator.NavigatorHandlerObjectOpen.execute(NavigatorHandlerObjectOpen.java:88)
	at org.eclipse.ui.internal.handlers.HandlerProxy.execute(HandlerProxy.java:295)
	at org.eclipse.ui.internal.handlers.E4HandlerProxy.execute(E4HandlerProxy.java:90)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.eclipse.e4.core.internal.di.MethodRequestor.execute(MethodRequestor.java:56)
	at org.eclipse.e4.core.internal.di.InjectorImpl.invokeUsingClass(InjectorImpl.java:252)
	at org.eclipse.e4.core.internal.di.InjectorImpl.invoke(InjectorImpl.java:234)
	at org.eclipse.e4.core.contexts.ContextInjectionFactory.invoke(ContextInjectionFactory.java:132)
	at org.eclipse.e4.core.commands.internal.HandlerServiceHandler.execute(HandlerServiceHandler.java:152)
	at org.eclipse.core.commands.Command.executeWithChecks(Command.java:493)
	at org.eclipse.core.commands.ParameterizedCommand.executeWithChecks(ParameterizedCommand.java:486)
	at org.eclipse.e4.core.commands.internal.HandlerServiceImpl.executeHandler(HandlerServiceImpl.java:210)
	at org.eclipse.e4.ui.workbench.renderers.swt.HandledContributionItem.executeItem(HandledContributionItem.java:799)
	at org.eclipse.e4.ui.workbench.renderers.swt.HandledContributionItem.handleWidgetSelection(HandledContributionItem.java:675)
	at org.eclipse.e4.ui.workbench.renderers.swt.HandledContributionItem.access$7(HandledContributionItem.java:659)
	at org.eclipse.e4.ui.workbench.renderers.swt.HandledContributionItem$4.handleEvent(HandledContributionItem.java:592)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:84)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4362)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1113)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4180)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3769)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$4.run(PartRenderingEngine.java:1127)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:337)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1018)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:156)
	at org.eclipse.ui.internal.Workbench$5.run(Workbench.java:694)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:337)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:606)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:150)
	at org.jkiss.dbeaver.core.application.DBeaverApplication.start(DBeaverApplication.java:189)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:380)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:235)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:669)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:608)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1515)

**Comment by serge-rider** [comment]
This might be a bug in DBeaver. Or this might be a bug in JDBC-ODBC bridge driver.

Please check debug log (https://github.com/serge-rider/dbeaver/wiki/Log-files) for error related to the connection process.

(Thanks for error log, I'll fix this issue but it has nothing to do with ODBC connection, just a minor UI issue).

**Comment by Lonniebiz** [comment]
As a user, I can only report things from the perceptive of what I appear to be blocked from accomplishing.

I'll test this again next version-upgrade (sooner if you request).

**Comment by serge-rider** [comment]
Could you check debug log? I can't do anything without any additional information.

**Comment by Lonniebiz** [comment]
I could only find one log file in the .meta folder:
[log.zip](https://github.com/serge-rider/dbeaver/files/308044/log.zip)

**Comment by serge-rider** [comment]
That's odd. There should be dbeaver-debug.log as well..

**Comment by Lonniebiz** [comment]
Well, I wish I could send that. I just looked again. I really don't see it:
http://neartalk.com/ss/2016-06-10_001_1123x519.png

**Comment by Lonniebiz** [comment]
The other machine I talked about (the Windows 10 machine), it has a debug-log that I've attached. This is the machine that I ultimately got it working using 32-bit-everything (except the OS). Maybe it will help.

[dbeaver-debug.log.zip](https://github.com/serge-rider/dbeaver/files/309513/dbeaver-debug.log.zip)

**Comment by serge-rider** [comment]
Debug log makes sense, thanks. But it doesn't contain the error you described in the beginning.

By the way, why are you trying to use ODBC driver + bridge? Pervasive has JDBC driver, which is much more native for DBeaver.
Just tested it and at least it doesn't have connectivity problems.

**Comment by strider72** [comment]
I have the exact same issue.  This is especially an issue now that you've discontinued the 32-bit version of DBeaver.  32-bit DBeaver works with a 32-bit ODBC connection.  64-bit DBeaver refuses to work with 64-bit ODBC connection with error: `[PSQL][ODBC Client Interface]Parameter number out of range.`

Here is my dbeaver-debug.log :

```
2019-03-28 18:01:31.875 - DBeaver 6.0.1.201903251040 is starting
2019-03-28 18:01:31.875 - OS: Windows 10 10.0 (amd64)
2019-03-28 18:01:31.891 - Java version: 1.8.0_77 by Oracle Corporation (64bit)
2019-03-28 18:01:31.891 - Install path: 'file:/C:/Program Files/DBeaver/'
2019-03-28 18:01:31.891 - Instance path: 'file:/C:/Users/srider/.dbeaver4/'
2019-03-28 18:01:31.891 - Memory available 61Mb/910Mb
2019-03-28 18:01:31.906 - Starting RMI server at 20488
2019-03-28 18:01:31.969 - Run workbench
2019-03-28 18:01:31.969 - > Start org.eclipse.e4.ui.workbench.swt [0.14.400.v20181022-1348]
2019-03-28 18:01:31.984 - > Start org.eclipse.e4.core.services [2.1.300.v20180930-0910]
2019-03-28 18:01:31.984 - > Start org.eclipse.e4.core.contexts [1.7.100.v20180817-1215]
2019-03-28 18:01:31.984 - > Start org.eclipse.e4.ui.services [1.3.300.v20180920-1522]
2019-03-28 18:01:32.031 - > Start org.eclipse.e4.ui.di [1.2.400.v20180920-1522]
2019-03-28 18:01:32.073 - > Start com.ibm.icu.base [58.2.0.v20170418-1837]
2019-03-28 18:01:32.074 - > Start org.eclipse.emf.common [2.15.0.v20180914-1817]
2019-03-28 18:01:32.089 - > Start org.eclipse.emf.ecore [2.16.0.v20181124-0637]
2019-03-28 18:01:32.167 - > Start org.eclipse.emf.ecore.xmi [2.15.0.v20180706-1146]
2019-03-28 18:01:32.308 - > Start org.eclipse.core.filesystem [1.7.200.v20180828-0158]
2019-03-28 18:01:32.355 - > Start org.eclipse.core.resources [3.13.200.v20181121-1020]
2019-03-28 18:01:32.480 - > Start org.eclipse.e4.ui.workbench.addons.swt [1.3.300.v20181102-1042]
2019-03-28 18:01:32.496 - > Start org.eclipse.core.expressions [3.6.200.v20180817-1401]
2019-03-28 18:01:32.527 - > Start org.eclipse.e4.ui.workbench.renderers.swt [0.14.400.v20181112-1716]
2019-03-28 18:01:32.621 - > Start org.eclipse.e4.ui.bindings [0.12.300.v20180913-1535]
2019-03-28 18:01:32.667 - > Start org.eclipse.e4.core.di.extensions [0.15.200.v20180817-1215]
2019-03-28 18:01:32.983 - > Start org.eclipse.e4.ui.css.swt [0.13.300.v20181030-1443]
2019-03-28 18:01:33.057 - > Start org.eclipse.e4.ui.css.swt.theme [0.12.100.v20180828-0227]
2019-03-28 18:01:33.791 - Initializing DBeaver 6.0.1
2019-03-28 18:01:33.791 - Host plugin: org.jkiss.dbeaver.core.application 6.0.1.201903251040
2019-03-28 18:01:33.791 - Initialize Core...
2019-03-28 18:01:33.791 - Can't find BC security provider. Use default JCE.
2019-03-28 18:01:33.791 - BouncyCastle not registered, using the default JCE provider
2019-03-28 18:01:33.900 - > Start org.eclipse.team.core [3.8.400.v20181109-0825]
2019-03-28 18:01:33.916 - > Start org.jkiss.dbeaver.ui.navigator [1.0.5.201903251040]
2019-03-28 18:01:34.010 - Total database drivers: 71 (71)
2019-03-28 18:01:34.025 - > Start org.eclipse.equinox.security [1.3.0.v20181115-0746]
2019-03-28 18:01:34.041 - > Start org.eclipse.ui.net [1.3.300.v20180827-1041]
2019-03-28 18:01:34.041 - Proxy service 'org.eclipse.core.net.proxy.IProxyService' loaded
2019-03-28 18:01:34.041 - Core initialized (250ms)
2019-03-28 18:01:34.041 - Configure workbench window
2019-03-28 18:01:34.041 - > Start org.eclipse.core.net [1.3.400.v20181030-1645]
2019-03-28 18:01:34.057 - > Start org.eclipse.help [3.8.200.v20180821-0700]
2019-03-28 18:01:34.088 - Create actions
2019-03-28 18:01:34.088 - Disable Eclipse action set 'org.eclipse.ui.edit.text.actionSet.annotationNavigation'
2019-03-28 18:01:34.104 - Disable Eclipse action set 'org.eclipse.ui.WorkingSetActionSet'
2019-03-28 18:01:34.135 - > Start org.eclipse.ui.editors [3.11.300.v20180914-0606]
2019-03-28 18:01:34.135 - > Start org.eclipse.core.filebuffers [3.6.400.v20181028-0633]
2019-03-28 18:01:34.603 - > Start org.eclipse.search [3.11.400.v20181028-0633]
2019-03-28 18:01:34.619 - > Start org.eclipse.ui.workbench.texteditor [3.11.200.v20181108-1458]
2019-03-28 18:01:34.641 - Initialize workbench window
2019-03-28 18:01:34.641 - Finish initialization
2019-03-28 18:01:34.672 - > Start org.jkiss.dbeaver.ui.editors.sql [1.0.5.201903251040]
2019-03-28 18:01:34.782 - > Start org.jkiss.dbeaver.ext.erd [2.0.107.201903251040]
2019-03-28 18:01:34.875 - > Start org.jkiss.dbeaver.ui.editors.base [1.0.5.201903251040]
2019-03-28 18:01:35.657 - > Start org.eclipse.equinox.p2.core [2.5.100.v20180822-1532]
2019-03-28 18:01:35.672 - > Start org.eclipse.equinox.p2.operations [2.5.200.v20180928-1359]
2019-03-28 18:01:35.688 - > Start org.eclipse.equinox.p2.engine [2.6.100.v20180822-1302]
2019-03-28 18:01:35.688 - > Start org.eclipse.equinox.p2.metadata [2.4.200.v20181102-0649]
2019-03-28 18:01:35.703 - > Start org.eclipse.equinox.p2.ui.sdk.scheduler [1.4.200.v20181102-0649]
2019-03-28 18:01:35.703 - > Start org.eclipse.equinox.p2.updatechecker [1.2.100.v20180827-1122]
2019-03-28 18:01:35.719 - > Start org.eclipse.equinox.p2.metadata.repository [1.3.100.v20180822-1302]
2019-03-28 18:01:35.719 - > Start org.eclipse.equinox.p2.repository [2.4.200.v20181005-1131]
2019-03-28 18:01:35.750 - > Start org.jkiss.dbeaver.ui.editors.data [1.0.5.201903251040]
2019-03-28 18:01:35.844 - > Start org.eclipse.equinox.p2.ui [2.5.400.v20181113-1303]
2019-03-28 18:01:35.907 - > Start org.jkiss.dbeaver.ext.sample.database [1.0.42.201903251040]
2019-03-28 18:01:35.907 - > Start org.jkiss.dbeaver.ext.ui.tipoftheday [1.0.11.201903251040]
2019-03-28 18:01:42.622 - > Start org.jkiss.dbeaver.ext.generic [2.3.91.201903251040]
2019-03-28 18:01:49.375 - Connect with 'jdbc:odbc:FOSDATA' (odbc-169c689bcaf-601dcda38da69361)
2019-03-28 18:01:49.515 - Connection failed (odbc-169c689bcaf-601dcda38da69361)
2019-03-28 18:01:49.515 - org.jkiss.dbeaver.model.exec.DBCConnectException: [PSQL][ODBC Client Interface]Parameter number out of range.
org.jkiss.dbeaver.model.exec.DBCConnectException: [PSQL][ODBC Client Interface]Parameter number out of range.
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.openConnection(JDBCDataSource.java:179)
	at org.jkiss.dbeaver.ext.generic.model.GenericDataSource.openConnection(GenericDataSource.java:124)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCExecutionContext.connect(JDBCExecutionContext.java:89)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCRemoteInstance.initializeMainContext(JDBCRemoteInstance.java:86)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCRemoteInstance.<init>(JDBCRemoteInstance.java:54)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.initializeRemoteInstance(JDBCDataSource.java:105)
	at org.jkiss.dbeaver.ext.generic.model.GenericDataSource.<init>(GenericDataSource.java:106)
	at org.jkiss.dbeaver.ext.generic.model.meta.GenericMetaModel.createDataSourceImpl(GenericMetaModel.java:67)
	at org.jkiss.dbeaver.ext.generic.GenericDataSourceProvider.openDataSource(GenericDataSourceProvider.java:95)
	at org.jkiss.dbeaver.registry.DataSourceDescriptor.connect(DataSourceDescriptor.java:770)
	at org.jkiss.dbeaver.runtime.jobs.ConnectJob.run(ConnectJob.java:70)
	at org.jkiss.dbeaver.ui.dialogs.connection.ConnectionWizard$ConnectionTester.run(ConnectionWizard.java:232)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:102)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
Caused by: java.sql.SQLException: [PSQL][ODBC Client Interface]Parameter number out of range.
	at sun.jdbc.odbc.JdbcOdbc.createSQLException(JdbcOdbc.java:6964)
	at sun.jdbc.odbc.JdbcOdbc.standardError(JdbcOdbc.java:7121)
	at sun.jdbc.odbc.JdbcOdbc.SQLGetDataInteger(JdbcOdbc.java:3818)
	at sun.jdbc.odbc.JdbcOdbcResultSet.getDataInteger(JdbcOdbcResultSet.java:5637)
	at sun.jdbc.odbc.JdbcOdbcResultSet.getInt(JdbcOdbcResultSet.java:582)
	at sun.jdbc.odbc.JdbcOdbcConnection.buildTypeInfo(JdbcOdbcConnection.java:1513)
	at sun.jdbc.odbc.JdbcOdbcConnection.initialize(JdbcOdbcConnection.java:381)
	at sun.jdbc.odbc.JdbcOdbcDriver.connect(JdbcOdbcDriver.java:174)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.lambda$0(JDBCDataSource.java:148)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.openConnection(JDBCDataSource.java:157)
	... 13 more
2019-03-28 18:01:58.835 - DBeaver is stopping
2019-03-28 18:01:58.835 - Stop RMI server
```
