### ISSUE TITLE
cassandra import data error

### ISSUE THREAD

**Issue by evildecay** [serge-rider/dbeaver#545]
```
!ENTRY org.jkiss.dbeaver.model 4 0 2016-06-18 14:15:53.295
!MESSAGE org.jkiss.dbeaver.model.exec.DBCException: Unsupported list type: com.jkiss.dbeaver.ent.cassandra.data.CasSetValue
!SUBENTRY 1 org.jkiss.dbeaver.model 4 0 2016-06-18 14:15:53.295
!MESSAGE Unsupported list type: com.jkiss.dbeaver.ent.cassandra.data.CasSetValue
!STACK 0
org.jkiss.dbeaver.model.exec.DBCException: Unsupported list type: com.jkiss.dbeaver.ent.cassandra.data.CasSetValue
	at com.jkiss.dbeaver.ent.cassandra.data.handlers.CasSetValueHandler.getValueFromObject(CasSetValueHandler.java:52)
	at org.jkiss.dbeaver.tools.transfer.database.DatabaseTransferConsumer.fetchRow(DatabaseTransferConsumer.java:127)
	at com.jkiss.dbeaver.ent.cassandra.model.CasTableBase.readData(CasTableBase.java:143)
	at org.jkiss.dbeaver.tools.transfer.database.DatabaseTransferProducer.transferData(DatabaseTransferProducer.java:119)
	at org.jkiss.dbeaver.tools.transfer.database.DatabaseTransferProducer.transferData(DatabaseTransferProducer.java:1)
	at org.jkiss.dbeaver.tools.transfer.wizard.DataTransferJob.transferData(DataTransferJob.java:104)
	at org.jkiss.dbeaver.tools.transfer.wizard.DataTransferJob.run(DataTransferJob.java:66)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:103)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)
```

**Comment by serge-rider** [comment]
Thanks for report
