### ISSUE TITLE
Null Pointer Exception in MySQL Procedure Generate DDL and Edit Procedure

### ISSUE THREAD

**Issue by sumisuburaianto** [serge-rider/dbeaver#587]
Using DBeaver 3.7.0 I receive a null pointer exception when connected to a MySQL database and trying to Generate DDL for a procedure, or trying to Edit Procedure. The null pointer exception is coming from method

private String normalizeCreateStatement(String createDDL)

in class org.jkiss.dbeaver.ext.mysql.model.MySQLProcedure.

It appears to be triggered by my database user not having appropriate rights.

Log entry:

!ENTRY org.jkiss.dbeaver.model 4 0 2016-07-07 17:38:35.621
!MESSAGE java.lang.NullPointerException
!SUBENTRY 1 org.jkiss.dbeaver.model 4 0 2016-07-07 17:38:35.621
!MESSAGE 
!STACK 0
java.lang.NullPointerException
	at org.jkiss.dbeaver.ext.mysql.model.MySQLProcedure.normalizeCreateStatement(MySQLProcedure.java:176)
	at org.jkiss.dbeaver.ext.mysql.model.MySQLProcedure.getDeclaration(MySQLProcedure.java:126)
	at org.jkiss.dbeaver.ext.mysql.model.MySQLProcedure.getObjectDefinitionText(MySQLProcedure.java:240)
	at org.jkiss.dbeaver.ui.editors.sql.SQLSourceViewer.getSourceText(SQLSourceViewer.java:34)
	at org.jkiss.dbeaver.ui.editors.sql.SQLEditorNested$ObjectDocumentProvider$1.run(SQLEditorNested.java:232)
	at org.jkiss.dbeaver.runtime.TasksJob.run(TasksJob.java:61)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:103)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)

And immediately preceding that:

!ENTRY org.jkiss.dbeaver.model 4 0 2016-07-07 17:38:35.016
!MESSAGE Error initializing property tabs
!SUBENTRY 1 org.jkiss.dbeaver.model 4 0 2016-07-07 17:38:35.016
!MESSAGE SQL Error [S1000]: User does not have access to metadata required to determine stored procedure parameter types. If rights can not be granted, configure connection with "noAccessToProcedureBodies=true" to have driver generate parameters that represent INOUT strings irregardless of actual parameter types.
!STACK 0
org.jkiss.dbeaver.DBException: SQL Error [S1000]: User does not have access to metadata required to determine stored procedure parameter types. If rights can not be granted, configure connection with "noAccessToProcedureBodies=true" to have driver generate parameters that represent INOUT strings irregardless of actual parameter types.
	at org.jkiss.dbeaver.model.impl.jdbc.cache.JDBCStructCache.loadChildren(JDBCStructCache.java:166)
	at org.jkiss.dbeaver.model.impl.jdbc.cache.JDBCStructCache.getChildren(JDBCStructCache.java:210)
	at org.jkiss.dbeaver.ext.mysql.model.MySQLProcedure.getParameters(MySQLProcedure.java:224)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.jkiss.dbeaver.model.navigator.DBNDatabaseNode.extractPropertyValue(DBNDatabaseNode.java:719)
	at org.jkiss.dbeaver.model.navigator.DBNDatabaseNode.loadTreeItems(DBNDatabaseNode.java:449)
	at org.jkiss.dbeaver.model.navigator.DBNDatabaseNode.loadChildren(DBNDatabaseNode.java:375)
	at org.jkiss.dbeaver.model.navigator.DBNDatabaseNode.getChildren(DBNDatabaseNode.java:192)
	at org.jkiss.dbeaver.model.navigator.DBNDatabaseNode.getChildren(DBNDatabaseNode.java:1)
	at org.jkiss.dbeaver.ui.editors.entity.properties.ObjectPropertiesEditor.collectNavigatorTabs(ObjectPropertiesEditor.java:422)
	at org.jkiss.dbeaver.ui.editors.entity.properties.ObjectPropertiesEditor.access$3(ObjectPropertiesEditor.java:415)
	at org.jkiss.dbeaver.ui.editors.entity.properties.ObjectPropertiesEditor$2.run(ObjectPropertiesEditor.java:382)
	at org.jkiss.dbeaver.core.DBeaverUI$4.run(DBeaverUI.java:253)
	at org.jkiss.dbeaver.runtime.RunnableContextDelegate$1.run(RunnableContextDelegate.java:45)
	at org.eclipse.jface.operation.ModalContext$ModalContextThread.run(ModalContext.java:119)
Caused by: java.sql.SQLException: User does not have access to metadata required to determine stored procedure parameter types. If rights can not be granted, configure connection with "noAccessToProcedureBodies=true" to have driver generate parameters that represent INOUT strings irregardless of actual parameter types.
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:959)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:898)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:887)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:862)
	at com.mysql.jdbc.DatabaseMetaData.getCallStmtParameterTypes(DatabaseMetaData.java:1633)
	at com.mysql.jdbc.DatabaseMetaData.getProcedureOrFunctionColumns(DatabaseMetaData.java:3968)
	at com.mysql.jdbc.JDBC4DatabaseMetaData.getProcedureColumns(JDBC4DatabaseMetaData.java:108)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCDatabaseMetaDataImpl.getProcedureColumns(JDBCDatabaseMetaDataImpl.java:1111)
	at org.jkiss.dbeaver.ext.mysql.model.MySQLCatalog$ProceduresCache.prepareChildrenStatement(MySQLCatalog.java:578)
	at org.jkiss.dbeaver.ext.mysql.model.MySQLCatalog$ProceduresCache.prepareChildrenStatement(MySQLCatalog.java:1)
	at org.jkiss.dbeaver.model.impl.jdbc.cache.JDBCStructCache.loadChildren(JDBCStructCache.java:90)
	... 17 more
!SUBENTRY 2 org.jkiss.dbeaver.model 4 0 2016-07-07 17:38:35.016
!MESSAGE User does not have access to metadata required to determine stored procedure parameter types. If rights can not be granted, configure connection with "noAccessToProcedureBodies=true" to have driver generate parameters that represent INOUT strings irregardless of actual parameter types.
!STACK 0
java.sql.SQLException: User does not have access to metadata required to determine stored procedure parameter types. If rights can not be granted, configure connection with "noAccessToProcedureBodies=true" to have driver generate parameters that represent INOUT strings irregardless of actual parameter types.
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:959)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:898)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:887)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:862)
	at com.mysql.jdbc.DatabaseMetaData.getCallStmtParameterTypes(DatabaseMetaData.java:1633)
	at com.mysql.jdbc.DatabaseMetaData.getProcedureOrFunctionColumns(DatabaseMetaData.java:3968)
	at com.mysql.jdbc.JDBC4DatabaseMetaData.getProcedureColumns(JDBC4DatabaseMetaData.java:108)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCDatabaseMetaDataImpl.getProcedureColumns(JDBCDatabaseMetaDataImpl.java:1111)
	at org.jkiss.dbeaver.ext.mysql.model.MySQLCatalog$ProceduresCache.prepareChildrenStatement(MySQLCatalog.java:578)
	at org.jkiss.dbeaver.ext.mysql.model.MySQLCatalog$ProceduresCache.prepareChildrenStatement(MySQLCatalog.java:1)
	at org.jkiss.dbeaver.model.impl.jdbc.cache.JDBCStructCache.loadChildren(JDBCStructCache.java:90)
	at org.jkiss.dbeaver.model.impl.jdbc.cache.JDBCStructCache.getChildren(JDBCStructCache.java:210)
	at org.jkiss.dbeaver.ext.mysql.model.MySQLProcedure.getParameters(MySQLProcedure.java:224)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.jkiss.dbeaver.model.navigator.DBNDatabaseNode.extractPropertyValue(DBNDatabaseNode.java:719)
	at org.jkiss.dbeaver.model.navigator.DBNDatabaseNode.loadTreeItems(DBNDatabaseNode.java:449)
	at org.jkiss.dbeaver.model.navigator.DBNDatabaseNode.loadChildren(DBNDatabaseNode.java:375)
	at org.jkiss.dbeaver.model.navigator.DBNDatabaseNode.getChildren(DBNDatabaseNode.java:192)
	at org.jkiss.dbeaver.model.navigator.DBNDatabaseNode.getChildren(DBNDatabaseNode.java:1)
	at org.jkiss.dbeaver.ui.editors.entity.properties.ObjectPropertiesEditor.collectNavigatorTabs(ObjectPropertiesEditor.java:422)
	at org.jkiss.dbeaver.ui.editors.entity.properties.ObjectPropertiesEditor.access$3(ObjectPropertiesEditor.java:415)
	at org.jkiss.dbeaver.ui.editors.entity.properties.ObjectPropertiesEditor$2.run(ObjectPropertiesEditor.java:382)
	at org.jkiss.dbeaver.core.DBeaverUI$4.run(DBeaverUI.java:253)
	at org.jkiss.dbeaver.runtime.RunnableContextDelegate$1.run(RunnableContextDelegate.java:45)
	at org.eclipse.jface.operation.ModalContext$ModalContextThread.run(ModalContext.java:119)

**Comment by serge-rider** [comment]
I'll fix NPE but I can't show procedure source if you don't have permissions for that.

`User does not have access to metadata required to determine stored procedure parameter types. If rights can not be granted, configure connection with "noAccessToProcedureBodies=true" to have driver generate parameters that represent INOUT strings irregardless of actual parameter types.`

Thanks for report.

**Comment by sumisuburaianto** [comment]
Thank you for so quickly addressing the issue.

**Comment by nmadham** [comment]
Database : MYSQL
Dbeaver Version : 3.8.3 --3.8.4 has many other problem so degraded back to 3.8.3
Action performed : Opened connection then DDL of a table
Errors as below,
![image](https://cloud.githubusercontent.com/assets/16705400/22310249/a5aa9082-e31c-11e6-9441-a4dc49186a91.png)
![image](https://cloud.githubusercontent.com/assets/16705400/22310298/d595b664-e31c-11e6-9e06-12b6241ca02b.png)

**Comment by serge-rider** [comment]
Can't reproduce.
Please post error stacktrace (you can get it in Error Log view).

**Comment by nmadham** [comment]
![image](https://cloud.githubusercontent.com/assets/16705400/22310888/d423f258-e31e-11e6-8df1-ccbb23a86faa.png)

**Comment by nmadham** [comment]
![image](https://cloud.githubusercontent.com/assets/16705400/22310924/038d0642-e31f-11e6-9613-78028f1edffe.png)

**Comment by nmadham** [comment]
Below is the content in Exception Stack trace :: 

java.lang.NullPointerException
	at org.jkiss.dbeaver.ui.editors.entity.EntityEditor.getDataSourceContainer(EntityEditor.java:787)
	at org.jkiss.dbeaver.ui.perspective.DataSourceManagementToolbar.getDataSourceContainer(DataSourceManagementToolbar.java:211)
	at org.jkiss.dbeaver.ui.perspective.DataSourceManagementToolbar.setActivePart(DataSourceManagementToolbar.java:281)
	at org.jkiss.dbeaver.ui.perspective.DataSourceManagementToolbar.partActivated(DataSourceManagementToolbar.java:661)
	at org.eclipse.ui.internal.WorkbenchPage$14.run(WorkbenchPage.java:4912)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.eclipse.ui.internal.WorkbenchPage.firePartActivated(WorkbenchPage.java:4909)
	at org.eclipse.ui.internal.WorkbenchPage.access$19(WorkbenchPage.java:4897)
	at org.eclipse.ui.internal.WorkbenchPage$E4PartListener.partActivated(WorkbenchPage.java:203)
	at org.eclipse.e4.ui.internal.workbench.PartServiceImpl$3.run(PartServiceImpl.java:245)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.eclipse.e4.ui.internal.workbench.PartServiceImpl.firePartActivated(PartServiceImpl.java:242)
	at org.eclipse.e4.ui.internal.workbench.PartServiceImpl.activate(PartServiceImpl.java:711)
	at org.eclipse.e4.ui.internal.workbench.PartServiceImpl.activate(PartServiceImpl.java:639)
	at org.eclipse.e4.ui.internal.workbench.PartServiceImpl.activate(PartServiceImpl.java:634)
	at org.eclipse.ui.internal.WorkbenchPage.activate(WorkbenchPage.java:980)
	at org.jkiss.dbeaver.ui.actions.navigator.NavigatorHandlerObjectOpen.openEntityEditor(NavigatorHandlerObjectOpen.java:168)
	at org.jkiss.dbeaver.ui.actions.navigator.NavigatorHandlerObjectOpen.openEntityEditor(NavigatorHandlerObjectOpen.java:128)
	at org.jkiss.dbeaver.ui.navigator.NavigatorUtils.openNavigatorNode(NavigatorUtils.java:594)
	at org.jkiss.dbeaver.ui.navigator.database.NavigatorViewBase$2.doubleClick(NavigatorViewBase.java:151)
	at org.eclipse.jface.viewers.StructuredViewer$1.run(StructuredViewer.java:832)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.eclipse.ui.internal.JFaceUtil$1.run(JFaceUtil.java:50)
	at org.eclipse.jface.util.SafeRunnable.run(SafeRunnable.java:173)
	at org.eclipse.jface.viewers.StructuredViewer.fireDoubleClick(StructuredViewer.java:829)
	at org.eclipse.jface.viewers.AbstractTreeViewer.handleDoubleSelect(AbstractTreeViewer.java:1470)
	at org.eclipse.jface.viewers.StructuredViewer$4.widgetDefaultSelected(StructuredViewer.java:1263)
	at org.eclipse.jface.util.OpenStrategy.fireDefaultSelectionEvent(OpenStrategy.java:252)
	at org.eclipse.jface.util.OpenStrategy.access$0(OpenStrategy.java:249)
	at org.eclipse.jface.util.OpenStrategy$1.handleEvent(OpenStrategy.java:311)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:84)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4362)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1113)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4180)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3769)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$4.run(PartRenderingEngine.java:1127)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:337)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1018)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:156)
	at org.eclipse.ui.internal.Workbench$5.run(Workbench.java:694)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:337)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:606)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:150)
	at org.jkiss.dbeaver.core.application.DBeaverApplication.start(DBeaverApplication.java:212)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:380)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:235)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:669)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:608)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1515)
