### ISSUE TITLE
can no longer select a datasource when opening a SQL File in SQL editor

### ISSUE THREAD

**Issue by farmboy0** [serge-rider/dbeaver#641]
Eclipse 4.5.2
DBeaver 3.7.2

This worked till I think 3.6.9 or so and now the only list entry in the toolbar is None.

**Comment by serge-rider** [comment]
Please check error logs
https://github.com/serge-rider/dbeaver/wiki/Log-files

**Comment by serge-rider** [comment]
After all the only thing I can suggest is to try to reset workbench (https://github.com/serge-rider/dbeaver/wiki/Reset-workspace) - maybe this issue was caused by broken toolbar config after version update.

**Comment by farmboy0** [comment]
This might be related

!ENTRY org.eclipse.ui 4 0 2016-08-24 11:14:36.403
!MESSAGE Unhandled event loop exception
!STACK 0
org.eclipse.swt.SWTException: Failed to execute runnable (java.lang.NullPointerException)
	at org.eclipse.swt.SWT.error(SWT.java:4491)
	at org.eclipse.swt.SWT.error(SWT.java:4406)
	at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Synchronizer.java:138)
	at org.eclipse.swt.widgets.Display.runAsyncMessages(Display.java:4155)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3772)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$4.run(PartRenderingEngine.java:1127)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:337)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1018)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:156)
	at org.eclipse.ui.internal.Workbench$5.run(Workbench.java:694)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:337)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:606)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:150)
	at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:139)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:380)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:235)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:669)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:608)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1515)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1488)
Caused by: java.lang.NullPointerException
	at org.jkiss.dbeaver.ui.controls.itemlist.NodeListControl.getDataSourceContainer(NodeListControl.java:126)
	at org.jkiss.dbeaver.ui.controls.itemlist.ObjectListControl.setListData(ObjectListControl.java:380)
	at org.jkiss.dbeaver.ui.controls.itemlist.ObjectListControl.access$4(ObjectListControl.java:344)
	at org.jkiss.dbeaver.ui.controls.itemlist.ObjectListControl$ObjectsLoadVisualizer.completeLoading(ObjectListControl.java:917)
	at org.jkiss.dbeaver.ui.controls.itemlist.ObjectListControl$ObjectsLoadVisualizer.completeLoading(ObjectListControl.java:1)
	at org.jkiss.dbeaver.ui.LoadingJob$LoadFinisher.run(LoadingJob.java:121)
	at org.eclipse.ui.internal.UILockListener.doPendingWork(UILockListener.java:162)
	at org.eclipse.ui.internal.UISynchronizer$3.run(UISynchronizer.java:154)
	at org.eclipse.swt.widgets.RunnableLock.run(RunnableLock.java:35)
	at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Synchronizer.java:135)
	... 24 more

**Comment by serge-rider** [comment]
Thanks for info. I've fixed this error although I'm not sure that it is related to datasource selector..
