### ISSUE TITLE
DDL error

### ISSUE THREAD

**Issue by HBartolin** [serge-rider/dbeaver#652]
DB2, Version: 3.68.61

/* ERROR WHILE READING SOURCE:

SQL Error [38553]: Routine "*RATE_DDL" (specific name "") has returned an error SQLSTATE with diagnostic text "SQL0551 Reason code or token: CTSADM,CREATE TABLE,SYSTOOLSP".. SQLCODE=-443, SQLSTATE=38553, DRIVER=3.68.61
*/

org.jkiss.dbeaver.DBException: SQL Error [38553]: Routine "*RATE_DDL" (specific name "") has returned an error SQLSTATE with diagnostic text "SQL0551 Reason code or token: CTSADM,CREATE TABLE,SYSTOOLSP".. SQLCODE=-443, SQLSTATE=38553, DRIVER=3.68.61

org.jkiss.dbeaver.DBException: SQL Error [38553]: Routine "*RATE_DDL" (specific name "") has returned an error SQLSTATE with diagnostic text "SQL0551 Reason code or token: CTSADM,CREATE TABLE,SYSTOOLSP".. SQLCODE=-443, SQLSTATE=38553, DRIVER=3.68.61
	at org.jkiss.dbeaver.ext.db2.DB2Utils.generateDDLforTable(DB2Utils.java:222)
	at org.jkiss.dbeaver.ext.db2.model.DB2Table.getObjectDefinitionText(DB2Table.java:221)
	at org.jkiss.dbeaver.ui.editors.sql.SQLSourceViewer.getSourceText(SQLSourceViewer.java:34)
	at org.jkiss.dbeaver.ui.editors.sql.SQLEditorNested$ObjectDocumentProvider$1.run(SQLEditorNested.java:232)
	at org.jkiss.dbeaver.runtime.TasksJob.run(TasksJob.java:61)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:103)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)
Caused by: com.ibm.db2.jcc.am.SqlException: Routine "*RATE_DDL" (specific name "") has returned an error SQLSTATE with diagnostic text "SQL0551 Reason code or token: CTSADM,CREATE TABLE,SYSTOOLSP".. SQLCODE=-443, SQLSTATE=38553, DRIVER=3.68.61
	at com.ibm.db2.jcc.am.gd.a(gd.java:752)
	at com.ibm.db2.jcc.am.gd.a(gd.java:66)
	at com.ibm.db2.jcc.am.gd.a(gd.java:135)
	at com.ibm.db2.jcc.am.uo.b(uo.java:2447)
	at com.ibm.db2.jcc.am.uo.c(uo.java:2430)
	at com.ibm.db2.jcc.t4.bb.l(bb.java:406)
	at com.ibm.db2.jcc.t4.bb.f(bb.java:98)
	at com.ibm.db2.jcc.t4.p.e(p.java:81)
	at com.ibm.db2.jcc.t4.vb.k(vb.java:170)
	at com.ibm.db2.jcc.am.uo.lb(uo.java:2396)
	at com.ibm.db2.jcc.am.vo.b(vo.java:4464)
	at com.ibm.db2.jcc.am.CallableStatement.ic(CallableStatement.java:191)
	at com.ibm.db2.jcc.am.CallableStatement.executeUpdate(CallableStatement.java:171)
	at com.ibm.db2.jcc.am.mf.executeUpdate(mf.java:68)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCPreparedStatementImpl.executeUpdate(JDBCPreparedStatementImpl.java:238)
	at org.jkiss.dbeaver.ext.db2.DB2Utils.generateDDLforTable(DB2Utils.java:176)
	... 6 more

**Comment by titou10titou10** [comment]
DBeaver uses the DB2 `db2look` command to generate tDDL.
`"SQL0551 Reason code or token: CTSADM,CREATE TABLE,SYSTOOLSP"` means that the user your are using to connect to the database and generate the DDL is not authorized to do so.
In fact `db2look` need some internal tables usually created in the SYSTOOLS schema and it appears that the user is not authorized to either create of access those tables and so it is not authroized to run `db2look`
[click here for the doc on db2look](http://www.ibm.com/support/knowledgecenter/SSEPGG_11.1.0/com.ibm.db2.luw.admin.cmd.doc/doc/r0002051.html)
Denis
