### ISSUE TITLE
mssqlserver, underscore in DB name results in errors.

### ISSUE THREAD

**Issue by adrinjalali** [serge-rider/dbeaver#730]
I have a MSSQL 2008 server, and a database called 06_Analysis.

Here's the output when I try to see the DDL of a SP in that DB.

```
$ dbeaver 
2016-09-14 14:11:09.500 - DBeaver 3.7.4 is starting
2016-09-14 14:11:09.510 - Install path: '/opt/dbeaver'
2016-09-14 14:11:09.510 - Instance path: 'file:/home/adrin/.dbeaver/'
2016-09-14 14:11:09.510 - Memory available 59Mb/880Mb
2016-09-14 14:11:09.528 - Starting RMI server at 34850
2016-09-14 14:11:09.799 - Initialize display
2016-09-14 14:11:12.496 - Initializing DBeaver 3.7.4
2016-09-14 14:11:12.504 - Host plugin: org.jkiss.dbeaver.core.application 3.7.4
2016-09-14 14:11:12.522 - Initialize Core...
2016-09-14 14:11:12.842 - Core initialized (320ms)
2016-09-14 14:11:12.846 - Configure workbench window
2016-09-14 14:11:13.008 - Create actions
2016-09-14 14:11:13.550 - Initialize workbench window
2016-09-14 14:11:13.598 - Finish initialization
1
1
1
1
2016-09-14 14:11:15.902 - Connect with 'MS SQL Server - server.name' (mssql_ms-15646a234ea-4d17038f266150e7)
2016-09-14 14:11:17.726 - Connected (mssql_ms-15646a234ea-4d17038f266150e7)
2016-09-14 14:11:43.946 - Error reading schemas in catalog '06_Analysis' - Incorrect syntax near '.'.
2016-09-14 14:11:54.616 - Can't get column 'SPECIFIC_NAME': The column name SPECIFIC_NAME is not valid.
2016-09-14 14:11:54.619 - Can't get column 'SPECIFIC_NAME': The column name SPECIFIC_NAME is not valid.
2016-09-14 14:11:54.620 - Can't get column 'SPECIFIC_NAME': The column name SPECIFIC_NAME is not valid.
2016-09-14 14:11:54.621 - Can't get column 'SPECIFIC_NAME': The column name SPECIFIC_NAME is not valid.
2016-09-14 14:11:54.621 - Can't get column 'SPECIFIC_NAME': The column name SPECIFIC_NAME is not valid.
2016-09-14 14:11:54.622 - Can't get column 'SPECIFIC_NAME': The column name SPECIFIC_NAME is not valid.
2016-09-14 14:11:54.622 - Can't get column 'SPECIFIC_NAME': The column name SPECIFIC_NAME is not valid.
2016-09-14 14:11:54.623 - Can't get column 'SPECIFIC_NAME': The column name SPECIFIC_NAME is not valid.
2016-09-14 14:11:54.623 - Can't get column 'SPECIFIC_NAME': The column name SPECIFIC_NAME is not valid.
2016-09-14 14:11:54.624 - Can't get column 'SPECIFIC_NAME': The column name SPECIFIC_NAME is not valid.
2016-09-14 14:11:54.624 - Can't get column 'SPECIFIC_NAME': The column name SPECIFIC_NAME is not valid.
2016-09-14 14:11:54.625 - Can't get column 'SPECIFIC_NAME': The column name SPECIFIC_NAME is not valid.
2016-09-14 14:11:54.626 - Can't get column 'SPECIFIC_NAME': The column name SPECIFIC_NAME is not valid.
2016-09-14 14:11:54.626 - Can't get column 'SPECIFIC_NAME': The column name SPECIFIC_NAME is not valid.
2016-09-14 14:11:54.627 - Can't get column 'SPECIFIC_NAME': The column name SPECIFIC_NAME is not valid.
2016-09-14 14:11:54.627 - Can't get column 'SPECIFIC_NAME': The column name SPECIFIC_NAME is not valid.
2016-09-14 14:11:54.628 - Can't get column 'SPECIFIC_NAME': The column name SPECIFIC_NAME is not valid.
2016-09-14 14:11:54.628 - Can't get column 'SPECIFIC_NAME': The column name SPECIFIC_NAME is not valid.
2016-09-14 14:11:54.629 - Can't get column 'SPECIFIC_NAME': The column name SPECIFIC_NAME is not valid.
2016-09-14 14:11:54.629 - Can't get column 'SPECIFIC_NAME': The column name SPECIFIC_NAME is not valid.
2016-09-14 14:11:54.630 - Can't get column 'SPECIFIC_NAME': The column name SPECIFIC_NAME is not valid.
2016-09-14 14:11:54.630 - Can't get column 'SPECIFIC_NAME': The column name SPECIFIC_NAME is not valid.
2016-09-14 14:11:54.631 - Can't get column 'SPECIFIC_NAME': The column name SPECIFIC_NAME is not valid.
2016-09-14 14:11:54.638 - Can't get column 'SPECIFIC_NAME': The column name SPECIFIC_NAME is not valid.
2016-09-14 14:11:54.639 - Can't get column 'SPECIFIC_NAME': The column name SPECIFIC_NAME is not valid.
2016-09-14 14:11:54.639 - Can't get column 'SPECIFIC_NAME': The column name SPECIFIC_NAME is not valid.
2016-09-14 14:11:54.640 - Can't get column 'SPECIFIC_NAME': The column name SPECIFIC_NAME is not valid.
2016-09-14 14:11:54.640 - Can't get column 'SPECIFIC_NAME': The column name SPECIFIC_NAME is not valid.
2016-09-14 14:11:54.640 - Can't get column 'SPECIFIC_NAME': The column name SPECIFIC_NAME is not valid.
2016-09-14 14:11:54.641 - Can't get column 'SPECIFIC_NAME': The column name SPECIFIC_NAME is not valid.
2016-09-14 14:11:54.641 - Can't get column 'SPECIFIC_NAME': The column name SPECIFIC_NAME is not valid.
2016-09-14 14:11:54.641 - Can't get column 'SPECIFIC_NAME': The column name SPECIFIC_NAME is not valid.
2016-09-14 14:11:54.642 - Can't get column 'SPECIFIC_NAME': The column name SPECIFIC_NAME is not valid.
2016-09-14 14:11:54.642 - Can't get column 'SPECIFIC_NAME': The column name SPECIFIC_NAME is not valid.
2016-09-14 14:11:54.642 - Can't get column 'SPECIFIC_NAME': The column name SPECIFIC_NAME is not valid.
2016-09-14 14:11:54.643 - Can't get column 'SPECIFIC_NAME': The column name SPECIFIC_NAME is not valid.
2016-09-14 14:11:54.643 - Can't get column 'SPECIFIC_NAME': The column name SPECIFIC_NAME is not valid.
2016-09-14 14:11:54.643 - Can't get column 'SPECIFIC_NAME': The column name SPECIFIC_NAME is not valid.
2016-09-14 14:11:54.644 - Can't get column 'SPECIFIC_NAME': The column name SPECIFIC_NAME is not valid.
2016-09-14 14:11:54.644 - Can't get column 'SPECIFIC_NAME': The column name SPECIFIC_NAME is not valid.
2016-09-14 14:11:54.645 - Can't get column 'SPECIFIC_NAME': The column name SPECIFIC_NAME is not valid.
2016-09-14 14:11:54.645 - Can't get column 'SPECIFIC_NAME': The column name SPECIFIC_NAME is not valid.
2016-09-14 14:11:54.645 - Can't get column 'SPECIFIC_NAME': The column name SPECIFIC_NAME is not valid.
2016-09-14 14:11:54.646 - Can't get column 'SPECIFIC_NAME': The column name SPECIFIC_NAME is not valid.
2016-09-14 14:11:54.646 - Can't get column 'SPECIFIC_NAME': The column name SPECIFIC_NAME is not valid.
2016-09-14 14:11:54.646 - Can't get column 'SPECIFIC_NAME': The column name SPECIFIC_NAME is not valid.
2016-09-14 14:12:05.315 - org.jkiss.dbeaver.DBException: SQL Error [102] [S0001]: Incorrect syntax near '06'.
org.jkiss.dbeaver.DBException: SQL Error [102] [S0001]: Incorrect syntax near '06'.
	at org.jkiss.dbeaver.ext.mssql.model.SQLServerMetaModel.extractSource(SQLServerMetaModel.java:151)
	at org.jkiss.dbeaver.ext.mssql.model.SQLServerMetaModel.getProcedureDDL(SQLServerMetaModel.java:62)
	at org.jkiss.dbeaver.ext.generic.model.GenericProcedure.getObjectDefinitionText(GenericProcedure.java:270)
	at org.jkiss.dbeaver.ui.editors.sql.SQLSourceViewer.getSourceText(SQLSourceViewer.java:54)
	at org.jkiss.dbeaver.ui.editors.sql.SQLEditorNested$ObjectDocumentProvider$1.run(SQLEditorNested.java:233)
	at org.jkiss.dbeaver.runtime.TasksJob.run(TasksJob.java:61)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:103)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)
Caused by: com.microsoft.sqlserver.jdbc.SQLServerException: Incorrect syntax near '06'.
	at com.microsoft.sqlserver.jdbc.SQLServerException.makeFromDatabaseError(SQLServerException.java:216)
	at com.microsoft.sqlserver.jdbc.SQLServerStatement.getNextResult(SQLServerStatement.java:1515)
	at com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement.doExecutePreparedStatement(SQLServerPreparedStatement.java:404)
	at com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement$PrepStmtExecCmd.doExecute(SQLServerPreparedStatement.java:350)
	at com.microsoft.sqlserver.jdbc.TDSCommand.execute(IOBuffer.java:5696)
	at com.microsoft.sqlserver.jdbc.SQLServerConnection.executeCommand(SQLServerConnection.java:1715)
	at com.microsoft.sqlserver.jdbc.SQLServerStatement.executeCommand(SQLServerStatement.java:180)
	at com.microsoft.sqlserver.jdbc.SQLServerStatement.executeStatement(SQLServerStatement.java:155)
	at com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement.executeQuery(SQLServerPreparedStatement.java:285)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCPreparedStatementImpl.executeQuery(JDBCPreparedStatementImpl.java:224)
	at org.jkiss.dbeaver.ext.mssql.model.SQLServerMetaModel.extractSource(SQLServerMetaModel.java:142)
	... 7 more
2016-09-14 14:12:17.463 - Shutdown Core...
2016-09-14 14:12:17.560 - Shutdown completed in 97ms
```

**Comment by serge-rider** [comment]
Thanks for report

**Comment by adrinjalali** [comment]
Thanks. I confirm it works for me.
