### ISSUE TITLE
multiple hive SQLQuery can't excute at the same time

### ISSUE THREAD

**Issue by hbhly** [serge-rider/dbeaver#761]

**Comment by serge-rider** [comment]
You can run multiple queries using `CTRL+\` shortcut (execute statement in a new tab).

**Comment by hbhly** [comment]
org.jkiss.dbeaver.model.exec.DBCException: SQL ERROR [08S01]: org.apache.thrift.TApplicationException: GetOperationStatus failed: out of sequence response
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCStatementImpl.executeStatement(JDBCStatementImpl.java:141)
	at org.jkiss.dbeaver.runtime.sql.SQLQueryJob.executeSingleQuery(SQLQueryJob.java:337)
	at org.jkiss.dbeaver.runtime.sql.SQLQueryJob.extractData(SQLQueryJob.java:716)
	at org.jkiss.dbeaver.ui.editors.sql.SQLEditor$QueryResultsContainer.readData(SQLEditor.java:1524)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetDataPumpJob.run(ResultSetDataPumpJob.java:139)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:103)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)
Caused by: java.sql.SQLException: org.apache.thrift.TApplicationException: GetOperationStatus failed: out of sequence response
	at org.apache.hive.jdbc.HiveStatement.execute(HiveStatement.java:311)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCStatementImpl.execute(JDBCStatementImpl.java:345)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCStatementImpl.executeStatement(JDBCStatementImpl.java:138)
	... 6 more
Caused by: org.apache.thrift.TApplicationException: GetOperationStatus failed: out of sequence response
	at org.apache.thrift.TServiceClient.receiveBase(TServiceClient.java:76)
	at org.apache.hive.service.cli.thrift.TCLIService$Client.recv_GetOperationStatus(TCLIService.java:409)
	at org.apache.hive.service.cli.thrift.TCLIService$Client.GetOperationStatus(TCLIService.java:396)
	at org.apache.hive.jdbc.HiveStatement.execute(HiveStatement.java:280)
	... 8 more

**Comment by hbhly** [comment]
org.jkiss.dbeaver.model.exec.DBCException: SQL ERROR[08S01]: org.apache.thrift.transport.TTransportException: Read a negative frame size (-2147418110)!
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCStatementImpl.executeStatement(JDBCStatementImpl.java:141)
	at org.jkiss.dbeaver.runtime.sql.SQLQueryJob.executeSingleQuery(SQLQueryJob.java:337)
	at org.jkiss.dbeaver.runtime.sql.SQLQueryJob.extractData(SQLQueryJob.java:716)
	at org.jkiss.dbeaver.ui.editors.sql.SQLEditor$QueryResultsContainer.readData(SQLEditor.java:1524)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetDataPumpJob.run(ResultSetDataPumpJob.java:139)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:103)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)
Caused by: java.sql.SQLException: org.apache.thrift.transport.TTransportException: Read a negative frame size (-2147418110)!
	at org.apache.hive.jdbc.HiveStatement.execute(HiveStatement.java:262)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCStatementImpl.execute(JDBCStatementImpl.java:345)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCStatementImpl.executeStatement(JDBCStatementImpl.java:138)
	... 6 more
Caused by: org.apache.thrift.transport.TTransportException: Read a negative frame size (-2147418110)!
	at org.apache.thrift.transport.TSaslTransport.readFrame(TSaslTransport.java:456)
	at org.apache.thrift.transport.TSaslTransport.read(TSaslTransport.java:435)
	at org.apache.thrift.transport.TSaslClientTransport.read(TSaslClientTransport.java:37)
	at org.apache.thrift.transport.TTransport.readAll(TTransport.java:86)
	at org.apache.thrift.protocol.TBinaryProtocol.readAll(TBinaryProtocol.java:429)
	at org.apache.thrift.protocol.TBinaryProtocol.readI32(TBinaryProtocol.java:318)
	at org.apache.thrift.protocol.TBinaryProtocol.readMessageBegin(TBinaryProtocol.java:219)
	at org.apache.thrift.TServiceClient.receiveBase(TServiceClient.java:69)
	at org.apache.hive.service.cli.thrift.TCLIService$Client.recv_ExecuteStatement(TCLIService.java:225)
	at org.apache.hive.service.cli.thrift.TCLIService$Client.ExecuteStatement(TCLIService.java:212)
	at org.apache.hive.jdbc.HiveStatement.execute(HiveStatement.java:253)
	... 8 more

**Comment by serge-rider** [comment]
Looks like Hive driver doesn't support multiple query executions (from different threads) in a single connection. I can't fix Hive driver.
The only workaround I can propose is to open multiple SQL editors (having option "Open separate connection for each editor" turned on) and run queries from different editors.
