### ISSUE TITLE
Crash on double clicking on another connection while a query is executing

### ISSUE THREAD

**Issue by dbza** [serge-rider/dbeaver#783]
Steps to reproduce:
1.Run a relatively long running query in connection1(db2 luw) so that you see the "Read data - xx secs" message
2. Double click another connection (db2 luw) in the  database pane
 (v 3.7.3 , jre1.8.0_101, Win 7 Enterprise)

**Comment by serge-rider** [comment]
What do you mean under "crash" exactly? Any error messages, logs?

**Comment by dbza** [comment]
The whole window becomes unresponsive. No error messages are displayed. 
No entry corresppoding to this timestamp in <workspace-path>/.metadata/.log or dbeaver-debug.log
I checked ${HOME}/.dbeaver and <install-path>/configuration and no files are last modified with timestamp as the crash time.

**Comment by serge-rider** [comment]
Yes, logs are useless in case of UI freeze.
Could you make a thread dump (https://github.com/serge-rider/dbeaver/wiki/Making-a-thread-dump) and post it here?

**Comment by dbza** [comment]
I tried to make the thread dump, but the UI freeze stopped after a few seconds (while I was opening the task manager for PID etc) and issued an error message saying query cancelled. I guess I was being impatient earlier and must have killed it soon after it stopped responding.

Below are the logs.

!ENTRY org.jkiss.dbeaver.model 4 0 2016-09-29 15:05:37.394
!MESSAGE Unexpected error while processing SQL
!SUBENTRY 1 org.jkiss.dbeaver.model 4 0 2016-09-29 15:05:37.394
!MESSAGE 
!STACK 0
java.lang.NullPointerException
	at org.jkiss.dbeaver.runtime.sql.SQLQueryJob.executeSingleQuery(SQLQueryJob.java:354)
	at org.jkiss.dbeaver.runtime.sql.SQLQueryJob.extractData(SQLQueryJob.java:719)
	at org.jkiss.dbeaver.ui.editors.sql.SQLEditor$QueryResultsContainer.readData(SQLEditor.java:1535)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetDataPumpJob.run(ResultSetDataPumpJob.java:139)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:103)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)

!ENTRY org.jkiss.dbeaver.model 2 0 2016-09-29 15:05:37.505
!MESSAGE SQL Warning (DataSource: 40D; Code: 4223; State: null): Origination unknown: [10228][11541][4.16.53] Security exceptions occurred while loading driver. ERRORCODE=4223, SQLSTATE=null

!ENTRY org.jkiss.dbeaver.model 4 0 2016-09-29 15:05:38.031
!MESSAGE org.jkiss.dbeaver.model.exec.DBCException
!SUBENTRY 1 org.jkiss.dbeaver.model 4 0 2016-09-29 15:05:38.031
!MESSAGE 
!STACK 0
java.lang.NullPointerException
	at org.jkiss.dbeaver.runtime.sql.SQLQueryJob.executeSingleQuery(SQLQueryJob.java:354)
	at org.jkiss.dbeaver.runtime.sql.SQLQueryJob.extractData(SQLQueryJob.java:719)
	at org.jkiss.dbeaver.ui.editors.sql.SQLEditor$QueryResultsContainer.readData(SQLEditor.java:1535)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetDataPumpJob.run(ResultSetDataPumpJob.java:139)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:103)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)

**Comment by serge-rider** [comment]
Well, these errors aren't directly related to UI freeze. Although NPE is definitely a bug and I've fixed it.
Maybe UI issues was a side-effect of NPE.
