### ISSUE TITLE
Keep-alive is not working properly

### ISSUE THREAD

**Issue by dimitriadisg** [serge-rider/dbeaver#860]
Hello,

I am trying to get the keep-alive to work, but probably I am missing something.

I am using a MySQL connection with SSH Tunnel, with public key, passphrase and save password enabled.

I'll describe my steps in Database Navigator :
If I use Keep-Alive interval 30 seconds - I can initialize the connection, but if I explore to Connection -> Databases -> mydbname -> Tables I am getting a connection error immediately.
   Connection with [myhost] lost
   Reason:
   SQL: Error [08S01]: Communications link failure
   The last packet successfully received from the server was 3,048 milliseconds ago. The last packet sent successfully to the server was 1 milliseconds ago.

If I use Keep-Alive interval 120 seconds (as shown in the keep-alives feature request), I can navigate in my database normally, but after 2 minutes, I am getting a similar error to the first case.

If I don't use Keep-Alive interval (set to 0), everything works normally and obviously I get timed out after a few minutes.

In all cases if I click "Test connection ..." before applying the changes, the connection is established successfully.

I tried figuring out what error 08S01 means, but it seems like a general connection error.

DBeaver version: 3.7.6 (current latest) - and earlier

Thanks in advance, let me know if I can provide more details !

**Comment by serge-rider** [comment]
Can't reproduce (in my case Keep-Alive works fine, connection never ends - no matter what keep-alive period I set). 
It looks like database ping operation just closes connection in your environment.

- What MySQL driver do you use (exact version)?
- Please check debug log (https://github.com/serge-rider/dbeaver/wiki/Log-files) for any related errors. In my case it contains lots of lines like this: 
`2016-10-19 14:07:36.903 - Ping connection mysql5-1423125916699-2071456069`
- Post first connectivity error (with stacktrace) from debug log.

**Comment by dimitriadisg** [comment]
I believe the driver used is JDBC, however I have no idea where it's installed or how to know its version. Any tips ?

<details> 
  <summary>Here is the first connection error from dbeaver-debug.log </summary>
    2016-10-19 11:48:03.096 - Connected (mysql5-157dc24f111-2a6e7b9c727b9cb4)
    2016-10-19 11:48:05.293 - SSH INFO: Caught an exception, leaving main loop due to Read timed out
    2016-10-19 11:48:05.298 - SSH INFO: Disconnecting from MY_HOST.COM port 22
    2016-10-19 11:48:15.991 - org.jkiss.dbeaver.model.exec.DBCException: SQL Error [08S01]: Communications link failure

    The last packet successfully received from the server was 12,888 milliseconds ago.  The last packet sent successfully to the server was 26 milliseconds ago.
    org.jkiss.dbeaver.model.exec.DBCException: SQL Error [08S01]: Communications link failure

    The last packet successfully received from the server was 12,888 milliseconds ago.  The last packet sent successfully to the server was 26 milliseconds ago.
        at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCPreparedStatementImpl.executeStatement(JDBCPreparedStatementImpl.java:199)
        at org.jkiss.dbeaver.model.impl.jdbc.cache.JDBCObjectCache.loadObjects(JDBCObjectCache.java:103)
        at org.jkiss.dbeaver.model.impl.jdbc.cache.JDBCObjectCache.getAllObjects(JDBCObjectCache.java:70)
        at org.jkiss.dbeaver.model.impl.AbstractObjectCache.getTypedObjects(AbstractObjectCache.java:76)
        at org.jkiss.dbeaver.ext.mysql.model.MySQLCatalog.getTables(MySQLCatalog.java:207)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.jkiss.dbeaver.model.navigator.DBNDatabaseNode.extractPropertyValue(DBNDatabaseNode.java:743)
        at org.jkiss.dbeaver.model.navigator.DBNDatabaseNode.loadTreeItems(DBNDatabaseNode.java:465)
        at org.jkiss.dbeaver.model.navigator.DBNDatabaseNode.loadChildren(DBNDatabaseNode.java:391)
        at org.jkiss.dbeaver.model.navigator.DBNDatabaseNode.getChildren(DBNDatabaseNode.java:190)
        at org.jkiss.dbeaver.model.navigator.DBNDatabaseNode.getChildren(DBNDatabaseNode.java:1)
        at org.jkiss.dbeaver.ui.navigator.database.load.TreeLoadService.evaluate(TreeLoadService.java:57)
        at org.jkiss.dbeaver.ui.navigator.database.load.TreeLoadService.evaluate(TreeLoadService.java:1)
        at org.jkiss.dbeaver.ui.LoadingJob.run(LoadingJob.java:83)
        at org.jkiss.dbeaver.ui.LoadingJob.run(LoadingJob.java:70)
        at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:103)
        at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)
    Caused by: com.mysql.jdbc.exceptions.jdbc4.CommunicationsException: Communications link failure

    The last packet successfully received from the server was 12,888 milliseconds ago.  The last packet sent successfully to the server was 26 milliseconds ago.
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
        at com.mysql.jdbc.Util.handleNewInstance(Util.java:404)
        at com.mysql.jdbc.SQLError.createCommunicationsException(SQLError.java:988)
        at com.mysql.jdbc.MysqlIO.reuseAndReadPacket(MysqlIO.java:3552)
        at com.mysql.jdbc.MysqlIO.reuseAndReadPacket(MysqlIO.java:3452)
        at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3893)
        at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2526)
        at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2673)
        at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2549)
        at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1861)
        at com.mysql.jdbc.PreparedStatement.execute(PreparedStatement.java:1192)
        at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCPreparedStatementImpl.execute(JDBCPreparedStatementImpl.java:252)
        at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCPreparedStatementImpl.executeStatement(JDBCPreparedStatementImpl.java:196)
        ... 19 more
    Caused by: java.net.SocketException: Software caused connection abort: recv failed
        at java.net.SocketInputStream.socketRead0(Native Method)
        at java.net.SocketInputStream.socketRead(SocketInputStream.java:116)
        at java.net.SocketInputStream.read(SocketInputStream.java:170)
        at java.net.SocketInputStream.read(SocketInputStream.java:141)
        at com.mysql.jdbc.util.ReadAheadInputStream.fill(ReadAheadInputStream.java:101)
        at com.mysql.jdbc.util.ReadAheadInputStream.readFromUnderlyingStreamIfNecessary(ReadAheadInputStream.java:144)
        at com.mysql.jdbc.util.ReadAheadInputStream.read(ReadAheadInputStream.java:174)
        at com.mysql.jdbc.MysqlIO.readFully(MysqlIO.java:3001)
        at com.mysql.jdbc.MysqlIO.reuseAndReadPacket(MysqlIO.java:3462)
        ... 28 more
</details>

**Comment by serge-rider** [comment]
Well, at least we know what happens:
```
2016-10-19 11:48:05.293 - SSH INFO: Caught an exception, leaving main loop due to Read timed out
2016-10-19 11:48:05.298 - SSH INFO: Disconnecting from MY_HOST.COM port 22
```
And this happens in 2 seconds after connection was established. Most likely as a result of keep-alive ping.
For now I have only one assumption: DBA of your MySQL server restricted usage of PING command - it's usage just closes connection immediately. Is this possible?
Potentially I can add some workaround for such situation..

To get driver version: open connection properties, click on "Edit Driver Settings"button. You will see driver version in the name of attached library:
![mysql-driver-settings](https://cloud.githubusercontent.com/assets/6398845/19520520/32ea25f8-9619-11e6-971a-41cd28878732.png)

**Comment by dimitriadisg** [comment]
My MySQL driver has exactly the same fields as yours, so I guess the version is 5.1.39.

That's right, the disconnection happens immediately in the case of 30 seconds.

Hmmm, unfortunately I am not familiar with the server's restrictions, I never had to do any configuration myself. So, how do I check this myself ?

I asked my colleague if he has the same problem with our server. He uses another database client and he has keep-alives enabled every 10 seconds without issues. Unfortunately, I don't know if his db client uses the PING command or something else, though.

**Comment by serge-rider** [comment]
That's a kind of a mystery.
I can use some other way to ping MySQL server (e.g. execute "SELECT 1" query).
Will look into it after 3.7.7 release.

**Comment by dimitriadisg** [comment]
Alright, let me know when the change is implemented so I can test.

Thanks !

**Comment by serge-rider** [comment]
This feature will be added in 3.7.8.

**Comment by dimitriadisg** [comment]
So, how do I change the keep-alive query ?

**Comment by serge-rider** [comment]
Well, you can't (at least for MySQL).
MySQL driver issues "SELECT 1" query for ping. 
Does it work in your environment?

**Comment by dimitriadisg** [comment]
Nope, still getting the same bug

<details>
<summary>Here's the log from dbeaver-debug.log</summary>
2016-11-01 09:22:34.397 - SSH INFO: Authentication succeeded (publickey).
2016-11-01 09:22:35.799 - Connected (mysql5-157dc24f111-2a6e7b9c727b9cb4)
2016-11-01 09:22:35.806 - SSH INFO: Disconnecting from MYHOST.com port 22
2016-11-01 09:22:35.815 - SSH INFO: Caught an exception, leaving main loop due to Socket Closed
2016-11-01 09:22:40.143 - Connect with 'MYHOST.com' (mysql5-157dc24f111-2a6e7b9c727b9cb4)
2016-11-01 09:22:40.156 - Instantiate SSH tunnel
2016-11-01 09:22:40.158 - Connect to tunnel host
2016-11-01 09:22:40.160 - SSH INFO: Connecting to MYHOST.com port 22
2016-11-01 09:22:40.179 - SSH INFO: Connection established
2016-11-01 09:22:40.223 - SSH INFO: Remote version string: SSH-2.0-OpenSSH_6.6.1
2016-11-01 09:22:40.225 - SSH INFO: Local version string: SSH-2.0-JSCH-0.1.53
2016-11-01 09:22:40.227 - SSH INFO: CheckCiphers: aes256-ctr,aes192-ctr,aes128-ctr,aes256-cbc,aes192-cbc,aes128-cbc,3des-ctr,arcfour,arcfour128,arcfour256
2016-11-01 09:22:40.235 - SSH INFO: CheckKexes: diffie-hellman-group14-sha1,ecdh-sha2-nistp256,ecdh-sha2-nistp384,ecdh-sha2-nistp521
2016-11-01 09:22:40.291 - SSH INFO: CheckSignatures: ecdsa-sha2-nistp256,ecdsa-sha2-nistp384,ecdsa-sha2-nistp521
2016-11-01 09:22:40.293 - SSH INFO: SSH_MSG_KEXINIT sent
2016-11-01 09:22:40.295 - SSH INFO: SSH_MSG_KEXINIT received
2016-11-01 09:22:40.296 - SSH INFO: kex: server: curve25519-sha256@libssh.org,ecdh-sha2-nistp256,ecdh-sha2-nistp384,ecdh-sha2-nistp521,diffie-hellman-group-exchange-sha256,diffie-hellman-group-exchange-sha1,diffie-hellman-group14-sha1,diffie-hellman-group1-sha1
2016-11-01 09:22:40.300 - SSH INFO: kex: server: ssh-rsa,ecdsa-sha2-nistp256,ssh-ed25519
2016-11-01 09:22:40.302 - SSH INFO: kex: server: aes128-ctr,aes192-ctr,aes256-ctr,arcfour256,arcfour128,aes128-gcm@openssh.com,aes256-gcm@openssh.com,chacha20-poly1305@openssh.com,aes128-cbc,3des-cbc,blowfish-cbc,cast128-cbc,aes192-cbc,aes256-cbc,arcfour,rijndael-cbc@lysator.liu.se
2016-11-01 09:22:40.306 - SSH INFO: kex: server: aes128-ctr,aes192-ctr,aes256-ctr,arcfour256,arcfour128,aes128-gcm@openssh.com,aes256-gcm@openssh.com,chacha20-poly1305@openssh.com,aes128-cbc,3des-cbc,blowfish-cbc,cast128-cbc,aes192-cbc,aes256-cbc,arcfour,rijndael-cbc@lysator.liu.se
2016-11-01 09:22:40.311 - SSH INFO: kex: server: hmac-md5-etm@openssh.com,hmac-sha1-etm@openssh.com,umac-64-etm@openssh.com,umac-128-etm@openssh.com,hmac-sha2-256-etm@openssh.com,hmac-sha2-512-etm@openssh.com,hmac-ripemd160-etm@openssh.com,hmac-sha1-96-etm@openssh.com,hmac-md5-96-etm@openssh.com,hmac-md5,hmac-sha1,umac-64@openssh.com,umac-128@openssh.com,hmac-sha2-256,hmac-sha2-512,hmac-ripemd160,hmac-ripemd160@openssh.com,hmac-sha1-96,hmac-md5-96
2016-11-01 09:22:40.318 - SSH INFO: kex: server: hmac-md5-etm@openssh.com,hmac-sha1-etm@openssh.com,umac-64-etm@openssh.com,umac-128-etm@openssh.com,hmac-sha2-256-etm@openssh.com,hmac-sha2-512-etm@openssh.com,hmac-ripemd160-etm@openssh.com,hmac-sha1-96-etm@openssh.com,hmac-md5-96-etm@openssh.com,hmac-md5,hmac-sha1,umac-64@openssh.com,umac-128@openssh.com,hmac-sha2-256,hmac-sha2-512,hmac-ripemd160,hmac-ripemd160@openssh.com,hmac-sha1-96,hmac-md5-96
2016-11-01 09:22:40.324 - SSH INFO: kex: server: none,zlib@openssh.com
2016-11-01 09:22:40.325 - SSH INFO: kex: server: none,zlib@openssh.com
2016-11-01 09:22:40.327 - SSH INFO: kex: server: 
2016-11-01 09:22:40.327 - SSH INFO: kex: server: 
2016-11-01 09:22:40.328 - SSH INFO: kex: client: ecdh-sha2-nistp256,ecdh-sha2-nistp384,ecdh-sha2-nistp521,diffie-hellman-group14-sha1,diffie-hellman-group-exchange-sha256,diffie-hellman-group-exchange-sha1,diffie-hellman-group1-sha1
2016-11-01 09:22:40.332 - SSH INFO: kex: client: ssh-rsa,ssh-dss,ecdsa-sha2-nistp256,ecdsa-sha2-nistp384,ecdsa-sha2-nistp521
2016-11-01 09:22:40.334 - SSH INFO: kex: client: aes128-ctr,aes128-cbc,3des-ctr,3des-cbc,blowfish-cbc,aes192-ctr,aes192-cbc,aes256-ctr,aes256-cbc
2016-11-01 09:22:40.337 - SSH INFO: kex: client: aes128-ctr,aes128-cbc,3des-ctr,3des-cbc,blowfish-cbc,aes192-ctr,aes192-cbc,aes256-ctr,aes256-cbc
2016-11-01 09:22:40.339 - SSH INFO: kex: client: hmac-md5,hmac-sha1,hmac-sha2-256,hmac-sha1-96,hmac-md5-96
2016-11-01 09:22:40.341 - SSH INFO: kex: client: hmac-md5,hmac-sha1,hmac-sha2-256,hmac-sha1-96,hmac-md5-96
2016-11-01 09:22:40.343 - SSH INFO: kex: client: none
2016-11-01 09:22:40.344 - SSH INFO: kex: client: none
2016-11-01 09:22:40.344 - SSH INFO: kex: client: 
2016-11-01 09:22:40.345 - SSH INFO: kex: client: 
2016-11-01 09:22:40.346 - SSH INFO: kex: server->client aes128-ctr hmac-md5 none
2016-11-01 09:22:40.348 - SSH INFO: kex: client->server aes128-ctr hmac-md5 none
2016-11-01 09:22:40.351 - SSH INFO: SSH_MSG_KEX_ECDH_INIT sent
2016-11-01 09:22:40.352 - SSH INFO: expecting SSH_MSG_KEX_ECDH_REPLY
2016-11-01 09:22:40.376 - SSH INFO: ssh_rsa_verify: signature true
2016-11-01 09:22:40.378 - SSH INFO: Host 'MYHOST.com' is known and matches the RSA host key
2016-11-01 09:22:40.380 - SSH INFO: SSH_MSG_NEWKEYS sent
2016-11-01 09:22:40.381 - SSH INFO: SSH_MSG_NEWKEYS received
2016-11-01 09:22:40.382 - SSH INFO: SSH_MSG_SERVICE_REQUEST sent
2016-11-01 09:22:40.393 - SSH INFO: SSH_MSG_SERVICE_ACCEPT received
2016-11-01 09:22:40.411 - SSH INFO: Authentications that can continue: publickey
2016-11-01 09:22:40.412 - SSH INFO: Next authentication method: publickey
2016-11-01 09:22:40.618 - SSH INFO: Authentication succeeded (publickey).
2016-11-01 09:22:41.813 - Connected (mysql5-157dc24f111-2a6e7b9c727b9cb4)
2016-11-01 09:22:44.310 - SSH INFO: Caught an exception, leaving main loop due to Read timed out
2016-11-01 09:22:44.316 - SSH INFO: Disconnecting from MYHOST.com port 22
2016-11-01 09:22:44.732 - org.jkiss.dbeaver.model.exec.DBCException: SQL Error [08S01]: Communications link failure

The last packet successfully received from the server was 2,911 milliseconds ago.  The last packet sent successfully to the server was 32 milliseconds ago.
org.jkiss.dbeaver.model.exec.DBCException: SQL Error [08S01]: Communications link failure

The last packet successfully received from the server was 2,911 milliseconds ago.  The last packet sent successfully to the server was 32 milliseconds ago.
    at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCPreparedStatementImpl.executeStatement(JDBCPreparedStatementImpl.java:199)
    at org.jkiss.dbeaver.model.impl.jdbc.cache.JDBCObjectCache.loadObjects(JDBCObjectCache.java:103)
    at org.jkiss.dbeaver.model.impl.jdbc.cache.JDBCObjectCache.getAllObjects(JDBCObjectCache.java:70)
    at org.jkiss.dbeaver.model.impl.AbstractObjectCache.getTypedObjects(AbstractObjectCache.java:76)
    at org.jkiss.dbeaver.ext.mysql.model.MySQLCatalog.getTables(MySQLCatalog.java:207)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at org.jkiss.dbeaver.model.navigator.DBNDatabaseNode.extractPropertyValue(DBNDatabaseNode.java:743)
    at org.jkiss.dbeaver.model.navigator.DBNDatabaseNode.loadTreeItems(DBNDatabaseNode.java:465)
    at org.jkiss.dbeaver.model.navigator.DBNDatabaseNode.loadChildren(DBNDatabaseNode.java:391)
    at org.jkiss.dbeaver.model.navigator.DBNDatabaseNode.getChildren(DBNDatabaseNode.java:190)
    at org.jkiss.dbeaver.model.navigator.DBNDatabaseNode.getChildren(DBNDatabaseNode.java:1)
    at org.jkiss.dbeaver.ui.navigator.database.load.TreeLoadService.evaluate(TreeLoadService.java:57)
    at org.jkiss.dbeaver.ui.navigator.database.load.TreeLoadService.evaluate(TreeLoadService.java:1)
    at org.jkiss.dbeaver.ui.LoadingJob.run(LoadingJob.java:83)
    at org.jkiss.dbeaver.ui.LoadingJob.run(LoadingJob.java:70)
    at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:103)
    at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)
Caused by: com.mysql.jdbc.exceptions.jdbc4.CommunicationsException: Communications link failure

The last packet successfully received from the server was 2,911 milliseconds ago.  The last packet sent successfully to the server was 32 milliseconds ago.
    at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
    at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
    at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
    at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
    at com.mysql.jdbc.Util.handleNewInstance(Util.java:404)
    at com.mysql.jdbc.SQLError.createCommunicationsException(SQLError.java:988)
    at com.mysql.jdbc.MysqlIO.reuseAndReadPacket(MysqlIO.java:3552)
    at com.mysql.jdbc.MysqlIO.reuseAndReadPacket(MysqlIO.java:3452)
    at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3893)
    at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2526)
    at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2673)
    at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2549)
    at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1861)
    at com.mysql.jdbc.PreparedStatement.execute(PreparedStatement.java:1192)
    at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCPreparedStatementImpl.execute(JDBCPreparedStatementImpl.java:252)
    at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCPreparedStatementImpl.executeStatement(JDBCPreparedStatementImpl.java:196)
    ... 19 more
Caused by: java.net.SocketException: Software caused connection abort: recv failed
    at java.net.SocketInputStream.socketRead0(Native Method)
    at java.net.SocketInputStream.socketRead(SocketInputStream.java:116)
    at java.net.SocketInputStream.read(SocketInputStream.java:170)
    at java.net.SocketInputStream.read(SocketInputStream.java:141)
    at com.mysql.jdbc.util.ReadAheadInputStream.fill(ReadAheadInputStream.java:101)
    at com.mysql.jdbc.util.ReadAheadInputStream.readFromUnderlyingStreamIfNecessary(ReadAheadInputStream.java:144)
    at com.mysql.jdbc.util.ReadAheadInputStream.read(ReadAheadInputStream.java:174)
    at com.mysql.jdbc.MysqlIO.readFully(MysqlIO.java:3001)
    at com.mysql.jdbc.MysqlIO.reuseAndReadPacket(MysqlIO.java:3462)
    ... 28 more
</details>

**Comment by serge-rider** [comment]
Well, this looks like SSH tunnel was closed, not MySQL connection.
Have no ideas how to fix this so far.
I need to think about that :)

**Comment by serge-rider** [comment]
Maybe the problem was in SSH connect timeout (#971)

**Comment by dimitriadisg** [comment]
Alright then, let me know in which version I should test again !

**Comment by serge-rider** [comment]
In the next version (see milestone info on the right panel).

**Comment by dimitriadisg** [comment]
Problem still there in 3.8
Timeout set to 10000 ms (default) and keepalive to 30, still disconnects immediately.
Timeout set to 10000 ms (default) and keepalive to 0, still disconnects after an idle period.

**Comment by dimitriadisg** [comment]
Here is something interesting, if I set the keep-alive to 10000 everything works smooth ! My connection is not timed-out.

Could it be that the keep-alive should be specified in milliseconds instead of seconds ?

**Comment by Desmaster** [comment]
Having the same kind of problem. 

When I don't use keep alive, it crashes after a while. When I configure it to every 10/20/30 seconds, it crashes when sending the keep alive.. 

@dimitriadisg Going to try setting it to 10000 then..

**Comment by serge-rider** [comment]
There are multiple keep-alive settings:
1. DBeaver connection keep-alive interval (present on General page of connection settings). It is in seconds.
2. SSH tunnel keep-alive interval (on SSH settings page). It is in milliseconds (there was a bug saying that it is in seconds). Thanks for noticing - fixed.
3. Driver specific keep-alive interval. Can be set on connection driver settings page. Measure units depends on driver.

**Comment by Desmaster** [comment]
Knowing that it's milliseconds, the issues make a lot of sense. Thanks!

**Comment by dimitriadisg** [comment]
Oh, didn't know there is a general setting, I could use that, thanks !
I guess we can say the issue is solve then,

Cheers !
