### ISSUE TITLE
Error when closing project

### ISSUE THREAD

**Issue by DeepSnowNeeL** [serge-rider/dbeaver#899]
Here is the eclipse report, the project was open and I just right click > Close project and this happenned. I hope it can help you fix it.

REPORT
 
eclipseBuildId      4.6.1.M20160907-1200
eclipseProduct      org.eclipse.epp.package.php.product
javaRuntimeVersion  1.8.0_77-b03
osgiWs              win32
osgiOs              Windows7
osgiOsVersion       6.1.0
osgiArch            x86
severity            UNKNOWN

STATUS

pluginId            org.eclipse.core.resources
pluginVersion       3.11.0.v20160503-1608
code                2
severity            4
message             Problems occurred when invoking code from plug-in: "org.eclipse.core.resources".
fingerprint         87fe2ef9ab42d5485fa86d280a22243e

Exception:java.lang.IllegalStateException: Can't read project contents
	 at org.jkiss.dbeaver.model.navigator.DBNProject.getDatabases(DBNProject.java:70)
	 at org.jkiss.dbeaver.model.navigator.DBNProject.openProject(DBNProject.java:180)
	 at org.jkiss.dbeaver.model.navigator.DBNModel.resourceChanged(DBNModel.java:503)
	 at org.eclipse.core.internal.events.NotificationManager$1.run(NotificationManager.java:299)
	 at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	 at org.eclipse.core.internal.events.NotificationManager.notify(NotificationManager.java:289)
	 at org.eclipse.core.internal.events.NotificationManager.broadcastChanges(NotificationManager.java:152)
	 at org.eclipse.core.internal.resources.Workspace.broadcastPostChange(Workspace.java:374)
	 at org.eclipse.core.internal.resources.Workspace.endOperation(Workspace.java:1469)
	 at org.eclipse.core.internal.resources.InternalWorkspaceJob.run(InternalWorkspaceJob.java:46)
	 at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)
Caused by: org.jkiss.dbeaver.DBException: Can't open project 'javaparser-core'
	 at org.jkiss.dbeaver.model.navigator.DBNProject.readChildNodes(DBNProject.java:135)
	 at org.jkiss.dbeaver.model.navigator.DBNResource.getChildren(DBNResource.java:147)
	 at org.jkiss.dbeaver.model.navigator.DBNProject.getDatabases(DBNProject.java:64)
	 at org.jkiss.dbeaver.model.navigator.DBNProject.openProject(DBNProject.java:180)
	 at org.jkiss.dbeaver.model.navigator.DBNModel.resourceChanged(DBNModel.java:503)
	 at org.eclipse.core.internal.events.NotificationManager$1.run(NotificationManager.java:299)
	 at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	 at org.eclipse.core.internal.events.NotificationManager.notify(NotificationManager.java:289)
	 at org.eclipse.core.internal.events.NotificationManager.broadcastChanges(NotificationManager.java:152)
	 at org.eclipse.core.internal.resources.Workspace.broadcastPostChange(Workspace.java:374)
	 at org.eclipse.core.internal.resources.Workspace.endOperation(Workspace.java:1469)
	 at org.eclipse.core.internal.resources.InternalWorkspaceJob.run(InternalWorkspaceJob.java:46)
	 at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)
Caused by: org.eclipse.core.internal.resources.ResourceException: The resource tree is locked for modifications.
	 at org.eclipse.core.internal.resources.WorkManager.checkIn(WorkManager.java:119)
	 at org.eclipse.core.internal.resources.Workspace.prepareOperation(Workspace.java:2188)
	 at org.eclipse.core.internal.resources.Project.open(Project.java:998)
	 at org.eclipse.core.internal.resources.Project.open(Project.java:1087)
	 at org.jkiss.dbeaver.model.navigator.DBNProject.readChildNodes(DBNProject.java:132)
	 at org.jkiss.dbeaver.model.navigator.DBNResource.getChildren(DBNResource.java:147)
	 at org.jkiss.dbeaver.model.navigator.DBNProject.getDatabases(DBNProject.java:64)
	 at org.jkiss.dbeaver.model.navigator.DBNProject.openProject(DBNProject.java:180)
	 at org.jkiss.dbeaver.model.navigator.DBNModel.resourceChanged(DBNModel.java:503)
	 at org.eclipse.core.internal.events.NotificationManager$1.run(NotificationManager.java:299)
	 at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	 at org.eclipse.core.internal.events.NotificationManager.notify(NotificationManager.java:289)
	 at org.eclipse.core.internal.events.NotificationManager.broadcastChanges(NotificationManager.java:152)
	 at org.eclipse.core.internal.resources.Workspace.broadcastPostChange(Workspace.java:374)
	 at org.eclipse.core.internal.resources.Workspace.endOperation(Workspace.java:1469)
	 at org.eclipse.core.internal.resources.InternalWorkspaceJob.run(InternalWorkspaceJob.java:46)
	 at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)

STATUS

pluginId            org.eclipse.core.resources
pluginVersion       3.11.0.v20160503-1608
code                380
severity            4
message             The resource tree is locked for modifications. [detached from CoreException of Status 'Problems occurred when invoking code from plug-in: "org.eclipse.core.resources".' by Error Reporting]
fingerprint         6c9fc5ab0de74388ebf79359c36c0ae8

BUNDLES

name                org.eclipse.core.jobs
version             3.8.0.v20160509-0411

name                org.eclipse.core.resources
version             3.11.0.v20160503-1608

name                org.eclipse.core.runtime
version             3.12.0.v20160606-1342

name                org.jkiss.dbeaver.model
version             1.0.32

**Comment by serge-rider** [comment]
Thanks for report
