### ISSUE TITLE
Looking through the error logs I saw a Null Pointer Exception

### ISSUE THREAD

**Issue by r-richmond** [serge-rider/dbeaver#905]
```
java.lang.NullPointerException
	at org.jkiss.dbeaver.model.sql.SQLUtils.stripComments(SQLUtils.java:87)
	at org.jkiss.dbeaver.model.sql.SQLUtils.stripComments(SQLUtils.java:75)
	at org.jkiss.dbeaver.ui.editors.sql.syntax.SQLCompletionProcessor.getTableFromAlias(SQLCompletionProcessor.java:487)
	at org.jkiss.dbeaver.ui.editors.sql.syntax.SQLCompletionProcessor.makeStructureProposals(SQLCompletionProcessor.java:274)
	at org.jkiss.dbeaver.ui.editors.sql.syntax.SQLCompletionProcessor.access$0(SQLCompletionProcessor.java:256)
	at org.jkiss.dbeaver.ui.editors.sql.syntax.SQLCompletionProcessor$ProposalSearchJob.run(SQLCompletionProcessor.java:935)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:103)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)

```

**Comment by serge-rider** [comment]
Most likely this issue was already resolved. Your version is outdated and there were a few fixes in SQL completion.

**Comment by r-richmond** [comment]
yea the date on that was before I upgraded.
