### ISSUE TITLE
Invalid thread access on tunnel opening

### ISSUE THREAD

**Issue by Azenet** [serge-rider/dbeaver#931]
Hi,

An `SWTException` is thrown when trying to unfold a connection that uses a SSH tunnel for which the password is not stored instead of showing the user/password prompt. The user/password prompt is shown properly when right-clicking the connection > Connect.

Relevant stack trace:
```
2016-11-02 15:00:47.017 - org.eclipse.swt.SWTException: Invalid thread access
org.eclipse.swt.SWTException: Invalid thread access
        at org.eclipse.swt.SWT.error(SWT.java:4491)
        at org.eclipse.swt.SWT.error(SWT.java:4406)
        at org.eclipse.swt.SWT.error(SWT.java:4377)
        at org.eclipse.swt.widgets.Display.error(Display.java:1186)
        at org.eclipse.swt.widgets.Display.checkDevice(Display.java:765)
        at org.eclipse.swt.widgets.Display.getActiveShell(Display.java:1400)
        at org.jkiss.dbeaver.core.DBeaverUI.getActiveWorkbenchShell(DBeaverUI.java:184)
        at org.jkiss.dbeaver.core.DBeaverUI.promptUserCredentials(DBeaverUI.java:351)
        at org.jkiss.dbeaver.ui.actions.datasource.DataSourceHandler.askForPassword(DataSourceHandler.java:179)
        at org.jkiss.dbeaver.ui.actions.datasource.DataSourceHandler.connectToDataSource(DataSourceHandler.java:92)
        at org.jkiss.dbeaver.registry.DataSourceDescriptor.initConnection(DataSourceDescriptor.java:602)
        at org.jkiss.dbeaver.model.navigator.DBNDataSource.initializeNode(DBNDataSource.java:123)
        at org.jkiss.dbeaver.model.navigator.DBNDatabaseNode.getChildren(DBNDatabaseNode.java:188)
        at org.jkiss.dbeaver.model.navigator.DBNDatabaseNode.getChildren(DBNDatabaseNode.java:1)
        at org.jkiss.dbeaver.ui.navigator.database.load.TreeLoadService.evaluate(TreeLoadService.java:57)
        at org.jkiss.dbeaver.ui.navigator.database.load.TreeLoadService.evaluate(TreeLoadService.java:1)
        at org.jkiss.dbeaver.ui.LoadingJob.run(LoadingJob.java:83)
        at org.jkiss.dbeaver.ui.LoadingJob.run(LoadingJob.java:70)
        at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:103)
        at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)

```

**Comment by serge-rider** [comment]
Thanks for report, will be fixed in the next version.
Workaround: select connection and click on "Connect" icon. Or open SQL editor for that connection.
