### ISSUE TITLE
Cassandra connection using SSH Tunnel not connecting

### ISSUE THREAD

**Issue by robinson-scott** [serge-rider/dbeaver#938]
Windows 10 client to Cassnadra on Centos 7.2.
If I manually create an openssh tunnel with the same information, I can connect to cassandra.
SSH tunnel to mongo works fine.

**Details:**
Using DBeaver version: 3.7.7 (windows 10 x64 client)
Cassandra version:  3.0.8 (centos 7.2)

**Trying to connect to a Linux Cassandra node from the windows DBeaver client using:**
	Host: localhost, Port: 9042, Keyspace: system
	[x] Use SSH Tunnel
	Host/IP: 10.250.1.32
	Port: 22
	Username: xxx
	Password: yyy
	[x] Save Password

**Getting this error:**
com.datastax.driver.core.exceptions.NoHostAvailableException: All host(s) tried for query failed (tried: localhost/127.0.0.1:9042 (com.datastax.driver.core.exceptions.TransportException: [localhost/127.0.0.1] Cannot connect), localhost/0:0:0:0:0:0:0:1:9042 (com.datastax.driver.core.exceptions.TransportException: [localhost/0:0:0:0:0:0:0:1] Cannot connect))

If I create a tunnel using SSH using the command below and just uncheck 'Use SSH', it works fine.
	ssh  -L 9042:localhost:9042 xxx@10.250.1.32

Connecting to mongo DBs using DBeaver built-in SSH tunnel works just fine.

**Here's the .log info for the connection:**
	!SESSION 2016-11-02 18:00:24.390 -----------------------------------------------
	eclipse.buildId=unknown
	java.version=1.8.0_77
	java.vendor=Oracle Corporation
	BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=en
	Command-line arguments:  -os win32 -ws win32 -arch x86_64
	
	!ENTRY org.jkiss.dbeaver.model 1 0 2016-11-02 18:00:29.348
	!MESSAGE IPM Server 1.0.1551-1
	
	
**Here's the java version info from the a cmd window:**
	H:\>java -XshowSettings:properties -version
	Property settings:
	    awt.toolkit = sun.awt.windows.WToolkit
	    file.encoding = Cp1252
	    file.encoding.pkg = sun.io
	    file.separator = \
	    java.awt.graphicsenv = sun.awt.Win32GraphicsEnvironment
	    java.awt.printerjob = sun.awt.windows.WPrinterJob
	    java.class.path = .
	    java.class.version = 52.0
	    java.endorsed.dirs = C:\Program Files (x86)\Java\jre1.8.0_111\lib\endorsed
	    java.ext.dirs = C:\Program Files (x86)\Java\jre1.8.0_111\lib\ext
	        C:\Windows\Sun\Java\lib\ext
	    java.home = C:\Program Files (x86)\Java\jre1.8.0_111
	    java.io.tmpdir = C:\Users\srobinso\AppData\Local\Temp\
	    java.library.path = C:\ProgramData\Oracle\Java\javapath
	        C:\Windows\Sun\Java\bin
	        C:\Windows\system32
	        C:\Windows
	        C:\ProgramData\Oracle\Java\javapath
	        C:\Program Files (x86)\Intel\iCLS Client\
	        C:\Program Files\Intel\iCLS Client\
	        C:\Windows\system32
	        C:\Windows
	        C:\Windows\System32\Wbem
	        C:\Windows\System32\WindowsPowerShell\v1.0\
	        C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\DAL
	        C:\Program Files\Intel\Intel(R) Management Engine Components\DAL
	        C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\IPT
	        C:\Program Files\Intel\Intel(R) Management Engine Components\IPT
	        C:\Program Files (x86)\Sennheiser\SoftphoneSDK\
	        C:\Program Files (x86)\Skype\Phone\
	        C:\Program Files (x86)\PuTTY\
	        C:\HashiCorp\Vagrant\bin
	        .
	    java.runtime.name = Java(TM) SE Runtime Environment
	    java.runtime.version = 1.8.0_111-b14
	    java.specification.name = Java Platform API Specification
	    java.specification.vendor = Oracle Corporation
	    java.specification.version = 1.8
	    java.vendor = Oracle Corporation
	    java.vendor.url = http://java.oracle.com/
	    java.vendor.url.bug = http://bugreport.sun.com/bugreport/
	    java.version = 1.8.0_111
	    java.vm.info = mixed mode
	    java.vm.name = Java HotSpot(TM) Client VM
	    java.vm.specification.name = Java Virtual Machine Specification
	    java.vm.specification.vendor = Oracle Corporation
	    java.vm.specification.version = 1.8
	    java.vm.vendor = Oracle Corporation
	    java.vm.version = 25.111-b14
	    line.separator = \r \n
	    os.arch = x86
	    os.name = Windows 10
	    os.version = 10.0
	    path.separator = ;
	    sun.arch.data.model = 32
	    sun.boot.class.path = C:\Program Files (x86)\Java\jre1.8.0_111\lib\resources.jar
	        C:\Program Files (x86)\Java\jre1.8.0_111\lib\rt.jar
	        C:\Program Files (x86)\Java\jre1.8.0_111\lib\sunrsasign.jar
	        C:\Program Files (x86)\Java\jre1.8.0_111\lib\jsse.jar
	        C:\Program Files (x86)\Java\jre1.8.0_111\lib\jce.jar
	        C:\Program Files (x86)\Java\jre1.8.0_111\lib\charsets.jar
	        C:\Program Files (x86)\Java\jre1.8.0_111\lib\jfr.jar
	        C:\Program Files (x86)\Java\jre1.8.0_111\classes
	    sun.boot.library.path = C:\Program Files (x86)\Java\jre1.8.0_111\bin
	    sun.cpu.endian = little
	    sun.cpu.isalist = pentium_pro+mmx pentium_pro pentium+mmx pentium i486 i386 i86
	    sun.desktop = windows
	    sun.io.unicode.encoding = UnicodeLittle
	    sun.java.launcher = SUN_STANDARD
	    sun.jnu.encoding = Cp1252
	    sun.management.compiler = HotSpot Client Compiler
	    sun.os.patch.level =
	    sun.stderr.encoding = cp437
	    sun.stdout.encoding = cp437
	    user.country = US
	    user.dir = H:\
	    user.home = C:\Users\srobinso
	    user.language = en
	    user.name = srobinso
	    user.script =
	    user.timezone =
	    user.variant =
	
	java version "1.8.0_111"
	Java(TM) SE Runtime Environment (build 1.8.0_111-b14)
	Java HotSpot(TM) Client VM (build 25.111-b14, mixed mode)

**From dbeaver-debug.log:**
	2016-11-03 08:44:52.290 - SSH INFO: SSH_MSG_NEWKEYS received
	2016-11-03 08:44:52.295 - SSH INFO: SSH_MSG_SERVICE_REQUEST sent
	2016-11-03 08:44:52.297 - SSH INFO: SSH_MSG_SERVICE_ACCEPT received
	2016-11-03 08:44:52.304 - IPM Server 1.0.1554-1
	
	2016-11-03 08:44:52.310 - SSH INFO: Authentications that can continue: password
	2016-11-03 08:44:52.311 - SSH INFO: Next authentication method: password
	2016-11-03 08:44:52.316 - SSH INFO: Authentication succeeded (password).
	2016-11-03 08:44:52.322 - > Start com.jkiss.dbeaver.ent.cassandra [2.0.16]
	SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
	SLF4J: Defaulting to no-operation (NOP) logger implementation
	SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
	2016-11-03 08:44:54.552 - Open [http://dbeaver.jkiss.org/product/version.xml]
	2016-11-03 08:44:54.646 - Connection failed (cql-1582137777b-356363384a37bca9)
	2016-11-03 08:44:54.657 - org.jkiss.dbeaver.model.exec.DBCException: All host(s) tried for query failed (tried: localhost/127.0.0.1:9042 (com.datastax.driver.core.exceptions.TransportException: [localhost/127.0.0.1] Cannot connect), localhost/0:0:0:0:0:0:0:1:9042 (com.datastax.driver.core.exceptions.TransportException: [localhost/0:0:0:0:0:0:0:1] Cannot connect))
	org.jkiss.dbeaver.model.exec.DBCException: All host(s) tried for query failed (tried: localhost/127.0.0.1:9042 (com.datastax.driver.core.exceptions.TransportException: [localhost/127.0.0.1] Cannot connect), localhost/0:0:0:0:0:0:0:1:9042 (com.datastax.driver.core.exceptions.TransportException: [localhost/0:0:0:0:0:0:0:1] Cannot connect))
		at com.jkiss.dbeaver.ent.cassandra.model.CasExecutionContext.connect(CasExecutionContext.java:56)
		at com.jkiss.dbeaver.ent.cassandra.model.CasDataSource.<init>(CasDataSource.java:103)
		at com.jkiss.dbeaver.ent.cassandra.CasDataSourceProvider.openDataSource(CasDataSourceProvider.java:65)
		at org.jkiss.dbeaver.registry.DataSourceDescriptor.connect(DataSourceDescriptor.java:644)
		at org.jkiss.dbeaver.runtime.jobs.ConnectJob.run(ConnectJob.java:74)
		at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:103)
		at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)
	Caused by: com.datastax.driver.core.exceptions.NoHostAvailableException: All host(s) tried for query failed (tried: localhost/127.0.0.1:9042 (com.datastax.driver.core.exceptions.TransportException: [localhost/127.0.0.1] Cannot connect), localhost/0:0:0:0:0:0:0:1:9042 (com.datastax.driver.core.exceptions.TransportException: [localhost/0:0:0:0:0:0:0:1] Cannot connect))
		at com.datastax.driver.core.ControlConnection.reconnectInternal(ControlConnection.java:231)
		at com.datastax.driver.core.ControlConnection.connect(ControlConnection.java:77)
		at com.datastax.driver.core.Cluster$Manager.init(Cluster.java:1382)
		at com.datastax.driver.core.Cluster.init(Cluster.java:162)
		at com.datastax.driver.core.Cluster.connectAsync(Cluster.java:333)
		at com.datastax.driver.core.Cluster.connect(Cluster.java:283)
		at com.jkiss.dbeaver.ent.cassandra.model.CasExecutionContext.reconnect(CasExecutionContext.java:112)
		at com.jkiss.dbeaver.ent.cassandra.model.CasExecutionContext.connect(CasExecutionContext.java:52)
		... 6 more

**Comment by serge-rider** [comment]
That's a bug in DBeaver, Cassandra extension uses wrong port number. Will be fixed in the next version, thanks for report.

**Comment by rmatte01** [comment]
Refer: https://github.com/serge-rider/dbeaver/issues/938
