### ISSUE TITLE
[GNU/Linux] Not running in noexe mounted home

### ISSUE THREAD

**Issue by alexander-alzate** [serge-rider/dbeaver#960]
When home is mounted with noexe mount-option dbeaver doesn't work.

**Comment by serge-rider** [comment]
Any errors in console/logs?

BTW you can start DBeaver with cl parameter "-data <path>" and set different workspace location.

**Comment by alexander-alzate** [comment]
- ~/ $: dbeaver -debug -verbose
~~~
Start VM: /usr/bin/java
-jar /opt/dbeaver//plugins/org.eclipse.equinox.launcher_1.3.100.v20150511-1540.jar
-os linux
-ws gtk
-arch x86_64
-showsplash
-launcher /opt/dbeaver/dbeaver
-name Dbeaver
--launcher.library /opt/dbeaver//plugins/org.eclipse.equinox.launcher.gtk.linux.x86_64_1.1.300.v20150602-1417/eclipse_1612.so
-startup /opt/dbeaver//plugins/org.eclipse.equinox.launcher_1.3.100.v20150511-1540.jar
--launcher.overrideVmargs
-exitdata e000a
-debug
-verbose
-vm /usr/bin/java
-vmargs
-jar /opt/dbeaver//plugins/org.eclipse.equinox.launcher_1.3.100.v20150511-1540.jar 
Install location:
    file:/opt/dbeaver/
Configuration file:
    file:/opt/dbeaver/configuration/config.ini loaded
Configuration location:
    file:$HOME/.eclipse/org.jkiss.dbeaver.product_3.7.8_1898519774_linux_gtk_x86_64/configuration/
Configuration file:
    file:$HOME/.eclipse/org.jkiss.dbeaver.product_3.7.8_1898519774_linux_gtk_x86_64/configuration/config.ini loaded
Loading timestamp file from:
	 file:$HOME/.eclipse/org.jkiss.dbeaver.product_3.7.8_1898519774_linux_gtk_x86_64/configuration/   .baseConfigIniTimestamp
	No timestamp file found
Timestamps found: 
	 config.ini in the base: 1478642214000
	 remembered -1
Shared configuration location:
    file:/opt/dbeaver/configuration/
Framework located:
    file:/opt/dbeaver/plugins/org.eclipse.osgi_3.10.102.v20160118-1700.jar
Loading extension: reference:file:org.eclipse.osgi.compatibility.state_1.0.100.v20150402-1551.jar
	eclipse.properties not found
Framework classpath:
    file:/opt/dbeaver/plugins/org.eclipse.osgi_3.10.102.v20160118-1700.jar
    file:/opt/dbeaver/plugins/
    file:/opt/dbeaver/plugins/org.eclipse.osgi.compatibility.state_1.0.100.v20150402-1551.jar
Splash location:
    $HOME/.eclipse/org.jkiss.dbeaver.product_3.7.8_1898519774_linux_gtk_x86_64/configuration/org.eclipse.equinox.launcher/org.jkiss.dbeaver.core.application_3.7.8/splash.bmp
Debug options:
    file:$HOME/.options loaded
Time to load bundles: 4
Starting application: 2343
2016-11-10 15:21:03.120 - DBeaver 3.7.8 is starting
2016-11-10 15:21:03.137 - Install path: '/opt/dbeaver'
2016-11-10 15:21:03.138 - Instance path: 'file:$HOME/.dbeaver/'
2016-11-10 15:21:03.139 - Memory available 56Mb/814Mb
2016-11-10 15:21:03.159 - Starting RMI server at 51592
2016-11-10 15:21:03.311 - Initialize display
~~~
- ~/ $: cat .dbeaver/.metadata/.log
~~~
!SESSION 2016-11-10 15:23:37.730 -----------------------------------------------
eclipse.buildId=unknown
java.version=1.8.0_112
java.vendor=Oracle Corporation
BootLoader constants: OS=linux, ARCH=x86_64, WS=gtk, NL=en_US
Framework arguments:  -verbose
Command-line arguments:  -os linux -ws gtk -arch x86_64 -debug -verbose

!ENTRY org.eclipse.core.filesystem 1 1 2016-11-10 15:23:39.009
!MESSAGE Could not load library: libunixfile_1_0_0.so.  This library provides platform-specific optimizations for certain file system operations.  This library is not present on all platforms, so this may not be an error.  The resources plug-in will safely fall back to using java.io.File functionality.
!STACK 0
java.lang.UnsatisfiedLinkError: $HOME/.eclipse/org.jkiss.dbeaver.product_3.7.8_1898519774_linux_gtk_x86_64/configuration/org.eclipse.osgi/27/0/.cp/os/linux/x86_64/libunixfile_1_0_0.so: $HOME/.eclipse/org.jkiss.dbeaver.product_3.7.8_1898519774_linux_gtk_x86_64/configuration/org.eclipse.osgi/27/0/.cp/os/linux/x86_64/libunixfile_1_0_0.so: failed to map segment from shared object
	at java.lang.ClassLoader$NativeLibrary.load(Native Method)
	at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1941)
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1837)
	at java.lang.Runtime.loadLibrary0(Runtime.java:870)
	at java.lang.System.loadLibrary(System.java:1122)
	at org.eclipse.core.internal.filesystem.local.unix.UnixFileNatives.<clinit>(UnixFileNatives.java:39)
	at org.eclipse.core.internal.filesystem.local.LocalFileNativesManager.<clinit>(LocalFileNativesManager.java:50)
	at org.eclipse.core.internal.filesystem.local.LocalFile.fetchInfo(LocalFile.java:155)
	at org.eclipse.core.filesystem.provider.FileStore.fetchInfo(FileStore.java:284)
	at org.eclipse.core.internal.localstore.FileSystemResourceManager.read(FileSystemResourceManager.java:906)
	at org.eclipse.core.internal.resources.SaveManager.restoreMetaInfo(SaveManager.java:902)
	at org.eclipse.core.internal.resources.SaveManager.restoreMetaInfo(SaveManager.java:882)
	at org.eclipse.core.internal.resources.SaveManager.restore(SaveManager.java:733)
	at org.eclipse.core.internal.resources.SaveManager.startup(SaveManager.java:1588)
	at org.eclipse.core.internal.resources.Workspace.startup(Workspace.java:2386)
	at org.eclipse.core.internal.resources.Workspace.open(Workspace.java:2157)
	at org.eclipse.core.resources.ResourcesPlugin.start(ResourcesPlugin.java:463)
	at org.eclipse.osgi.internal.framework.BundleContextImpl$3.run(BundleContextImpl.java:771)
	at org.eclipse.osgi.internal.framework.BundleContextImpl$3.run(BundleContextImpl.java:1)
	at java.security.AccessController.doPrivileged(Native Method)
	at org.eclipse.osgi.internal.framework.BundleContextImpl.startActivator(BundleContextImpl.java:764)
	at org.eclipse.osgi.internal.framework.BundleContextImpl.start(BundleContextImpl.java:721)
	at org.eclipse.osgi.internal.framework.EquinoxBundle.startWorker0(EquinoxBundle.java:941)
	at org.eclipse.osgi.internal.framework.EquinoxBundle$EquinoxModule.startWorker(EquinoxBundle.java:318)
	at org.eclipse.osgi.container.Module.doStart(Module.java:571)
	at org.eclipse.osgi.container.Module.start(Module.java:439)
	at org.eclipse.osgi.framework.util.SecureAction.start(SecureAction.java:454)
	at org.eclipse.osgi.internal.hooks.EclipseLazyStarter.postFindLocalClass(EclipseLazyStarter.java:107)
	at org.eclipse.osgi.internal.loader.classpath.ClasspathManager.findLocalClass(ClasspathManager.java:531)
	at org.eclipse.osgi.internal.loader.ModuleClassLoader.findLocalClass(ModuleClassLoader.java:324)
	at org.eclipse.osgi.internal.loader.BundleLoader.findLocalClass(BundleLoader.java:327)
	at org.eclipse.osgi.internal.loader.sources.SingleSourcePackage.loadClass(SingleSourcePackage.java:36)
	at org.eclipse.osgi.internal.loader.BundleLoader.findClassInternal(BundleLoader.java:398)
	at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:352)
	at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:344)
	at org.eclipse.osgi.internal.loader.ModuleClassLoader.loadClass(ModuleClassLoader.java:160)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at org.jkiss.dbeaver.model.impl.PropertyDescriptor$PropertyType.<clinit>(PropertyDescriptor.java:48)
	at org.jkiss.dbeaver.model.impl.PropertyDescriptor.<init>(PropertyDescriptor.java:116)
	at org.jkiss.dbeaver.model.impl.PropertyDescriptor.extractProperties(PropertyDescriptor.java:99)
	at org.jkiss.dbeaver.registry.formatter.DataFormatterDescriptor.<init>(DataFormatterDescriptor.java:60)
	at org.jkiss.dbeaver.registry.formatter.DataFormatterRegistry.<init>(DataFormatterRegistry.java:72)
	at org.jkiss.dbeaver.registry.formatter.DataFormatterRegistry.getInstance(DataFormatterRegistry.java:56)
	at org.jkiss.dbeaver.registry.formatter.DataFormatterProfile.initDefaultPreferences(DataFormatterProfile.java:212)
	at org.jkiss.dbeaver.core.DBeaverPreferencesInitializer.initializeDefaultPreferences(DBeaverPreferencesInitializer.java:169)
	at org.eclipse.core.internal.preferences.PreferenceServiceRegistryHelper$1.run(PreferenceServiceRegistryHelper.java:300)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.eclipse.core.internal.preferences.PreferenceServiceRegistryHelper.runInitializer(PreferenceServiceRegistryHelper.java:303)
	at org.eclipse.core.internal.preferences.PreferenceServiceRegistryHelper.applyRuntimeDefaults(PreferenceServiceRegistryHelper.java:131)
	at org.eclipse.core.internal.preferences.PreferencesService.applyRuntimeDefaults(PreferencesService.java:368)
	at org.eclipse.core.internal.preferences.DefaultPreferences.applyRuntimeDefaults(DefaultPreferences.java:221)
	at org.eclipse.core.internal.preferences.DefaultPreferences.load(DefaultPreferences.java:274)
	at org.eclipse.core.internal.preferences.EclipsePreferences.create(EclipsePreferences.java:409)
	at org.eclipse.core.internal.preferences.EclipsePreferences.internalNode(EclipsePreferences.java:670)
	at org.eclipse.core.internal.preferences.EclipsePreferences.node(EclipsePreferences.java:812)
	at org.eclipse.core.internal.preferences.AbstractScope.getNode(AbstractScope.java:38)
	at org.eclipse.core.runtime.preferences.DefaultScope.getNode(DefaultScope.java:76)
	at org.jkiss.dbeaver.model.impl.preferences.BundlePreferenceStore.<init>(BundlePreferenceStore.java:19)
	at org.jkiss.dbeaver.ModelPreferences.setMainBundle(ModelPreferences.java:92)
	at org.jkiss.dbeaver.core.DBeaverActivator.start(DBeaverActivator.java:64)
	at org.eclipse.osgi.internal.framework.BundleContextImpl$3.run(BundleContextImpl.java:771)
	at org.eclipse.osgi.internal.framework.BundleContextImpl$3.run(BundleContextImpl.java:1)
	at java.security.AccessController.doPrivileged(Native Method)
	at org.eclipse.osgi.internal.framework.BundleContextImpl.startActivator(BundleContextImpl.java:764)
	at org.eclipse.osgi.internal.framework.BundleContextImpl.start(BundleContextImpl.java:721)
	at org.eclipse.osgi.internal.framework.EquinoxBundle.startWorker0(EquinoxBundle.java:941)
	at org.eclipse.osgi.internal.framework.EquinoxBundle$EquinoxModule.startWorker(EquinoxBundle.java:318)
	at org.eclipse.osgi.container.Module.doStart(Module.java:571)
	at org.eclipse.osgi.container.Module.start(Module.java:439)
	at org.eclipse.osgi.framework.util.SecureAction.start(SecureAction.java:454)
	at org.eclipse.osgi.internal.hooks.EclipseLazyStarter.postFindLocalClass(EclipseLazyStarter.java:107)
	at org.eclipse.osgi.internal.loader.classpath.ClasspathManager.findLocalClass(ClasspathManager.java:531)
	at org.eclipse.osgi.internal.loader.ModuleClassLoader.findLocalClass(ModuleClassLoader.java:324)
	at org.eclipse.osgi.internal.loader.BundleLoader.findLocalClass(BundleLoader.java:327)
	at org.eclipse.osgi.internal.loader.sources.SingleSourcePackage.loadClass(SingleSourcePackage.java:36)
	at org.eclipse.osgi.internal.loader.BundleLoader.findClassInternal(BundleLoader.java:398)
	at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:352)
	at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:344)
	at org.eclipse.osgi.internal.loader.ModuleClassLoader.loadClass(ModuleClassLoader.java:160)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at org.jkiss.dbeaver.core.application.DBeaverApplication.start(DBeaverApplication.java:177)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:380)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:235)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:669)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:608)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1515)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1488)

!ENTRY org.eclipse.equinox.preferences 4 2 2016-11-10 15:23:39.103
!MESSAGE Problems occurred when invoking code from plug-in: "org.eclipse.equinox.preferences".
!STACK 0
java.lang.UnsatisfiedLinkError: Could not load SWT library. Reasons: 
	$HOME/.eclipse/org.jkiss.dbeaver.product_3.7.8_1898519774_linux_gtk_x86_64/configuration/org.eclipse.osgi/84/0/.cp/libswt-gtk-4530.so: $HOME/.eclipse/org.jkiss.dbeaver.product_3.7.8_1898519774_linux_gtk_x86_64/configuration/org.eclipse.osgi/84/0/.cp/libswt-gtk-4530.so: failed to map segment from shared object
	no swt-gtk in java.library.path
	$HOME/.swt/lib/linux/x86_64/libswt-gtk-4530.so: $HOME/.swt/lib/linux/x86_64/libswt-gtk-4530.so: failed to map segment from shared object
	Can't load library: $HOME/.swt/lib/linux/x86_64/libswt-gtk.so

	at org.eclipse.swt.internal.Library.loadLibrary(Library.java:327)
	at org.eclipse.swt.internal.Library.loadLibrary(Library.java:236)
	at org.eclipse.swt.internal.C.<clinit>(C.java:16)
	at org.eclipse.swt.internal.Converter.wcsToMbcs(Converter.java:63)
	at org.eclipse.swt.internal.Converter.wcsToMbcs(Converter.java:54)
	at org.eclipse.swt.widgets.Display.<clinit>(Display.java:134)
	at org.eclipse.jface.preference.PreferenceConverter.<clinit>(PreferenceConverter.java:79)
	at org.eclipse.ui.texteditor.AbstractDecoratedTextEditorPreferenceConstants.initializeDefaultValues(AbstractDecoratedTextEditorPreferenceConstants.java:687)
	at org.eclipse.ui.editors.text.TextEditorPreferenceConstants.initializeDefaultValues(TextEditorPreferenceConstants.java:259)
	at org.eclipse.ui.internal.editors.text.EditorsPluginPreferenceInitializer.initializeDefaultPreferences(EditorsPluginPreferenceInitializer.java:43)
	at org.eclipse.core.internal.preferences.PreferenceServiceRegistryHelper$1.run(PreferenceServiceRegistryHelper.java:300)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.eclipse.core.internal.preferences.PreferenceServiceRegistryHelper.runInitializer(PreferenceServiceRegistryHelper.java:303)
	at org.eclipse.core.internal.preferences.PreferenceServiceRegistryHelper.applyRuntimeDefaults(PreferenceServiceRegistryHelper.java:131)
	at org.eclipse.core.internal.preferences.PreferencesService.applyRuntimeDefaults(PreferencesService.java:368)
	at org.eclipse.core.internal.preferences.DefaultPreferences.applyRuntimeDefaults(DefaultPreferences.java:221)
	at org.eclipse.core.internal.preferences.DefaultPreferences.load(DefaultPreferences.java:274)
	at org.eclipse.core.internal.preferences.EclipsePreferences.create(EclipsePreferences.java:409)
	at org.eclipse.core.internal.preferences.EclipsePreferences.internalNode(EclipsePreferences.java:670)
	at org.eclipse.core.internal.preferences.EclipsePreferences.node(EclipsePreferences.java:812)
	at org.eclipse.core.internal.preferences.AbstractScope.getNode(AbstractScope.java:38)
	at org.eclipse.core.runtime.preferences.DefaultScope.getNode(DefaultScope.java:76)
	at org.eclipse.ui.preferences.ScopedPreferenceStore.getDefaultPreferences(ScopedPreferenceStore.java:238)
	at org.eclipse.ui.preferences.ScopedPreferenceStore.setDefault(ScopedPreferenceStore.java:529)
	at org.jkiss.dbeaver.core.DBeaverPreferencesInitializer.initializeDefaultPreferences(DBeaverPreferencesInitializer.java:174)
	at org.eclipse.core.internal.preferences.PreferenceServiceRegistryHelper$1.run(PreferenceServiceRegistryHelper.java:300)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.eclipse.core.internal.preferences.PreferenceServiceRegistryHelper.runInitializer(PreferenceServiceRegistryHelper.java:303)
	at org.eclipse.core.internal.preferences.PreferenceServiceRegistryHelper.applyRuntimeDefaults(PreferenceServiceRegistryHelper.java:131)
	at org.eclipse.core.internal.preferences.PreferencesService.applyRuntimeDefaults(PreferencesService.java:368)
	at org.eclipse.core.internal.preferences.DefaultPreferences.applyRuntimeDefaults(DefaultPreferences.java:221)
	at org.eclipse.core.internal.preferences.DefaultPreferences.load(DefaultPreferences.java:274)
	at org.eclipse.core.internal.preferences.EclipsePreferences.create(EclipsePreferences.java:409)
	at org.eclipse.core.internal.preferences.EclipsePreferences.internalNode(EclipsePreferences.java:670)
	at org.eclipse.core.internal.preferences.EclipsePreferences.node(EclipsePreferences.java:812)
	at org.eclipse.core.internal.preferences.AbstractScope.getNode(AbstractScope.java:38)
	at org.eclipse.core.runtime.preferences.DefaultScope.getNode(DefaultScope.java:76)
	at org.jkiss.dbeaver.model.impl.preferences.BundlePreferenceStore.<init>(BundlePreferenceStore.java:19)
	at org.jkiss.dbeaver.ModelPreferences.setMainBundle(ModelPreferences.java:92)
	at org.jkiss.dbeaver.core.DBeaverActivator.start(DBeaverActivator.java:64)
	at org.eclipse.osgi.internal.framework.BundleContextImpl$3.run(BundleContextImpl.java:771)
	at org.eclipse.osgi.internal.framework.BundleContextImpl$3.run(BundleContextImpl.java:1)
	at java.security.AccessController.doPrivileged(Native Method)
	at org.eclipse.osgi.internal.framework.BundleContextImpl.startActivator(BundleContextImpl.java:764)
	at org.eclipse.osgi.internal.framework.BundleContextImpl.start(BundleContextImpl.java:721)
	at org.eclipse.osgi.internal.framework.EquinoxBundle.startWorker0(EquinoxBundle.java:941)
	at org.eclipse.osgi.internal.framework.EquinoxBundle$EquinoxModule.startWorker(EquinoxBundle.java:318)
	at org.eclipse.osgi.container.Module.doStart(Module.java:571)
	at org.eclipse.osgi.container.Module.start(Module.java:439)
	at org.eclipse.osgi.framework.util.SecureAction.start(SecureAction.java:454)
	at org.eclipse.osgi.internal.hooks.EclipseLazyStarter.postFindLocalClass(EclipseLazyStarter.java:107)
	at org.eclipse.osgi.internal.loader.classpath.ClasspathManager.findLocalClass(ClasspathManager.java:531)
	at org.eclipse.osgi.internal.loader.ModuleClassLoader.findLocalClass(ModuleClassLoader.java:324)
	at org.eclipse.osgi.internal.loader.BundleLoader.findLocalClass(BundleLoader.java:327)
	at org.eclipse.osgi.internal.loader.sources.SingleSourcePackage.loadClass(SingleSourcePackage.java:36)
	at org.eclipse.osgi.internal.loader.BundleLoader.findClassInternal(BundleLoader.java:398)
	at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:352)
	at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:344)
	at org.eclipse.osgi.internal.loader.ModuleClassLoader.loadClass(ModuleClassLoader.java:160)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at org.jkiss.dbeaver.core.application.DBeaverApplication.start(DBeaverApplication.java:177)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:380)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:235)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:669)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:608)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1515)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1488)

!ENTRY org.eclipse.osgi 4 0 2016-11-10 15:23:39.188
!MESSAGE Application error
!STACK 1
java.lang.NoClassDefFoundError: Could not initialize class org.eclipse.swt.widgets.Display
	at org.eclipse.ui.internal.Workbench.createDisplay(Workbench.java:774)
	at org.eclipse.ui.PlatformUI.createDisplay(PlatformUI.java:162)
	at org.jkiss.dbeaver.core.application.DBeaverApplication.start(DBeaverApplication.java:195)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:380)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:235)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:669)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:608)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1515)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1488)
~~~

**Comment by alexander-alzate** [comment]
Running `dbeaver -data /tmp` does not work.

**Comment by serge-rider** [comment]
That's weird.
Value of Java system property "user.home" is "$HOME" instead of real path, environment variable value wasn't substituted. Obviously any attempts to read/write files from "$HOME/anything" will fail.
This is not just DBeaver problem - any Java program which relies on user.home variable won't work.
Value of user.home depends on local system. In some cases it is taken from /etc/passwd. Are you sure you have correct system config?

You can try to run DBeaver with extra parameter `-vmargs -Duser.home=<real-user-home>`. Maybe it'll help.
Running `dbeaver -data /tmp` is a bad idea - /tmp is general purpose folder. But /home/<user>/dbeaver-workspace might work.

**Comment by alexander-alzate** [comment]
No, sorry, I changed my home manually to $HOME

**Comment by alexander-alzate** [comment]
being `/var/opt/dbeaver` writable, `dbeaver -data /var/opt/dbeaver` gives me the same error.

**Comment by serge-rider** [comment]
Yeah, just realized that changing workspace path won't help - Eclipse still writes it's files in user.home.
So, with corrupted user.home DBeaver won't work. You could try to redefine it as suggested above.

**Comment by alexander-alzate** [comment]
`dbeaver -vmargs -Duser.home=/var/opt/dbeaver/` works.

**Comment by serge-rider** [comment]
Good
