### ISSUE TITLE
Error to connect to SQLite DB on Linux

### ISSUE THREAD

**Issue by debuger** [serge-rider/dbeaver#968]
I have `/tmp` mounted with `noexec` flag:
```
>mount | grep /tmp
/dev/sda2 on /tmp type ext4 (rw,noexec,relatime,data=writeback)
```
While running dBeaver from console I have the error:

```
Connect with 'SQLite - cron.sql3' (sqlite_jdbc-1440948163552-1573451469)
Failed to load native library:sqlite-3.14.2.1-80f969f8-c3ce-406c-beb5-8c8fa9564b56-libsqlitejdbc.so. osinfo: Linux/x86_64
java.lang.UnsatisfiedLinkError: /tmp/sqlite-3.14.2.1-80f969f8-c3ce-406c-beb5-8c8fa9564b56-libsqlitejdbc.so: /tmp/sqlite-3.14.2.1-80f969f8-c3ce-406c-beb5-8c8fa9564b56-libsqlitejdbc.so: сбой отображения сегмента из разделяемого объекта: Операция не позволена
2016-11-13 16:36:32.276 - Connection failed (sqlite_jdbc-1440948163552-1573451469)
2016-11-13 16:36:32.284 - org.jkiss.dbeaver.model.exec.DBCConnectException: Unexpected driver error occurred while connecting to database
org.jkiss.dbeaver.model.exec.DBCConnectException: Unexpected driver error occurred while connecting to database
        at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.openConnection(JDBCDataSource.java:181)
        at org.jkiss.dbeaver.model.impl.jdbc.JDBCExecutionContext.connect(JDBCExecutionContext.java:73)
        at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.<init>(JDBCDataSource.java:96)
        at org.jkiss.dbeaver.ext.generic.model.GenericDataSource.<init>(GenericDataSource.java:83)
        at org.jkiss.dbeaver.ext.generic.model.meta.GenericMetaModel.createDataSource(GenericMetaModel.java:86)
        at org.jkiss.dbeaver.ext.generic.GenericDataSourceProvider.openDataSource(GenericDataSourceProvider.java:153)
        at org.jkiss.dbeaver.registry.DataSourceDescriptor.connect(DataSourceDescriptor.java:644)
        at org.jkiss.dbeaver.runtime.jobs.ConnectJob.run(ConnectJob.java:74)
        at org.jkiss.dbeaver.runtime.jobs.ConnectJob.runSync(ConnectJob.java:104)
        at org.jkiss.dbeaver.ui.actions.datasource.DataSourceHandler.connectToDataSource(DataSourceHandler.java:127)
        at org.jkiss.dbeaver.registry.DataSourceDescriptor.initConnection(DataSourceDescriptor.java:602)
        at org.jkiss.dbeaver.model.navigator.DBNDataSource.initializeNode(DBNDataSource.java:123)
        at org.jkiss.dbeaver.model.navigator.DBNDatabaseNode.getChildren(DBNDatabaseNode.java:188)
        at org.jkiss.dbeaver.model.navigator.DBNDatabaseNode.getChildren(DBNDatabaseNode.java:1)
        at org.jkiss.dbeaver.ui.navigator.database.load.TreeLoadService.evaluate(TreeLoadService.java:57)
        at org.jkiss.dbeaver.ui.navigator.database.load.TreeLoadService.evaluate(TreeLoadService.java:1)
        at org.jkiss.dbeaver.ui.LoadingJob.run(LoadingJob.java:83)
        at org.jkiss.dbeaver.ui.LoadingJob.run(LoadingJob.java:70)
        at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:103)
        at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)
Caused by: java.lang.UnsatisfiedLinkError: org.sqlite.core.NativeDB._open(Ljava/lang/String;I)V
        at org.sqlite.core.NativeDB._open(Native Method)
        at org.sqlite.core.DB.open(DB.java:174)
        at org.sqlite.core.CoreConnection.open(CoreConnection.java:220)
        at org.sqlite.core.CoreConnection.<init>(CoreConnection.java:76)
        at org.sqlite.jdbc3.JDBC3Connection.<init>(JDBC3Connection.java:24)
        at org.sqlite.jdbc4.JDBC4Connection.<init>(JDBC4Connection.java:24)
        at org.sqlite.SQLiteConnection.<init>(SQLiteConnection.java:45)
        at org.sqlite.JDBC.createConnection(JDBC.java:114)
        at org.sqlite.JDBC.connect(JDBC.java:88)
        at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.openConnection(JDBCDataSource.java:161)
        ... 19 more
```
When `/tmp` mounted without `noexec` flag all works fine

**Comment by serge-rider** [comment]
SQLite driver contains native executable binaries (so).
When you connect to database these binaries are extracted in temp directory from driver jar. Looks like noexec restricts loading so binaries.

Possible workaround (not tested): run DBeaver with CL parameter `-vmargs -Djava.io.tmpdir=<path>` where path is location with exec permissions.

**Comment by debuger** [comment]
Workaround works. Is there any way to add `-vmargs -Djava.io.tmpdir` into `dbeaver.ini` or somw other place to make provided args as default?

**Comment by serge-rider** [comment]
Good.
Yes, sure. You can put this in dbeaver.ini (in the end, each argument on a separate line)

**Comment by debuger** [comment]
Thanks. It works. Possible the issue should be mentioned in readme.
